export const homeModalsScript = [
  'function openModal(contentHtml, titleHtml) {',
  '  const resolvedTitle = titleHtml || \'<i class="fas fa-pen"></i> 操作\';',
  "  const overlay = document.createElement('div');",
  "  overlay.className = 'modal-overlay';",
  '  overlay.innerHTML = [',
  '    \'<div class="modal-content">\',',
  '    \'  <div class="modal-header">\',',
  "    '    <h2>' + resolvedTitle + '</h2>',",
  '    \'    <button class="close-btn" type="button"><i class="fas fa-times"></i></button>\',',
  "    '  </div>',",
  "    '  <div class=\"modal-body\">' + contentHtml + '</div>',",
  "    '</div>',",
  "  ].join('');",
  '  const requestClose = () => {',
  "    if (overlay.dataset.dirty === 'true' && !confirm('有未保存的修改，确定放弃吗？')) return false;",
  '    overlay.remove();',
  '    return true;',
  '  };',
  "  overlay.addEventListener('click', event => {",
  "    if (event.target === overlay && overlay.dataset.dirty === 'true' && !confirm('有未保存的修改，确定放弃吗？')) event.stopImmediatePropagation();",
  '  }, true);',
  "  overlay.addEventListener('input', event => { if (event.target.closest('form')) overlay.dataset.dirty = 'true'; });",
  "  overlay.addEventListener('change', event => { if (event.target.closest('form')) overlay.dataset.dirty = 'true'; });",
  "  overlay.addEventListener('click', event => {",
  '    if (event.target === overlay) {',
  '      overlay.remove();',
  '    }',
  '  });',
  "  overlay.querySelector('.close-btn').addEventListener('click', requestClose);",
  '  document.body.appendChild(overlay);',
  '  bindCoverImageFallbacks(overlay);',
  '  bindSafeExternalLinkButtons(overlay);',
  '  return overlay;',
  '}',
  '',
  'function bindSafeExternalLinkButtons(root) {',
  '  if (!root?.querySelectorAll) return;',
  '  root.querySelectorAll("[data-external-url]").forEach(button => {',
  '    if (button.dataset.externalUrlBound === "1") return;',
  '    button.dataset.externalUrlBound = "1";',
  '    button.addEventListener("click", event => {',
  '      event.preventDefault();',
  '      event.stopPropagation();',
  '      openExternalLinkWarning(button.dataset.externalUrl || "");',
  '    });',
  '  });',
  '}',
  '',
  'function openExternalLinkWarning(rawUrl) {',
  '  const url = normalizeExternalHttpUrl(rawUrl);',
  '  if (!url) { showToast("链接格式无效，已阻止操作。", "warning"); return null; }',
  '  let hostname = "外部网站";',
  '  try { hostname = new URL(url).hostname || hostname; } catch {}',
  '  const bodyHtml = `<div class="external-link-warning"><div class="external-link-warning-icon"><i class="fas fa-triangle-exclamation"></i></div><div class="external-link-warning-copy"><strong>这是创作者提供的外部链接</strong><p>创意工坊不会自动打开，也没有验证目标页面的内容。请复制链接后自行决定是否访问。</p><span class="external-link-warning-host">${escapeHtml(hostname)}</span><code>${escapeHtml(url)}</code></div><div class="external-link-warning-actions"><button class="btn btn-outline external-link-warning-cancel" type="button">取消</button><button class="btn btn-primary external-link-warning-copy-btn" type="button"><i class="fas fa-copy"></i> 复制链接</button></div></div>`;',
  '  const warningOverlay = openModal(bodyHtml, `<i class="fas fa-shield-halved"></i> 外部链接`);',
  '  warningOverlay.classList.add("external-link-warning-modal");',
  '  const cancelButton = warningOverlay.querySelector(".external-link-warning-cancel");',
  '  if (cancelButton) cancelButton.addEventListener("click", () => warningOverlay.remove());',
  '  const copyButton = warningOverlay.querySelector(".external-link-warning-copy-btn");',
  '  if (copyButton) copyButton.addEventListener("click", async () => {',
  '    const copied = await copyTextToClipboard(url);',
  '    if (!copied) { showToast("浏览器禁止自动复制，请手动选择链接复制。", "warning"); return; }',
  '    warningOverlay.remove();',
  '    showToast("链接已复制，请自行决定是否打开。", "info");',
  '  });',
  '  return warningOverlay;',
  '}',
  '',
  'function openReleaseNoticeModal() {',
  '  const bodyHtml = `',
  '    <div class="release-update-guide">',
  '      <p class="release-update-lead">旧版 Creative Workshop 脚本可能缺少新的安装、更新与兼容性修复。请更新到 <strong>v${WORKSHOP_RELEASE_VERSION}</strong>。</p>',
  '      <ol class="release-update-steps">',
  '        <li>点击下方按钮复制最新版导入代码。</li>',
  '        <li>回到 <strong>SillyTavern</strong>，打开 <strong>酒馆助手</strong>。</li>',
  '        <li>找到你现在使用的「命定创意工坊」脚本。</li>',
  '        <li>把旧的 <code>import ...</code> 整行替换成下面的新代码。</li>',
  '        <li>保存脚本，然后刷新 SillyTavern 或重新打开创意工坊。</li>',
  '      </ol>',
  '      <div class="release-update-codebox">',
  '        <textarea class="release-update-code" id="releaseUpdateCode" readonly spellcheck="false">${escapeHtml(WORKSHOP_RELEASE_IMPORT)}</textarea>',
  '        <button class="release-update-copy-btn" id="releaseUpdateCopyBtn" type="button" aria-label="复制导入代码"><i class="fas fa-copy"></i><span>复制</span></button>',
  '      </div>',
  '    </div>',
  '  `;',
  '  const overlay = openModal(bodyHtml, `<i class="fas fa-rotate"></i> Creative Workshop 更新指南`);',
  '  const copyBtn = overlay.querySelector("#releaseUpdateCopyBtn");',
  '  const codeField = overlay.querySelector("#releaseUpdateCode");',
  '  if (copyBtn && codeField) copyBtn.addEventListener("click", async () => {',
  '    codeField.focus();',
  '    codeField.select();',
  '    codeField.setSelectionRange(0, codeField.value.length);',
  '    let copied = false;',
  '    try { copied = document.execCommand("copy"); } catch (error) { console.warn("Selected-field copy failed", error); }',
  '    if (!copied && navigator.clipboard?.writeText) {',
  '      try {',
  '        await navigator.clipboard.writeText(codeField.value);',
  '        copied = true;',
  '      } catch (error) {',
  '        console.warn("Clipboard API unavailable", error);',
  '      }',
  '    }',
  '    if (copied) {',
  '      copyBtn.innerHTML = `<i class="fas fa-check"></i><span>已复制</span>`;',
  '      showToast("已复制。下一步：SillyTavern → 酒馆助手 → 替换旧 import → 保存并刷新。");',
  '    } else {',
  '      showToast("浏览器禁止自动复制，代码已经选中，请长按或右键复制。", "warning");',
  '    }',
  '  });',
  '}',
  '',
  'function setButtonLoading(button, pendingText) {',
  '  if (!button) return () => {};',
  '  const originalHtml = button.innerHTML;',
  '  button.disabled = true;',
  '  button.classList.add("is-loading");',
  '  button.innerHTML = `<span class="inline-loading-spinner"></span><span>${pendingText}</span>`;',
  '  return () => {',
  '    button.disabled = false;',
  '    button.classList.remove("is-loading");',
  '    button.innerHTML = originalHtml;',
  '  };',
  '}',
  '',
  'async function showProjectDetail(project) {',
  '  const loadingOverlay = openModal(\'<div class="detail-loading"><div class="loading-spinner"></div><div class="detail-loading-text">正在加载项目详情...</div></div>\', \'<i class="fas fa-info-circle"></i> 项目详情\');',
  '  loadingOverlay.classList.add("project-detail-modal");',
  '  try {',
  '    const detail = await fetchProjectEntries(project);',
  '    if (!loadingOverlay.isConnected) return;',
  '    loadingOverlay.remove();',
  '    const overlay = openModal(renderProjectDetail(detail.project || project, detail.entries || [], detail.regexEntries || []), \'<i class="fas fa-info-circle"></i> 项目详情\');',
  '    overlay.classList.add("project-detail-modal");',
  "    overlay.addEventListener('click', event => {",
  '      const jump = event.target instanceof Element ? event.target.closest(".detail-toc-item") : null;',
  '      if (!jump) return;',
  '      const href = String(jump.getAttribute("href") || "");',
  '      if (!href.startsWith("#")) return;',
  '      const target = overlay.querySelector(href);',
  '      if (!target) return;',
  '      event.preventDefault();',
  '      overlay.querySelectorAll(".detail-toc-item").forEach(item => item.classList.remove("active"));',
  '      jump.classList.add("active");',
  '      const reduceMotion = typeof window.matchMedia === "function" && window.matchMedia("(prefers-reduced-motion: reduce)").matches;',
  '      const scroller = overlay.querySelector(".modal-body");',
  '      if (scroller instanceof HTMLElement) {',
  '        const scrollerRect = scroller.getBoundingClientRect();',
  '        const targetRect = target.getBoundingClientRect();',
  '        const top = scroller.scrollTop + targetRect.top - scrollerRect.top - 12;',
  '        scroller.scrollTo({ top: Math.max(0, top), behavior: reduceMotion ? "auto" : "smooth" });',
  '      } else {',
  '        target.scrollIntoView({ behavior: reduceMotion ? "auto" : "smooth", block: "start" });',
  '      }',
  '    });',
  "    overlay.querySelectorAll('[data-entry-toggle]').forEach(header => {",
  "      header.addEventListener('click', () => {",
  "        header.classList.toggle('open');",
  '        const content = header.nextElementSibling;',
  "        if (content) content.classList.toggle('open');",
  '      });',
  '    });',
  "    overlay.querySelectorAll('[data-detail-entry-group-toggle]').forEach(toggle => {",
  "      toggle.addEventListener('click', () => {",
  '        const group = toggle.closest("[data-detail-entry-group]");',
  '        const nav = toggle.closest(".detail-entry-nav");',
  '        if (!group || !nav) return;',
  '        const shouldOpen = !group.classList.contains("open");',
  '        if (shouldOpen) {',
  '          nav.querySelectorAll("[data-detail-entry-group].open").forEach(item => {',
  '            if (item === group) return;',
  '            item.classList.remove("open");',
  '            const itemToggle = item.querySelector("[data-detail-entry-group-toggle]");',
  '            if (itemToggle) itemToggle.setAttribute("aria-expanded", "false");',
  '          });',
  '        }',
  '        group.classList.toggle("open", shouldOpen);',
  '        toggle.setAttribute("aria-expanded", shouldOpen ? "true" : "false");',
  '      });',
  '    });',
  "    overlay.querySelectorAll('[data-detail-entry-nav]').forEach(button => {",
  "      button.addEventListener('click', () => {",
  '        const workspace = button.closest(".detail-entry-workspace");',
  '        const target = String(button.dataset.detailEntryNav || "");',
  '        if (!workspace || !target) return;',
  '        workspace.querySelectorAll("[data-detail-entry-nav]").forEach(item => { item.classList.remove("active"); item.setAttribute("aria-selected", "false"); });',
  '        workspace.querySelectorAll("[data-detail-entry-panel]").forEach(panel => panel.classList.remove("active"));',
  '        button.classList.add("active");',
  '        button.setAttribute("aria-selected", "true");',
  '        const panel = workspace.querySelector(`[data-detail-entry-panel="${target}"]`);',
  '        if (panel) panel.classList.add("active");',
  '        const pane = workspace.querySelector(".detail-entry-pane");',
  '        if (pane) pane.scrollIntoView({ block: "start" });',
  '      });',
  '    });',
  "    const detailLikeButton = overlay.querySelector('.detail-like-btn');",
  '    if (detailLikeButton) {',
  "      detailLikeButton.addEventListener('click', async event => {",
  '        event.stopPropagation();',
  '        if (detailLikeButton.disabled) return;',
  '        const projectId = detailLikeButton.dataset.id || detail.project?.id || project.id;',
  '        if (!projectId) return;',
  '        await toggleLike(projectId);',
  '        const nextLike = getLikeState(projectId);',
  "        detailLikeButton.classList.toggle('liked', nextLike.liked);",
  "        detailLikeButton.setAttribute('aria-pressed', nextLike.liked ? 'true' : 'false');",
  "        const count = detailLikeButton.querySelector('strong');",
  '        if (count) count.textContent = String(nextLike.count);',
  "        detailLikeButton.title = nextLike.liked ? '取消点赞' : '点赞项目';",
  '      });',
  '    }',
  "    overlay.querySelectorAll('.detail-install-btn,.install-btn').forEach(button => {",
  "      button.addEventListener('click', event => {",
  '        event.stopPropagation();',
  '        if (button.disabled) return;',
  '        const projectId = button.dataset.id || detail.project?.id || project.id;',
  '        if (!projectId) return;',
  '        const localMeta = getLocalProjectMeta(projectId);',
  '        if (localMeta) {',
  '          requestUninstallProject(projectId);',
  "          showToast('已发送卸载请求', 'info');",
  '        } else {',
  '          void beginProjectInstall(detail.project || project, detail).catch(error => showToast("安装失败: " + error.message, "error"));',

  '        }',
  '        overlay.remove();',
  '      });',
  '    });',
  "    overlay.querySelectorAll('.detail-update-btn,.update-btn').forEach(button => {",
  "      button.addEventListener('click', event => {",
  '        event.stopPropagation();',
  '        if (button.disabled) return;',
  '        const targetProject = detail.project || project;',
  '        if (!targetProject?.id) return;',
  '        const restore = setButtonLoading(button, "加载差异");',
  '        requestProjectDiff(targetProject.id, targetProject.version)',
  '          .then(diff => openProjectUpdateModal(targetProject, diff))',
  '          .catch(error => showToast("加载更新差异失败: " + error.message, "error"))',
  '          .finally(restore);',
  '      });',
  '    });',
  '  } catch (error) {',
  '    loadingOverlay.remove();',
  "    showToast('加载详情失败: ' + error.message, 'error');",
  '  }',
  '}',
  '',
  'function renderDiffGroup(title, icon, worldbookEntries, regexEntries) {',
  '  const hasWorldbook = Array.isArray(worldbookEntries) && worldbookEntries.length > 0;',
  '  const hasRegex = Array.isArray(regexEntries) && regexEntries.length > 0;',
  '  if (!hasWorldbook && !hasRegex) return "";',
  '  const worldbookHtml = hasWorldbook ? renderDetailSection("世界书条目", "fa-scroll", worldbookEntries, renderDetailEntry, "") : "";',
  '  const regexHtml = hasRegex ? renderDetailSection("正则列表", "fa-code", regexEntries, renderRegexEntry, "") : "";',
  '  return `<div class="update-diff-group"><div class="detail-section-title"><span><i class="fas ${icon}"></i> ${title}</span></div>${worldbookHtml}${regexHtml}</div>`;',
  '}',
  '',
  'function openProjectUpdateModal(project, resolvedDiff) {',
  '  const diff = resolvedDiff || getProjectUpdateDiff(project.id) || {',
  '    added: { worldbookEntries: [], regexEntries: [] },',
  '    modified: { worldbookEntries: [], regexEntries: [] },',
  '    removed: { worldbookEntries: [], regexEntries: [] },',
  '  };',
  '  const headerHtml = renderProjectDetail(project, [], []).replace(/<div class="detail-section">[\\s\\S]*$/, "</div>");',
  '  const bodyHtml = [',
  '    `<div class="update-modal">${headerHtml}`,',
  '    renderDiffGroup("新增内容", "fa-plus", diff.added?.worldbookEntries || [], diff.added?.regexEntries || []),',
  '    renderDiffGroup("修改内容", "fa-pen", diff.modified?.worldbookEntries || [], diff.modified?.regexEntries || []),',
  '    renderDiffGroup("删除内容", "fa-trash", diff.removed?.worldbookEntries || [], diff.removed?.regexEntries || []),',
  '    `<div class="update-modal-actions"><button class="btn btn-outline" data-update-cancel>取消</button><button class="btn btn-primary" data-update-confirm>确认更新</button></div></div>`,',
  '  ].join("");',
  '  const overlay = openModal(bodyHtml, `<i class="fas fa-arrows-rotate"></i> 更新项目`);',
  '  overlay.querySelector("[data-update-cancel]")?.addEventListener("click", () => overlay.remove());',
  '  overlay.querySelector("[data-update-confirm]")?.addEventListener("click", () => {',
  '    confirmProjectUpdate(project.id, project.version);',
  "    showToast('已发送更新请求', 'info');",
  '    overlay.remove();',
  '  });',
  '}',
  '',
  'async function beginProjectInstall(project, knownDetail = null) {',
  '  const projectId = project?.id;',
  '  if (!projectId) throw new Error("缺少项目 ID");',
  '  const detail = knownDetail || await fetchProjectEntries(project);',
  '  const worldbookEntries = Array.isArray(detail?.entries) ? detail.entries : [];',
  '  const regexEntries = Array.isArray(detail?.regexEntries) ? detail.regexEntries : [];',
  '  const projectVersion = detail?.project?.version || project?.version || null;',
  '  if (worldbookEntries.length > 0) {',
  '    openInstallWorldbookModal(projectId, projectVersion);',
  '    return;',
  '  }',
  '  if (regexEntries.length > 0) {',
  '    requestInstallProject(projectId, { ...(projectVersion ? { projectVersion } : {}) });',
  '    showToast("已发送正则安装请求", "info");',
  '    return;',
  '  }',
  '  throw new Error("项目没有可安装的世界书或正则内容");',
  '}',
  '',
  'function openInstallWorldbookModal(projectId, projectVersion) {',
  '  const worldbooks = state.tavern.worldbooks || {};',
  '  const primary = worldbooks.primary || null;',
  '  const additional = Array.isArray(worldbooks.additional) ? worldbooks.additional.filter(Boolean) : [];',
  '  const available = Array.isArray(worldbooks.available) ? worldbooks.available.filter(Boolean) : [];',
  '  const additionalCandidates = Array.from(new Set([...additional, ...available])).filter(name => name !== primary);',

  '  const initialMode = primary ? "primary" : "additional";',
  '  const bodyHtml = `<form id="installWorldbookForm" class="install-worldbook-form"><div class="form-group"><label>安装位置</label><div class="install-target-switch"><button type="button" class="btn install-target-option${initialMode === "primary" ? " active" : ""}" data-install-target="primary"${primary ? "" : " disabled"}><i class="fas fa-book"></i><span>角色主世界书</span></button><button type="button" class="btn install-target-option${initialMode === "additional" ? " active" : ""}" data-install-target="additional"><i class="fas fa-layer-group"></i><span>附加世界书</span></button></div></div><div class="form-group install-additional-panel" data-additional-worldbook${initialMode === "additional" ? "" : " hidden"}><label for="additionalWorldbookSearch">选择附加世界书</label><div class="install-worldbook-search-wrap"><i class="fas fa-search"></i><input type="search" id="additionalWorldbookSearch" placeholder="搜索附加世界书" autocomplete="off"></div><div class="install-worldbook-list" data-additional-worldbook-list></div></div><button type="submit" class="btn install-submit-btn"><i class="fas fa-download"></i> 安装</button></form>`;',


  '  const overlay = openModal(bodyHtml, `<i class="fas fa-book"></i> 选择安装世界书`);',
  '  const form = overlay.querySelector("#installWorldbookForm");',
  '  const additionalPanel = overlay.querySelector("[data-additional-worldbook]");',
  '  const additionalSearch = overlay.querySelector("#additionalWorldbookSearch");',
  '  const additionalList = overlay.querySelector("[data-additional-worldbook-list]");',
  '  const targetButtons = Array.from(overlay.querySelectorAll("[data-install-target]"));',
  '  let installMode = initialMode;',
  '  let selectedAdditional = null;',
  '  const renderAdditionalList = query => {',
  '    if (!additionalList || installMode !== "additional") return;',
  '    const keyword = String(query || "").trim().toLowerCase();',
  '    const matches = additionalCandidates.filter(name => !keyword || String(name).toLowerCase().includes(keyword));',
  '    if (!matches.length) {',
  '      additionalList.innerHTML = `<div class="install-worldbook-empty">${additionalCandidates.length ? "没有匹配的附加世界书" : "当前角色没有附加世界书"}</div>`;',
  '      return;',
  '    }',
  '    additionalList.innerHTML = matches.map(name => `<button type="button" class="install-worldbook-option${selectedAdditional === name ? " active" : ""}" data-worldbook-name="${escapeHtml(name)}"><i class="fas fa-book-open"></i><span>${escapeHtml(name)}</span><i class="fas fa-check"></i></button>`).join("");',
  '    additionalList.querySelectorAll("[data-worldbook-name]").forEach(button => button.addEventListener("click", () => {',
  '      if (installMode !== "additional") return;',
  '      selectedAdditional = button.dataset.worldbookName || null;',
  '      renderAdditionalList(additionalSearch?.value || "");',
  '    }));',
  '  };',
  '  const setInstallMode = mode => {',
  '    installMode = mode;',
  '    targetButtons.forEach(button => {',
  '      const active = button.dataset.installTarget === mode;',
  '      button.classList.toggle("active", active);',

  '    });',
  '    if (additionalPanel) additionalPanel.hidden = mode !== "additional";',
  '    if (mode === "additional") { renderAdditionalList(additionalSearch?.value || ""); additionalSearch?.focus(); }',
  '  };',
  '  targetButtons.forEach(button => button.addEventListener("click", () => setInstallMode(button.dataset.installTarget)));',
  '  additionalSearch?.addEventListener("input", () => renderAdditionalList(additionalSearch.value));',
  '  setInstallMode(initialMode);',

  '  form?.addEventListener("submit", event => {',
  '    event.preventDefault();',
  '    const worldbookName = installMode === "primary" ? String(primary || "").trim() : String(selectedAdditional || "").trim();',
  '    if (!worldbookName) { showToast(installMode === "primary" ? "当前角色没有主世界书" : "请先选择一个附加世界书", "warning"); return; }',
  '    requestInstallProject(projectId, { worldbookName, projectVersion });',
  '    showToast(`已发送安装请求：${worldbookName}`, "info");',
  '    overlay.dataset.dirty = "false";',
  '    overlay.remove();',
  '  });',
  '}',
  '',
  'function bindFileDrop(drop, input, emptyText, onFilesChanged) {',
  '  let selectedFiles = [];',
  '  const applyFiles = async files => {',
  '    const nextFiles = Array.from(files || []);',
  '    const accepted = onFilesChanged ? await onFilesChanged([...nextFiles]) : true;',
  '    if (accepted === false) return false;',
  '    selectedFiles = nextFiles;',
  '    drop.textContent = input.multiple && selectedFiles.length ? `${selectedFiles.length} 个文件（点击或拖入继续添加）` : (selectedFiles[0]?.name || emptyText);',
  '    return true;',
  '  };',
  '  if (input.multiple) {',
  '    ["dragenter", "dragover"].forEach(type => drop.addEventListener(type, event => {',
  '      event.preventDefault();',
  '      if (event.dataTransfer) event.dataTransfer.dropEffect = "copy";',
  '      drop.classList.add("is-dragover");',
  '    }));',
  '    ["dragleave", "drop"].forEach(type => drop.addEventListener(type, event => {',
  '      event.preventDefault();',
  '      drop.classList.remove("is-dragover");',
  '    }));',
  '    drop.addEventListener("drop", event => {',
  '      const incoming = Array.from(event.dataTransfer?.files || []);',
  '      void applyFiles(appendUniqueUploadFiles(selectedFiles, incoming));',
  '    });',
  '  }',
  '  input._fileDropController = { getFiles: () => [...selectedFiles], setFiles: files => applyFiles(files), clear: () => applyFiles([]) };',
  '  drop.onclick = () => input.click();',
  '  input.onchange = async () => {',
  '    const incoming = Array.from(input.files || []);',
  '    const nextFiles = input.multiple ? appendUniqueUploadFiles(selectedFiles, incoming) : incoming.slice(0, 1);',
  '    await applyFiles(nextFiles);',
  '    if (input.multiple) input.value = "";',
  '  };',
  '}',
  '',
  'async function validateJsonUpload(file, kind) {',
  '  if (!file) return null;',
  '  assertUploadSize(file);',
  '  if (!String(file.name || "").toLowerCase().endsWith(".json")) {',
  '    throw new Error(kind === "worldbook" ? "世界书文件必须是 .json" : "正则文件必须是 .json");',
  '  }',
  '  let parsed;',
  '  try {',
  '    parsed = JSON.parse(await file.text());',
  '  } catch {',
  '    throw new Error(kind === "worldbook" ? "世界书文件不是有效 JSON" : "正则文件不是有效 JSON");',
  '  }',
  '  if (kind === "worldbook") {',
  '    const entries = parsed && typeof parsed === "object" ? parsed.entries : null;',
  '    const recognized = Boolean(parsed && typeof parsed === "object" && !Array.isArray(parsed) && (Array.isArray(entries) || (entries && typeof entries === "object" && !Array.isArray(entries))));',
  '    if (!recognized) {',
  '      throw new Error("世界书 JSON 格式不正确：需要 SillyTavern 世界书的顶层 entries");',
  '    }',
  '  }',
  '  if (kind === "worldbook") {',
  '    const entries = parsed.entries;',
  '    const values = Array.isArray(entries) ? entries : Object.values(entries);',
  '    if (!values.length || values.some(entry => !entry || typeof entry !== "object" || Array.isArray(entry))) {',
  '      throw new Error("世界书 JSON 格式不正确：entries 必须包含至少一个条目对象");',
  '    }',
  '  } else {',
  '    const regexEntries = Array.isArray(parsed) ? parsed : [parsed];',
  '    const validRegex = regexEntries.length > 0 && regexEntries.every(entry => entry && typeof entry === "object" && !Array.isArray(entry) && typeof entry.scriptName === "string" && entry.scriptName.trim());',
  '    if (!validRegex) {',
  '      const worldbookEntries = parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed.entries : null;',
  '      const looksLikeWorldbook = Array.isArray(worldbookEntries) || (worldbookEntries && typeof worldbookEntries === "object" && !Array.isArray(worldbookEntries));',
  '      throw new Error(looksLikeWorldbook ? "检测到世界书 JSON，请上传到世界书文件" : "正则 JSON 格式不正确：每个正则必须包含非空 scriptName");',
  '    }',
  '  }',
  '  return parsed;',
  '}',
  '',
  'function buildTagOptions(baseTagOptions, currentBaseTag) {',
  '  return baseTagOptions',
  "    .map(tag => '<option value=\"' + tag + '\"' + (tag === currentBaseTag ? ' selected' : '') + '>' + tag + '</option>')",
  "    .join('');",
  '}',
  '',
  'function buildVersionLabelHtml(project) {',
  '  const value = escapeHtml(project?.versionLabel || "");',
  '  return `<div class="form-group"><label>版本名称（可选）</label><input type="text" id="versionLabel" maxlength="80" value="${value}" placeholder="例如：4.2 Beta、夏季版、Final"><div class="form-hint">仅用于展示；更新版本由工坊自动管理。</div></div>`;',
  '}',
  '',
  'function buildExtensionTypeOptions(currentExtensionType) {',
  '  return (PROJECT_TAXONOMY.extensionTypes || []).map(value => `<option value="${escapeHtml(value)}"${value === currentExtensionType ? " selected" : ""}>${escapeHtml(value)}</option>`).join("");',
  '}',
  '',
  'function buildCharacterFacetOptions(project) {',
  '  const selectedFacets = project?.facets && typeof project.facets === "object" && !Array.isArray(project.facets) ? project.facets : {};',
  '  return Object.entries(PROJECT_TAXONOMY.characterFacets || {}).map(([group, options], groupIndex) => {',
  '    const selected = new Set(Array.isArray(selectedFacets[group]) ? selectedFacets[group].map(String) : []);',
  '    const choices = options.map(value => `<label class="taxonomy-chip"><input type="checkbox" data-facet-group="${escapeHtml(group)}" value="${escapeHtml(value)}"${selected.has(String(value)) ? " checked" : ""}><span>${escapeHtml(value)}</span></label>`).join("");',
  '    const openAttr = selected.size > 0 || groupIndex === 0 ? " open" : "";',
  '    return `<details class="taxonomy-facet-group"${openAttr}><summary><span>${escapeHtml(group)}</span><small>可多选</small></summary><div class="taxonomy-chip-list">${choices}</div></details>`;',
  '  }).join("");',
  '}',
  '',
  'function buildDisplayTagOptions(project) {',
  '  const pool = project ? getProjectTagPool(project) : [];',
  '  const selected = new Set(project ? getProjectDisplayTags(project) : []);',
  '  return pool.map(value => `<label class="taxonomy-chip display-tag-chip"><input type="checkbox" data-display-tag value="${escapeHtml(value)}"${selected.has(String(value)) ? " checked" : ""}><span>${escapeHtml(value)}</span></label>`).join("");',
  '}',
  '',
  'function validateProjectTaxonomySelection(payload) {',
  '  if (payload.projectType === "扩展" && !payload.extensionType) return { valid: false, error: "扩展项目必须选择规则或内容" };',
  '  const maxCustomTags = Number(PROJECT_TAXONOMY.maxCustomTags || 20);',
  '  const maxDisplayTags = Number(PROJECT_TAXONOMY.maxDisplayTags || 5);',
  '  if ((payload.customTags || []).length > maxCustomTags) return { valid: false, error: `自定义标签最多 ${maxCustomTags} 个` };',
  '  if ((payload.displayTags || []).length > maxDisplayTags) return { valid: false, error: `首页展示标签最多 ${maxDisplayTags} 个` };',
  '  return { valid: true };',
  '}',
  '',
  'const PROJECT_CONTENT_KIND_LABELS = { worldbook: "世界书", regex: "正则" };',
  '',
  'function getProjectContentRule(baseTag) {',
  '  return PROJECT_CONTENT_POLICY[baseTag] || PROJECT_CONTENT_POLICY["系统核心"];',
  '}',
  '',
  'function validateProjectContentSelection(baseTag, hasWorldbook, hasRegex) {',
  '  const rule = getProjectContentRule(baseTag);',
  '  const presence = { worldbook: Boolean(hasWorldbook), regex: Boolean(hasRegex) };',
  '  for (const kind of rule.required || []) {',
  '    if (!presence[kind]) return { valid: false, error: `${baseTag}项目必须包含有效${PROJECT_CONTENT_KIND_LABELS[kind] || kind}` };',
  '  }',
  '  if ((rule.anyOf || []).length && !rule.anyOf.some(kind => presence[kind])) {',
  '    const names = rule.anyOf.map(kind => PROJECT_CONTENT_KIND_LABELS[kind] || kind).join("或");',
  '    return { valid: false, error: `${baseTag}项目必须包含${names}` };',
  '  }',
  '  return { valid: true };',
  '}',
  '',
  'function getProjectContentRequirementText(baseTag) {',
  '  const rule = getProjectContentRule(baseTag);',
  '  const required = (rule.required || []).map(kind => `${PROJECT_CONTENT_KIND_LABELS[kind] || kind}必填`);',
  '  const anyOf = (rule.anyOf || []).length ? [`${rule.anyOf.map(kind => PROJECT_CONTENT_KIND_LABELS[kind] || kind).join("或")}至少一种`] : [];',
  '  return `${baseTag}：${[...required, ...anyOf].join("；") || "无额外内容要求"}`;',
  '}',
  '',
  'function buildProjectFormHtml(mode, project) {',
  "  const isEdit = mode === 'edit';",
  '  const baseTagOptions = BASE_TAGS;',
  '  const currentBaseTag = project ? getBaseTag(project) : "系统核心";',
  '  const currentExtensionType = project ? getProjectExtensionType(project) : "";',
  '  const characterFacetsHtml = buildCharacterFacetOptions(project);',
  "  const customTags = project ? getProjectCustomTags(project).join(', ') : '';",
  '  const displayTagsHtml = buildDisplayTagOptions(project);',
  '  const displayTagCount = project ? getProjectDisplayTags(project).length : 0;',
  '  const worldbookEntries = Array.isArray(project?.worldbookEntriesPreview) ? project.worldbookEntriesPreview : [];',
  '  const regexEntries = Array.isArray(project?.regexEntriesPreview) ? project.regexEntriesPreview : [];',
  '  const currentCoverSources = project ? getCoverImageSources(project) : null;',
  '  const currentCoverSrc = currentCoverSources?.authenticated ? currentCoverSources.placeholder : getDirectCoverUrl(project);',
  '  const currentCoverAuthAttrs = currentCoverSources?.authenticated ? ` data-cover-img-auth-src="${escapeHtml(currentCoverSources.authenticated)}" data-cover-img-placeholder-src="${escapeHtml(currentCoverSources.placeholder)}"` : "";',
  "  const currentCoverHtml = project?.coverImage ? '<div class=\"edit-current-cover\"><div class=\"detail-section-title\"><span><i class=\"fas fa-image\"></i> 当前预览图</span></div><img src=\"' + escapeHtml(currentCoverSrc) + '\"' + currentCoverAuthAttrs + ' alt=\"当前预览图\"></div>' : '<div class=\"edit-current-cover edit-current-cover--empty\"><div class=\"detail-section-title\"><span><i class=\"fas fa-image\"></i> 当前预览图</span></div><div class=\"empty-state\">未上传预览图</div></div>';",
  '  const currentContentHtml = isEdit ? `<div class="edit-current-content">${currentCoverHtml}${renderDetailSection("世界书条目", "fa-scroll", worldbookEntries, renderDetailEntry, "无条目内容", project, true, false)}${renderDetailSection("正则列表", "fa-code", regexEntries, renderRegexEntry, "无正则内容", project, true, false)}</div>` : "";',





  '  return [',
  '    \'<form id="projectForm" class="project-form" data-mode="\' + mode + \'">\',',
  '    \'  <div class="project-form-layout">\',',
  '    \'    <div class="project-form-column project-form-column--main">\',',
  '    \'      <section class="project-form-section" aria-labelledby="projectFormIdentityTitle">\',',
  '    \'        <div class="project-form-section-head"><span class="project-form-section-index">01</span><div><h3 id="projectFormIdentityTitle">项目资料</h3><p>名称、介绍与版本显示。</p></div></div>\',',
  '    \'        <div class="project-form-grid project-form-grid--identity">\',',
  '    \'          <div class="form-group project-form-field--wide"><label>项目名称 *</label><input type="text" id="projName" value="\' + escapeHtml(project?.name || \'\') + \'" required></div>\',',
  '    \'          <div class="form-group project-form-field--wide"><label>描述</label><textarea id="projDesc" rows="5" placeholder="告诉玩家这个项目做什么、适合谁，以及需要注意什么。">\' + escapeHtml(project?.description || \'\') + \'</textarea></div>\',',
  '    buildVersionLabelHtml(project),',
  '    \'        </div>\',',
  '    \'      </section>\',',
  '    \'      <section class="project-form-section" aria-labelledby="projectFormTaxonomyTitle">\',',
  '    \'        <div class="project-form-section-head"><span class="project-form-section-index">02</span><div><h3 id="projectFormTaxonomyTitle">分类与标签</h3><p>决定作品如何被发现，不需要把所有信息都塞到首页。</p></div></div>\',',
  '    \'        <div class="project-form-grid project-form-grid--taxonomy">\',',
  '    \'          <div class="form-group"><label>项目类型 *</label><select id="baseTag">\' + buildTagOptions(baseTagOptions, currentBaseTag) + \'</select></div>\',',
  '    \'          <div class="form-group" id="extensionTypeGroup"\' + (currentBaseTag === \'扩展\' ? \'\' : \' hidden\') + \'><label>扩展类型 *</label><select id="extensionType"><option value="">请选择</option>\' + buildExtensionTypeOptions(currentExtensionType) + \'</select></div>\',',
  '    \'          <div class="form-group project-form-field--wide" id="characterFacetsGroup"\' + (currentBaseTag === \'角色\' ? \'\' : \' hidden\') + \'><label>角色官方标签</label>\' + characterFacetsHtml + \'<div class="form-hint">官方标签可多选；仅角色项目使用。</div></div>\',',
  '    \'          <div class="form-group project-form-field--wide"><label>自定义标签 <small class="form-label-meta">最多 \' + (PROJECT_TAXONOMY.maxCustomTags || 20) + \' 个</small></label><input type="text" id="customTags" value="\' + escapeHtml(customTags) + \'" placeholder="纯爱, 慢热, 高自由度"><div class="form-hint">逗号分隔；与官方标签同名会自动合并。</div></div>\',',
  '    \'          <div class="form-group project-form-field--wide" id="displayTagsGroup"><label class="display-tags-label">首页展示标签 <small id="displayTagCount">\' + displayTagCount + \' / \' + (PROJECT_TAXONOMY.maxDisplayTags || 5) + \'</small></label><div class="taxonomy-chip-list display-tag-picker" id="displayTagPicker">\' + (displayTagsHtml || \'<div class="display-tag-picker-empty">先选择官方标签或填写自定义标签</div>\') + \'</div><div class="form-hint">只挑最能帮助浏览的标签；“有角色立绘”是独立功能标记，不占名额。</div></div>\',',
  '    \'        </div>\',',
  '    \'      </section>\',',
  '    currentContentHtml,',
  '    \'    </div>\',',
  '    \'    <div class="project-form-column project-form-column--assets">\',',
  '    \'      <section class="project-form-section project-form-section--assets" aria-labelledby="projectFormContentTitle">\',',
  '    \'        <div class="project-form-section-head"><span class="project-form-section-index">03</span><div><h3 id="projectFormContentTitle">项目内容</h3><p>上传实际内容与预览图，选择后会先在本页检查。</p></div></div>\',',
  '    \'        <div class="project-upload-stack">\',',
  '    \'          <div class="form-group project-upload-field"><label id="worldbookFileLabel">\' + (isEdit ? \'替换世界书文件\' : \'世界书文件 *\') + \'</label><div class="file-drop project-file-drop project-file-drop--worldbook" id="fileDrop">\' + (isEdit ? \'选择新世界书 JSON\' : \'点击选择世界书 JSON\') + \'</div><input type="file" id="fileInput" accept=".json" style="display:none;"><div class="upload-file-preview" id="worldbookUploadPreview" hidden></div></div>\',',
  '    \'          <div class="form-group project-upload-field"><label id="regexFileLabel">\' + (isEdit ? \'替换正则文件\' : \'正则文件 (可选)\') + \'</label><div class="file-drop project-file-drop project-file-drop--regex" id="regexDrop">\' + (isEdit ? \'选择或拖入一个/多个新正则 JSON\' : \'点击选择或拖入一个/多个正则 JSON\') + \'</div><input type="file" id="regexInput" accept=".json" multiple style="display:none;"><div class="upload-file-preview" id="regexUploadPreview" hidden></div><div class="form-hint" id="contentRequirementHint"></div></div>\',',
  '    \'          <div class="form-group project-upload-field"><label>\' + (isEdit ? \'替换预览图\' : \'预览图 (仅一张图片)\') + \'</label><div class="file-drop project-file-drop project-file-drop--cover" id="coverDrop">\' + (isEdit ? \'选择新图片\' : \'点击选择图片 (jpg/png/webp)\') + \'</div><input type="file" id="coverInput" accept="image/jpeg,image/png,image/webp" style="display:none;"><div class="upload-file-preview" id="coverUploadPreview" hidden></div></div>\',',
  '    \'        </div>\',',
  '    \'      </section>\',',
  '    \'    </div>\',',
  '    \'  </div>\',',
  '    \'  <div class="project-form-footer"><div class="project-form-footer-note"><i class="fas fa-circle-check"></i><span>选择文件后会先校验与预览，再提交到工坊。</span></div><button type="submit" class="btn btn-primary form-submit-btn"><i class="fas fa-cloud-upload-alt"></i> \' + (isEdit ? \'保存修改\' : \'创建并上传\') + \'</button></div>\',',
  "    '</form>',",
  "  ].join('');",
  '}',
  '',
  'function collectProjectFormPayload(form) {',
  "  const name = form.querySelector('#projName').value.trim();",
  "  const description = form.querySelector('#projDesc').value;",
  "  const versionLabel = form.querySelector('#versionLabel')?.value.trim() || null;",
  "  const projectType = form.querySelector('#baseTag').value;",
  "  const extensionType = projectType === '扩展' ? (form.querySelector('#extensionType')?.value || null) : null;",
  "  const rawCustomTags = parseTagsInput(form.querySelector('#customTags').value);",
  '  const facets = {};',
  '  if (projectType === "角色") {',
  '    form.querySelectorAll("[data-facet-group]:checked").forEach(input => {',
  '      const group = String(input.dataset.facetGroup || "");',
  '      if (!group) return;',
  '      if (!Array.isArray(facets[group])) facets[group] = [];',
  '      facets[group].push(String(input.value));',
  '    });',
  '  }',
  '  const officialTagValues = new Set(Object.values(facets).flat().map(String));',
  '  const customTags = rawCustomTags.filter(tag => !officialTagValues.has(tag));',
  '  const tagPool = new Set([...officialTagValues, ...customTags]);',
  '  const displayTags = Array.from(form.querySelectorAll("[data-display-tag]:checked")).map(input => String(input.value)).filter(tag => tagPool.has(tag));',
  "  const legacyBaseTag = projectType === '系统核心' ? '系统' : projectType;",
  '  return { name, description, versionLabel, projectType, extensionType, facets, customTags, displayTags, tags: [legacyBaseTag, ...customTags] };',
  '}',
  '',
  'function prepareProjectForm(overlay) {',
  "  const form = overlay.querySelector('#projectForm');",
  "  const baseTagSelect = overlay.querySelector('#baseTag');",
  "  const extensionTypeGroup = overlay.querySelector('#extensionTypeGroup');",
  "  const characterFacetsGroup = overlay.querySelector('#characterFacetsGroup');",
  "  const customTagsInput = overlay.querySelector('#customTags');",
  "  const displayTagPicker = overlay.querySelector('#displayTagPicker');",
  "  const displayTagCount = overlay.querySelector('#displayTagCount');",
  "  const worldbookFileLabel = overlay.querySelector('#worldbookFileLabel');",
  "  const regexFileLabel = overlay.querySelector('#regexFileLabel');",
  "  const contentRequirementHint = overlay.querySelector('#contentRequirementHint');",
  "  const fileInput = overlay.querySelector('#fileInput');",
  "  const regexInput = overlay.querySelector('#regexInput');",
  "  const coverInput = overlay.querySelector('#coverInput');",
  "  const fileDrop = overlay.querySelector('#fileDrop');",
  "  const regexDrop = overlay.querySelector('#regexDrop');",
  "  const coverDrop = overlay.querySelector('#coverDrop');",
  "  const worldbookPreview = overlay.querySelector('#worldbookUploadPreview');",
  "  const regexPreview = overlay.querySelector('#regexUploadPreview');",
  "  const coverPreview = overlay.querySelector('#coverUploadPreview');",
  '  const worldbookEmptyText = fileDrop.textContent;',
  '  const regexEmptyText = regexDrop.textContent;',
  '  const coverEmptyText = coverDrop.textContent;',
  '  const uploadState = { worldbook: null, regex: null, regexFiles: [] };',
  '  const getCurrentFormTagPool = () => {',
  '    const official = baseTagSelect?.value === "角色" ? Array.from(form.querySelectorAll("[data-facet-group]:checked")).map(input => String(input.value).trim()).filter(Boolean) : [];',
  '    const custom = parseTagsInput(customTagsInput?.value || "");',
  '    return Array.from(new Set([...official, ...custom]));',
  '  };',
  '  const refreshDisplayTagPicker = () => {',
  '    if (!displayTagPicker) return;',
  '    const maxTags = Number(PROJECT_TAXONOMY.maxDisplayTags || 5);',
  '    const previousSelected = new Set(Array.from(displayTagPicker.querySelectorAll("[data-display-tag]:checked")).map(input => String(input.value)));',
  '    const pool = getCurrentFormTagPool();',
  '    const selected = new Set(Array.from(previousSelected).filter(tag => pool.includes(tag)).slice(0, maxTags));',
  '    displayTagPicker.innerHTML = pool.length ? pool.map(value => `<label class="taxonomy-chip display-tag-chip"><input type="checkbox" data-display-tag value="${escapeHtml(value)}"${selected.has(value) ? " checked" : ""}><span>${escapeHtml(value)}</span></label>`).join("") : `<div class="display-tag-picker-empty">先选择官方标签或填写自定义标签</div>`;',
  '    const updateCount = () => { if (displayTagCount) displayTagCount.textContent = `${displayTagPicker.querySelectorAll("[data-display-tag]:checked").length} / ${maxTags}`; };',
  '    displayTagPicker.querySelectorAll("[data-display-tag]").forEach(input => {',
  '      input.addEventListener("change", () => {',
  '        if (input.checked && displayTagPicker.querySelectorAll("[data-display-tag]:checked").length > maxTags) {',
  '          input.checked = false;',
  '          showToast(`首页展示标签最多 ${maxTags} 个`, "warning");',
  '        }',
  '        updateCount();',
  '      });',
  '    });',
  '    updateCount();',
  '  };',
  '  const refreshContentRequirementUi = () => {',
  '    const baseTag = baseTagSelect?.value || "系统核心";',
  '    const rule = getProjectContentRule(baseTag);',
  '    const worldbookRequired = (rule.required || []).includes("worldbook");',
  '    const eitherContent = (rule.anyOf || []).includes("worldbook") && (rule.anyOf || []).includes("regex");',
  '    if (extensionTypeGroup) extensionTypeGroup.hidden = baseTag !== "扩展";',
  '    if (characterFacetsGroup) characterFacetsGroup.hidden = baseTag !== "角色";',
  '    if (form.dataset.mode !== "edit") {',
  '      if (worldbookFileLabel) worldbookFileLabel.textContent = worldbookRequired ? "世界书文件 *" : (eitherContent ? "世界书文件 (二选一)" : "世界书文件 (可选)");',
  '      if (regexFileLabel) regexFileLabel.textContent = eitherContent ? "正则文件 (二选一)" : "正则文件 (可选)";',
  '    }',
  '    if (contentRequirementHint) contentRequirementHint.textContent = getProjectContentRequirementText(baseTag);',
  '  };',
  '  const normalizeCustomTagsInput = () => {',
  '    if (!customTagsInput) return;',
  '    const official = baseTagSelect?.value === "角色" ? new Set(Array.from(form.querySelectorAll("[data-facet-group]:checked")).map(input => String(input.value))) : new Set();',
  '    customTagsInput.value = parseTagsInput(customTagsInput.value).filter(tag => !official.has(tag)).join(", ");',
  '  };',
  '  if (baseTagSelect) baseTagSelect.addEventListener("change", () => { refreshContentRequirementUi(); refreshDisplayTagPicker(); });',
  '  if (characterFacetsGroup) characterFacetsGroup.addEventListener("change", refreshDisplayTagPicker);',
  '  if (customTagsInput) customTagsInput.addEventListener("input", refreshDisplayTagPicker);',
  '  if (customTagsInput) customTagsInput.addEventListener("blur", () => { normalizeCustomTagsInput(); refreshDisplayTagPicker(); });',
  '  refreshContentRequirementUi();',
  '  refreshDisplayTagPicker();',
  '  const bindPreviewClear = (container, kind, onClear) => {',
  '    const button = container?.querySelector(`[data-upload-preview-clear="${kind}"]`);',
  '    if (button) button.onclick = event => { event.stopPropagation(); onClear(); };',
  '  };',
  '  const refreshRegexSelection = async nextFiles => {',
  '    if (!nextFiles.length) {',
  '      uploadState.regex = null;',
  '      uploadState.regexFiles = [];',
  '      clearUploadPreview(regexPreview);',
  '      regexDrop.textContent = regexEmptyText;',
  '      return true;',
  '    }',
  '    try {',
  '      const prepared = await prepareRegexUploads(nextFiles);',
  '      uploadState.regex = prepared;',
  '      uploadState.regexFiles = prepared.files;',
  '      renderRegexUploadPreview(regexPreview, prepared);',
  '      regexDrop.textContent = `${prepared.files.length} 个正则 JSON（点击或拖入继续添加）`;',
  '      regexPreview.querySelectorAll("[data-regex-upload-remove]").forEach(button => {',
  '        button.onclick = event => {',
  '          event.stopPropagation();',
  '          const index = Number(button.dataset.regexUploadRemove);',
  '          if (!Number.isInteger(index)) return;',
  '          const remaining = uploadState.regexFiles.filter((_, fileIndex) => fileIndex !== index);',
  '          void refreshRegexSelection(remaining);',
  '        };',
  '      });',
  '      return true;',
  '    } catch (error) {',
  '      regexDrop.textContent = uploadState.regexFiles.length ? `${uploadState.regexFiles.length} 个正则 JSON（点击或拖入继续添加）` : regexEmptyText;',
  '      if (uploadState.regex) showToast("未添加正则文件：" + error.message, "error");',
  '      else renderUploadPreviewError(regexPreview, error);',
  '      return false;',
  '    }',
  '  };',
  '  bindFileDrop(fileDrop, fileInput, worldbookEmptyText, async files => {',
  '    uploadState.worldbook = null;',
  '    clearUploadPreview(worldbookPreview);',
  '    if (!files[0]) return;',
  '    try {',
  '      const prepared = await prepareWorldbookUpload(files[0]);',
  '      uploadState.worldbook = prepared;',
  '      renderWorldbookUploadPreview(worldbookPreview, prepared);',
  '      bindPreviewClear(worldbookPreview, "worldbook", () => {',
  '        fileInput.value = "";',
  '        uploadState.worldbook = null;',
  '        clearUploadPreview(worldbookPreview);',
  '        fileDrop.textContent = worldbookEmptyText;',
  '      });',
  '    } catch (error) {',
  '      renderUploadPreviewError(worldbookPreview, error);',
  '    }',
  '  });',
  '  bindFileDrop(regexDrop, regexInput, regexEmptyText, async files => {',
  '    const previousRegex = uploadState.regex;',
  '    uploadState.regex = null;',
  '    clearUploadPreview(regexPreview);',
  '    if (!files.length) return;',
  '    try {',
  '      const prepared = await prepareRegexUploads(files);',
  '      uploadState.regex = prepared;',
  '      renderRegexUploadPreview(regexPreview, prepared);',
  '    } catch (error) {',
  '      uploadState.regex = previousRegex;',
  '      if (previousRegex) {',
  '        renderRegexUploadPreview(regexPreview, previousRegex);',
  '        showToast("未添加正则文件：" + error.message, "error");',
  '      } else {',
  '        renderUploadPreviewError(regexPreview, error);',
  '      }',
  '      return false;',
  '    }',
  '  });',
  '  regexPreview.addEventListener("click", event => {',
  '    const button = event.target.closest("[data-regex-upload-remove]");',
  '    if (!button) return;',
  '    event.stopPropagation();',
  '    const index = Number(button.dataset.regexUploadRemove);',
  '    if (!Number.isInteger(index)) return;',
  '    const remaining = (uploadState.regex?.files || []).filter((_, fileIndex) => fileIndex !== index);',
  '    void regexInput._fileDropController?.setFiles(remaining);',
  '  });',
  '  bindFileDrop(coverDrop, coverInput, coverEmptyText, async files => {',
  '    clearUploadPreview(coverPreview);',
  '    if (!files[0]) return;',
  '    try {',
  '      await renderCoverUploadPreview(coverPreview, files[0]);',
  '      bindPreviewClear(coverPreview, "cover", () => {',
  '        coverInput.value = "";',
  '        clearUploadPreview(coverPreview);',
  '        coverDrop.textContent = coverEmptyText;',
  '      });',
  '    } catch (error) {',
  '      renderUploadPreviewError(coverPreview, error);',
  '    }',
  '  });',
  '  return { form, fileInput, regexInput, coverInput, uploadState, submitBtn: overlay.querySelector(".form-submit-btn") };',
  '}',
  '',
  'function setSubmitState(button, pendingText, idleText, pending) {',
  '  if (!button) return;',
  '  button.disabled = pending;',
  '  button.textContent = pending ? pendingText : idleText;',
  '}',
  '',
  'function openUploadModal() {',
  '  if (!state.currentUser) {',
  "    showToast('请先登录', 'warning');",
  '    return;',
  '  }',
  "  const overlay = openModal(buildProjectFormHtml('create'), '<i class=\"fas fa-cloud-upload-alt\"></i> 上传项目');",
  "  overlay.classList.add('project-form-modal');",
  '  const { form, fileInput, regexInput, coverInput, uploadState, submitBtn } = prepareProjectForm(overlay);',
  '  form.onsubmit = async event => {',
  '    event.preventDefault();',
  "    setSubmitState(submitBtn, '上传中...', '创建并上传', true);",
  '    const payload = collectProjectFormPayload(form);',
  '    const hasWorldbook = Boolean(fileInput.files[0]);',
  '    const hasRegex = Boolean(uploadState.regex?.uploadFile);',
  '    if (!payload.name) {',
  "      showToast('请填写项目名称', 'warning');",
  "      setSubmitState(submitBtn, '上传中...', '创建并上传', false);",
  '      return;',
  '    }',
  '    const taxonomyValidation = validateProjectTaxonomySelection(payload);',
  '    if (!taxonomyValidation.valid) {',
  '      showToast(taxonomyValidation.error, "warning");',
  "      setSubmitState(submitBtn, '上传中...', '创建并上传', false);",
  '      return;',
  '    }',
  '    const contentValidation = validateProjectContentSelection(payload.projectType, hasWorldbook, hasRegex);',
  '    if (!contentValidation.valid) {',
  '      showToast(contentValidation.error, "warning");',
  "      setSubmitState(submitBtn, '上传中...', '创建并上传', false);",
  '      return;',
  '    }',
  '    try {',
  '      const preparedWorldbook = hasWorldbook ? (uploadState.worldbook || await prepareWorldbookUpload(fileInput.files[0])) : null;',
  '      const preparedRegex = uploadState.regex?.uploadFile ? uploadState.regex : null;',
  '      const createRes = await createProject(payload);',
  '      const projectId = createRes.projectId;',
  '      if (preparedWorldbook?.file) await uploadProjectFile(projectId, preparedWorldbook.file);',
  '      if (preparedRegex?.uploadFile) await uploadRegexFile(projectId, preparedRegex.uploadFile);',
  '      if (coverInput.files[0]) await uploadCoverFile(projectId, coverInput.files[0]);',
  "      showToast('项目上传成功，等待审核');",
  '      overlay.remove();',
  '      await fetchProjects();',
  '    } catch (error) {',
  "      showToast('上传失败: ' + error.message, 'error');",
  '    } finally {',
  "      setSubmitState(submitBtn, '上传中...', '创建并上传', false);",
  '    }',
  '  };',
  '}',
  '',
  'function openEditProjectModal(project) {',
  "  const overlay = openModal(buildProjectFormHtml('edit', project), '<i class=\"fas fa-edit\"></i> 修改项目');",
  "  overlay.classList.add('project-form-modal');",
  "  overlay.querySelectorAll('[data-entry-toggle]').forEach(header => {",
  "    header.addEventListener('click', event => {",
  "      if (event.target.closest('button,input,label')) return;",
  "      header.classList.toggle('open');",
  '      const content = header.nextElementSibling;',
  "      if (content) content.classList.toggle('open');",
  '    });',
  '  });',
  "  overlay.querySelectorAll('[data-entry-remove]').forEach(button => {",
  "    button.addEventListener('click', async event => {",
  '      event.stopPropagation();',
  '      const projectId = button.dataset.projectId;',
  '      const kind = button.dataset.entryKind;',
  '      const entryKey = button.dataset.entryKey;',
  '      if (!projectId || !kind || !entryKey) return;',
  "      if (!confirm('确定从当前项目中移除此条内容？修改会进入审核草稿。')) return;",
  "      const restore = setButtonLoading(button, '删除中');",
  '      try {',
  '        const result = await removeProjectEntry(projectId, kind, entryKey);',
  "        showToast('条目已移除，已切换到最新草稿');",
  '        overlay.remove();',
  '        await fetchProjects(true);',
  '        const targetId = result.projectId || projectId;',
  '        const nextDetail = await fetchProjectEntries(targetId, { forceRefresh: true });',
  '        const nextProject = nextDetail.project ? { ...nextDetail.project, publishedVersion: project.publishedVersion } : { ...project, id: targetId };',
  '        openEditProjectModal(nextProject);',
  '      } catch (error) {',
  "        showToast('删除失败: ' + error.message, 'error');",
  '      } finally { restore(); }',
  '    });',
  '  });',
  '  const { form, fileInput, regexInput, coverInput, uploadState, submitBtn } = prepareProjectForm(overlay);',
  '  form.onsubmit = async event => {',
  '    event.preventDefault();',
  "    setSubmitState(submitBtn, '保存中...', '保存修改', true);",
  '    const payload = collectProjectFormPayload(form);',
  '    const hasNewFile = Boolean(fileInput.files[0]);',
  '    const hasNewRegex = Boolean(uploadState.regex?.uploadFile);',
  '    const hasNewCover = Boolean(coverInput.files[0]);',
  '    const hasExistingWorldbook = Array.isArray(project?.worldbookEntriesPreview) && project.worldbookEntriesPreview.length > 0;',
  '    const hasExistingRegex = Array.isArray(project?.regexEntriesPreview) && project.regexEntriesPreview.length > 0;',
  '    if (!payload.name && !hasNewFile && !hasNewRegex && !hasNewCover) {',
  "      showToast('请至少填写项目名称或上传文件', 'warning');",
  "      setSubmitState(submitBtn, '保存中...', '保存修改', false);",
  '      return;',
  '    }',
  '    const taxonomyValidation = validateProjectTaxonomySelection(payload);',
  '    if (!taxonomyValidation.valid) {',
  '      showToast(taxonomyValidation.error, "warning");',
  "      setSubmitState(submitBtn, '保存中...', '保存修改', false);",
  '      return;',
  '    }',
  '    const contentValidation = validateProjectContentSelection(payload.projectType, hasNewFile || hasExistingWorldbook, hasNewRegex || hasExistingRegex);',
  '    if (!contentValidation.valid) {',
  '      showToast(contentValidation.error, "warning");',
  "      setSubmitState(submitBtn, '保存中...', '保存修改', false);",
  '      return;',
  '    }',
  '    try {',
  '      const preparedWorldbook = hasNewFile ? (uploadState.worldbook || await prepareWorldbookUpload(fileInput.files[0])) : null;',
  '      const preparedRegex = hasNewRegex ? uploadState.regex : null;',
  '      const updateResult = await updateProject(project.id, payload);',
  '      const targetProjectId = updateResult.draftProjectId || updateResult.projectId || project.id;',
  '      if (preparedWorldbook?.file) await uploadProjectFile(targetProjectId, preparedWorldbook.file);',
  '      if (preparedRegex?.uploadFile) await uploadRegexFile(targetProjectId, preparedRegex.uploadFile);',
  '      if (hasNewCover) await uploadCoverFile(targetProjectId, coverInput.files[0]);',
  "      showToast(hasNewFile || hasNewRegex || hasNewCover ? '修改已提交审核，主页仍显示旧版本' : (project.status === 'rejected' ? '项目已重新提交审核' : '项目更新成功'));",
  '      overlay.remove();',
  '      await fetchProjects();',
  '    } catch (error) {',
  "      showToast('更新失败: ' + error.message, 'error');",
  '    } finally {',
  "      setSubmitState(submitBtn, '保存中...', '保存修改', false);",
  '    }',
  '  };',
  '}',
  '',
  'function renderAdminReviewCard(project, index, total) {',
  '  const coverSources = getCoverImageSources(project);',
  '  const typeLabel = getProjectTypeDisplayLabel(project);',
  '  return `',
  '    <article class="admin-review-card" data-review-card data-project-id="${escapeHtml(String(project.id || ""))}" role="button" tabindex="0" aria-label="查看审核详情：${escapeHtml(project.name || "未命名项目")}">',
  '      <div class="admin-review-card-grid">',
  '        <div class="admin-review-thumb" data-cover-src="${escapeHtml(coverSources.primary)}" data-cover-fallback-src="${escapeHtml(coverSources.fallback)}" data-cover-placeholder-src="${escapeHtml(coverSources.placeholder)}" data-cover-auth-src="${escapeHtml(coverSources.authenticated || "")}" style="background-image:url(\'${escapeHtml(coverSources.primary)}\')"></div>',
  '        <div class="admin-review-card-body">',
  '          <div class="admin-review-card-head">',
  '            <span class="admin-review-position" data-review-position>${index + 1}/${total}</span>',
  '            <div class="admin-review-card-heading">',
  '              <div class="admin-review-title-line"><span class="type-badge ${getTypeClass(project)}">${escapeHtml(typeLabel)}</span><span class="admin-review-title">${escapeHtml(project.name || "未命名项目")}</span></div>',
  '              <div class="admin-review-author"><i class="fas fa-user"></i> ${escapeHtml(getAuthorName(project))}</div>',
  '            </div>',

  '          </div>',
  '          <div class="admin-review-card-actions">',
  '            <button class="btn btn-primary" type="button" data-id="${escapeHtml(String(project.id || ""))}" data-action="detail"><i class="fas fa-magnifying-glass"></i> 查看详情</button>',
  '            <button class="btn btn-outline" type="button" data-id="${escapeHtml(String(project.id || ""))}" data-action="skip"><i class="fas fa-forward"></i> 跳过</button>',
  '          </div>',
  '        </div>',
  '      </div>',
  '    </article>',
  '  `;',
  '}',
  '',
  'function refreshAdminReviewPositions(overlay) {',
  '  const cards = Array.from(overlay.querySelectorAll("[data-review-card]"));',
  '  cards.forEach((card, index) => {',
  '    const position = card.querySelector("[data-review-position]");',
  '    if (position) position.textContent = `${index + 1}/${cards.length}`;',
  '  });',
  '}',
  '',
  'function skipAdminReviewCard(overlay, projectId) {',
  '  const card = Array.from(overlay.querySelectorAll("[data-review-card]")).find(item => item.dataset.projectId === String(projectId));',
  '  if (!card || !card.parentElement) return;',
  '  const list = card.parentElement;',
  '  list.appendChild(card);',
  '  card.classList.remove("is-skipped");',
  '  void card.offsetWidth;',
  '  card.classList.add("is-skipped");',
  '  refreshAdminReviewPositions(overlay);',
  '  const nextCard = list.querySelector("[data-review-card]");',
  '  nextCard?.scrollIntoView({ behavior: "smooth", block: "nearest" });',
  "  showToast('已跳过，项目已移到队尾', 'info');",
  '}',
  '',
  'function renderAdminInspectionSignals(entries, regexEntries) {',
  '  const worldbookEntries = Array.isArray(entries) ? entries : [];',
  '  const regexList = Array.isArray(regexEntries) ? regexEntries : [];',
  '  const allEntries = [...worldbookEntries, ...regexList];',
  '  const hasInspectionData = allEntries.some(entry => entry && (Object.prototype.hasOwnProperty.call(entry, "hasEjs") || Object.prototype.hasOwnProperty.call(entry, "hasCharacterArtwork") || Object.prototype.hasOwnProperty.call(entry, "inspectionWarnings") || Object.prototype.hasOwnProperty.call(entry, "externalLinks")));',
  '  const hasEjs = allEntries.some(entry => Boolean(entry?.hasEjs));',
  '  const hasCharacterArtwork = allEntries.some(entry => Boolean(entry?.hasCharacterArtwork));',
  '  const warningCount = allEntries.reduce((count, entry) => count + (Array.isArray(entry?.inspectionWarnings) ? entry.inspectionWarnings.length : 0), 0);',
  '  const externalLinkCount = collectProjectExternalLinks(worldbookEntries, regexList).reduce((count, group) => count + group.links.length, 0);',
  '  const signals = [',
  '    `<span class="admin-review-signal"><i class="fas fa-book-open"></i> 世界书 ${worldbookEntries.length}</span>`,',
  '    `<span class="admin-review-signal"><i class="fas fa-code"></i> 正则 ${regexList.length}</span>`,',
  '  ];',
  '  if (hasInspectionData && hasEjs) signals.push(`<span class="admin-review-signal admin-review-signal--ejs">EJS</span>`);',
  '  if (hasInspectionData && hasCharacterArtwork) signals.push(`<span class="admin-review-signal admin-review-signal--good">👍🏻 角色立绘</span>`);',
  '  if (hasInspectionData && externalLinkCount) signals.push(`<span class="admin-review-signal admin-review-signal--info"><i class="fas fa-link"></i> 外链 ${externalLinkCount}</span>`);',
  '  if (hasInspectionData && warningCount) signals.push(`<span class="admin-review-signal admin-review-signal--warning"><i class="fas fa-triangle-exclamation"></i> ${warningCount} 个检查警告</span>`);',
  '  return `<div class="admin-review-signals">${signals.join("")}</div>`;',
  '}',
  '',
  'function bindAdminReviewEntryToggles(overlay) {',
  "  overlay.querySelectorAll('[data-entry-toggle]').forEach(header => {",
  "    header.addEventListener('click', () => {",
  "      header.classList.toggle('open');",
  '      const content = header.nextElementSibling;',
  "      if (content) content.classList.toggle('open');",
  '    });',
  '  });',
  '}',
  '',
  'function getAdminReviewQueueProjects(queueOverlay, queueProjects) {',
  '  const source = Array.isArray(queueProjects) ? queueProjects : [];',
  '  const byId = new Map(source.map(item => [String(item.id), item]));',
  '  return Array.from(queueOverlay?.querySelectorAll?.("[data-review-card]") || []).map(card => byId.get(String(card.dataset.projectId))).filter(Boolean);',
  '}',
  '',
  'function getAdminReviewAdjacentProject(queueOverlay, queueProjects, projectId, direction) {',
  '  const ordered = getAdminReviewQueueProjects(queueOverlay, queueProjects);',
  '  if (ordered.length <= 1) return null;',
  '  const currentIndex = ordered.findIndex(item => String(item.id) === String(projectId));',
  '  if (currentIndex < 0) return null;',
  '  const nextIndex = currentIndex + (direction < 0 ? -1 : 1);',
  '  if (nextIndex < 0 || nextIndex >= ordered.length) return null;',
  '  return ordered[nextIndex] || null;',
  '}',
  '',
  'function removeAdminReviewQueueProject(queueOverlay, queueProjects, projectId) {',
  '  const card = Array.from(queueOverlay?.querySelectorAll?.("[data-review-card]") || []).find(item => item.dataset.projectId === String(projectId));',
  '  card?.remove();',
  '  if (Array.isArray(queueProjects)) {',
  '    const index = queueProjects.findIndex(item => String(item.id) === String(projectId));',
  '    if (index >= 0) queueProjects.splice(index, 1);',
  '  }',
  '  refreshAdminReviewPositions(queueOverlay);',
  '  const count = queueOverlay?.querySelector(".admin-review-queue-summary strong");',
  '  if (count) count.textContent = String(queueOverlay.querySelectorAll("[data-review-card]").length);',
  '}',
  '',
  'async function openAdminReviewDetail(project, queueOverlay, queueProjects = []) {',
  '  const loadingOverlay = openModal(\'<div class="detail-loading"><div class="loading-spinner"></div><div class="detail-loading-text">正在加载审核内容...</div></div>\', \'<i class="fas fa-clipboard-check"></i> 审核详情\');',
  '  try {',
  '    const detail = await fetchAdminReviewDetail(project.id);',
  '    loadingOverlay.remove();',
  '    const reviewProjectData = detail.project || project;',
  '    const entries = detail.worldbookEntriesPreview || detail.project?.worldbookEntriesPreview || [];',
  '    const regexEntries = detail.regexEntriesPreview || detail.project?.regexEntriesPreview || [];',
  '    const reviewDiff = detail.reviewDiff || null;',
  '    const isDiffReview = reviewDiff?.mode === "update";',
  '    const contentReviewHtml = isDiffReview ? `${renderAdminReviewDiffSummary(reviewDiff)}${renderAdminReviewDiffSection("世界书变化", "fa-scroll", reviewDiff.worldbook, "worldbook")}${renderAdminReviewDiffSection("正则变化", "fa-code", reviewDiff.regex, "regex")}` : `${renderDetailSection("世界书条目", "fa-scroll", entries, renderDetailEntry, "无世界书内容")}${renderDetailSection("正则列表", "fa-code", regexEntries, renderRegexEntry, "无正则内容")}`;',
  '    const description = String(reviewProjectData.description || "暂无项目简介").trim() || "暂无项目简介";',
  '    const orderedQueueProjects = getAdminReviewQueueProjects(queueOverlay, queueProjects);',
  '    const currentQueueIndex = orderedQueueProjects.findIndex(item => String(item.id) === String(project.id));',
  '    const canPrev = currentQueueIndex > 0;',
  '    const canNext = currentQueueIndex >= 0 && currentQueueIndex < orderedQueueProjects.length - 1;',
  '    const bodyHtml = [',
  '      `<div class="admin-review-detail-shell">`,',
  '      `<section class="admin-review-summary">`,',
  '      `<div class="admin-review-summary-head"><span class="type-badge ${getTypeClass(reviewProjectData)}">${escapeHtml(getBaseTag(reviewProjectData))}</span><div class="admin-review-summary-heading"><h3>${escapeHtml(reviewProjectData.name || "未命名项目")}</h3><div>${escapeHtml(getAuthorName(reviewProjectData))}</div></div></div>`,',
  '      renderAdminInspectionSignals(entries, regexEntries),',
  '      `<details class="admin-review-description"><summary><span><i class="fas fa-align-left"></i> 项目简介</span><span class="admin-review-description-hint">点击展开 / 收起</span></summary><div class="admin-review-description-body">${escapeHtml(description)}</div></details>`,',
  '      `</section>`,',
  '      renderExternalLinksPanel(entries, regexEntries, { title: "审核外链", notice: "静态检测结果，仅供审核定位；未访问、未验证这些 URL 的远端内容。" }),',
  '      contentReviewHtml,',
  '      `<div class="admin-review-sticky-actions">`,',
  '      `<button class="btn btn-outline" type="button" data-admin-review-back><i class="fas fa-arrow-left"></i> 返回队列</button>`,',
  '      `<button class="btn btn-outline" type="button" data-admin-review-prev ${canPrev ? "" : "disabled"}><i class="fas fa-chevron-left"></i> 上一个</button>`,',
  '      `<button class="btn btn-outline" type="button" data-admin-review-next ${canNext ? "" : "disabled"}>下一个 <i class="fas fa-chevron-right"></i></button>`,',
  '      `<button class="btn admin-review-reject-btn" type="button" data-admin-review-submit="reject"><i class="fas fa-xmark"></i> 拒绝</button>`,',
  '      `<button class="btn admin-review-approve-btn" type="button" data-admin-review-submit="approve"><i class="fas fa-check"></i> 批准</button>`,',
  '      `</div></div>`,',
  '    ].join("");',
  '    const overlay = openModal(bodyHtml, `<i class="fas fa-clipboard-check"></i> 审核详情`);',
  '    overlay.classList.add("admin-review-detail-overlay");',
  '    overlay.querySelector(".modal-content")?.classList.add("admin-review-detail-modal");',
  '    bindAdminReviewEntryToggles(overlay);',
  '    if (isDiffReview) bindAdminReviewDiffLazyContent(overlay, reviewDiff);',
  '    overlay.querySelector("[data-admin-review-back]")?.addEventListener("click", () => overlay.remove());',
  '    const openAdjacent = direction => {',
  '      const adjacent = getAdminReviewAdjacentProject(queueOverlay, queueProjects, project.id, direction);',
  '      if (!adjacent) return;',
  '      overlay.remove();',
  '      openAdminReviewDetail(adjacent, queueOverlay, queueProjects);',
  '    };',
  '    overlay.querySelector("[data-admin-review-prev]")?.addEventListener("click", () => openAdjacent(-1));',
  '    overlay.querySelector("[data-admin-review-next]")?.addEventListener("click", () => openAdjacent(1));',
  '    overlay.querySelectorAll("[data-admin-review-submit]").forEach(button => {',
  '      button.addEventListener("click", async () => {',
  '        const action = button.dataset.adminReviewSubmit;',
  '        if (action !== "approve" && action !== "reject") return;',
  '        if (action === "approve" && !confirm(`确定批准「${reviewProjectData.name || "该项目"}」吗？`)) return;',
  '        let rejectReason;',
  '        if (action === "reject") {',
  "          rejectReason = prompt('请输入拒绝原因');",
  '          if (!rejectReason) return;',
  '        }',
  '        const restore = setButtonLoading(button, action === "approve" ? "批准中" : "拒绝中");',
  '        try {',
  '          const orderedBefore = getAdminReviewQueueProjects(queueOverlay, queueProjects);',
  '          const currentIndex = orderedBefore.findIndex(item => String(item.id) === String(project.id));',
  '          await reviewProject(project.id, { action, ...(rejectReason ? { rejectReason } : {}), expectedRevision: project?.draftRevision || reviewProjectData?.draftRevision });',
  "          showToast(action === 'approve' ? '已批准' : '已拒绝');",
  '          overlay.remove();',
  '          removeAdminReviewQueueProject(queueOverlay, queueProjects, project.id);',
  '          await fetchProjects(true).catch(error => console.warn("刷新项目列表失败，继续审核队列", error));',
  '          const remaining = getAdminReviewQueueProjects(queueOverlay, queueProjects);',
  '          if (remaining.length > 0) {',
  '            const nextIndex = currentIndex >= 0 && currentIndex < remaining.length ? currentIndex : 0;',
  '            openAdminReviewDetail(remaining[nextIndex], queueOverlay, queueProjects);',
  '          } else {',
  '            const sort = queueOverlay?.dataset.reviewSort || "oldest";',
  '            const projectType = queueOverlay?.dataset.reviewProjectType || "";',
  '            queueOverlay.remove();',
  '            openAdminPanel({ sort, projectType });',
  '          }',
  '        } catch (error) {',
  "          showToast(error.message, 'error');",
  '        } finally { restore(); }',
  '      });',
  '    });',
  '  } catch (error) {',
  '    loadingOverlay.remove();',
  "    showToast('加载审核详情失败: ' + error.message, 'error');",
  '  }',
  '}',
  '',
  'async function openAdminPanel(options = {}) {',
  '  if (!state.currentUser?.isAdmin) {',
  "    showToast('无权限', 'error');",
  '    return;',
  '  }',
  '  const sort = options.sort === "latest" ? "latest" : "oldest";',
  '  const projectType = BASE_TAGS.includes(options.projectType) ? options.projectType : "";',
  '  try {',
  '    const data = await fetchPendingProjects({ sort, projectType });',
  '    const pending = data.projects || [];',
  '    const total = Number(data.total ?? pending.length);',
  '    const typeOptions = ["", "角色", "系统核心", "扩展", "事件"];',
  '    const toolbarHtml = `<div class="admin-review-toolbar"><label class="admin-review-sort-control"><span>排序</span><select data-admin-review-sort><option value="oldest" ${sort === "oldest" ? "selected" : ""}>最旧优先</option><option value="latest" ${sort === "latest" ? "selected" : ""}>最新优先</option></select></label><div class="admin-review-type-filters">${typeOptions.map(type => `<button type="button" class="admin-review-filter-btn ${type === projectType ? "active" : ""}" data-admin-review-type="${escapeHtml(type)}">${escapeHtml(type || "全部")}</button>`).join("")}</div></div>`;',
  '    const summaryHtml = `<div class="admin-review-queue-summary"><div><strong>${total}</strong> 个项目等待审核</div><span>点击卡片或「查看详情」进入完整审核</span></div>`;',
  '    const listHtml = pending.length ? `<div class="admin-review-list">${pending.map((project, index) => renderAdminReviewCard(project, index, pending.length)).join("")}</div>` : `<div class="empty-state"><i class="fas fa-circle-check"></i><div>当前筛选下暂无待审核项目</div></div>`;',
  '    const html = `<div class="admin-review-queue">${toolbarHtml}${summaryHtml}${listHtml}</div>`;',
  "    const overlay = openModal(html, '<i class=\"fas fa-clipboard-check\"></i> 审核中心');",
  '    overlay.classList.add("admin-review-overlay");',
  '    overlay.dataset.reviewSort = sort;',
  '    overlay.dataset.reviewProjectType = projectType;',
  '    overlay.querySelector(".modal-content")?.classList.add("admin-review-modal");',
  '    bindCoverImageFallbacks(overlay);',
  '    overlay.querySelector("[data-admin-review-sort]")?.addEventListener("change", event => {',
  '      const nextSort = event.target?.value === "latest" ? "latest" : "oldest";',
  '      overlay.remove();',
  '      openAdminPanel({ sort: nextSort, projectType });',
  '    });',
  '    overlay.querySelectorAll("[data-admin-review-type]").forEach(button => {',
  '      button.addEventListener("click", () => {',
  '        const nextType = button.dataset.adminReviewType || "";',
  '        if (nextType === projectType) return;',
  '        overlay.remove();',
  '        openAdminPanel({ sort, projectType: nextType });',
  '      });',
  '    });',
  "    overlay.querySelectorAll('button[data-action]').forEach(button => {",
  "      button.addEventListener('click', async () => {",
  '        const projectId = button.dataset.id;',
  '        const action = button.dataset.action;',
  '        const project = pending.find(item => String(item.id) === String(projectId));',
  '        if (!projectId || !project) return;',
  "        if (action === 'skip') {",
  '          skipAdminReviewCard(overlay, projectId);',
  '          return;',
  '        }',
  "        if (action === 'detail') {",
  "          const restore = setButtonLoading(button, '加载审核内容');",
  '          Promise.resolve(openAdminReviewDetail(project, overlay, pending)).finally(restore);',
  '        }',
  '      });',
  '    });',
  '    overlay.querySelectorAll("[data-review-card]").forEach(card => {',
  '      const openFromCard = event => {',
  '        if (event?.target?.closest?.("button, select")) return;',
  '        const project = pending.find(item => String(item.id) === String(card.dataset.projectId));',
  '        if (project) openAdminReviewDetail(project, overlay, pending);',
  '      };',
  '      card.addEventListener("click", openFromCard);',
  '      card.addEventListener("keydown", event => {',
  '        if (event.key !== "Enter" && event.key !== " ") return;',
  '        event.preventDefault();',
  '        openFromCard(event);',
  '      });',
  '    });',
  '  } catch (error) {',
  "    showToast(error.message, 'error');",
  '  }',
  '}',
  '',

  'async function openAdminLogsModal() {',
  '  if (!state.currentUser?.isSuperAdmin) {',
  "    showToast('无权限', 'error');",
  '    return;',
  '  }',
  '  try {',
  '    const data = await fetchAdminLogs();',
  '    const logs = data.logs || [];',
  '    const actionLabels = { project_approved: "批准项目", project_rejected: "拒绝项目", admin_added: "添加管理员", admin_removed: "移除管理员" };',
  '    const html = logs.length ? logs.map(log => {',
  '      let detail = {};',
  '      try { detail = log.detail ? JSON.parse(log.detail) : {}; } catch { detail = {}; }',
  '      const actionLabel = actionLabels[log.action] || log.action;',
  '      const projectName = detail.projectName ? `<strong>${escapeHtml(detail.projectName)}</strong>` : escapeHtml(log.targetType || "操作记录");',
  '      const rejectHtml = detail.rejectReason ? `<div class="admin-log-reason"><strong>拒绝原因：</strong>${escapeHtml(detail.rejectReason)}</div>` : "";',
  '      const traceRows = [',
  '        ["目标 ID", log.targetId],',
  '        ["修订号", detail.draftRevision],',
  '        ["审核目标", detail.reviewTarget],',
  '        ["发布项目 ID", detail.publishedProjectId],',
  '        ["项目创建", detail.projectCreatedAt ? formatDateTime(detail.projectCreatedAt) : null],',
  '        ["项目更新", detail.projectUpdatedAt ? formatDateTime(detail.projectUpdatedAt) : null],',
  '        ["版本变化", detail.previousVersion && detail.version ? `${detail.previousVersion} → ${detail.version}` : detail.version],',
  '        ["版本名称", detail.versionLabel],',
  '      ].filter(([, value]) => value !== undefined && value !== null && value !== "");',
  '      const traceHtml = traceRows.length ? `<details class="admin-log-trace"><summary>追踪信息</summary>${traceRows.map(([label, value]) => `<div><span>${escapeHtml(label)}</span><code>${escapeHtml(String(value))}</code></div>`).join("")}</details>` : "";',
  '      return `<div class="admin-card admin-log-card"><div class="admin-log-head"><div><div class="admin-card-title">${escapeHtml(actionLabel)}</div><div>${projectName}</div></div><time>${escapeHtml(formatDateTime(log.createdAt))}</time></div><div class="admin-log-actor"><i class="fas fa-user-shield"></i> ${escapeHtml(log.actorName)} (${escapeHtml(log.actorId)})</div>${rejectHtml}${traceHtml}</div>`;',
  '    }).join("") : "<p>暂无日志</p>";',
  '    openModal(`<h3>管理员操作日志</h3>${html}`, `<i class=\\"fas fa-clock-rotate-left\\"></i> 操作日志`);',
  '  } catch (error) {',
  "    showToast('加载管理员日志失败: ' + (error && error.message ? error.message : '未知错误'), 'error');",
  '  }',
  '}',
  '',
  'async function openAddAdminModal() {',
  '  if (!state.currentUser?.isSuperAdmin) {',
  "    showToast('无权限', 'error');",
  '    return;',
  '  }',
  '  let admins = [];',
  '  try {',
  '    const data = await fetchAdminList();',
  '    admins = data.admins || [];',
  '  } catch (error) {',
  "    showToast('加载管理员列表失败: ' + (error && error.message ? error.message : '未知错误'), 'error');",
  '  }',
  '  const adminsHtml = admins.length',
  '    ? admins.map(admin => {',
  '        return \'<div class="admin-list-item">\'',
  "          + '<div><img src=\"' + escapeHtml(admin.avatarUrl || 'https://cdn.discordapp.com/embed/avatars/0.png') + '\" style=\"width:32px; height:32px; border-radius:50%; margin-right:8px; vertical-align:middle;\">'",
  "          + escapeHtml(admin.globalName || admin.username) + ' (' + escapeHtml(admin.id) + ')</div>'",
  '          + \'<button class="btn" data-id="\' + admin.id + \'" data-action="remove">移除管理员</button>\'',
  "          + '</div>';",
  "      }).join('')",
  "    : '<p>暂无管理员</p>';",
  '  const overlay = openModal(',
  '    [',
  "      '<div>',",
  "      '<h3>添加管理员</h3>',",
  '      \'<input type="text" id="targetUserId" placeholder="用户ID" style="width:100%; padding:8px; margin-bottom:16px;">\',',
  '      \'<button class="btn btn-primary" id="confirmAdd">设为管理员</button>\',',
  '      \'<hr style="margin:20px 0;">\',',
  "      '<h3>现有管理员列表</h3>',",
  "      '<div id=\"adminListContainer\">' + adminsHtml + '</div>',",
  "      '</div>',",
  "    ].join(''),",
  '    \'<i class="fas fa-user-shield"></i> 管理员设置\',',
  '  );',
  "  overlay.querySelector('#confirmAdd').onclick = async () => {",
  "    const targetId = overlay.querySelector('#targetUserId').value.trim();",
  '    if (!targetId) return;',
  '    try {',
  '      await setAdmin(targetId, true);',
  "      showToast('已设为管理员');",
  '      overlay.remove();',
  '      openAddAdminModal();',
  '    } catch (error) {',
  "      showToast(error.message, 'error');",
  '    }',
  '  };',
  '  overlay.querySelectorAll(\'button[data-action="remove"]\').forEach(button => {',
  "    button.addEventListener('click', async () => {",
  '      const userId = button.dataset.id;',
  "      if (!userId || !confirm('确定要移除该管理员吗？')) return;",
  '      try {',
  '        await setAdmin(userId, false);',
  "        showToast('已移除管理员');",
  '        overlay.remove();',
  '        openAddAdminModal();',
  '      } catch (error) {',
  "        showToast(error.message, 'error');",
  '      }',
  '    });',
  '  });',
  '}',
].join('\n');
