export const homeModalsScript = [
  'function openModal(contentHtml, titleHtml) {',
  '  const resolvedTitle = titleHtml || \'<i class="fas fa-pen"></i> 操作\';',
  "  const overlay = document.createElement('div');",
  "  overlay.className = 'modal-overlay';",
  '  overlay.innerHTML = [',
  '    \'<div class="modal-content">\',',
  '    \'  <div class="modal-header">\',',
  "    '    <h2>' + resolvedTitle + '</h2>',",
  '    \'    <button class="close-btn" type="button"><i class="fas fa-times"></i></button>\',',
  "    '  </div>',",
  "    '  <div class=\"modal-body\">' + contentHtml + '</div>',",
  "    '</div>',",
  "  ].join('');",
  '  const requestClose = () => {',
  "    if (overlay.dataset.dirty === 'true' && !confirm('有未保存的修改，确定放弃吗？')) return false;",
  '    overlay.remove();',
  '    return true;',
  '  };',
  "  overlay.addEventListener('click', event => {",
  "    if (event.target === overlay && overlay.dataset.dirty === 'true' && !confirm('有未保存的修改，确定放弃吗？')) event.stopImmediatePropagation();",
  '  }, true);',
  "  overlay.addEventListener('input', event => { if (event.target.closest('form')) overlay.dataset.dirty = 'true'; });",
  "  overlay.addEventListener('change', event => { if (event.target.closest('form')) overlay.dataset.dirty = 'true'; });",
  "  overlay.addEventListener('click', event => {",
  '    if (event.target === overlay) {',
  '      overlay.remove();',
  '    }',
  '  });',
  "  overlay.querySelector('.close-btn').addEventListener('click', requestClose);",
  '  document.body.appendChild(overlay);',
  '  bindCoverImageFallbacks(overlay);',
  '  return overlay;',
  '}',
  '',
  'function openReleaseNoticeModal() {',
  '  const bodyHtml = `',
  '    <div class="release-update-guide">',
  '      <p class="release-update-lead">旧版 Creative Workshop 脚本可能缺少新的安装、更新与兼容性修复。请更新到 <strong>v${WORKSHOP_RELEASE_VERSION}</strong>。</p>',
  '      <ol class="release-update-steps">',
  '        <li>点击下方按钮复制最新版导入代码。</li>',
  '        <li>回到 <strong>SillyTavern</strong>，打开 <strong>酒馆助手</strong>。</li>',
  '        <li>找到你现在使用的「命定创意工坊」脚本。</li>',
  '        <li>把旧的 <code>import ...</code> 整行替换成下面的新代码。</li>',
  '        <li>保存脚本，然后刷新 SillyTavern 或重新打开创意工坊。</li>',
  '      </ol>',
  '      <code class="release-update-code">${escapeHtml(WORKSHOP_RELEASE_IMPORT)}</code>',
  '      <button class="btn btn-primary release-update-copy-btn" id="releaseUpdateCopyBtn" type="button"><i class="fas fa-copy"></i> 复制最新版导入代码</button>',
  '    </div>',
  '  `;',
  '  const overlay = openModal(bodyHtml, `<i class="fas fa-rotate"></i> Creative Workshop 更新指南`);',
  '  const copyBtn = overlay.querySelector("#releaseUpdateCopyBtn");',
  '  if (copyBtn) copyBtn.addEventListener("click", async () => {',
  '    try {',
  '      await navigator.clipboard.writeText(WORKSHOP_RELEASE_IMPORT);',
  '      copyBtn.innerHTML = `<i class="fas fa-check"></i> 已复制`;',
  '      showToast("已复制。下一步：SillyTavern → 酒馆助手 → 替换旧 import → 保存并刷新。");',
  '    } catch (error) {',
  '      window.prompt("复制最新版 Creative Workshop 导入代码", WORKSHOP_RELEASE_IMPORT);',
  '    }',
  '  });',
  '}',
  '',
  'function setButtonLoading(button, pendingText) {',
  '  if (!button) return () => {};',
  '  const originalHtml = button.innerHTML;',
  '  button.disabled = true;',
  '  button.classList.add("is-loading");',
  '  button.innerHTML = `<span class="inline-loading-spinner"></span><span>${pendingText}</span>`;',
  '  return () => {',
  '    button.disabled = false;',
  '    button.classList.remove("is-loading");',
  '    button.innerHTML = originalHtml;',
  '  };',
  '}',
  '',
  'async function showProjectDetail(project) {',
  '  const loadingOverlay = openModal(\'<div class="detail-loading"><div class="loading-spinner"></div><div class="detail-loading-text">正在加载项目详情、世界书与正则内容...</div></div>\', \'<i class="fas fa-info-circle"></i> 项目详情\');',
  '  try {',
  '    const detail = await fetchProjectEntries(project);',
  '    loadingOverlay.remove();',
  '    const overlay = openModal(renderProjectDetail(detail.project || project, detail.entries || [], detail.regexEntries || []), \'<i class="fas fa-info-circle"></i> 项目详情\');',
  "    overlay.querySelectorAll('[data-entry-toggle]').forEach(header => {",
  "      header.addEventListener('click', () => {",
  "        header.classList.toggle('open');",
  '        const content = header.nextElementSibling;',
  "        if (content) content.classList.toggle('open');",
  '      });',
  '    });',
  "    overlay.querySelectorAll('.detail-install-btn,.install-btn').forEach(button => {",
  "      button.addEventListener('click', event => {",
  '        event.stopPropagation();',
  '        if (button.disabled) return;',
  '        const projectId = button.dataset.id || detail.project?.id || project.id;',
  '        if (!projectId) return;',
  '        const localMeta = getLocalProjectMeta(projectId);',
  '        if (localMeta) {',
  '          requestUninstallProject(projectId);',
  "          showToast('已发送卸载请求', 'info');",
  '        } else {',
  '          openInstallWorldbookModal(projectId, detail.project?.version || project.version);',

  '        }',
  '        overlay.remove();',
  '      });',
  '    });',
  "    overlay.querySelectorAll('.detail-update-btn,.update-btn').forEach(button => {",
  "      button.addEventListener('click', event => {",
  '        event.stopPropagation();',
  '        if (button.disabled) return;',
  '        const targetProject = detail.project || project;',
  '        if (!targetProject?.id) return;',
  '        const restore = setButtonLoading(button, "加载差异");',
  '        requestProjectDiff(targetProject.id, targetProject.version)',
  '          .then(diff => openProjectUpdateModal(targetProject, diff))',
  '          .catch(error => showToast("加载更新差异失败: " + error.message, "error"))',
  '          .finally(restore);',
  '      });',
  '    });',
  '  } catch (error) {',
  '    loadingOverlay.remove();',
  "    showToast('加载详情失败: ' + error.message, 'error');",
  '  }',
  '}',
  '',
  'function renderDiffGroup(title, icon, worldbookEntries, regexEntries) {',
  '  const hasWorldbook = Array.isArray(worldbookEntries) && worldbookEntries.length > 0;',
  '  const hasRegex = Array.isArray(regexEntries) && regexEntries.length > 0;',
  '  if (!hasWorldbook && !hasRegex) return "";',
  '  const worldbookHtml = hasWorldbook ? renderDetailSection("世界书条目", "fa-scroll", worldbookEntries, renderDetailEntry, "") : "";',
  '  const regexHtml = hasRegex ? renderDetailSection("正则列表", "fa-code", regexEntries, renderRegexEntry, "") : "";',
  '  return `<div class="update-diff-group"><div class="detail-section-title"><span><i class="fas ${icon}"></i> ${title}</span></div>${worldbookHtml}${regexHtml}</div>`;',
  '}',
  '',
  'function openProjectUpdateModal(project, resolvedDiff) {',
  '  const diff = resolvedDiff || getProjectUpdateDiff(project.id) || {',
  '    added: { worldbookEntries: [], regexEntries: [] },',
  '    modified: { worldbookEntries: [], regexEntries: [] },',
  '    removed: { worldbookEntries: [], regexEntries: [] },',
  '  };',
  '  const headerHtml = renderProjectDetail(project, [], []).replace(/<div class="detail-section">[\\s\\S]*$/, "</div>");',
  '  const bodyHtml = [',
  '    `<div class="update-modal">${headerHtml}`,',
  '    renderDiffGroup("新增内容", "fa-plus", diff.added?.worldbookEntries || [], diff.added?.regexEntries || []),',
  '    renderDiffGroup("修改内容", "fa-pen", diff.modified?.worldbookEntries || [], diff.modified?.regexEntries || []),',
  '    renderDiffGroup("删除内容", "fa-trash", diff.removed?.worldbookEntries || [], diff.removed?.regexEntries || []),',
  '    `<div class="update-modal-actions"><button class="btn btn-outline" data-update-cancel>取消</button><button class="btn btn-primary" data-update-confirm>确认更新</button></div></div>`,',
  '  ].join("");',
  '  const overlay = openModal(bodyHtml, `<i class="fas fa-arrows-rotate"></i> 更新项目`);',
  '  overlay.querySelector("[data-update-cancel]")?.addEventListener("click", () => overlay.remove());',
  '  overlay.querySelector("[data-update-confirm]")?.addEventListener("click", () => {',
  '    confirmProjectUpdate(project.id, project.version);',
  "    showToast('已发送更新请求', 'info');",
  '    overlay.remove();',
  '  });',
  '}',
  '',
  'function openInstallWorldbookModal(projectId, projectVersion) {',
  '  const worldbooks = state.tavern.worldbooks || {};',
  '  const primary = worldbooks.primary || null;',
  '  const additional = Array.isArray(worldbooks.additional) ? worldbooks.additional.filter(Boolean) : [];',

  '  const additionalCandidates = Array.from(new Set(additional)).filter(name => name !== primary);',

  '  const initialMode = primary ? "primary" : "additional";',
  '  const bodyHtml = `<form id="installWorldbookForm" class="install-worldbook-form"><div class="form-group"><label>安装位置</label><div class="install-target-switch"><button type="button" class="btn install-target-option${initialMode === "primary" ? " active" : ""}" data-install-target="primary"${primary ? "" : " disabled"}><i class="fas fa-book"></i><span>角色主世界书</span></button><button type="button" class="btn install-target-option${initialMode === "additional" ? " active" : ""}" data-install-target="additional"><i class="fas fa-layer-group"></i><span>附加世界书</span></button></div></div><div class="form-group install-additional-panel" data-additional-worldbook${initialMode === "additional" ? "" : " hidden"}><label for="additionalWorldbookSearch">选择附加世界书</label><div class="install-worldbook-search-wrap"><i class="fas fa-search"></i><input type="search" id="additionalWorldbookSearch" placeholder="搜索附加世界书" autocomplete="off"></div><div class="install-worldbook-list" data-additional-worldbook-list></div></div><button type="submit" class="btn install-submit-btn"><i class="fas fa-download"></i> 安装</button></form>`;',


  '  const overlay = openModal(bodyHtml, `<i class="fas fa-book"></i> 选择安装世界书`);',
  '  const form = overlay.querySelector("#installWorldbookForm");',
  '  const additionalPanel = overlay.querySelector("[data-additional-worldbook]");',
  '  const additionalSearch = overlay.querySelector("#additionalWorldbookSearch");',
  '  const additionalList = overlay.querySelector("[data-additional-worldbook-list]");',
  '  const targetButtons = Array.from(overlay.querySelectorAll("[data-install-target]"));',
  '  let installMode = initialMode;',
  '  let selectedAdditional = null;',
  '  const renderAdditionalList = query => {',
  '    if (!additionalList) return;',
  '    const keyword = String(query || "").trim().toLowerCase();',
  '    const matches = additionalCandidates.filter(name => !keyword || String(name).toLowerCase().includes(keyword));',
  '    if (!matches.length) {',
  '      additionalList.innerHTML = `<div class="install-worldbook-empty">${additionalCandidates.length ? "没有匹配的附加世界书" : "当前角色没有附加世界书"}</div>`;',
  '      return;',
  '    }',
  '    additionalList.innerHTML = matches.map(name => `<button type="button" class="install-worldbook-option${selectedAdditional === name ? " active" : ""}" data-worldbook-name="${escapeHtml(name)}"><i class="fas fa-book-open"></i><span>${escapeHtml(name)}</span><i class="fas fa-check"></i></button>`).join("");',
  '    additionalList.querySelectorAll("[data-worldbook-name]").forEach(button => button.addEventListener("click", () => {',
  '      selectedAdditional = button.dataset.worldbookName || null;',
  '      renderAdditionalList(additionalSearch?.value || "");',
  '    }));',
  '  };',
  '  const setInstallMode = mode => {',
  '    installMode = mode;',
  '    targetButtons.forEach(button => {',
  '      const active = button.dataset.installTarget === mode;',
  '      button.classList.toggle("active", active);',

  '    });',
  '    if (additionalPanel) additionalPanel.hidden = mode !== "additional";',
  '    if (mode === "additional") { renderAdditionalList(additionalSearch?.value || ""); additionalSearch?.focus(); }',
  '  };',
  '  targetButtons.forEach(button => button.addEventListener("click", () => setInstallMode(button.dataset.installTarget)));',
  '  additionalSearch?.addEventListener("input", () => renderAdditionalList(additionalSearch.value));',
  '  renderAdditionalList("");',

  '  form?.addEventListener("submit", event => {',
  '    event.preventDefault();',
  '    const worldbookName = installMode === "primary" ? String(primary || "").trim() : String(selectedAdditional || "").trim();',
  '    if (!worldbookName) { showToast(installMode === "primary" ? "当前角色没有主世界书" : "请先选择一个附加世界书", "warning"); return; }',
  '    requestInstallProject(projectId, { worldbookName, projectVersion });',
  '    showToast(`已发送安装请求：${worldbookName}`, "info");',
  '    overlay.dataset.dirty = "false";',
  '    overlay.remove();',
  '  });',
  '}',
  '',
  'function bindFileDrop(drop, input, emptyText) {',
  '  drop.onclick = () => input.click();',
  '  input.onchange = () => {',
  '    drop.textContent = input.files[0]?.name || emptyText;',
  '  };',
  '}',
  '',
  'async function validateJsonUpload(file, kind) {',
  '  if (!file) return null;',
  '  if (!String(file.name || "").toLowerCase().endsWith(".json")) {',
  '    throw new Error(kind === "worldbook" ? "世界书文件必须是 .json" : "正则文件必须是 .json");',
  '  }',
  '  let parsed;',
  '  try {',
  '    parsed = JSON.parse(await file.text());',
  '  } catch {',
  '    throw new Error(kind === "worldbook" ? "世界书文件不是有效 JSON" : "正则文件不是有效 JSON");',
  '  }',
  '  if (kind === "worldbook") {',
  '    const entries = parsed && typeof parsed === "object" ? parsed.entries : null;',
  '    const recognized = Array.isArray(parsed) || Array.isArray(entries) || (entries && typeof entries === "object" && !Array.isArray(entries));',
  '    if (!recognized) {',
  '      throw new Error("世界书 JSON 格式不正确：需要条目数组，或包含 entries 数组/对象");',
  '    }',
  '  }',
  '  return parsed;',
  '}',
  '',
  'function buildTagOptions(baseTagOptions, currentBaseTag) {',
  '  return baseTagOptions',
  "    .map(tag => '<option value=\"' + tag + '\"' + (tag === currentBaseTag ? ' selected' : '') + '>' + tag + '</option>')",
  "    .join('');",
  '}',
  '',
  'function buildVersionLabelHtml(project) {',
  '  const value = escapeHtml(project?.versionLabel || "");',
  '  return `<div class="form-group"><label>版本名称（可选）</label><input type="text" id="versionLabel" maxlength="80" value="${value}" placeholder="例如：4.2 Beta、夏季版、Final"><div class="form-hint">仅用于展示；更新版本由工坊自动管理。</div></div>`;',
  '}',
  '',
  'function buildProjectFormHtml(mode, project) {',
  "  const isEdit = mode === 'edit';",
  '  const baseTagOptions = BASE_TAGS;',
  '  const currentBaseTag = project ? getBaseTag(project) : BASE_TAGS[0];',
  "  const customTags = project ? (project.tags || []).filter(tag => !baseTagOptions.includes(tag)).join(', ') : '';",
  '  const worldbookEntries = Array.isArray(project?.worldbookEntriesPreview) ? project.worldbookEntriesPreview : [];',
  '  const regexEntries = Array.isArray(project?.regexEntriesPreview) ? project.regexEntriesPreview : [];',
  '  const currentCoverSources = project ? getCoverImageSources(project) : null;',
  '  const currentCoverSrc = currentCoverSources?.authenticated ? currentCoverSources.placeholder : getDirectCoverUrl(project);',
  '  const currentCoverAuthAttrs = currentCoverSources?.authenticated ? ` data-cover-img-auth-src="${escapeHtml(currentCoverSources.authenticated)}" data-cover-img-placeholder-src="${escapeHtml(currentCoverSources.placeholder)}"` : "";',
  "  const currentCoverHtml = project?.coverImage ? '<div class=\"edit-current-cover\"><div class=\"detail-section-title\"><span><i class=\"fas fa-image\"></i> 当前预览图</span></div><img src=\"' + escapeHtml(currentCoverSrc) + '\"' + currentCoverAuthAttrs + ' alt=\"当前预览图\"></div>' : '<div class=\"edit-current-cover edit-current-cover--empty\"><div class=\"detail-section-title\"><span><i class=\"fas fa-image\"></i> 当前预览图</span></div><div class=\"empty-state\">未上传预览图</div></div>';",
  '  const currentContentHtml = isEdit ? `<div class="edit-current-content">${currentCoverHtml}${renderDetailSection("世界书条目", "fa-scroll", worldbookEntries, renderDetailEntry, "无条目内容", project, true, false)}${renderDetailSection("正则列表", "fa-code", regexEntries, renderRegexEntry, "无正则内容", project, true, false)}</div>` : "";',





  '  return [',
  '    \'<form id="projectForm">\',',
  '    \'  <div class="form-group"><label>项目名称 *</label><input type="text" id="projName" value="\' + escapeHtml(project?.name || \'\') + \'" required></div>\',',
  '    \'  <div class="form-group"><label>描述</label><textarea id="projDesc" rows="3">\' + escapeHtml(project?.description || \'\') + \'</textarea></div>\',',
  '    buildVersionLabelHtml(project),',
  '    \'  <div class="form-group"><label>基础标签</label><select id="baseTag">\' + buildTagOptions(baseTagOptions, currentBaseTag) + \'</select></div>\',',
  '    \'  <div class="form-group"><label>自定义标签 (逗号分隔)</label><input type="text" id="customTags" value="\' + escapeHtml(customTags) + \'" placeholder="冒险, 战斗"></div>\',',
  '    currentContentHtml,',
  '    \'  <div class="form-group"><label>\' + (isEdit ? \'替换世界书文件\' : \'世界书文件 *\') + \'</label><div class="file-drop" id="fileDrop">\' + (isEdit ? \'选择新世界书 JSON\' : \'点击或拖拽世界书 JSON\') + \'</div><input type="file" id="fileInput" accept=".json" style="display:none;"></div>\',',
  '    \'  <div class="form-group"><label>\' + (isEdit ? \'替换正则文件\' : \'正则文件 (可选)\') + \'</label><div class="file-drop" id="regexDrop">\' + (isEdit ? \'选择新正则 JSON\' : \'点击或拖拽\') + \'</div><input type="file" id="regexInput" accept=".json" style="display:none;"></div>\',',
  '    \'  <div class="form-group"><label>\' + (isEdit ? \'替换预览图\' : \'预览图 (仅一张图片)\') + \'</label><div class="file-drop" id="coverDrop">\' + (isEdit ? \'选择新图片\' : \'点击或拖拽图片 (jpg/png/webp)\') + \'</div><input type="file" id="coverInput" accept="image/jpeg,image/png,image/webp" style="display:none;"></div>\',',
  "    '  <button type=\"submit\" class=\"btn btn-primary form-submit-btn\">' + (isEdit ? '保存修改' : '创建并上传') + '</button>',",
  "    '</form>',",
  "  ].join('');",
  '}',
  '',
  'function collectProjectFormPayload(form) {',
  "  const name = form.querySelector('#projName').value.trim();",
  "  const description = form.querySelector('#projDesc').value;",
  "  const versionLabel = form.querySelector('#versionLabel')?.value.trim() || null;",
  "  const baseTag = form.querySelector('#baseTag').value;",
  "  const customTags = parseTagsInput(form.querySelector('#customTags').value);",
  '  return { name, description, versionLabel, tags: [baseTag, ...customTags].slice(0, 4) };',
  '}',
  '',
  'function prepareProjectForm(overlay) {',
  "  const form = overlay.querySelector('#projectForm');",
  "  const fileInput = overlay.querySelector('#fileInput');",
  "  const regexInput = overlay.querySelector('#regexInput');",
  "  const coverInput = overlay.querySelector('#coverInput');",
  "  bindFileDrop(overlay.querySelector('#fileDrop'), fileInput, overlay.querySelector('#fileDrop').textContent);",
  "  bindFileDrop(overlay.querySelector('#regexDrop'), regexInput, overlay.querySelector('#regexDrop').textContent);",
  "  bindFileDrop(overlay.querySelector('#coverDrop'), coverInput, overlay.querySelector('#coverDrop').textContent);",
  '  return { form, fileInput, regexInput, coverInput, submitBtn: overlay.querySelector(".form-submit-btn") };',
  '}',
  '',
  'function setSubmitState(button, pendingText, idleText, pending) {',
  '  if (!button) return;',
  '  button.disabled = pending;',
  '  button.textContent = pending ? pendingText : idleText;',
  '}',
  '',
  'function openUploadModal() {',
  '  if (!state.currentUser) {',
  "    showToast('请先登录', 'warning');",
  '    return;',
  '  }',
  "  const overlay = openModal(buildProjectFormHtml('create'), '<i class=\"fas fa-cloud-upload-alt\"></i> 上传项目');",
  '  const { form, fileInput, regexInput, coverInput, submitBtn } = prepareProjectForm(overlay);',
  '  form.onsubmit = async event => {',
  '    event.preventDefault();',
  "    setSubmitState(submitBtn, '上传中...', '创建并上传', true);",
  '    const payload = collectProjectFormPayload(form);',
  '    if (!payload.name || !fileInput.files[0]) {',
  "      showToast('请填写名称并选择文件', 'warning');",
  "      setSubmitState(submitBtn, '上传中...', '创建并上传', false);",
  '      return;',
  '    }',
  '    try {',
  '      await validateJsonUpload(fileInput.files[0], "worldbook");',
  '      if (regexInput.files[0]) await validateJsonUpload(regexInput.files[0], "regex");',
  '      const createRes = await createProject(payload);',
  '      const projectId = createRes.projectId;',
  '      await uploadProjectFile(projectId, fileInput.files[0]);',
  '      if (regexInput.files[0]) await uploadRegexFile(projectId, regexInput.files[0]);',
  '      if (coverInput.files[0]) await uploadCoverFile(projectId, coverInput.files[0]);',
  "      showToast('项目上传成功，等待审核');",
  '      overlay.remove();',
  '      await fetchProjects();',
  '    } catch (error) {',
  "      showToast('上传失败: ' + error.message, 'error');",
  '    } finally {',
  "      setSubmitState(submitBtn, '上传中...', '创建并上传', false);",
  '    }',
  '  };',
  '}',
  '',
  'function openEditProjectModal(project) {',
  "  const overlay = openModal(buildProjectFormHtml('edit', project), '<i class=\"fas fa-edit\"></i> 修改项目');",
  "  overlay.querySelectorAll('[data-entry-toggle]').forEach(header => {",
  "    header.addEventListener('click', event => {",
  "      if (event.target.closest('button,input,label')) return;",
  "      header.classList.toggle('open');",
  '      const content = header.nextElementSibling;',
  "      if (content) content.classList.toggle('open');",
  '    });',
  '  });',
  "  overlay.querySelectorAll('[data-entry-remove]').forEach(button => {",
  "    button.addEventListener('click', async event => {",
  '      event.stopPropagation();',
  '      const projectId = button.dataset.projectId;',
  '      const kind = button.dataset.entryKind;',
  '      const entryKey = button.dataset.entryKey;',
  '      if (!projectId || !kind || !entryKey) return;',
  "      if (!confirm('确定从当前项目中移除此条内容？修改会进入审核草稿。')) return;",
  "      const restore = setButtonLoading(button, '删除中');",
  '      try {',
  '        const result = await removeProjectEntry(projectId, kind, entryKey);',
  "        showToast('条目已移除，已切换到最新草稿');",
  '        overlay.remove();',
  '        await fetchProjects(true);',
  '        const targetId = result.projectId || projectId;',
  '        const nextDetail = await fetchProjectEntries(targetId, { forceRefresh: true });',
  '        const nextProject = nextDetail.project ? { ...nextDetail.project, publishedVersion: project.publishedVersion } : { ...project, id: targetId };',
  '        openEditProjectModal(nextProject);',
  '      } catch (error) {',
  "        showToast('删除失败: ' + error.message, 'error');",
  '      } finally { restore(); }',
  '    });',
  '  });',
  '  const { form, fileInput, regexInput, coverInput, submitBtn } = prepareProjectForm(overlay);',
  '  form.onsubmit = async event => {',
  '    event.preventDefault();',
  "    setSubmitState(submitBtn, '保存中...', '保存修改', true);",
  '    const payload = collectProjectFormPayload(form);',
  '    const hasNewFile = Boolean(fileInput.files[0]);',
  '    const hasNewRegex = Boolean(regexInput.files[0]);',
  '    const hasNewCover = Boolean(coverInput.files[0]);',
  '    if (!payload.name && !hasNewFile && !hasNewRegex && !hasNewCover) {',
  "      showToast('请至少填写项目名称或上传文件', 'warning');",
  "      setSubmitState(submitBtn, '保存中...', '保存修改', false);",
  '      return;',
  '    }',
  '    try {',
  '      if (hasNewFile) await validateJsonUpload(fileInput.files[0], "worldbook");',
  '      if (hasNewRegex) await validateJsonUpload(regexInput.files[0], "regex");',
  '      const updateResult = await updateProject(project.id, payload);',
  '      const targetProjectId = updateResult.draftProjectId || updateResult.projectId || project.id;',
  '      if (hasNewFile) await uploadProjectFile(targetProjectId, fileInput.files[0]);',
  '      if (hasNewRegex) await uploadRegexFile(targetProjectId, regexInput.files[0]);',
  '      if (hasNewCover) await uploadCoverFile(targetProjectId, coverInput.files[0]);',
  "      showToast(hasNewFile || hasNewRegex || hasNewCover ? '修改已提交审核，主页仍显示旧版本' : (project.status === 'rejected' ? '项目已重新提交审核' : '项目更新成功'));",
  '      overlay.remove();',
  '      await fetchProjects();',
  '    } catch (error) {',
  "      showToast('更新失败: ' + error.message, 'error');",
  '    } finally {',
  "      setSubmitState(submitBtn, '保存中...', '保存修改', false);",
  '    }',
  '  };',
  '}',
  '',
  'function getAdminReviewVersionLabel(project) {',
  '  const creatorVersionLabel = project.versionLabel ? `版本名称：${project.versionLabel}` : "版本名称：未填写";',
  '  const machineVersionLabel = project.publishedVersion ? `系统版本：${project.publishedVersion} → ${project.version}` : `系统版本：${project.version || "1.0.0"}`;',
  '  return `${creatorVersionLabel} · ${machineVersionLabel}`;',
  '}',
  '',
  'function renderAdminReviewCard(project, index, total) {',
  '  const description = String(project.description || "暂无项目简介").trim() || "暂无项目简介";',
  '  const updatedAt = project.updatedAt || project.createdAt || "";',
  '  const revisionLabel = project.draftRevision ? `草稿 #${project.draftRevision}` : "待审核";',
  '  return `',
  '    <article class="admin-review-card" data-review-card data-project-id="${escapeHtml(String(project.id || ""))}">',
  '      <div class="admin-review-card-head">',
  '        <span class="admin-review-position" data-review-position>${index + 1}/${total}</span>',
  '        <div class="admin-review-card-heading">',
  '          <div class="admin-review-title">${escapeHtml(project.name || "未命名项目")}</div>',
  '          <div class="admin-review-author"><i class="fas fa-user"></i> ${escapeHtml(getAuthorName(project))}</div>',
  '        </div>',
  '        <span class="admin-review-state">${escapeHtml(revisionLabel)}</span>',
  '      </div>',
  '      <div class="admin-review-meta">',
  '        <span class="admin-review-meta-item"><i class="fas fa-code-branch"></i> ${escapeHtml(getAdminReviewVersionLabel(project))}</span>',
  '        ${updatedAt ? `<span class="admin-review-meta-item"><i class="fas fa-clock"></i> ${escapeHtml(formatDate(updatedAt))}</span>` : ""}',
  '      </div>',
  '      <div class="admin-review-desc-preview">${escapeHtml(description)}</div>',
  '      <div class="admin-review-card-actions">',
  '        <button class="btn btn-primary" type="button" data-id="${escapeHtml(String(project.id || ""))}" data-action="detail"><i class="fas fa-magnifying-glass"></i> 开始审核</button>',
  '        <button class="btn btn-outline" type="button" data-id="${escapeHtml(String(project.id || ""))}" data-action="skip"><i class="fas fa-forward"></i> 跳过</button>',
  '      </div>',
  '    </article>',
  '  `;',
  '}',
  '',
  'function refreshAdminReviewPositions(overlay) {',
  '  const cards = Array.from(overlay.querySelectorAll("[data-review-card]"));',
  '  cards.forEach((card, index) => {',
  '    const position = card.querySelector("[data-review-position]");',
  '    if (position) position.textContent = `${index + 1}/${cards.length}`;',
  '  });',
  '}',
  '',
  'function skipAdminReviewCard(overlay, projectId) {',
  '  const card = Array.from(overlay.querySelectorAll("[data-review-card]")).find(item => item.dataset.projectId === String(projectId));',
  '  if (!card || !card.parentElement) return;',
  '  const list = card.parentElement;',
  '  list.appendChild(card);',
  '  card.classList.remove("is-skipped");',
  '  void card.offsetWidth;',
  '  card.classList.add("is-skipped");',
  '  refreshAdminReviewPositions(overlay);',
  '  const nextCard = list.querySelector("[data-review-card]");',
  '  nextCard?.scrollIntoView({ behavior: "smooth", block: "nearest" });',
  "  showToast('已跳过，项目已移到队尾', 'info');",
  '}',
  '',
  'function renderAdminInspectionSignals(entries, regexEntries) {',
  '  const worldbookEntries = Array.isArray(entries) ? entries : [];',
  '  const regexList = Array.isArray(regexEntries) ? regexEntries : [];',
  '  const allEntries = [...worldbookEntries, ...regexList];',
  '  const hasInspectionData = allEntries.some(entry => entry && (Object.prototype.hasOwnProperty.call(entry, "hasEjs") || Object.prototype.hasOwnProperty.call(entry, "hasCharacterArtwork") || Object.prototype.hasOwnProperty.call(entry, "inspectionWarnings") || Object.prototype.hasOwnProperty.call(entry, "externalLinks")));',
  '  const hasEjs = allEntries.some(entry => Boolean(entry?.hasEjs));',
  '  const hasCharacterArtwork = allEntries.some(entry => Boolean(entry?.hasCharacterArtwork));',
  '  const warningCount = allEntries.reduce((count, entry) => count + (Array.isArray(entry?.inspectionWarnings) ? entry.inspectionWarnings.length : 0), 0);',
  '  const externalLinkCount = collectProjectExternalLinks(worldbookEntries, regexList).reduce((count, group) => count + group.links.length, 0);',
  '  const signals = [',
  '    `<span class="admin-review-signal"><i class="fas fa-book-open"></i> 世界书 ${worldbookEntries.length}</span>`,',
  '    `<span class="admin-review-signal"><i class="fas fa-code"></i> 正则 ${regexList.length}</span>`,',
  '  ];',
  '  if (hasInspectionData && hasEjs) signals.push(`<span class="admin-review-signal admin-review-signal--info">EJS</span>`);',
  '  if (hasInspectionData && hasCharacterArtwork) signals.push(`<span class="admin-review-signal admin-review-signal--good">👍🏻 角色立绘</span>`);',
  '  if (hasInspectionData && externalLinkCount) signals.push(`<span class="admin-review-signal admin-review-signal--info"><i class="fas fa-link"></i> 外链 ${externalLinkCount}</span>`);',
  '  if (hasInspectionData && warningCount) signals.push(`<span class="admin-review-signal admin-review-signal--warning"><i class="fas fa-triangle-exclamation"></i> ${warningCount} 个检查警告</span>`);',
  '  return `<div class="admin-review-signals">${signals.join("")}</div>`;',
  '}',
  '',
  'function bindAdminReviewEntryToggles(overlay) {',
  "  overlay.querySelectorAll('[data-entry-toggle]').forEach(header => {",
  "    header.addEventListener('click', () => {",
  "      header.classList.toggle('open');",
  '      const content = header.nextElementSibling;',
  "      if (content) content.classList.toggle('open');",
  '    });',
  '  });',
  '}',
  '',
  'async function openAdminReviewDetail(project, queueOverlay) {',
  '  const loadingOverlay = openModal(\'<div class="detail-loading"><div class="loading-spinner"></div><div class="detail-loading-text">正在加载审核内容...</div></div>\', \'<i class="fas fa-clipboard-check"></i> 审核详情\');',
  '  try {',
  '    const detail = await fetchAdminReviewDetail(project.id);',
  '    loadingOverlay.remove();',
  '    const reviewProjectData = detail.project || project;',
  '    const entries = detail.worldbookEntriesPreview || detail.project?.worldbookEntriesPreview || [];',
  '    const regexEntries = detail.regexEntriesPreview || detail.project?.regexEntriesPreview || [];',
  '    const reviewDiff = detail.reviewDiff || null;',
  '    const isDiffReview = reviewDiff?.mode === "update";',
  '    const contentReviewHtml = isDiffReview ? `${renderAdminReviewDiffSummary(reviewDiff)}${renderAdminReviewDiffSection("世界书变化", "fa-scroll", reviewDiff.worldbook, "worldbook")}${renderAdminReviewDiffSection("正则变化", "fa-code", reviewDiff.regex, "regex")}` : `${renderDetailSection("世界书条目", "fa-scroll", entries, renderDetailEntry, "无世界书内容")}${renderDetailSection("正则列表", "fa-code", regexEntries, renderRegexEntry, "无正则内容")}`;',
  '    const description = String(reviewProjectData.description || "暂无项目简介").trim() || "暂无项目简介";',
  '    const bodyHtml = [',
  '      `<div class="admin-review-detail-shell">`,',
  '      `<section class="admin-review-summary">`,',
  '      `<div class="admin-review-summary-head"><span class="type-badge ${getTypeClass(reviewProjectData)}">${escapeHtml(getBaseTag(reviewProjectData))}</span><div class="admin-review-summary-heading"><h3>${escapeHtml(reviewProjectData.name || "未命名项目")}</h3><div>${escapeHtml(getAuthorName(reviewProjectData))} · ${escapeHtml(getAdminReviewVersionLabel(reviewProjectData))}</div></div></div>`,',
  '      renderAdminInspectionSignals(entries, regexEntries),',
  '      `<details class="admin-review-description"><summary><span><i class="fas fa-align-left"></i> 项目简介</span><span class="admin-review-description-hint">点击展开 / 收起</span></summary><div class="admin-review-description-body">${escapeHtml(description)}</div></details>`,',
  '      `</section>`,',
  '      renderExternalLinksPanel(entries, regexEntries, { title: "审核外链", notice: "静态检测结果，仅供审核定位；未访问、未验证这些 URL 的远端内容。" }),',
  '      contentReviewHtml,',
  '      `<div class="admin-review-sticky-actions">`,',
  '      `<button class="btn btn-outline" type="button" data-admin-review-back><i class="fas fa-arrow-left"></i> 返回队列</button>`,',
  '      `<button class="btn btn-outline" type="button" data-admin-review-skip><i class="fas fa-forward"></i> 跳过</button>`,',
  '      `<button class="btn admin-review-reject-btn" type="button" data-admin-review-submit="reject"><i class="fas fa-xmark"></i> 拒绝</button>`,',
  '      `<button class="btn admin-review-approve-btn" type="button" data-admin-review-submit="approve"><i class="fas fa-check"></i> 批准</button>`,',
  '      `</div></div>`,',
  '    ].join("");',
  '    const overlay = openModal(bodyHtml, `<i class="fas fa-clipboard-check"></i> 审核详情`);',
  '    overlay.classList.add("admin-review-detail-overlay");',
  '    overlay.querySelector(".modal-content")?.classList.add("admin-review-detail-modal");',
  '    bindAdminReviewEntryToggles(overlay);',
  '    if (isDiffReview) bindAdminReviewDiffLazyContent(overlay, reviewDiff);',
  '    overlay.querySelector("[data-admin-review-back]")?.addEventListener("click", () => overlay.remove());',
  '    overlay.querySelector("[data-admin-review-skip]")?.addEventListener("click", () => {',
  '      overlay.remove();',
  '      skipAdminReviewCard(queueOverlay, project.id);',
  '    });',
  '    overlay.querySelectorAll("[data-admin-review-submit]").forEach(button => {',
  '      button.addEventListener("click", async () => {',
  '        const action = button.dataset.adminReviewSubmit;',
  '        if (action !== "approve" && action !== "reject") return;',
  '        if (action === "approve" && !confirm(`确定批准「${reviewProjectData.name || "该项目"}」吗？`)) return;',
  '        let rejectReason;',
  '        if (action === "reject") {',
  "          rejectReason = prompt('请输入拒绝原因');",
  '          if (!rejectReason) return;',
  '        }',
  '        const restore = setButtonLoading(button, action === "approve" ? "批准中" : "拒绝中");',
  '        try {',
  '          await reviewProject(project.id, { action, ...(rejectReason ? { rejectReason } : {}), expectedRevision: project?.draftRevision || reviewProjectData?.draftRevision });',
  "          showToast(action === 'approve' ? '已批准' : '已拒绝');",
  '          overlay.remove();',
  '          queueOverlay.remove();',
  '          await fetchProjects(true);',
  '          openAdminPanel();',
  '        } catch (error) {',
  "          showToast(error.message, 'error');",
  '        } finally { restore(); }',
  '      });',
  '    });',
  '  } catch (error) {',
  '    loadingOverlay.remove();',
  "    showToast('加载审核详情失败: ' + error.message, 'error');",
  '  }',
  '}',
  '',
  'async function openAdminPanel() {',
  '  if (!state.currentUser?.isAdmin) {',
  "    showToast('无权限', 'error');",
  '    return;',
  '  }',
  '  try {',
  '    const data = await fetchPendingProjects();',
  '    const pending = data.projects || [];',
  '    const html = pending.length',
  '      ? `<div class="admin-review-queue"><div class="admin-review-queue-summary"><div><strong>${pending.length}</strong> 个项目等待审核</div><span>先看摘要，需要时再展开条目正文</span></div><div class="admin-review-list">${pending.map((project, index) => renderAdminReviewCard(project, index, pending.length)).join("")}</div></div>`',
  '      : `<div class="empty-state"><i class="fas fa-circle-check"></i><div>暂无待审核项目</div></div>`;',
  "    const overlay = openModal(html, '<i class=\"fas fa-clipboard-check\"></i> 审核中心');",
  '    overlay.classList.add("admin-review-overlay");',
  '    overlay.querySelector(".modal-content")?.classList.add("admin-review-modal");',
  "    overlay.querySelectorAll('button[data-action]').forEach(button => {",
  "      button.addEventListener('click', async () => {",
  '        const projectId = button.dataset.id;',
  '        const action = button.dataset.action;',
  '        const project = pending.find(item => String(item.id) === String(projectId));',
  '        if (!projectId || !project) return;',
  "        if (action === 'skip') {",
  '          skipAdminReviewCard(overlay, projectId);',
  '          return;',
  '        }',
  "        if (action === 'detail') {",
  "          const restore = setButtonLoading(button, '加载审核内容');",
  '          Promise.resolve(openAdminReviewDetail(project, overlay)).finally(restore);',
  '        }',
  '      });',
  '    });',
  '  } catch (error) {',
  "    showToast(error.message, 'error');",
  '  }',
  '}',
  '',

  'async function openAdminLogsModal() {',
  '  if (!state.currentUser?.isSuperAdmin) {',
  "    showToast('无权限', 'error');",
  '    return;',
  '  }',
  '  try {',
  '    const data = await fetchAdminLogs();',
  '    const logs = data.logs || [];',
  '    const html = logs.length ? logs.map(log => `<div class="admin-card"><div class="admin-card-title">${escapeHtml(log.action)}</div><div>操作人: ${escapeHtml(log.actorName)} (${escapeHtml(log.actorId)})</div><div>目标: ${escapeHtml(log.targetType)} ${escapeHtml(log.targetId || "-")}</div><div>时间: ${escapeHtml(log.createdAt || "")}</div><pre style="white-space:pre-wrap;word-break:break-all;">${escapeHtml(log.detail || "")}</pre></div>`).join("") : "<p>暂无日志</p>";',
  '    openModal(`<h3>管理员操作日志</h3>${html}`, `<i class=\\"fas fa-clock-rotate-left\\"></i> 操作日志`);',
  '  } catch (error) {',
  "    showToast('加载管理员日志失败: ' + (error && error.message ? error.message : '未知错误'), 'error');",
  '  }',
  '}',
  '',
  'async function openAddAdminModal() {',
  '  if (!state.currentUser?.isSuperAdmin) {',
  "    showToast('无权限', 'error');",
  '    return;',
  '  }',
  '  let admins = [];',
  '  try {',
  '    const data = await fetchAdminList();',
  '    admins = data.admins || [];',
  '  } catch (error) {',
  "    showToast('加载管理员列表失败: ' + (error && error.message ? error.message : '未知错误'), 'error');",
  '  }',
  '  const adminsHtml = admins.length',
  '    ? admins.map(admin => {',
  '        return \'<div class="admin-list-item">\'',
  "          + '<div><img src=\"' + escapeHtml(admin.avatarUrl || 'https://cdn.discordapp.com/embed/avatars/0.png') + '\" style=\"width:32px; height:32px; border-radius:50%; margin-right:8px; vertical-align:middle;\">'",
  "          + escapeHtml(admin.globalName || admin.username) + ' (' + escapeHtml(admin.id) + ')</div>'",
  '          + \'<button class="btn" data-id="\' + admin.id + \'" data-action="remove">移除管理员</button>\'',
  "          + '</div>';",
  "      }).join('')",
  "    : '<p>暂无管理员</p>';",
  '  const overlay = openModal(',
  '    [',
  "      '<div>',",
  "      '<h3>添加管理员</h3>',",
  '      \'<input type="text" id="targetUserId" placeholder="用户ID" style="width:100%; padding:8px; margin-bottom:16px;">\',',
  '      \'<button class="btn btn-primary" id="confirmAdd">设为管理员</button>\',',
  '      \'<hr style="margin:20px 0;">\',',
  "      '<h3>现有管理员列表</h3>',",
  "      '<div id=\"adminListContainer\">' + adminsHtml + '</div>',",
  "      '</div>',",
  "    ].join(''),",
  '    \'<i class="fas fa-user-shield"></i> 管理员设置\',',
  '  );',
  "  overlay.querySelector('#confirmAdd').onclick = async () => {",
  "    const targetId = overlay.querySelector('#targetUserId').value.trim();",
  '    if (!targetId) return;',
  '    try {',
  '      await setAdmin(targetId, true);',
  "      showToast('已设为管理员');",
  '      overlay.remove();',
  '      openAddAdminModal();',
  '    } catch (error) {',
  "      showToast(error.message, 'error');",
  '    }',
  '  };',
  '  overlay.querySelectorAll(\'button[data-action="remove"]\').forEach(button => {',
  "    button.addEventListener('click', async () => {",
  '      const userId = button.dataset.id;',
  "      if (!userId || !confirm('确定要移除该管理员吗？')) return;",
  '      try {',
  '        await setAdmin(userId, false);',
  "        showToast('已移除管理员');",
  '        overlay.remove();',
  '        openAddAdminModal();',
  '      } catch (error) {',
  "        showToast(error.message, 'error');",
  '      }',
  '    });',
  '  });',
  '}',
].join('\n');
