export const homeModalsScript = [
  'function openModal(contentHtml, titleHtml) {',
  '  const resolvedTitle = titleHtml || \'<i class="fas fa-pen"></i> 操作\';',
  "  const overlay = document.createElement('div');",
  "  overlay.className = 'modal-overlay';",
  '  overlay.innerHTML = [',
  '    \'<div class="modal-content">\',',
  '    \'  <div class="modal-header">\',',
  "    '    <h2>' + resolvedTitle + '</h2>',",
  '    \'    <button class="close-btn" type="button"><i class="fas fa-times"></i></button>\',',
  "    '  </div>',",
  "    '  <div class=\"modal-body\">' + contentHtml + '</div>',",
  "    '</div>',",
  "  ].join('');",
  '  const requestClose = () => {',
  "    if (overlay.dataset.dirty === 'true' && !confirm('有未保存的修改，确定放弃吗？')) return false;",
  '    overlay.remove();',
  '    return true;',
  '  };',
  "  overlay.addEventListener('click', event => {",
  "    if (event.target === overlay && overlay.dataset.dirty === 'true' && !confirm('有未保存的修改，确定放弃吗？')) event.stopImmediatePropagation();",
  '  }, true);',
  "  overlay.addEventListener('input', event => { if (event.target.closest('form')) overlay.dataset.dirty = 'true'; });",
  "  overlay.addEventListener('change', event => { if (event.target.closest('form')) overlay.dataset.dirty = 'true'; });",
  "  overlay.addEventListener('click', event => {",
  '    if (event.target === overlay) {',
  '      overlay.remove();',
  '    }',
  '  });',
  "  overlay.querySelector('.close-btn').addEventListener('click', requestClose);",
  '  document.body.appendChild(overlay);',
  '  bindCoverImageFallbacks(overlay);',
  '  return overlay;',
  '}',
  '',
  'function setButtonLoading(button, pendingText) {',
  '  if (!button) return () => {};',
  '  const originalHtml = button.innerHTML;',
  '  button.disabled = true;',
  '  button.classList.add("is-loading");',
  '  button.innerHTML = `<span class="inline-loading-spinner"></span><span>${pendingText}</span>`;',
  '  return () => {',
  '    button.disabled = false;',
  '    button.classList.remove("is-loading");',
  '    button.innerHTML = originalHtml;',
  '  };',
  '}',
  '',
  'async function showProjectDetail(project) {',
  '  const loadingOverlay = openModal(\'<div class="detail-loading"><div class="loading-spinner"></div><div class="detail-loading-text">正在加载项目详情、世界书与正则内容...</div></div>\', \'<i class="fas fa-info-circle"></i> 项目详情\');',
  '  try {',
  '    const detail = await fetchProjectEntries(project);',
  '    loadingOverlay.remove();',
  '    const overlay = openModal(renderProjectDetail(detail.project || project, detail.entries || [], detail.regexEntries || []), \'<i class="fas fa-info-circle"></i> 项目详情\');',
  "    overlay.querySelectorAll('[data-entry-toggle]').forEach(header => {",
  "      header.addEventListener('click', () => {",
  "        header.classList.toggle('open');",
  '        const content = header.nextElementSibling;',
  "        if (content) content.classList.toggle('open');",
  '      });',
  '    });',
  "    overlay.querySelectorAll('.detail-install-btn,.install-btn').forEach(button => {",
  "      button.addEventListener('click', event => {",
  '        event.stopPropagation();',
  '        if (button.disabled) return;',
  '        const projectId = button.dataset.id || detail.project?.id || project.id;',
  '        if (!projectId) return;',
  '        const localMeta = getLocalProjectMeta(projectId);',
  '        if (localMeta) {',
  '          requestUninstallProject(projectId);',
  "          showToast('已发送卸载请求', 'info');",
  '        } else {',
  '          openInstallWorldbookModal(projectId);',

  '        }',
  '        overlay.remove();',
  '      });',
  '    });',
  "    overlay.querySelectorAll('.detail-update-btn,.update-btn').forEach(button => {",
  "      button.addEventListener('click', event => {",
  '        event.stopPropagation();',
  '        if (button.disabled) return;',
  '        const targetProject = detail.project || project;',
  '        if (!targetProject?.id) return;',
  '        const restore = setButtonLoading(button, "加载差异");',
  '        requestProjectDiff(targetProject.id)',
  '          .then(diff => openProjectUpdateModal(targetProject, diff))',
  '          .catch(error => showToast("加载更新差异失败: " + error.message, "error"))',
  '          .finally(restore);',
  '      });',
  '    });',
  '  } catch (error) {',
  '    loadingOverlay.remove();',
  "    showToast('加载详情失败: ' + error.message, 'error');",
  '  }',
  '}',
  '',
  'function renderDiffGroup(title, icon, worldbookEntries, regexEntries) {',
  '  const hasWorldbook = Array.isArray(worldbookEntries) && worldbookEntries.length > 0;',
  '  const hasRegex = Array.isArray(regexEntries) && regexEntries.length > 0;',
  '  if (!hasWorldbook && !hasRegex) return "";',
  '  const worldbookHtml = hasWorldbook ? renderDetailSection("世界书条目", "fa-scroll", worldbookEntries, renderDetailEntry, "") : "";',
  '  const regexHtml = hasRegex ? renderDetailSection("正则列表", "fa-code", regexEntries, renderRegexEntry, "") : "";',
  '  return `<div class="update-diff-group"><div class="detail-section-title"><span><i class="fas ${icon}"></i> ${title}</span></div>${worldbookHtml}${regexHtml}</div>`;',
  '}',
  '',
  'function openProjectUpdateModal(project, resolvedDiff) {',
  '  const diff = resolvedDiff || getProjectUpdateDiff(project.id) || {',
  '    added: { worldbookEntries: [], regexEntries: [] },',
  '    modified: { worldbookEntries: [], regexEntries: [] },',
  '    removed: { worldbookEntries: [], regexEntries: [] },',
  '  };',
  '  const headerHtml = renderProjectDetail(project, [], []).replace(/<div class="detail-section">[\\s\\S]*$/, "</div>");',
  '  const bodyHtml = [',
  '    `<div class="update-modal">${headerHtml}`,',
  '    renderDiffGroup("新增内容", "fa-plus", diff.added?.worldbookEntries || [], diff.added?.regexEntries || []),',
  '    renderDiffGroup("修改内容", "fa-pen", diff.modified?.worldbookEntries || [], diff.modified?.regexEntries || []),',
  '    renderDiffGroup("删除内容", "fa-trash", diff.removed?.worldbookEntries || [], diff.removed?.regexEntries || []),',
  '    `<div class="update-modal-actions"><button class="btn btn-outline" data-update-cancel>取消</button><button class="btn btn-primary" data-update-confirm>确认更新</button></div></div>`,',
  '  ].join("");',
  '  const overlay = openModal(bodyHtml, `<i class="fas fa-arrows-rotate"></i> 更新项目`);',
  '  overlay.querySelector("[data-update-cancel]")?.addEventListener("click", () => overlay.remove());',
  '  overlay.querySelector("[data-update-confirm]")?.addEventListener("click", () => {',
  '    confirmProjectUpdate(project.id);',
  "    showToast('已发送更新请求', 'info');",
  '    overlay.remove();',
  '  });',
  '}',
  '',
  'function openInstallWorldbookModal(projectId) {',
  '  const worldbooks = state.tavern.worldbooks || {};',
  '  const primary = worldbooks.primary || null;',
  '  const additional = Array.isArray(worldbooks.additional) ? worldbooks.additional.filter(Boolean) : [];',
  '  const available = Array.from(new Set([primary, ...additional, ...(worldbooks.available || [])].filter(Boolean)));',
  '  const dedicatedName = "创意工坊";',
  '  const createDedicated = !available.includes(dedicatedName);',
  '  const optionLabel = name => name === primary ? `${name}（角色主世界书）` : (additional.includes(name) ? `${name}（附加世界书）` : name);',
  '  const optionsHtml = available.map(name => `<option value="${escapeHtml(name)}"${!createDedicated && name === dedicatedName ? " selected" : ""}>${escapeHtml(optionLabel(name))}</option>`).join("")',
  '    + `<option value="__new__"${createDedicated ? " selected" : ""}>新建独立世界书…</option>`;',
  '  const bodyHtml = `<form id="installWorldbookForm"><div class="form-group"><label>安装到世界书</label><select id="installWorldbookSelect">${optionsHtml}</select></div><div class="form-group" id="newWorldbookGroup"${createDedicated ? "" : " hidden"}><label>新世界书名称</label><input type="text" id="newWorldbookName" value="${dedicatedName}"></div><button type="submit" class="btn btn-primary">安装</button></form>`;',
  '  const overlay = openModal(bodyHtml, `<i class="fas fa-book"></i> 选择安装世界书`);',
  '  const form = overlay.querySelector("#installWorldbookForm");',
  '  const select = overlay.querySelector("#installWorldbookSelect");',
  '  const newGroup = overlay.querySelector("#newWorldbookGroup");',
  '  const newNameInput = overlay.querySelector("#newWorldbookName");',
  '  const syncNewWorldbookField = () => { if (newGroup) newGroup.hidden = select?.value !== "__new__"; };',
  '  select?.addEventListener("change", syncNewWorldbookField);',
  '  syncNewWorldbookField();',
  '  form?.addEventListener("submit", event => {',
  '    event.preventDefault();',
  '    const worldbookName = select?.value === "__new__" ? String(newNameInput?.value || "").trim() : String(select?.value || "").trim();',
  '    if (!worldbookName) { showToast("请输入世界书名称", "warning"); return; }',
  '    requestInstallProject(projectId, { worldbookName });',
  '    showToast(`已发送安装请求：${worldbookName}`, "info");',
  '    overlay.dataset.dirty = "false";',
  '    overlay.remove();',
  '  });',
  '}',
  '',
  'function bindFileDrop(drop, input, emptyText) {',
  '  drop.onclick = () => input.click();',
  '  input.onchange = () => {',
  '    drop.textContent = input.files[0]?.name || emptyText;',
  '  };',
  '}',
  '',
  'async function validateJsonUpload(file, kind) {',
  '  if (!file) return null;',
  '  if (!String(file.name || "").toLowerCase().endsWith(".json")) {',
  '    throw new Error(kind === "worldbook" ? "世界书文件必须是 .json" : "正则文件必须是 .json");',
  '  }',
  '  let parsed;',
  '  try {',
  '    parsed = JSON.parse(await file.text());',
  '  } catch {',
  '    throw new Error(kind === "worldbook" ? "世界书文件不是有效 JSON" : "正则文件不是有效 JSON");',
  '  }',
  '  if (kind === "worldbook") {',
  '    const entries = parsed && typeof parsed === "object" ? parsed.entries : null;',
  '    const recognized = Array.isArray(parsed) || Array.isArray(entries) || (entries && typeof entries === "object" && !Array.isArray(entries));',
  '    if (!recognized) {',
  '      throw new Error("世界书 JSON 格式不正确：需要条目数组，或包含 entries 数组/对象");',
  '    }',
  '  }',
  '  return parsed;',
  '}',
  '',
  'function buildTagOptions(baseTagOptions, currentBaseTag) {',
  '  return baseTagOptions',
  "    .map(tag => '<option value=\"' + tag + '\"' + (tag === currentBaseTag ? ' selected' : '') + '>' + tag + '</option>')",
  "    .join('');",
  '}',
  '',
  'function previewVersionBump(version, bump) {',
  '  const match = String(version || "").trim().match(/^v?(\\d+)\\.(\\d+)\\.(\\d+)$/i);',
  '  const normalized = match || [null, "1", "0", "0"];',
  '  const major = Number(normalized[1]);',
  '  const minor = Number(normalized[2]);',
  '  const patch = Number(normalized[3]);',
  '  if (bump === "major") return `${major + 1}.0.0`;',
  '  if (bump === "minor") return `${major}.${minor + 1}.0`;',
  '  return `${major}.${minor}.${patch + 1}`;',
  '}',
  '',
  'function inferVersionBump(baseVersion, targetVersion) {',
  '  return ["patch", "minor", "major"].find(bump => previewVersionBump(baseVersion, bump) === targetVersion) || "patch";',
  '}',
  '',
  'function buildVersionPolicyHtml(isEdit, project) {',
  '  const hasPublishedBase = Boolean(project?.isPublished || project?.publishedProjectId || project?.publishedVersion);',
  '  if (!isEdit || !hasPublishedBase) return `<div class="form-group"><label>版本</label><div class="version-policy-row"><strong class="version-current">首次发布 v1.0.0</strong></div></div>`;',
  '  const baseVersion = project?.publishedVersion || project?.version || "1.0.0";',
  '  const selectedBump = inferVersionBump(baseVersion, project?.version);',
  '  const labels = { patch: "Patch", minor: "Minor", major: "Major" };',
  '  const options = ["patch", "minor", "major"].map(bump => {',
  '    const nextVersion = previewVersionBump(baseVersion, bump);',
  '    const label = nextVersion ? `${labels[bump]} → ${nextVersion}` : labels[bump];',
  '    return `<option value="${bump}" ${selectedBump === bump ? "selected" : ""}>${label}</option>`;',
  '  }).join("");',
  '  return `<div class="form-group"><label>版本</label><div class="version-policy-row"><strong class="version-current">当前 v${escapeHtml(baseVersion)}</strong><select id="versionBump" class="version-bump-select">${options}</select></div></div>`;',
  '}',
  '',
  'function buildProjectFormHtml(mode, project) {',
  "  const isEdit = mode === 'edit';",
  '  const baseTagOptions = BASE_TAGS;',
  '  const currentBaseTag = project ? getBaseTag(project) : BASE_TAGS[0];',
  "  const customTags = project ? (project.tags || []).filter(tag => !baseTagOptions.includes(tag)).join(', ') : '';",
  '  const worldbookEntries = Array.isArray(project?.worldbookEntriesPreview) ? project.worldbookEntriesPreview : [];',
  '  const regexEntries = Array.isArray(project?.regexEntriesPreview) ? project.regexEntriesPreview : [];',
  "  const currentCoverHtml = project?.coverImage ? '<div class=\"edit-current-cover\"><div class=\"detail-section-title\"><span><i class=\"fas fa-image\"></i> 当前预览图</span></div><img src=\"' + escapeHtml(getDirectCoverUrl(project)) + '\" alt=\"当前预览图\"></div>' : '<div class=\"edit-current-cover edit-current-cover--empty\"><div class=\"detail-section-title\"><span><i class=\"fas fa-image\"></i> 当前预览图</span></div><div class=\"empty-state\">未上传预览图</div></div>';",
  '  const currentContentHtml = isEdit ? `<div class="edit-current-content">${currentCoverHtml}${renderDetailSection("世界书条目", "fa-scroll", worldbookEntries, renderDetailEntry, "无条目内容", project, true, false)}${renderDetailSection("正则列表", "fa-code", regexEntries, renderRegexEntry, "无正则内容", project, true, false)}</div>` : "";',





  '  return [',
  '    \'<form id="projectForm">\',',
  '    \'  <div class="form-group"><label>项目名称 *</label><input type="text" id="projName" value="\' + escapeHtml(project?.name || \'\') + \'" required></div>\',',
  '    \'  <div class="form-group"><label>描述</label><textarea id="projDesc" rows="3">\' + escapeHtml(project?.description || \'\') + \'</textarea></div>\',',
  '    buildVersionPolicyHtml(isEdit, project),',
  '    \'  <div class="form-group"><label>基础标签</label><select id="baseTag">\' + buildTagOptions(baseTagOptions, currentBaseTag) + \'</select></div>\',',
  '    \'  <div class="form-group"><label>自定义标签 (逗号分隔)</label><input type="text" id="customTags" value="\' + escapeHtml(customTags) + \'" placeholder="冒险, 战斗"></div>\',',
  '    currentContentHtml,',
  '    \'  <div class="form-group"><label>\' + (isEdit ? \'替换世界书文件\' : \'世界书文件 *\') + \'</label><div class="file-drop" id="fileDrop">\' + (isEdit ? \'选择新世界书 JSON\' : \'点击或拖拽世界书 JSON\') + \'</div><input type="file" id="fileInput" accept=".json" style="display:none;"></div>\',',
  '    \'  <div class="form-group"><label>\' + (isEdit ? \'替换正则文件\' : \'正则文件 (可选)\') + \'</label><div class="file-drop" id="regexDrop">\' + (isEdit ? \'选择新正则 JSON\' : \'点击或拖拽\') + \'</div><input type="file" id="regexInput" accept=".json" style="display:none;"></div>\',',
  '    \'  <div class="form-group"><label>\' + (isEdit ? \'替换预览图\' : \'预览图 (仅一张图片)\') + \'</label><div class="file-drop" id="coverDrop">\' + (isEdit ? \'选择新图片\' : \'点击或拖拽图片 (jpg/png/webp)\') + \'</div><input type="file" id="coverInput" accept="image/jpeg,image/png,image/webp" style="display:none;"></div>\',',
  "    '  <button type=\"submit\" class=\"btn btn-primary form-submit-btn\">' + (isEdit ? '保存修改' : '创建并上传') + '</button>',",
  "    '</form>',",
  "  ].join('');",
  '}',
  '',
  'function collectProjectFormPayload(form) {',
  "  const name = form.querySelector('#projName').value.trim();",
  "  const description = form.querySelector('#projDesc').value;",
  "  const versionBump = form.querySelector('#versionBump')?.value || null;",
  "  const baseTag = form.querySelector('#baseTag').value;",
  "  const customTags = parseTagsInput(form.querySelector('#customTags').value);",
  '  return { name, description, ...(versionBump ? { versionBump } : {}), tags: [baseTag, ...customTags].slice(0, 4) };',
  '}',
  '',
  'function prepareProjectForm(overlay) {',
  "  const form = overlay.querySelector('#projectForm');",
  "  const fileInput = overlay.querySelector('#fileInput');",
  "  const regexInput = overlay.querySelector('#regexInput');",
  "  const coverInput = overlay.querySelector('#coverInput');",
  "  bindFileDrop(overlay.querySelector('#fileDrop'), fileInput, overlay.querySelector('#fileDrop').textContent);",
  "  bindFileDrop(overlay.querySelector('#regexDrop'), regexInput, overlay.querySelector('#regexDrop').textContent);",
  "  bindFileDrop(overlay.querySelector('#coverDrop'), coverInput, overlay.querySelector('#coverDrop').textContent);",
  '  return { form, fileInput, regexInput, coverInput, submitBtn: overlay.querySelector(".form-submit-btn") };',
  '}',
  '',
  'function setSubmitState(button, pendingText, idleText, pending) {',
  '  if (!button) return;',
  '  button.disabled = pending;',
  '  button.textContent = pending ? pendingText : idleText;',
  '}',
  '',
  'function openUploadModal() {',
  '  if (!state.currentUser) {',
  "    showToast('请先登录', 'warning');",
  '    return;',
  '  }',
  "  const overlay = openModal(buildProjectFormHtml('create'), '<i class=\"fas fa-cloud-upload-alt\"></i> 上传项目');",
  '  const { form, fileInput, regexInput, coverInput, submitBtn } = prepareProjectForm(overlay);',
  '  form.onsubmit = async event => {',
  '    event.preventDefault();',
  "    setSubmitState(submitBtn, '上传中...', '创建并上传', true);",
  '    const payload = collectProjectFormPayload(form);',
  '    if (!payload.name || !fileInput.files[0]) {',
  "      showToast('请填写名称并选择文件', 'warning');",
  "      setSubmitState(submitBtn, '上传中...', '创建并上传', false);",
  '      return;',
  '    }',
  '    try {',
  '      await validateJsonUpload(fileInput.files[0], "worldbook");',
  '      if (regexInput.files[0]) await validateJsonUpload(regexInput.files[0], "regex");',
  '      const createRes = await createProject(payload);',
  '      const projectId = createRes.projectId;',
  '      await uploadProjectFile(projectId, fileInput.files[0]);',
  '      if (regexInput.files[0]) await uploadRegexFile(projectId, regexInput.files[0]);',
  '      if (coverInput.files[0]) await uploadCoverFile(projectId, coverInput.files[0]);',
  "      showToast('项目上传成功，等待审核');",
  '      overlay.remove();',
  '      await fetchProjects();',
  '    } catch (error) {',
  "      showToast('上传失败: ' + error.message, 'error');",
  '    } finally {',
  "      setSubmitState(submitBtn, '上传中...', '创建并上传', false);",
  '    }',
  '  };',
  '}',
  '',
  'function openEditProjectModal(project) {',
  "  const overlay = openModal(buildProjectFormHtml('edit', project), '<i class=\"fas fa-edit\"></i> 修改项目');",
  "  overlay.querySelectorAll('[data-entry-toggle]').forEach(header => {",
  "    header.addEventListener('click', event => {",
  "      if (event.target.closest('button,input,label')) return;",
  "      header.classList.toggle('open');",
  '      const content = header.nextElementSibling;',
  "      if (content) content.classList.toggle('open');",
  '    });',
  '  });',
  "  overlay.querySelectorAll('[data-entry-remove]').forEach(button => {",
  "    button.addEventListener('click', async event => {",
  '      event.stopPropagation();',
  '      const projectId = button.dataset.projectId;',
  '      const kind = button.dataset.entryKind;',
  '      const entryKey = button.dataset.entryKey;',
  '      if (!projectId || !kind || !entryKey) return;',
  "      if (!confirm('确定从当前项目中移除此条内容？修改会进入审核草稿。')) return;",
  "      const restore = setButtonLoading(button, '删除中');",
  '      try {',
  '        const result = await removeProjectEntry(projectId, kind, entryKey);',
  "        showToast('条目已移除，已切换到最新草稿');",
  '        overlay.remove();',
  '        await fetchProjects(true);',
  '        const targetId = result.projectId || projectId;',
  '        const nextDetail = await fetchProjectEntries(targetId, { forceRefresh: true });',
  '        const nextProject = nextDetail.project ? { ...nextDetail.project, publishedVersion: project.publishedVersion } : { ...project, id: targetId };',
  '        openEditProjectModal(nextProject);',
  '      } catch (error) {',
  "        showToast('删除失败: ' + error.message, 'error');",
  '      } finally { restore(); }',
  '    });',
  '  });',
  '  const { form, fileInput, regexInput, coverInput, submitBtn } = prepareProjectForm(overlay);',
  '  form.onsubmit = async event => {',
  '    event.preventDefault();',
  "    setSubmitState(submitBtn, '保存中...', '保存修改', true);",
  '    const payload = collectProjectFormPayload(form);',
  '    const hasNewFile = Boolean(fileInput.files[0]);',
  '    const hasNewRegex = Boolean(regexInput.files[0]);',
  '    const hasNewCover = Boolean(coverInput.files[0]);',
  '    if (!payload.name && !hasNewFile && !hasNewRegex && !hasNewCover) {',
  "      showToast('请至少填写项目名称或上传文件', 'warning');",
  "      setSubmitState(submitBtn, '保存中...', '保存修改', false);",
  '      return;',
  '    }',
  '    try {',
  '      if (hasNewFile) await validateJsonUpload(fileInput.files[0], "worldbook");',
  '      if (hasNewRegex) await validateJsonUpload(regexInput.files[0], "regex");',
  '      const updateResult = await updateProject(project.id, payload);',
  '      const targetProjectId = updateResult.draftProjectId || updateResult.projectId || project.id;',
  '      if (hasNewFile) await uploadProjectFile(targetProjectId, fileInput.files[0]);',
  '      if (hasNewRegex) await uploadRegexFile(targetProjectId, regexInput.files[0]);',
  '      if (hasNewCover) await uploadCoverFile(targetProjectId, coverInput.files[0]);',
  "      showToast(hasNewFile || hasNewRegex || hasNewCover ? '修改已提交审核，主页仍显示旧版本' : (project.status === 'rejected' ? '项目已重新提交审核' : '项目更新成功'));",
  '      overlay.remove();',
  '      await fetchProjects();',
  '    } catch (error) {',
  "      showToast('更新失败: ' + error.message, 'error');",
  '    } finally {',
  "      setSubmitState(submitBtn, '保存中...', '保存修改', false);",
  '    }',
  '  };',
  '}',
  '',
  'async function openAdminPanel() {',
  '  if (!state.currentUser?.isAdmin) {',
  "    showToast('无权限', 'error');",
  '    return;',
  '  }',
  '  try {',
  '    const data = await fetchPendingProjects();',
  '    const pending = data.projects || [];',
  '    const html = pending.length',
  '      ? pending.map(project => {',
  '          const versionBump = project.publishedVersion ? inferVersionBump(project.publishedVersion, project.version) : null;',
  '          const bumpLabel = versionBump ? versionBump.charAt(0).toUpperCase() + versionBump.slice(1) : "";',
  '          const versionLabel = project.publishedVersion ? `v${project.publishedVersion} → v${project.version}${bumpLabel ? ` · ${bumpLabel}` : ""}` : `v${project.version || "1.0.0"}`;',
  '          return \'<div class="admin-card">\'',
  "            + '<div class=\"admin-card-title\">' + escapeHtml(project.name) + '</div>'",
  "            + '<div>作者: ' + escapeHtml(getAuthorName(project)) + ' · ' + escapeHtml(versionLabel) + '</div>'",
  "            + '<div class=\"admin-card-desc\">' + escapeHtml(project.description || '') + '</div>'",
  '            + \'<div class="admin-card-actions">\'',
  '            + \'<button class="btn" data-id="\' + project.id + \'" data-action="approve">✔️ 批准</button>\'',
  '            + \'<button class="btn" data-id="\' + project.id + \'" data-action="reject">❌ 拒绝</button>\'',
  '            + \'<button class="btn" data-id="\' + project.id + \'" data-action="detail">📄 详情</button>\'',
  "            + '</div>'",
  "            + '</div>';",
  "        }).join('')",
  "      : '<p>暂无待审核项目</p>';",
  "    const overlay = openModal('<h3>待审核项目</h3>' + html, '<i class=\"fas fa-clipboard-check\"></i> 审核中心');",
  "    overlay.querySelectorAll('button[data-action]').forEach(button => {",
  "      button.addEventListener('click', async () => {",
  '        const projectId = button.dataset.id;',
  '        const action = button.dataset.action;',
  '        const project = pending.find(item => item.id === projectId);',
  '        if (!projectId) return;',
  "        if (action === 'detail' && project) {",
  "          const restore = setButtonLoading(button, '加载中');",
  '          Promise.resolve(showProjectDetail(project)).finally(restore);',
  '          return;',
  '        }',
  '        try {',
  "          if (action === 'reject') {",
  "            const reason = prompt('请输入拒绝原因');",
  '            if (!reason) return;',
  '            await reviewProject(projectId, { action, rejectReason: reason });',
  "            showToast('已拒绝');",
  '          } else {',
  '            await reviewProject(projectId, { action });',
  "            showToast('已批准');",
  '          }',
  '          overlay.remove();',
  '          await fetchProjects(true);',
  '          openAdminPanel();',
  '        } catch (error) {',
  "          showToast(error.message, 'error');",
  '        }',
  '      });',
  '    });',
  '  } catch (error) {',
  "    showToast(error.message, 'error');",
  '  }',
  '}',
  '',
  'async function openAdminLogsModal() {',
  '  if (!state.currentUser?.isSuperAdmin) {',
  "    showToast('无权限', 'error');",
  '    return;',
  '  }',
  '  try {',
  '    const data = await fetchAdminLogs();',
  '    const logs = data.logs || [];',
  '    const html = logs.length ? logs.map(log => `<div class="admin-card"><div class="admin-card-title">${escapeHtml(log.action)}</div><div>操作人: ${escapeHtml(log.actorName)} (${escapeHtml(log.actorId)})</div><div>目标: ${escapeHtml(log.targetType)} ${escapeHtml(log.targetId || "-")}</div><div>时间: ${escapeHtml(log.createdAt || "")}</div><pre style="white-space:pre-wrap;word-break:break-all;">${escapeHtml(log.detail || "")}</pre></div>`).join("") : "<p>暂无日志</p>";',
  '    openModal(`<h3>管理员操作日志</h3>${html}`, `<i class=\\"fas fa-clock-rotate-left\\"></i> 操作日志`);',
  '  } catch (error) {',
  "    showToast('加载管理员日志失败: ' + (error && error.message ? error.message : '未知错误'), 'error');",
  '  }',
  '}',
  '',
  'async function openAddAdminModal() {',
  '  if (!state.currentUser?.isSuperAdmin) {',
  "    showToast('无权限', 'error');",
  '    return;',
  '  }',
  '  let admins = [];',
  '  try {',
  '    const data = await fetchAdminList();',
  '    admins = data.admins || [];',
  '  } catch (error) {',
  "    showToast('加载管理员列表失败: ' + (error && error.message ? error.message : '未知错误'), 'error');",
  '  }',
  '  const adminsHtml = admins.length',
  '    ? admins.map(admin => {',
  '        return \'<div class="admin-list-item">\'',
  "          + '<div><img src=\"' + escapeHtml(admin.avatarUrl || 'https://cdn.discordapp.com/embed/avatars/0.png') + '\" style=\"width:32px; height:32px; border-radius:50%; margin-right:8px; vertical-align:middle;\">'",
  "          + escapeHtml(admin.globalName || admin.username) + ' (' + escapeHtml(admin.id) + ')</div>'",
  '          + \'<button class="btn" data-id="\' + admin.id + \'" data-action="remove">移除管理员</button>\'',
  "          + '</div>';",
  "      }).join('')",
  "    : '<p>暂无管理员</p>';",
  '  const overlay = openModal(',
  '    [',
  "      '<div>',",
  "      '<h3>添加管理员</h3>',",
  '      \'<input type="text" id="targetUserId" placeholder="用户ID" style="width:100%; padding:8px; margin-bottom:16px;">\',',
  '      \'<button class="btn btn-primary" id="confirmAdd">设为管理员</button>\',',
  '      \'<hr style="margin:20px 0;">\',',
  "      '<h3>现有管理员列表</h3>',",
  "      '<div id=\"adminListContainer\">' + adminsHtml + '</div>',",
  "      '</div>',",
  "    ].join(''),",
  '    \'<i class="fas fa-user-shield"></i> 管理员设置\',',
  '  );',
  "  overlay.querySelector('#confirmAdd').onclick = async () => {",
  "    const targetId = overlay.querySelector('#targetUserId').value.trim();",
  '    if (!targetId) return;',
  '    try {',
  '      await setAdmin(targetId, true);',
  "      showToast('已设为管理员');",
  '      overlay.remove();',
  '      openAddAdminModal();',
  '    } catch (error) {',
  "      showToast(error.message, 'error');",
  '    }',
  '  };',
  '  overlay.querySelectorAll(\'button[data-action="remove"]\').forEach(button => {',
  "    button.addEventListener('click', async () => {",
  '      const userId = button.dataset.id;',
  "      if (!userId || !confirm('确定要移除该管理员吗？')) return;",
  '      try {',
  '        await setAdmin(userId, false);',
  "        showToast('已移除管理员');",
  '        overlay.remove();',
  '        openAddAdminModal();',
  '      } catch (error) {',
  "        showToast(error.message, 'error');",
  '      }',
  '    });',
  '  });',
  '}',
].join('\n');
