export const homeCardsRenderScript = [
  'function buildProjectCardViewModel(project) {',
  '  const likes = getLikeState(project.id);',
  '  const localMeta = getLocalProjectMeta(project.id);',
  '  const legacyInstalledMatches = localMeta ? [] : getLegacyInstalledProjectMatches(project);',
  '  const hasLegacyIdentityConflict = legacyInstalledMatches.length > 0;',
  '  const pendingAction = getProjectPendingAction(project.id);',
  '  const rebindCandidate = project?.source === "local-only" ? getInstalledProjectRebindCandidate(project.id) : null;',
  '  const isInstalling = pendingAction === "install";',
  '  const isUninstalling = pendingAction === "uninstall";',
  '  const isInstallStateLoading = Boolean(state.tavern.connected && !state.tavern.installedProjectsLoaded);',
  '  const localVersion = localMeta?.localVersion || project.localVersion || null;',
  '  const remoteVersion = project.version || null;',
  '  const displayVersionLabel = project.versionLabel ? String(project.versionLabel) : project.version ? String(project.version) : "";',
  '  const hasVersionDiff = Boolean(localMeta && remoteVersion && (!localVersion || localVersion !== remoteVersion));',
  '  const canUpdate = Boolean(state.tavern.connected && localMeta && hasVersionDiff);',
  '  return {',
  '    likes,',
  '    localMeta,',
  '    isInstalled: Boolean(localMeta),',
  '    canInstall: Boolean(state.tavern.connected && state.tavern.installedProjectsLoaded && !hasLegacyIdentityConflict),',
  '    hasLegacyIdentityConflict,',
  '    rebindCandidate,',
  '    canUpdate,',
  '    localVersion,',
  '    worldbookName: localMeta?.worldbookName || project.worldbookName || null,',
  '    remoteVersion,',
  '    hasVersionDiff,',
  '    versionHtml: displayVersionLabel ? `<span>${escapeHtml(displayVersionLabel)}</span>` : "",',
  '    downloadsCount: Number(project.downloadsCount || 0),',
  '    installText: isInstallStateLoading ? "检查安装状态..." : hasLegacyIdentityConflict ? "旧版安装待识别" : isInstalling ? "安装中..." : isUninstalling ? "卸载中..." : localMeta ? "卸载" : "安装",',
  '    installDisabled: !state.tavern.connected || !state.tavern.installedProjectsLoaded || hasLegacyIdentityConflict || Boolean(pendingAction),',
  '    installPending: Boolean(pendingAction) || isInstallStateLoading,',
  '  };',
  '}',
  'function getProjectCoverPresentation(project) {',
  '  const x = Math.min(100, Math.max(0, Number(project?.coverPositionX ?? 50)));',
  '  const y = Math.min(100, Math.max(0, Number(project?.coverPositionY ?? 50)));',
  '  const zoom = Math.min(3, Math.max(1, Number(project?.coverZoom ?? 1)));',
  '  return { x, y, zoom, style: `background-position:${x}% ${y}%;transform:scale(${zoom});transform-origin:${x}% ${y}%;` };',
  '}',
  'function renderDiscoverCard(project) {',
  '  const authorName = getAuthorName(project);',
  '  const hasCover = Boolean(project?.coverImage);',
  '  const coverSources = hasCover ? getCoverImageSources(project) : null;',
  '  const presentation = getProjectCoverPresentation(project);',
  '  const likes = getLikeState(project.id);',
  '  const likeHint = state.currentUser ? (likes.liked ? "取消点赞" : "点赞") : "登录后可点赞";',
  '  const statsHtml = `<div class="discover-card-stats"><button type="button" class="discover-card-stat discover-card-like like-btn ${likes.liked ? "liked" : ""}" data-id="${project.id}" title="${likeHint}" aria-pressed="${likes.liked ? "true" : "false"}" ${state.currentUser ? "" : "disabled"}><i class="fas fa-heart"></i><span>${likes.count}</span></button><span class="discover-card-stat" title="下载数"><i class="fas fa-download"></i><span>${Number(project.downloadsCount || 0)}</span></span></div>`;',
  '  const mediaHtml = hasCover',
  '    ? `<div class="discover-card-cover-shell"><div class="discover-card-cover" data-cover-src="${escapeHtml(coverSources.primary)}" data-cover-fallback-src="${escapeHtml(coverSources.fallback)}" data-cover-placeholder-src="${escapeHtml(coverSources.placeholder)}" data-cover-auth-src="${escapeHtml(coverSources.authenticated || "")}" data-cover-title="${escapeHtml(project.name)}" data-cover-position-x="${presentation.x}" data-cover-position-y="${presentation.y}" data-cover-zoom="${presentation.zoom}" style="background-image:url(\'${escapeHtml(coverSources.primary)}\');${presentation.style}"></div></div>`',
  '    : `<div class="discover-card-cover-shell"><div class="discover-card-cover discover-card-cover--title"><span>${escapeHtml(project.name)}</span></div></div>`;',
  '  return `<article class="discover-card" data-id="${project.id}" role="button" tabindex="0" aria-label="查看项目详情：${escapeHtml(project.name)}">${mediaHtml}<div class="discover-card-copy"><h3>${escapeHtml(project.name)}</h3><div class="discover-card-copy-meta"><p>${escapeHtml(authorName)}</p>${statsHtml}</div></div></article>`;',
  '}',
  'function renderDevTeamRecommendations() {',
  '  const curators = Array.isArray(state.devTeamCurators) ? state.devTeamCurators : [];',
  '  if (!curators.length) return state.currentUser?.isAdmin ? `<section class="devteam-recommendations"><div class="devteam-recommendations-title"><small>DEVTEAM RECOMMEND</small><h2>开发组推荐</h2></div><div class="devteam-recommend-empty"><i class="fas fa-user-pen"></i><div><strong>还没有推荐</strong><p>打开任意公开作品详情，点击「DevTeam 推荐」就可以写第一条。</p></div></div></section>` : "";',
  '  const blocks = curators.map(curator => {',
  '    const recommendations = Array.isArray(curator?.recommendations) ? curator.recommendations.filter(item => item?.project) : [];',
  '    if (!recommendations.length) return "";',
  '    const avatar = curator.avatarUrl || "https://cdn.discordapp.com/embed/avatars/0.png";',
  '    const name = curator.name || "DevTeam";',
  '    const bio = String(curator.bio || "").trim();',
  '    const items = recommendations.map(item => `<div class="devteam-recommend-item">${renderDiscoverCard(item.project)}<div class="devteam-recommend-comment"><span><i class="fas fa-thumbs-up"></i> 推荐</span><p>${escapeHtml(String(item.comment || ""))}</p></div></div>`).join("");',
  '    return `<section class="devteam-curator-block"><header class="devteam-curator-head"><img src="${escapeHtml(avatar)}" alt=""><div><small>关注 ${escapeHtml(name)} 来查看更多类似的推荐</small><h3>${escapeHtml(name)}</h3>${bio ? `<p>${escapeHtml(bio)}</p>` : ""}</div></header><div class="devteam-curator-track">${items}</div></section>`;',
  '  }).join("");',
  '  return blocks ? `<section class="devteam-recommendations"><div class="devteam-recommendations-title"><small>DEVTEAM RECOMMEND</small><h2>开发组推荐</h2></div>${blocks}</section>` : "";',
  '}',
  'function renderProjectCard(project) {',
  '  const coverSources = getCoverImageSources(project);',
  '  const projectType = getBaseTag(project);',
  '  const baseTag = getProjectTypeDisplayLabel(project);',
  '  const typeClass = getTypeClass(project);',

  '  const authorName = getAuthorName(project);',
  '  const view = buildProjectCardViewModel(project);',
  '  const presentation = getProjectCoverPresentation(project);',
  '  const showAdminActions = isProjectEditable(project);',
  '  const isPendingProject = isProjectPending(project);',
  '  const isRejectedDraftProject = isRejectedDraft(project);',
  '  const isReviewDraftProject = Boolean(project?.reviewTarget === "draft" && project?.publishedProjectId);',
  '  const isPendingReviewDraft = Boolean(isReviewDraftProject && isPendingProject);',
  '  const isInitialPendingProject = Boolean(!isReviewDraftProject && isPendingProject && !project?.isPublished);',
  '  const isDraftingProject = Boolean(isReviewDraftProject && project?.status === "drafting");',
  '  const hasCurrentDraft = Boolean(project?.isPublished && project?.draftProjectId);',
  '  const deleteLabel = isPendingReviewDraft ? "继续编辑" : isInitialPendingProject ? "撤回提交" : isDraftingProject ? "删除草稿" : isReviewDraftProject ? "撤回更新" : "删除";',
  '  const deleteTitle = isPendingReviewDraft',
  '    ? "保留这次审核快照，并从它创建新的编辑草稿"',
  '    : isReviewDraftProject',
  '      ? "撤回当前草稿，已发布版本会保留"',
  '    : project?.isPublished && (project?.hasPendingDraft || project?.draftProjectId)',
  '      ? "删除正式项目；关联的审核草稿也会一并删除"',
  '      : "删除项目";',
  '  const deleteWholeProjectHtml = isReviewDraftProject',
  '    ? `<button class="action-btn delete-project-btn" data-id="${project.publishedProjectId}" title="删除整个项目，包括当前更新草稿"><i class="fas fa-trash"></i> 删除项目</button>`',
  '    : "";',
  '  const editButtonHtml = isPendingProject || hasCurrentDraft',
  '    ? ""',
  '    : `<button class="action-btn edit-btn" data-id="${project.id}" title="${isRejectedDraftProject ? "修改后可重新提交审核" : "修改项目"}"><i class="fas fa-edit"></i> 修改</button>`;',
  '  const coverAdjustButtonHtml = project.coverImage && !isPendingReviewDraft ? `<button class="action-btn cover-presentation-btn" data-id="${project.id}"><i class="fas fa-crop-simple"></i> 调整封面</button>` : "";',
  '  const myRecommendation = state.currentUser?.isAdmin ? getMyDevTeamRecommendation(project.id) : null;',
  '  const devTeamRecommendButtonHtml = state.currentUser?.isAdmin && project.status === "approved" && project.isPublished && project.visibility !== false ? `<button class="action-btn devteam-recommend-btn" data-id="${project.id}"><i class="fas fa-thumbs-up"></i> ${myRecommendation ? "修改推荐" : "DevTeam 推荐"}</button>` : "";',
  '  const visibilityButtonHtml = isPendingReviewDraft ? "" : `<button class="action-btn visibility-btn" data-id="${project.id}" data-visible="${project.visibility ? "1" : "0"}"><i class="fas ${project.visibility ? "fa-eye-slash" : "fa-eye"}"></i> ${project.visibility ? "隐藏" : "公开"}</button>`;',
  '  const reviewBadge = getProjectReviewBadge(project);',
  '  const rejectReason = getProjectRejectReason(project);',
  '  const signalPolicy = PROJECT_TAXONOMY.systemSignals || {};',
  '  const visibleTags = getProjectDisplayTags(project).slice(0, 5);',
  '  const displayTagsHtml = visibleTags.map(tag => `<span class="tag">#${escapeHtml(tag)}</span>`).join("");',
  '  const tagsRowHtml = displayTagsHtml ? `<div class="project-tags">${displayTagsHtml}</div>` : "";',
  '  const artworkLabel = escapeHtml(signalPolicy.characterArtwork?.label || "游戏内图片");',
  '  const artworkBadgeHtml = project.hasCharacterArtwork && signalPolicy.characterArtwork?.card !== false ? `<span class="card-art-badge" aria-label="${artworkLabel}" title="${artworkLabel}"><i class="fas fa-images"></i></span>` : "";',
  '  const installedSignalHtml = view.isInstalled ? `<span class="card-quality-signal card-quality-signal--installed"><i class="fas fa-circle-check"></i><span>${view.canUpdate ? "可更新" : "已安装"}</span></span>` : "";',
  '  const likeHint = state.currentUser ? (view.likes.liked ? "取消点赞" : "点赞") : "登录后可点赞";',
  '  const cardStatsHtml = `<div class="card-owner-stats card-public-stats" aria-label="项目统计"><button type="button" class="card-like-stat like-btn ${view.likes.liked ? "liked" : ""}" data-id="${project.id}" title="${likeHint}" aria-pressed="${view.likes.liked ? "true" : "false"}" ${state.currentUser ? "" : "disabled"}><i class="fas fa-heart"></i><span>${view.likes.count}</span></button><span title="下载数"><i class="fas fa-download"></i>${view.downloadsCount}</span></div>`;',
  '  const statusHtml = reviewBadge || rejectReason ? `<div class="card-status-line">${reviewBadge}${rejectReason ? `<span class="card-reject-reason">退回：${escapeHtml(rejectReason)}</span>` : ""}</div>` : "";',
  '  const adminActionsHtml = showAdminActions',
  '    ? `<div class="card-admin-control"><button class="card-more-btn" type="button" aria-label="管理作品" title="管理作品">⋯</button><div class="card-admin-menu${isReviewDraftProject && !isPendingProject ? " card-admin-menu--draft" : ""}">${editButtonHtml}${coverAdjustButtonHtml}${devTeamRecommendButtonHtml}${visibilityButtonHtml}<button class="action-btn delete-btn" data-id="${project.id}" title="${deleteTitle}"><i class="fas fa-trash"></i> ${deleteLabel}</button>${deleteWholeProjectHtml}</div></div>`',
  '    : "";',
  '  const installButtonClass = `${view.installDisabled ? "action-btn install-btn is-disabled" : "action-btn install-btn"}${view.installPending ? " is-loading" : ""}`;',
  '  const updateButton = view.canUpdate ? `<button class="action-btn inline-update-btn update-btn" data-id="${project.id}"><i class="fas fa-arrows-rotate"></i><span>更新</span></button>` : "";',
  '  const rebindButton = view.rebindCandidate ? `<button class="action-btn rebind-project-btn" data-id="${project.id}"><i class="fas fa-link"></i><span>${view.rebindCandidate.projects.length === 1 ? "确认对应项目" : "选择对应项目"}</span></button>` : "";',
  '  const hasCustomCover = Boolean(project?.coverImage);',
  '  const previewBodyHtml = hasCustomCover',
  '    ? `<div class="card-cover" data-cover-src="${escapeHtml(coverSources.primary)}" data-cover-fallback-src="${escapeHtml(coverSources.fallback)}" data-cover-placeholder-src="${escapeHtml(coverSources.placeholder)}" data-cover-auth-src="${escapeHtml(coverSources.authenticated || "")}" data-cover-position-x="${presentation.x}" data-cover-position-y="${presentation.y}" data-cover-zoom="${presentation.zoom}" style="background-image:url(\'${escapeHtml(coverSources.primary)}\')"></div>`',
  '    : `<div class="card-text-preview"><span class="card-text-preview__type">${escapeHtml(baseTag)}</span><p>${escapeHtml(project.description || "这个项目暂时没有提供首页简介。")}</p><span class="card-text-preview__hint">打开查看完整说明 →</span></div>`;',
  '  const previewHtml = `<div class="card-cover-wrap">${previewBodyHtml}${artworkBadgeHtml}</div>`;',
  '  const titleHtml = `<div class="card-title-row"><div class="project-name"><span class="card-type-badge card-type-badge--${typeClass}"><span class="card-type-label">${escapeHtml(projectType)}</span></span><span class="project-title-text">${escapeHtml(project.name)}</span></div></div>`;',
  '  return `<article class="project-card" data-id="${project.id}" role="button" tabindex="0" aria-label="查看项目详情：${escapeHtml(project.name)}"><div class="card-head"><span class="card-creator">${escapeHtml(authorName)}</span>${adminActionsHtml}</div>${titleHtml}${previewHtml}<div class="card-content">${tagsRowHtml}${statusHtml}<div class="card-footer"><div class="card-signals">${cardStatsHtml}${installedSignalHtml}</div><div class="card-footer-actions">${rebindButton}${updateButton}<button class="${installButtonClass}" data-id="${project.id}" ${view.installDisabled ? "disabled" : ""}><i class="fas ${view.installPending ? "fa-spinner fa-spin" : view.isInstalled ? "fa-trash" : "fa-download"}"></i><span>${view.installText}</span></button></div></div></div></article>`;',
  '}',
].join('\n');
