export const homeCardsRenderScript = [
  'function buildProjectCardViewModel(project) {',
  '  const likes = getLikeState(project.id);',
  '  const subs = getSubscribeState(project.id);',
  '  const localMeta = getLocalProjectMeta(project.id);',
  '  const pendingAction = getProjectPendingAction(project.id);',
  '  const isInstalling = pendingAction === "install";',
  '  const isUninstalling = pendingAction === "uninstall";',
  '  const localVersion = localMeta?.localVersion || project.localVersion || null;',
  '  const remoteVersion = project.version || null;',
  '  const hasVersionDiff = Boolean(localMeta && localVersion && remoteVersion && localVersion !== remoteVersion);',
  '  const canUpdate = Boolean(state.tavern.connected && localMeta && hasVersionDiff);',
  '  return {',
  '    likes,',
  '    subs,',
  '    localMeta,',
  '    isInstalled: Boolean(localMeta),',
  '    canInstall: Boolean(state.tavern.connected),',
  '    canUpdate,',
  '    localVersion,',
  '    remoteVersion,',
  '    hasVersionDiff,',
  '    versionHtml: hasVersionDiff ? `<span class="version-diff"><span class="version-diff__from">${escapeHtml(localVersion)}</span><i class="fas fa-arrow-right"></i><span class="version-diff__to">${escapeHtml(remoteVersion)}</span></span>` : `<span>v${escapeHtml(remoteVersion || "1.0.0")}</span>`,',
  '    installText: isInstalling ? "安装中..." : isUninstalling ? "卸载中..." : localMeta ? "卸载" : "安装",',
  '    installDisabled: !state.tavern.connected || Boolean(pendingAction),',
  '    installPending: Boolean(pendingAction),',
  '    downloadsCount: Number(project.downloadsCount || 0),',
  '  };',
  '}',
  'function renderProjectCard(project) {',
  '  const coverSources = getCoverImageSources(project);',
  '  const typeClass = getTypeClass(project);',
  '  const baseTag = getBaseTag(project);',
  '  const authorName = getAuthorName(project);',
  '  const authorAvatar = getAuthorAvatar(project);',
  '  const view = buildProjectCardViewModel(project);',
  '  const showAdminActions = isProjectEditable(project);',
  '  const isPendingProject = isProjectPending(project);',
  '  const isRejectedDraftProject = isRejectedDraft(project);',
  '  const reviewBadge = getProjectReviewBadge(project);',
  '  const tagsHtml = (project.tags || []).slice(0, 4).map(tag => `<span class="tag">${escapeHtml(tag)}</span>`).join("");',
  '  const interactionDisabled = !state.currentUser;',
  '  const likeDisabledAttr = interactionDisabled ? "disabled" : "";',
  '  const subscribeDisabledAttr = interactionDisabled ? "disabled" : "";',
  '  const adminHtml = showAdminActions',
  '    ? `<div class="admin-actions"><button class="action-btn edit-btn ${isPendingProject ? "is-disabled" : ""}" data-id="${project.id}" ${isPendingProject ? "disabled" : ""} title="${isPendingProject ? "审核中的项目暂不可修改" : isRejectedDraftProject ? "修改后可重新提交审核" : "修改项目"}"><i class="fas fa-edit"></i> 修改</button><button class="action-btn visibility-btn" data-id="${project.id}" data-visible="${project.visibility ? "1" : "0"}"><i class="fas ${project.visibility ? "fa-eye-slash" : "fa-eye"}"></i> ${project.visibility ? "隐藏" : "公开"}</button><button class="action-btn delete-btn ${isPendingProject ? "is-disabled" : ""}" data-id="${project.id}" ${isPendingProject ? "disabled" : ""} title="${isPendingProject ? "审核中的项目暂不可删除" : isRejectedDraftProject ? "删除该被拒绝草稿" : "删除项目"}"><i class="fas fa-trash"></i> 删除</button></div>`',
  '    : "";',
  '  const installedBadge = view.isInstalled ? `<span class="install-badge ${view.canUpdate ? "install-badge--update" : ""}"><i class="fas fa-check-circle"></i> 已安装</span>` : "";',
  '  const updateButton = view.canUpdate ? `<button class="inline-update-btn update-btn" data-id="${project.id}"><i class="fas fa-arrows-rotate"></i> 更新</button>` : "";',
  '  const installButtonClass = `${view.installDisabled ? "action-btn install-btn is-disabled" : "action-btn install-btn"}${view.installPending ? " is-loading" : ""}`;',
  '  const likeHint = interactionDisabled ? "登录后可点赞" : (view.likes.liked ? "取消点赞" : "点赞项目");',
  '  const subscribeHint = interactionDisabled ? "登录后可订阅" : (view.subs.subscribed ? "取消订阅" : "订阅更新");',
  '  return `<div class="project-card" data-id="${project.id}"><div class="card-cover" data-cover-src="${escapeHtml(coverSources.primary)}" data-cover-fallback-src="${escapeHtml(coverSources.fallback)}" data-cover-placeholder-src="${escapeHtml(coverSources.placeholder)}" style="background-image: url(\'${escapeHtml(coverSources.primary)}\');"><div class="card-overlay-actions"><button class="icon-stat-btn like-btn ${view.likes.liked ? "liked" : ""} ${interactionDisabled ? "is-disabled" : ""}" data-id="${project.id}" title="${likeHint}" aria-label="${likeHint}" ${likeDisabledAttr}><i class="fas fa-heart"></i><span>${view.likes.count}</span><span class="icon-stat-btn__hint">${likeHint}</span></button><button class="icon-stat-btn subscribe-btn ${view.subs.subscribed ? "subscribed" : ""} ${interactionDisabled ? "is-disabled" : ""}" data-id="${project.id}" title="${subscribeHint}" aria-label="${subscribeHint}" ${subscribeDisabledAttr}><i class="fas fa-bell"></i><span>${view.subs.count}</span><span class="icon-stat-btn__hint">${subscribeHint}</span></button><div class="icon-stat-btn icon-stat-btn--static"><i class="fas fa-download"></i><span>${view.downloadsCount}</span></div></div></div><div class="card-content"><div class="card-row1"><span class="type-badge ${typeClass}">${escapeHtml(baseTag)}</span><span class="project-name">${escapeHtml(project.name)}</span></div><div class="card-author"><img class="author-avatar" src="${escapeHtml(authorAvatar)}" alt="avatar"><span>${escapeHtml(authorName)}</span>${installedBadge}</div><div class="project-tags">${tagsHtml}</div><div class="card-meta card-meta--version"><span class="version-block">${view.versionHtml}</span>${updateButton}<span>${escapeHtml(formatDate(project.updatedAt))}</span></div><div class="card-meta">${reviewBadge}${project.rejectReason ? `<span>拒绝原因：${escapeHtml(project.rejectReason)}</span>` : ""}</div><div class="card-actions card-actions--primary"><button class="action-btn detail-btn" data-id="${project.id}"><i class="fas fa-info-circle"></i> 详情</button><button class="${installButtonClass}" data-id="${project.id}" ${view.installDisabled ? "disabled" : ""}><i class="fas ${view.installPending ? "fa-spinner fa-spin" : view.isInstalled ? "fa-trash" : "fa-download"}"></i> ${view.installText}</button></div>${adminHtml}</div></div>`;',
  '}',
].join('\n');
