export const homeCardsRenderScript = [
  'function buildProjectCardViewModel(project) {',
  '  const likes = getLikeState(project.id);',
  '  const localMeta = getLocalProjectMeta(project.id);',
  '  const legacyInstalledMatches = localMeta ? [] : getLegacyInstalledProjectMatches(project);',
  '  const hasLegacyIdentityConflict = legacyInstalledMatches.length > 0;',
  '  const pendingAction = getProjectPendingAction(project.id);',
  '  const isInstalling = pendingAction === "install";',
  '  const isUninstalling = pendingAction === "uninstall";',
  '  const isInstallStateLoading = Boolean(state.tavern.connected && !state.tavern.installedProjectsLoaded);',
  '  const localVersion = localMeta?.localVersion || project.localVersion || null;',
  '  const remoteVersion = project.version || null;',
  '  const displayVersionLabel = project.versionLabel ? String(project.versionLabel) : project.version ? String(project.version) : "";',
  '  const hasVersionDiff = Boolean(localMeta && remoteVersion && (!localVersion || localVersion !== remoteVersion));',
  '  const canUpdate = Boolean(state.tavern.connected && localMeta && hasVersionDiff);',
  '  return {',
  '    likes,',
  '    localMeta,',
  '    isInstalled: Boolean(localMeta),',
  '    canInstall: Boolean(state.tavern.connected && state.tavern.installedProjectsLoaded && !hasLegacyIdentityConflict),',
  '    hasLegacyIdentityConflict,',
  '    canUpdate,',
  '    localVersion,',
  '    worldbookName: localMeta?.worldbookName || project.worldbookName || null,',
  '    remoteVersion,',
  '    hasVersionDiff,',
  '    versionHtml: displayVersionLabel ? `<span>${escapeHtml(displayVersionLabel)}</span>` : "",',
  '    downloadsCount: Number(project.downloadsCount || 0),',
  '    installText: isInstallStateLoading ? "检查安装状态..." : hasLegacyIdentityConflict ? "旧版安装待识别" : isInstalling ? "安装中..." : isUninstalling ? "卸载中..." : localMeta ? "卸载" : "安装",',
  '    installDisabled: !state.tavern.connected || !state.tavern.installedProjectsLoaded || hasLegacyIdentityConflict || Boolean(pendingAction),',
  '    installPending: Boolean(pendingAction) || isInstallStateLoading,',
  '  };',
  '}',
  'function renderProjectCard(project) {',
  '  const coverSources = getCoverImageSources(project);',
  '  const baseTag = getProjectTypeDisplayLabel(project);',
  '  const authorName = getAuthorName(project);',
  '  const view = buildProjectCardViewModel(project);',
  '  const showAdminActions = isProjectEditable(project);',
  '  const isPendingProject = isProjectPending(project);',
  '  const isRejectedDraftProject = isRejectedDraft(project);',
  '  const isReviewDraftProject = Boolean(project?.reviewTarget === "draft" && project?.publishedProjectId);',
  '  const deleteLabel = isReviewDraftProject ? "撤回更新" : "删除";',
  '  const deleteTitle = isReviewDraftProject',
  '    ? "撤回当前审核草稿，已发布版本会保留"',
  '    : project?.isPublished && (project?.hasPendingDraft || project?.draftProjectId)',
  '      ? "删除正式项目；关联的审核草稿也会一并删除"',
  '      : "删除项目";',
  '  const deleteWholeProjectHtml = isReviewDraftProject',
  '    ? `<button class="action-btn delete-project-btn" data-id="${project.publishedProjectId}" title="删除整个项目，包括当前更新草稿"><i class="fas fa-trash"></i> 删除项目</button>`',
  '    : "";',
  '  const editButtonHtml = isReviewDraftProject && isPendingProject',
  '    ? ""',
  '    : `<button class="action-btn edit-btn" data-id="${project.id}" title="${isPendingProject ? "修改审核中的草稿" : isRejectedDraftProject ? "修改后可重新提交审核" : "修改项目"}"><i class="fas fa-edit"></i> 修改</button>`;',
  '  const reviewBadge = getProjectReviewBadge(project);',
  '  const rejectReason = getProjectRejectReason(project);',
  '  const signalPolicy = PROJECT_TAXONOMY.systemSignals || {};',
  '  const visibleTags = Array.from(new Set([baseTag, ...getProjectDisplayTags(project)])).slice(0, 5);',
  '  const displayTagsHtml = visibleTags.map(tag => `<span class="tag">${escapeHtml(tag)}</span>`).join("");',
  '  const tagsRowHtml = displayTagsHtml ? `<div class="project-tags">${displayTagsHtml}</div>` : "";',
  '  const artworkLabel = escapeHtml(signalPolicy.characterArtwork?.label || "游戏内图片");',
  '  const artworkSignalHtml = project.hasCharacterArtwork && signalPolicy.characterArtwork?.card !== false ? `<span class="card-quality-signal" title="${artworkLabel}"><i class="fas fa-images"></i><span>有图</span></span>` : "";',
  '  const installedSignalHtml = view.isInstalled ? `<span class="card-quality-signal card-quality-signal--installed"><i class="fas fa-circle-check"></i><span>${view.canUpdate ? "可更新" : "已安装"}</span></span>` : "";',
  '  const ownerStatsHtml = state.showOnlyMyProjects ? `<div class="card-owner-stats" aria-label="项目统计"><span title="点赞数"><i class="fas fa-heart"></i>${view.likes.count}</span><span title="下载数"><i class="fas fa-download"></i>${view.downloadsCount}</span></div>` : "";',
  '  const statusHtml = reviewBadge || rejectReason ? `<div class="card-status-line">${reviewBadge}${rejectReason ? `<span class="card-reject-reason">退回：${escapeHtml(rejectReason)}</span>` : ""}</div>` : "";',
  '  const adminActionsHtml = showAdminActions',
  '    ? `<div class="card-admin-control"><button class="card-more-btn" type="button" aria-label="管理作品" title="管理作品">⋯</button><div class="card-admin-menu${isReviewDraftProject && !isPendingProject ? " card-admin-menu--draft" : ""}">${editButtonHtml}<button class="action-btn visibility-btn" data-id="${project.id}" data-visible="${project.visibility ? "1" : "0"}"><i class="fas ${project.visibility ? "fa-eye-slash" : "fa-eye"}"></i> ${project.visibility ? "隐藏" : "公开"}</button><button class="action-btn delete-btn" data-id="${project.id}" title="${deleteTitle}"><i class="fas fa-trash"></i> ${deleteLabel}</button>${deleteWholeProjectHtml}</div></div>`',
  '    : "";',
  '  const installButtonClass = `${view.installDisabled ? "action-btn install-btn is-disabled" : "action-btn install-btn"}${view.installPending ? " is-loading" : ""}`;',
  '  const updateButton = view.canUpdate ? `<button class="action-btn inline-update-btn update-btn" data-id="${project.id}"><i class="fas fa-arrows-rotate"></i><span>更新</span></button>` : "";',
  '  const hasCustomCover = Boolean(project?.coverImage);',
  '  const previewHtml = hasCustomCover',
  '    ? `<div class="card-cover" data-cover-src="${escapeHtml(coverSources.primary)}" data-cover-fallback-src="${escapeHtml(coverSources.fallback)}" data-cover-placeholder-src="${escapeHtml(coverSources.placeholder)}" data-cover-auth-src="${escapeHtml(coverSources.authenticated || "")}" style="background-image:url(\'${escapeHtml(coverSources.primary)}\')"></div>`',
  '    : `<div class="card-text-preview"><span class="card-text-preview__type">${escapeHtml(baseTag)}</span><p>${escapeHtml(project.description || "这个项目暂时没有提供首页简介。")}</p><span class="card-text-preview__hint">打开查看完整说明 →</span></div>`;',
  '  return `<article class="project-card" data-id="${project.id}" role="button" tabindex="0" aria-label="查看项目详情：${escapeHtml(project.name)}"><div class="card-head"><span class="card-creator">${escapeHtml(authorName)}</span>${adminActionsHtml}</div>${previewHtml}<div class="card-content"><div class="project-name">${escapeHtml(project.name)}</div>${tagsRowHtml}${statusHtml}<div class="card-footer"><div class="card-signals">${ownerStatsHtml}${artworkSignalHtml}${installedSignalHtml}</div><div class="card-footer-actions">${updateButton}<button class="${installButtonClass}" data-id="${project.id}" ${view.installDisabled ? "disabled" : ""}><i class="fas ${view.installPending ? "fa-spinner fa-spin" : view.isInstalled ? "fa-trash" : "fa-download"}"></i><span>${view.installText}</span></button></div></div></div></article>`;',
  '}',
].join('\n');
