export const homeDetailModalRenderScript = [
  'function renderEntryRemoveButton(project, kind, entry, allowRemove) {',
  '  if (!allowRemove || !project?.id || !entry?.entryKey) return "";',
  '  return `<button class="entry-remove-btn" type="button" title="删除此条" aria-label="删除此条" data-entry-remove data-project-id="${escapeHtml(String(project.id))}" data-entry-kind="${kind}" data-entry-key="${escapeHtml(String(entry.entryKey))}"><i class="fas fa-trash"></i></button>`;',
  '}',
  'function renderRegexEntry(entry, context) {',
  '  const title = entry.scriptName || entry.name || entry.id || "未命名正则";',
  '  const replaceText = entry.replaceString || entry.replace_string || "无替换文本";',
  '  const removeButton = renderEntryRemoveButton(context?.project, "regex", entry, context?.allowRemove);',
  '  return `<div class="entry-item"><div class="entry-header" data-entry-toggle><i class="fas fa-chevron-right"></i><span class="strategy-badge strategy-selective">R</span><span class="entry-title">${escapeHtml(title)}</span>${removeButton}</div><div class="entry-content"><div class="detail-entry-meta"><div class="detail-keywords-block"><div class="detail-keywords-title">匹配表达式</div><div class="detail-keyword-list"><span class="keyword-chip">${escapeHtml(entry.findRegex || entry.find_regex || "无")}</span></div></div><div class="detail-entry-content">${escapeHtml(replaceText)}</div></div></div></div>`;',
  '}',
  'function renderDetailSection(title, icon, entries, renderer, emptyText, project, allowRemove) {',
  '  const context = { project, allowRemove: Boolean(allowRemove) };',
  '  const itemsHtml = entries.length ? entries.map(entry => renderer(entry, context)).join("") : `<div class="empty-state">${emptyText}</div>`;',
  '  return `<div class="detail-section"><div class="detail-section-title"><span><i class="fas ${icon}"></i> ${title}</span><span>${entries.length} 条</span></div><div class="detail-entry-list">${itemsHtml}</div></div>`;',
  '}',
  'function renderDetailEntry(entry, context) {',
  '  const strategy = getEntryStrategy(entry);',
  '  const keywords = normalizeEntryKeywords(entry);',
  '  const secondaryKeywords = normalizeEntrySecondaryKeywords(entry);',
  '  const keywordsHtml = keywords.length ? keywords.map(keyword => `<span class="keyword-chip">${escapeHtml(keyword)}</span>`).join("") : `<span class="keyword-chip">无</span>`;',
  '  const secondaryKeywordsHtml = secondaryKeywords.length ? secondaryKeywords.map(keyword => `<span class="keyword-chip">${escapeHtml(keyword)}</span>`).join("") : `<span class="keyword-chip">无</span>`;',
  '  const removeButton = renderEntryRemoveButton(context?.project, "worldbook", entry, context?.allowRemove);',
  '  return `<div class="entry-item"><div class="entry-header" data-entry-toggle><i class="fas fa-chevron-right"></i><span class="strategy-badge ${strategy.className}">${strategy.symbol}</span><span class="entry-title">${escapeHtml(entry.comment || "无标题")}</span>${removeButton}</div><div class="entry-content"><div class="detail-entry-meta"><div class="detail-keywords-block"><div><div class="detail-keywords-title">主要关键词</div><div class="detail-keyword-list">${keywordsHtml}</div></div><div><div class="detail-keywords-title">次要关键词</div><div class="detail-keyword-list">${secondaryKeywordsHtml}</div></div></div><div class="detail-entry-content">${escapeHtml(entry.content || "无内容")}</div></div></div></div>`;',
  '}',
  'function renderProjectDetail(project, entries, regexEntries) {',
  '  const authorName = getAuthorName(project);',
  '  const authorAvatar = getAuthorAvatar(project);',
  '  const coverSources = getCoverImageSources(project);',
  '  const baseTag = getBaseTag(project);',
  '  const publishedDate = formatDate(getProjectPublishedAt(project));',
  '  const tagsHtml = (project.tags || []).map(tag => `<span class="tag">${escapeHtml(tag)}</span>`).join("");',
  '  const view = buildProjectCardViewModel(project);',
  '  const installButtonClass = `${view.installDisabled ? "btn btn-primary detail-install-btn is-disabled" : "btn btn-primary detail-install-btn"}${view.installPending ? " is-loading" : ""}`;',
  '  const updateButton = view.canUpdate ? `<button class="btn btn-outline detail-update-btn update-btn" data-id="${project.id}"><i class="fas fa-arrows-rotate"></i> 更新</button>` : "";',
  '  const installBadge = view.isInstalled ? `<span class="install-badge ${view.canUpdate ? "install-badge--update" : ""}"><i class="fas fa-check-circle"></i> 已安装</span>` : "";',
  '  const summaryActions = `<div class="detail-actions-panel">${installBadge}<button class="${installButtonClass}" data-id="${project.id}" ${view.installDisabled ? "disabled" : ""}><i class="fas ${view.installPending ? "fa-spinner" : view.isInstalled ? "fa-trash" : "fa-download"}"></i> ${view.installText}</button>${updateButton}</div>`;',
  '  const worldbookSection = renderDetailSection("世界书条目", "fa-scroll", entries, renderDetailEntry, "无条目内容");',
  '  const regexSection = renderDetailSection("正则列表", "fa-code", regexEntries || [], renderRegexEntry, "无正则内容");',
  '  return `<div class="detail-panel detail-panel-scroll"><div class="detail-cover" data-cover-src="${escapeHtml(coverSources.primary)}" data-cover-fallback-src="${escapeHtml(coverSources.fallback)}" data-cover-placeholder-src="${escapeHtml(coverSources.placeholder)}" data-cover-auth-src="${escapeHtml(coverSources.authenticated || "")}" style="background-image: url(\'${escapeHtml(coverSources.primary)}\');"></div><div class="detail-summary detail-summary--split"><div class="detail-summary-main"><div class="detail-card-row detail-card-row-title"><span class="type-badge ${getTypeClass(project)}">${escapeHtml(baseTag)}</span><div class="detail-project-name">${escapeHtml(project.name)}</div></div><div class="detail-card-row"><div class="detail-author"><img class="detail-author-avatar" src="${escapeHtml(authorAvatar)}" alt="avatar"><span>${escapeHtml(authorName)}</span></div></div><div class="project-tags detail-tags-row">${tagsHtml}</div><div class="detail-card-row detail-meta-row">${view.versionHtml ? `<span class="detail-meta-item"><i class="fas fa-code-branch"></i> ${view.versionHtml}</span>` : ""}<span class="detail-meta-item"><i class="fas fa-calendar-alt"></i> ${escapeHtml(publishedDate)}</span><span class="detail-meta-item"><i class="fas fa-book-open"></i> ${entries.length} 条世界书条目</span><span class="detail-meta-item"><i class="fas fa-code"></i> ${(regexEntries || []).length} 条正则</span></div><div class="detail-description">${escapeHtml(project.description || "无简介")}</div></div>${summaryActions}</div>${worldbookSection}${regexSection}</div>`;',
  '}',
].join('\n');
