export const homeDetailModalRenderScript = [
  'function renderEntryRemoveButton(project, kind, entry, allowRemove) {',
  '  if (!allowRemove || !project?.id || !entry?.entryKey) return "";',
  '  return `<button class="entry-remove-btn" type="button" title="删除此条" aria-label="删除此条" data-entry-remove data-project-id="${escapeHtml(String(project.id))}" data-entry-kind="${kind}" data-entry-key="${escapeHtml(String(entry.entryKey))}"><i class="fas fa-trash"></i></button>`;',
  '}',
  'function renderCharacterArtworkContent(rawContent) {',
  '  const text = String(rawContent || "无内容");',
  '  const startMarker = "<%# char-info-ejs-builder:start:v2 %>";',
  '  const endMarker = "<%# char-info-ejs-builder:end:v2 %>";',
  '  let cursor = 0;',
  '  let html = "";',
  '  while (cursor < text.length) {',
  '    const start = text.indexOf(startMarker, cursor);',
  '    if (start < 0) {',
  '      html += escapeHtml(text.slice(cursor));',
  '      break;',
  '    }',
  '    const end = text.indexOf(endMarker, start + startMarker.length);',
  '    if (end < 0) {',
  '      html += escapeHtml(text.slice(cursor));',
  '      break;',
  '    }',
  '    html += escapeHtml(text.slice(cursor, start));',
  '    const blockEnd = end + endMarker.length;',
  '    const block = text.slice(start, blockEnd);',
  '    html += `<details class="character-artwork-block"><summary>👍🏻 角色立绘模板 · 点击展开</summary><pre>${escapeHtml(block)}</pre></details>`;',
  '    cursor = blockEnd;',
  '  }',
  '  return html || escapeHtml(text);',
  '}',
  'function summarizeContentInspection(entries, regexEntries) {',
  '  const allEntries = [...(Array.isArray(entries) ? entries : []), ...(Array.isArray(regexEntries) ? regexEntries : [])];',
  '  return {',
  '    hasEjs: allEntries.some(entry => Boolean(entry?.hasEjs)),',
  '    hasCharacterArtwork: allEntries.some(entry => Boolean(entry?.hasCharacterArtwork)),',
  '    hasIncompleteArtworkMarker: allEntries.some(entry => Array.isArray(entry?.inspectionWarnings) && entry.inspectionWarnings.includes("character_artwork_marker_incomplete")),',
  '  };',
  '}',
  'function getExternalLinkSourceTitle(entry, kind) {',
  '  if (kind === "worldbook") return String(entry?.comment || entry?.name || entry?.uid || "未命名世界书");',
  '  return String(entry?.scriptName || entry?.script_name || entry?.name || entry?.id || "未命名正则");',
  '}',
  'function collectProjectExternalLinks(entries, regexEntries) {',
  '  const byUrl = new Map();',
  '  const addEntries = (list, kind) => {',
  '    (Array.isArray(list) ? list : []).forEach(entry => {',
  '      const source = `${kind === "worldbook" ? "世界书" : "正则"} · ${getExternalLinkSourceTitle(entry, kind)}`;',
  '      (Array.isArray(entry?.externalLinks) ? entry.externalLinks : []).forEach(link => {',
  '        const url = String(link?.url || "").trim();',
  '        const hostname = String(link?.hostname || "").trim().toLowerCase();',
  '        if (!url || !hostname) return;',
  '        let item = byUrl.get(url);',
  '        if (!item) { item = { url, hostname, sources: [] }; byUrl.set(url, item); }',
  '        if (!item.sources.includes(source)) item.sources.push(source);',
  '      });',
  '    });',
  '  };',
  '  addEntries(entries, "worldbook");',
  '  addEntries(regexEntries, "regex");',
  '  const byHostname = new Map();',
  '  Array.from(byUrl.values()).forEach(item => {',
  '    let group = byHostname.get(item.hostname);',
  '    if (!group) { group = { hostname: item.hostname, links: [] }; byHostname.set(item.hostname, group); }',
  '    group.links.push(item);',
  '  });',
  '  return Array.from(byHostname.values())',
  '    .map(group => ({ ...group, links: group.links.sort((a, b) => a.url.localeCompare(b.url)) }))',
  '    .sort((a, b) => a.hostname.localeCompare(b.hostname));',
  '}',
  'function renderExternalLinksPanel(entries, regexEntries, options) {',
  '  const groups = collectProjectExternalLinks(entries, regexEntries);',
  '  const total = groups.reduce((count, group) => count + group.links.length, 0);',
  '  if (!total) return "";',
  '  const title = options?.title || "外链信息";',
  '  const notice = options?.notice || "仅列出内容中检测到的网址；未访问、未验证远端内容。";',
  '  const groupsHtml = groups.map(group => {',
  '    const linksHtml = group.links.map(item => `<div class="external-link-item"><code>${escapeHtml(item.url)}</code><div class="external-link-sources">${item.sources.map(source => `<span>${escapeHtml(source)}</span>`).join("")}</div></div>`).join("");',
  '    return `<details class="external-link-domain"><summary><span><i class="fas fa-globe"></i> ${escapeHtml(group.hostname)}</span><span>${group.links.length} 条</span></summary><div class="external-link-list">${linksHtml}</div></details>`;',
  '  }).join("");',
  '  return `<details class="detail-section detail-disclosure external-links-section"><summary class="detail-section-title"><span><i class="fas fa-link"></i> ${escapeHtml(title)}</span><span>${total} 条 · ${groups.length} 个域名</span></summary><div class="detail-disclosure-body"><div class="external-links-note"><i class="fas fa-circle-info"></i> ${escapeHtml(notice)}</div><div class="external-link-groups">${groupsHtml}</div></div></details>`;',
  '}',
  'function renderRegexEntry(entry, context) {',
  '  const title = entry.scriptName || entry.name || entry.id || "未命名正则";',
  '  const replaceText = entry.replaceString || entry.replace_string || "无替换文本";',
  '  const removeButton = renderEntryRemoveButton(context?.project, "regex", entry, context?.allowRemove);',
  '  return `<div class="entry-item"><div class="entry-header" data-entry-toggle><i class="fas fa-chevron-right"></i><span class="strategy-badge strategy-selective">R</span><span class="entry-title">${escapeHtml(title)}</span>${removeButton}</div><div class="entry-content"><div class="detail-entry-meta"><div class="detail-keywords-block"><div class="detail-keywords-title">匹配表达式</div><div class="detail-keyword-list"><span class="keyword-chip">${escapeHtml(entry.findRegex || entry.find_regex || "无")}</span></div></div><div class="detail-entry-content">${escapeHtml(replaceText)}</div></div></div></div>`;',
  '}',
  'function renderDetailSection(title, icon, entries, renderer, emptyText, project, allowRemove) {',
  '  const context = { project, allowRemove: Boolean(allowRemove) };',
  '  const itemsHtml = entries.length ? entries.map(entry => renderer(entry, context)).join("") : `<div class="empty-state">${emptyText}</div>`;',
  '  return `<div class="detail-section"><div class="detail-section-title"><span><i class="fas ${icon}"></i> ${title}</span><span>${entries.length} 条</span></div><div class="detail-entry-list">${itemsHtml}</div></div>`;',
  '}',
  'function getWorldbookPositionLabel(entry) {',
  '  const type = String(entry?.positionType || "");',
  '  const labels = { before_character_definition: "角色定义前", after_character_definition: "角色定义后", before_example_messages: "示例消息前", after_example_messages: "示例消息后", before_author_note: "作者注释前", after_author_note: "作者注释后" };',
  '  if (type === "at_depth") return `D${Number.isFinite(Number(entry?.depth)) ? Number(entry.depth) : 4}`;',
  '  if (type === "outlet") return entry?.outletName ? `出口 · ${String(entry.outletName)}` : "出口";',
  '  if (labels[type]) return labels[type];',
  '  if (type.startsWith("unknown:")) return `未知位置 ${type.slice(8)}`;',
  '  return type || "角色定义前";',
  '}',
  'function renderWorldbookEntryBehaviorMeta(entry) {',
  '  const type = String(entry?.positionType || "");',
  '  const order = Number.isFinite(Number(entry?.order)) ? Number(entry.order) : 0;',
  '  const role = ["system", "user", "assistant"].includes(String(entry?.role)) ? String(entry.role) : "system";',
  '  const items = [`<span><i class="fas fa-location-dot"></i> ${escapeHtml(getWorldbookPositionLabel(entry))}</span>`, `<span>顺序 ${order}</span>`];',
  '  if (type === "at_depth") items.push(`<span>${escapeHtml(role)}</span>`);',
  '  return `<div class="entry-behavior-meta">${items.join("")}</div>`;',
  '}',
  'function renderDetailEntry(entry, context) {',
  '  const strategy = getEntryStrategy(entry);',
  '  const keywords = normalizeEntryKeywords(entry);',
  '  const secondaryKeywords = normalizeEntrySecondaryKeywords(entry);',
  '  const keywordsHtml = keywords.length ? keywords.map(keyword => `<span class="keyword-chip">${escapeHtml(keyword)}</span>`).join("") : `<span class="keyword-chip">无</span>`;',
  '  const secondaryKeywordsHtml = secondaryKeywords.length ? secondaryKeywords.map(keyword => `<span class="keyword-chip">${escapeHtml(keyword)}</span>`).join("") : `<span class="keyword-chip">无</span>`;',
  '  const removeButton = renderEntryRemoveButton(context?.project, "worldbook", entry, context?.allowRemove);',
  '  return `<div class="entry-item"><div class="entry-header" data-entry-toggle><i class="fas fa-chevron-right"></i><span class="strategy-badge ${strategy.className}">${strategy.symbol}</span><span class="entry-title">${escapeHtml(entry.comment || "无标题")}</span>${removeButton}</div><div class="entry-content"><div class="detail-entry-meta">${renderWorldbookEntryBehaviorMeta(entry)}<div class="detail-keywords-block"><div><div class="detail-keywords-title">主要关键词</div><div class="detail-keyword-list">${keywordsHtml}</div></div><div><div class="detail-keywords-title">次要关键词</div><div class="detail-keyword-list">${secondaryKeywordsHtml}</div></div></div><div class="detail-entry-content">${renderCharacterArtworkContent(entry.content || "无内容")}</div></div></div></div>`;',
  '}',
  'function renderWorldbookWorkspace(entries) {',
  '  if (!entries.length) return "";',
  '  const navHtml = entries.map((entry, index) => {',
  '    const strategy = getEntryStrategy(entry);',
  '    return `<button class="detail-entry-nav-item${index === 0 ? " active" : ""}" type="button" data-detail-entry-nav="${index}" aria-selected="${index === 0 ? "true" : "false"}"><span class="strategy-badge ${strategy.className}">${strategy.symbol}</span><span class="detail-entry-nav-copy"><strong>${escapeHtml(entry.comment || "无标题")}</strong><small>${escapeHtml(getWorldbookPositionLabel(entry))}</small></span></button>`;',
  '  }).join("");',
  '  const panelsHtml = entries.map((entry, index) => {',
  '    const strategy = getEntryStrategy(entry);',
  '    const keywords = normalizeEntryKeywords(entry);',
  '    const secondaryKeywords = normalizeEntrySecondaryKeywords(entry);',
  '    const keywordsHtml = keywords.length ? keywords.map(keyword => `<span class="keyword-chip">${escapeHtml(keyword)}</span>`).join("") : `<span class="keyword-chip">无</span>`;',
  '    const secondaryKeywordsHtml = secondaryKeywords.length ? secondaryKeywords.map(keyword => `<span class="keyword-chip">${escapeHtml(keyword)}</span>`).join("") : `<span class="keyword-chip">无</span>`;',
  '    return `<article class="detail-entry-panel${index === 0 ? " active" : ""}" data-detail-entry-panel="${index}"><div class="detail-entry-panel-heading"><span class="strategy-badge ${strategy.className}">${strategy.symbol}</span><h3>${escapeHtml(entry.comment || "无标题")}</h3></div><div class="detail-entry-info">${renderWorldbookEntryBehaviorMeta(entry)}<div class="detail-keywords-inline"><div class="detail-keywords-group"><span class="detail-keywords-title">主要关键词</span><div class="detail-keyword-list">${keywordsHtml}</div></div><div class="detail-keywords-group"><span class="detail-keywords-title">次要关键词</span><div class="detail-keyword-list">${secondaryKeywordsHtml}</div></div></div></div><div class="detail-entry-content">${renderCharacterArtworkContent(entry.content || "无内容")}</div></article>`;',
  '  }).join("");',
  '  return `<div class="detail-section detail-entry-workspace-section"><div class="detail-section-title"><span><i class="fas fa-scroll"></i> 世界书内容</span><span>${entries.length} 条</span></div><div class="detail-entry-workspace"><nav class="detail-entry-nav" aria-label="世界书条目">${navHtml}</nav><div class="detail-entry-pane">${panelsHtml}</div></div></div>`;',
  '}',
  'function renderProjectDetail(project, entries, regexEntries) {',
  '  const authorName = getAuthorName(project);',
  '  const authorAvatar = getAuthorAvatar(project);',
  '  const coverSources = getCoverImageSources(project);',
  '  const baseTag = getProjectTypeDisplayLabel(project);',
  '  const publishedDate = formatDate(getProjectPublishedAt(project));',
  '  const resolvedRegexEntries = Array.isArray(regexEntries) ? regexEntries : [];',
  '  const inspection = summarizeContentInspection(entries, resolvedRegexEntries);',
  '  const creatorTagsHtml = getProjectDetailTags(project).map(tag => `<span class="tag">${escapeHtml(tag)}</span>`).join("");',
  '  const signalPolicy = PROJECT_TAXONOMY.systemSignals || {};',
  '  const inspectionTagsHtml = `${inspection.hasEjs && signalPolicy.ejs?.detail !== false ? `<span class="tag tag-system-ejs" title="系统自动检测">${escapeHtml(signalPolicy.ejs?.label || "EJS")}</span>` : ""}${inspection.hasCharacterArtwork && signalPolicy.characterArtwork?.detail !== false ? `<span class="tag tag-system-artwork" title="系统自动检测">${escapeHtml(signalPolicy.characterArtwork?.label || "👍🏻有角色立绘")}</span>` : ""}`;',
  '  const tagsHtml = inspectionTagsHtml + creatorTagsHtml;',
  '  const tagsBlock = tagsHtml ? `<div class="project-tags detail-tags-row" aria-label="项目标签">${tagsHtml}</div>` : "";',
  '  const inspectionWarningHtml = inspection.hasIncompleteArtworkMarker ? `<div class="detail-warning"><i class="fas fa-triangle-exclamation"></i><span>角色立绘模板标记不完整，已保留原文显示。</span></div>` : "";',
  '  const view = buildProjectCardViewModel(project);',
  '  const installButtonClass = `${view.installDisabled ? "btn btn-primary detail-install-btn is-disabled" : "btn btn-primary detail-install-btn"}${view.installPending ? " is-loading" : ""}`;',
  '  const updateButton = view.canUpdate ? `<button class="btn btn-outline detail-update-btn update-btn" data-id="${project.id}"><i class="fas fa-arrows-rotate"></i> 更新</button>` : "";',
  '  const installBadge = view.isInstalled ? `<span class="install-badge ${view.canUpdate ? "install-badge--update" : ""}"><i class="fas fa-check-circle"></i> 已安装</span>` : "";',
  '  const likeHint = !state.currentUser ? "登录后可点赞" : (view.likes.liked ? "取消点赞" : "点赞项目");',
  '  const detailStats = `<div class="detail-stats-row"><button class="detail-stat detail-like-btn ${view.likes.liked ? "liked" : ""}" type="button" data-id="${project.id}" title="${likeHint}" aria-pressed="${view.likes.liked ? "true" : "false"}" ${!state.currentUser ? "disabled" : ""}><i class="fas fa-heart"></i><strong>${view.likes.count}</strong><span>喜欢</span></button><div class="detail-stat"><i class="fas fa-download"></i><strong>${view.downloadsCount}</strong><span>下载</span></div></div>`;',
  '  const summaryActions = `<div class="detail-actions-panel">${installBadge}<div class="detail-action-buttons"><button class="${installButtonClass}" data-id="${project.id}" ${view.installDisabled ? "disabled" : ""}><i class="fas ${view.installPending ? "fa-spinner" : view.isInstalled ? "fa-trash" : "fa-download"}"></i> ${view.installText}</button>${updateButton}</div></div>`;',
  '  const detailFacts = `<div class="detail-facts">${view.versionHtml ? `<div class="detail-fact"><i class="fas fa-code-branch"></i><span>版本</span><strong>${view.versionHtml}</strong></div>` : ""}<div class="detail-fact"><i class="fas fa-calendar-alt"></i><span>发布</span><strong>${escapeHtml(publishedDate)}</strong></div><div class="detail-fact"><i class="fas fa-book-open"></i><span>世界书</span><strong>${entries.length} 条</strong></div><div class="detail-fact"><i class="fas fa-code"></i><span>正则</span><strong>${resolvedRegexEntries.length} 条</strong></div></div>`;',
  '  const worldbookSection = renderWorldbookWorkspace(entries);',
  '  const regexSection = resolvedRegexEntries.length ? renderDetailSection("正则脚本", "fa-code", resolvedRegexEntries, renderRegexEntry, "") : "";',
  '  const externalLinksSection = renderExternalLinksPanel(entries, resolvedRegexEntries);',
  '  const heroHtml = `<div class="detail-hero"><div class="detail-cover" data-cover-src="${escapeHtml(coverSources.primary)}" data-cover-fallback-src="${escapeHtml(coverSources.fallback)}" data-cover-placeholder-src="${escapeHtml(coverSources.placeholder)}" data-cover-auth-src="${escapeHtml(coverSources.authenticated || "")}" style="background-image: url(\'${escapeHtml(coverSources.primary)}\');"></div><div class="detail-primary"><div class="detail-project-name">${escapeHtml(project.name)}</div><div class="detail-identity-row"><div class="detail-author"><span class="detail-author-avatar" aria-hidden="true" style="background-image:url(\'${escapeHtml(authorAvatar)}\'),url(\'https://cdn.discordapp.com/embed/avatars/0.png\');"></span><span>${escapeHtml(authorName)}</span></div><span class="detail-identity-separator">·</span><span class="detail-type-label">${escapeHtml(baseTag)}</span></div>${summaryActions}${tagsBlock}${detailStats}${detailFacts}</div></div>`;',
  '  const overviewHtml = `<section class="detail-overview"><div class="detail-block-title"><span>简介</span></div><div class="detail-description">${escapeHtml(project.description || "这个项目暂时没有提供简介。")}</div></section>`;',
  '  return `<div class="detail-panel detail-panel-scroll">${heroHtml}${inspectionWarningHtml}${overviewHtml}${worldbookSection}${regexSection}${externalLinksSection}</div>`;',
  '}',
].join('\n');
