export const homeDetailModalRenderScript = [
  'function formatEntryPosition(entry) {',
  '  const type = entry?.positionType;',
  '  const numeric = Number.isInteger(entry?.position) ? entry.position : null;',
  '  const depth = Number.isFinite(entry?.depth) ? entry.depth : 4;',
  '  const roleMap = { 0: "system", 1: "user", 2: "assistant", system: "system", user: "user", assistant: "assistant" };',
  '  const role = roleMap[entry?.role] || "system";',
  '  if (type === "before_character_definition" || type === "before_char" || numeric === 0) return "角色定义前";',
  '  if (type === "after_character_definition" || type === "after_char" || numeric === 1) return "角色定义后";',
  '  if (type === "before_author_note" || numeric === 2) return "作者注释前";',
  '  if (type === "after_author_note" || numeric === 3) return "作者注释后";',
  '  if (type === "at_depth" || numeric === 4) return `@D ${depth} · ${role}`;',
  '  if (type === "before_example_messages" || numeric === 5) return "示例消息前";',
  '  if (type === "after_example_messages" || numeric === 6) return "示例消息后";',
  '  if (type === "outlet" || numeric === 7) return `Outlet${entry?.outletName ? ` · ${entry.outletName}` : ""}`;',
  '  return type ? `未知位置: ${type}` : (numeric !== null ? `未知位置: ${numeric}` : "未指定位置");',
  '}',
  'function renderEntryFacts(entry) {',
  '  const strategy = getEntryStrategy(entry);',
  '  const order = Number.isFinite(entry?.order) ? entry.order : "-";',
  '  return `<div class="detail-entry-facts"><span><i class="fas fa-location-dot"></i> ${escapeHtml(formatEntryPosition(entry))}</span><span><i class="fas fa-arrow-down-wide-short"></i> Order ${escapeHtml(order)}</span><span>${strategy.symbol} ${escapeHtml(strategy.label)}</span></div>`;',
  '}',
  'function renderEntryControls(project, entry, kind, canManage, allowSelection) {',
  '  const entryKey = entry?.entryKey || "";',
  '  const select = allowSelection && entryKey ? `<label class="entry-install-toggle" title="本次安装此条"><input type="checkbox" data-install-kind="${kind}" data-entry-key="${escapeHtml(entryKey)}" checked><span>安装</span></label>` : "";',
  '  const remove = canManage && entryKey ? `<button type="button" class="entry-remove-btn" data-entry-remove data-project-id="${escapeHtml(project.id)}" data-entry-kind="${kind}" data-entry-key="${escapeHtml(entryKey)}" title="从项目中移除此条"><i class="fas fa-trash"></i></button>` : "";',
  '  return `<div class="entry-inline-actions">${select}${remove}</div>`;',
  '}',
  'function renderRegexEntry(entry, index, project, canManage, allowSelection) {',
  '  const title = entry.scriptName || entry.name || entry.id || "未命名正则";',
  '  const replaceText = entry.replaceString || entry.replace_string || "无替换文本";',
  '  const controls = renderEntryControls(project, entry, "regex", canManage, allowSelection);',
  '  const depthText = Number.isFinite(entry.minDepth) || Number.isFinite(entry.maxDepth) ? `<div class="detail-entry-facts"><span>深度 ${escapeHtml(entry.minDepth ?? "-")} ~ ${escapeHtml(entry.maxDepth ?? "-")}</span></div>` : "";',
  '  return `<div class="entry-item"><div class="entry-header" data-entry-toggle><i class="fas fa-chevron-right"></i><span class="strategy-badge strategy-selective">R</span><span class="entry-header-title">${escapeHtml(title)}</span>${controls}</div><div class="entry-content">${depthText}<div class="detail-entry-meta"><div class="detail-keywords-block"><div class="detail-keywords-title">匹配表达式</div><div class="detail-keyword-list"><span class="keyword-chip">${escapeHtml(entry.findRegex || entry.find_regex || "无")}</span></div></div><div class="detail-entry-content">${escapeHtml(replaceText)}</div></div></div></div>`;',
  '}',
  'function renderDetailSection(title, icon, entries, renderer, emptyText, project, canManage, allowSelection) {',
  '  const itemsHtml = entries.length ? entries.map((entry, index) => renderer(entry, index, project, canManage, allowSelection)).join("") : `<div class="empty-state">${emptyText}</div>`;',
  '  return `<div class="detail-section"><div class="detail-section-title"><span><i class="fas ${icon}"></i> ${title}</span><span>${entries.length} 条</span></div><div class="detail-entry-list">${itemsHtml}</div></div>`;',
  '}',
  'function renderDetailEntry(entry, index, project, canManage, allowSelection) {',
  '  const strategy = getEntryStrategy(entry);',
  '  const keywords = normalizeEntryKeywords(entry);',
  '  const secondaryKeywords = normalizeEntrySecondaryKeywords(entry);',
  '  const keywordsHtml = keywords.length ? keywords.map(keyword => `<span class="keyword-chip">${escapeHtml(keyword)}</span>`).join("") : `<span class="keyword-chip">无</span>`;',
  '  const secondaryKeywordsHtml = secondaryKeywords.length ? secondaryKeywords.map(keyword => `<span class="keyword-chip">${escapeHtml(keyword)}</span>`).join("") : `<span class="keyword-chip">无</span>`;',
  '  const controls = renderEntryControls(project, entry, "worldbook", canManage, allowSelection);',
  '  return `<div class="entry-item"><div class="entry-header" data-entry-toggle><i class="fas fa-chevron-right"></i><span class="strategy-badge ${strategy.className}">${strategy.symbol}</span><span class="entry-header-title">${escapeHtml(entry.comment || "无标题")}</span>${controls}</div><div class="entry-content">${renderEntryFacts(entry)}<div class="detail-entry-meta"><div class="detail-keywords-block"><div><div class="detail-keywords-title">主要关键词</div><div class="detail-keyword-list">${keywordsHtml}</div></div><div><div class="detail-keywords-title">次要关键词</div><div class="detail-keyword-list">${secondaryKeywordsHtml}</div></div></div><div class="detail-entry-content">${escapeHtml(entry.content || "无内容")}</div></div></div></div>`;',
  '}',
  'function renderProjectDetail(project, entries, regexEntries) {',
  '  const authorName = getAuthorName(project);',
  '  const authorAvatar = getAuthorAvatar(project);',
  '  const coverSources = getCoverImageSources(project);',
  '  const baseTag = getBaseTag(project);',
  '  const updatedDate = formatDate(project.updatedAt);',
  '  const tagsHtml = (project.tags || []).map(tag => `<span class="tag">${escapeHtml(tag)}</span>`).join("");',
  '  const view = buildProjectCardViewModel(project);',
  '  const canManage = Boolean(state.currentUser && (state.currentUser.isAdmin || state.currentUser.id === project.authorId));',
  '  const allowSelection = !view.isInstalled;',
  '  const installButtonClass = `${view.installDisabled ? "btn btn-primary detail-install-btn is-disabled" : "btn btn-primary detail-install-btn"}${view.installPending ? " is-loading" : ""}`;',
  '  const updateButton = view.canUpdate ? `<button class="btn btn-outline detail-update-btn update-btn" data-id="${project.id}"><i class="fas fa-arrows-rotate"></i> 更新</button>` : "";',
  '  const installBadge = view.isInstalled ? `<span class="install-badge ${view.canUpdate ? "install-badge--update" : ""}"><i class="fas fa-check-circle"></i> 已安装</span>` : "";',
  '  const summaryActions = `<div class="detail-actions-panel">${installBadge}<button class="${installButtonClass}" data-id="${project.id}" ${view.installDisabled ? "disabled" : ""}><i class="fas ${view.installPending ? "fa-spinner" : view.isInstalled ? "fa-trash" : "fa-download"}"></i> ${view.installText}</button>${updateButton}</div>`;',
  '  const worldbookSection = renderDetailSection("世界书条目", "fa-scroll", entries, renderDetailEntry, "无条目内容", project, canManage, allowSelection);',
  '  const regexSection = renderDetailSection("正则列表", "fa-code", regexEntries || [], renderRegexEntry, "无正则内容", project, canManage, allowSelection);',
  '  const revisionBadge = project.reviewTarget === "draft" ? `<span class="detail-meta-item"><i class="fas fa-code-commit"></i> Draft rev ${escapeHtml(project.draftRevision || 1)}</span>` : "";',
  '  return `<div class="detail-panel detail-panel-scroll"><div class="detail-cover" data-cover-src="${escapeHtml(coverSources.primary)}" data-cover-fallback-src="${escapeHtml(coverSources.fallback)}" data-cover-placeholder-src="${escapeHtml(coverSources.placeholder)}" style="background-image: url(\'${escapeHtml(coverSources.primary)}\');"></div><div class="detail-summary detail-summary--split"><div class="detail-summary-main"><div class="detail-card-row detail-card-row-title"><span class="type-badge ${getTypeClass(project)}">${escapeHtml(baseTag)}</span><div class="detail-project-name">${escapeHtml(project.name)}</div></div><div class="detail-card-row"><div class="detail-author"><img class="detail-author-avatar" src="${escapeHtml(authorAvatar)}" alt="avatar"><span>${escapeHtml(authorName)}</span></div></div><div class="project-tags detail-tags-row">${tagsHtml}</div><div class="detail-card-row detail-meta-row"><span class="detail-meta-item"><i class="fas fa-code-branch"></i> ${view.versionHtml}</span><span class="detail-meta-item"><i class="fas fa-calendar-alt"></i> ${escapeHtml(updatedDate)}</span><span class="detail-meta-item"><i class="fas fa-book-open"></i> ${entries.length} 条世界书条目</span><span class="detail-meta-item"><i class="fas fa-code"></i> ${(regexEntries || []).length} 条正则</span>${revisionBadge}</div><div class="detail-description">${escapeHtml(project.description || "无简介")}</div></div>${summaryActions}</div>${worldbookSection}${regexSection}</div>`;',
  '}',
].join('\n');
