export const homeLayoutRenderScript = [
  'const WORKSHOP_RELEASE_VERSION = "2.1.1";',
  'function isDesktopWorkshopLayout() {',
  '  return typeof window !== "undefined" && typeof window.matchMedia === "function" && window.matchMedia("(min-width: 1024px)").matches;',
  '}',
  'let workshopDesktopLayoutMatch = isDesktopWorkshopLayout();',
  'window.addEventListener("resize", () => {',
  '  const nextDesktopLayoutMatch = isDesktopWorkshopLayout();',
  '  if (nextDesktopLayoutMatch === workshopDesktopLayoutMatch) return;',
  '  workshopDesktopLayoutMatch = nextDesktopLayoutMatch;',
  '  renderApp();',
  '});',
  'function renderScriptDependencyHealthNotice() {',
  '  if (!state.tavern.scriptDependenciesLoaded || !state.tavern.scriptDependenciesSupported) return "";',
  '  const health = getScriptDependencyHealthSummary();',
  '  if (!health.outdated.length) return "";',
  '  return `<button class="btn btn-outline script-dependency-health-btn" type="button" title="${health.outdated.length} 个其他脚本有更新" aria-label="其他脚本有更新"><i class="fas fa-circle-up"></i><span>其他脚本有更新</span></button>`;',
  '}',
  'function renderSortControl() {',
  '  if (state.showOnlyMyProjects || state.showSubscribedAndInstalledProjects) return "";',
  '  const options = [',
  '    { value: "published", label: "最新" },',
  '    { value: "rating", label: "玩家好评" },',
  '    { value: "downloads", label: "下载最多" },',
  '  ];',
  '  const current = options.find(option => option.value === state.sortMode);',
  '  const currentLabel = current?.label || "排序";',
  '  const optionHtml = options.map(option => `<button class="user-menu-item sort-menu-item ${state.sortMode === option.value ? "active" : ""}" type="button" data-sort-value="${option.value}"><i class="fas ${state.sortMode === option.value ? "fa-circle-check" : "fa-arrow-right"}"></i> ${option.label}</button>`).join("");',
  '  return `<div class="user-menu sort-menu ${state.sortMenuOpen ? "open" : ""}" id="sortMenu"><button class="user-menu-trigger sort-menu-trigger" id="sortMenuTrigger"><i class="fas fa-arrow-down-wide-short"></i><span class="user-menu-name">${escapeHtml(currentLabel)}</span><i class="fas fa-chevron-down"></i></button><div class="user-menu-dropdown">${optionHtml}</div></div>`;',
  '}',
  'function renderFontControl() {',
  '  const current = getContentFontOption(state.contentFont);',
  '  const optionHtml = CONTENT_FONT_OPTIONS.map(option => `<button class=\"user-menu-item font-menu-item ${state.contentFont === option.value ? "active" : ""}\" type=\"button\" data-font-value=\"${option.value}\"><i class=\"fas ${state.contentFont === option.value ? "fa-circle-check" : "fa-font"}\"></i><span>${escapeHtml(option.label)}</span></button>`).join("");',
  '  return `<div class=\"user-menu font-menu ${state.fontMenuOpen ? "open" : ""}\" id=\"fontMenu\"><button class=\"user-menu-trigger font-menu-trigger\" id=\"fontMenuTrigger\" type=\"button\" title=\"切换内容字体\"><i class=\"fas fa-font\"></i><span class=\"user-menu-name\">${escapeHtml(current.label)}</span><i class=\"fas fa-chevron-down\"></i></button><div class=\"user-menu-dropdown\">${optionHtml}</div></div>`;',
  '}',
  'function renderTavernStatus() {',
  '  const status = state.tavern.status || "disconnected";',
  '  const meta = {',
  '    disconnected: { label: "未连接 SillyTavern", icon: "fa-plug-circle-xmark" },',
  '    connecting: { label: "正在连接 SillyTavern", icon: "fa-spinner fa-spin" },',
  '    connected: { label: "已连接 SillyTavern", icon: "fa-plug-circle-check" },',
  '    error: { label: "SillyTavern 连接异常", icon: "fa-triangle-exclamation" },',
  '  }[status] || { label: "未连接 SillyTavern", icon: "fa-plug-circle-xmark" };',
  '  return `<div class="tavern-status tavern-status--${status}" title="${meta.label}"><i class="fas ${meta.icon}"></i><span>${meta.label}</span></div>`;',
  '}',
  'function renderTagFilter() {',
  '  if (state.showOnlyMyProjects) return `<nav class="sidebar-nav sidebar-view-actions" aria-label="我的项目导航"><button type="button" class="sidebar-nav-btn sidebar-back-shortcut" data-return-all-projects><i class="fas fa-arrow-left"></i><span>全部项目</span></button></nav>`;',
  '  if (state.showSubscribedAndInstalledProjects) return `<div class="sidebar-view-state"><i class="fas fa-bookmark"></i><span><small>当前视图</small><strong>订阅 / 已安装</strong></span></div>`;',
  '  const options = [{ value: "all", label: "全部项目", typeClass: "all", icon: "fa-border-all" }, ...BASE_TAG_META.map(option => ({ ...option, icon: { system: "fa-microchip", extension: "fa-puzzle-piece", character: "fa-user-group", event: "fa-calendar-days" }[option.typeClass] || "fa-folder" }))];',
  '  const pendingAttr = state.filterRequestPending ? "disabled" : "";',
  '  const pendingClass = state.filterRequestPending ? "is-disabled" : "";',
  '  const discoverHtml = `<button class="sidebar-nav-btn sidebar-discover-btn ${state.viewMode === "discover" ? "active" : ""} ${pendingClass}" type="button" data-workshop-view="discover" ${pendingAttr}><i class="fas fa-sparkles"></i><span>发现</span></button><div class="sidebar-nav-divider"></div>`;',
  '  const optionHtml = options.map(option => `<button class="tag-filter-btn sidebar-nav-btn ${state.viewMode === "catalog" && state.activeBaseTag === option.value ? "active" : ""} ${option.typeClass} ${pendingClass}" type="button" data-base-tag="${option.value}" ${pendingAttr}><i class="fas ${option.icon}"></i><span>${escapeHtml(option.label)}</span></button>`).join("");',
  '  return `<nav class="tag-filter sidebar-nav" id="baseTagFilter" aria-label="作品分类">${discoverHtml}${optionHtml}</nav>`;',
  '}',
  'function getProjectTagFilterGroups() {',
  '  const groups = [];',
  '  if (state.activeBaseTag === "all" || state.activeBaseTag === "扩展") {',
  '    const extensionTypes = Array.from(new Set((PROJECT_TAXONOMY.extensionTypes || []).map(value => String(value).trim()).filter(Boolean)));',
  '    if (extensionTypes.length) groups.push({ label: "扩展方向", tags: extensionTypes });',
  '  }',
  '  if (state.activeBaseTag === "all" || state.activeBaseTag === "角色") {',
  '    Object.entries(PROJECT_TAXONOMY.characterFacets || {}).forEach(([label, values]) => {',
  '      const tags = Array.from(new Set((values || []).map(value => String(value).trim()).filter(Boolean)));',
  '      if (tags.length) groups.push({ label, tags });',
  '    });',
  '  }',
  '  return groups;',
  '}',
  'function renderSearchTagSuggestions() {',
  '  if (state.showOnlyMyProjects || state.showSubscribedAndInstalledProjects) return `<div class="search-tag-empty-state">当前视图不使用官方标签筛选。</div>`;',
  '  const selectedTags = getActivePublicTags();',
  '  const groupsHtml = getProjectTagFilterGroups().map(group => {',
  '    const tagsHtml = group.tags.map(tag => { const active = selectedTags.includes(tag); return `<button type="button" class="search-tag-chip ${active ? "active" : ""}" data-search-tag="${escapeHtml(tag)}" aria-pressed="${active ? "true" : "false"}">${escapeHtml(tag)}${active ? `<i class="fas fa-check"></i>` : ""}</button>`; }).join("");',
  '    return `<section class="search-tag-group" data-search-tag-group><div class="search-tag-group-title">${escapeHtml(group.label)}</div><div class="search-tag-chip-row">${tagsHtml}</div></section>`;',
  '  }).join("");',
  '  return `<div class="search-tag-groups">${groupsHtml || `<div class="search-tag-empty-state">这个分类没有官方标签</div>`}</div><div class="search-tag-empty" hidden>没有匹配的官方标签，按 Enter 可直接搜索项目 / 作者。</div>`;',
  '}',
  'function renderActiveSearchTags() {',
  '  const tags = getActivePublicTags();',
  '  if (!tags.length) return "";',
  '  return `<div class="search-active-tags"><div class="search-active-tags-head"><span>已选官方标签</span><button type="button" data-clear-all-search-tags>清除全部</button></div><div class="search-active-tag-row">${tags.map(tag => `<button type="button" class="search-active-tag" data-remove-search-tag="${escapeHtml(tag)}">${escapeHtml(tag)}<i class="fas fa-xmark"></i></button>`).join("")}</div></div>`;',
  '}',
  'function renderUnifiedSearch(mode) {',
  '  const mobile = mode === "mobile";',
  '  const inputId = mobile ? "projectSearchInputMobile" : "projectSearchInput";',
  '  const draft = String(state.searchDraft ?? state.searchKeyword ?? "");',
  '  const committed = String(state.searchKeyword || "").trim();',
  '  return `<div class="unified-search unified-search--${mode}" data-unified-search="${mode}"><div class="unified-search-box"><i class="fas fa-search"></i><input id="${inputId}" type="search" autocomplete="off" placeholder="搜索项目、作者或官方标签" value="${escapeHtml(draft)}">${committed ? `<button type="button" class="unified-search-clear" data-clear-text-search title="清除文字搜索"><i class="fas fa-xmark"></i></button>` : ""}</div><div class="search-assist"><div class="search-assist-head"><span>官方标签</span><small>点标签加入条件 · Enter 搜索文字</small></div>${renderActiveSearchTags()}${renderSearchTagSuggestions()}</div></div>`;',
  '}',
  'function getMobileCurrentPageLabel() {',
  '  if (state.showOnlyMyProjects) return "我的项目";',
  '  if (state.showSubscribedAndInstalledProjects) return "订阅 / 已安装";',
  '  if (state.viewMode === "discover") return "发现";',
  '  const options = [{ value: "all", label: "全部" }, ...BASE_TAG_META];',
  '  return (options.find(option => option.value === state.activeBaseTag) || options[0]).label;',
  '}',
  'function getMobileCurrentSortLabel() {',
  '  const labels = { published: "最新", rating: "玩家好评", downloads: "下载最多" };',
  '  return labels[state.sortMode] || "最新";',
  '}',
  'function renderMobileBreadcrumb() {',
  '  const specialView = state.showOnlyMyProjects || state.showSubscribedAndInstalledProjects;',
  '  const homeCrumb = specialView ? `<button type="button" class="mobile-breadcrumb-home" data-return-all-projects>工坊</button>` : `<span>工坊</span>`;',
  '  const sortCrumb = specialView || state.viewMode === "discover" ? "" : `<i class="fas fa-chevron-right"></i><strong>${escapeHtml(getMobileCurrentSortLabel())}</strong>`;',
  '  return `<div class="mobile-breadcrumb" aria-label="当前位置">${homeCrumb}<i class="fas fa-chevron-right"></i><strong>${escapeHtml(getMobileCurrentPageLabel())}</strong>${sortCrumb}</div>`;',
  '}',
  'function renderMobilePageOptions() {',
  '  if (state.showOnlyMyProjects || state.showSubscribedAndInstalledProjects) return `<div class="mobile-page-list mobile-page-list--special"><button type="button" class="mobile-page-option mobile-page-return" data-return-all-projects><i class="fas fa-arrow-left"></i><span>返回全部项目</span><i class="fas fa-chevron-right"></i></button></div>`;',
  '  const iconMap = { system: "fa-microchip", extension: "fa-puzzle-piece", character: "fa-user-group", event: "fa-calendar-days" };',
  '  const options = [{ value: "all", label: "全部", typeClass: "all", icon: "fa-border-all" }, ...BASE_TAG_META.map(option => ({ ...option, icon: iconMap[option.typeClass] || "fa-folder" }))];',
  '  const pendingAttr = state.filterRequestPending ? "disabled" : "";',
  '  return `<div class="mobile-page-list" id="mobileBaseTagFilter">${options.map(option => `<button type="button" class="mobile-page-option ${state.viewMode === "catalog" && state.activeBaseTag === option.value ? "active" : ""}" data-base-tag="${option.value}" ${pendingAttr}><i class="fas ${option.icon}"></i><span>${escapeHtml(option.label)}</span>${state.viewMode === "catalog" && state.activeBaseTag === option.value ? `<i class="fas fa-check"></i>` : ""}</button>`).join("")}</div>`;',
  '}',
  'function renderSearchSummary() {',
  '  const keyword = String(state.searchKeyword || "").trim();',
  '  const tags = getActivePublicTags();',
  '  if (!keyword && !tags.length) return "";',
  '  const keywordHtml = keyword ? `<button type="button" class="search-summary-chip search-summary-query" data-clear-text-search><i class="fas fa-search"></i>${escapeHtml(keyword)}<i class="fas fa-xmark"></i></button>` : "";',
  '  const tagsHtml = tags.map(tag => `<button type="button" class="search-summary-chip" data-remove-search-tag="${escapeHtml(tag)}">${escapeHtml(tag)}<i class="fas fa-xmark"></i></button>`).join("");',
  '  return `<div class="search-query-summary"><span class="search-query-summary-label">当前条件</span>${keywordHtml}${tagsHtml}${tags.length > 1 ? `<button type="button" class="search-summary-clear" data-clear-all-search-tags>清除标签</button>` : ""}</div>`;',
  '}',
  'function renderMobileSortOptions() {',
  '  if (state.showOnlyMyProjects || state.showSubscribedAndInstalledProjects) return `<div class="mobile-tool-empty">当前视图使用固定排序。</div>`;',
  '  const options = [',
  '    { value: "published", label: "最新" },',
  '    { value: "rating", label: "玩家好评" },',
  '    { value: "downloads", label: "下载最多" },',
  '  ];',
  '  return options.map(option => `<button class="mobile-sort-option ${state.sortMode === option.value ? "active" : ""}" type="button" data-sort-value="${option.value}"><span>${option.label}</span>${state.sortMode === option.value ? `<i class="fas fa-check"></i>` : ""}</button>`).join("");',
  '}',
  'function renderMobileAccountPanel() {',
  '  const installedActive = state.showSubscribedAndInstalledProjects;',
  '  const installedHtml = `<button type="button" class="mobile-account-action ${installedActive ? "active" : ""}" id="mobileInstalledProjectsBtn"><i class="fas fa-bookmark"></i><span><strong>订阅 / 已安装</strong><small>查看订阅与本机已安装内容</small></span>${installedActive ? `<i class="fas fa-check"></i>` : `<i class="fas fa-chevron-right"></i>`}</button>`;',
  '  const repairHtml = isEmbedded ? `<button type="button" class="mobile-account-action" id="mobileDlcRepairBtn"><i class="fas fa-screwdriver-wrench"></i><span><strong>DLC 修复</strong><small>找回有问题的 DLC，并重新安装最新版</small></span><i class="fas fa-chevron-right"></i></button>` : "";',
  '  if (!state.currentUser) {',
  '    const localAdminHtml = isPrivateLocalPreviewHost() ? `<button type="button" class="mobile-account-action" id="mobileLocalAdminLoginBtn"><i class="fas fa-user-shield"></i><span><strong>本地 Admin</strong><small>仅本地预览环境</small></span><i class="fas fa-chevron-right"></i></button>` : "";',
  '    return `<div class="mobile-account-panel">${installedHtml}${repairHtml}<div class="mobile-account-divider"></div>${localAdminHtml}<button type="button" class="mobile-account-action mobile-account-primary" id="mobileLoginBtn"><i class="fab fa-discord"></i><span><strong>Discord 登录</strong><small>登录后管理项目与订阅</small></span><i class="fas fa-chevron-right"></i></button></div>`;',
  '  }',
  '  const user = state.currentUser;',
  '  const adminHtml = user.isAdmin ? `<button type="button" class="mobile-account-action" id="mobileAdminPanelBtn"><i class="fas fa-clipboard-check"></i><span><strong>审核</strong></span><i class="fas fa-chevron-right"></i></button><button type="button" class="mobile-account-action" id="mobileBannerSettingsBtn"><i class="fas fa-panorama"></i><span><strong>首页 Banner</strong></span><i class="fas fa-chevron-right"></i></button>` : "";',
  '  const superAdminHtml = user.isSuperAdmin ? `<button type="button" class="mobile-account-action" id="mobileAddAdminBtn"><i class="fas fa-user-shield"></i><span><strong>添加管理员</strong></span><i class="fas fa-chevron-right"></i></button><button type="button" class="mobile-account-action" id="mobileAdminLogsBtn"><i class="fas fa-clock-rotate-left"></i><span><strong>日志</strong></span><i class="fas fa-chevron-right"></i></button>` : "";',
  '  return `<div class="mobile-account-panel"><div class="mobile-account-profile"><img src="${escapeHtml(user.avatarUrl || "https://cdn.discordapp.com/embed/avatars/0.png")}" alt=""><span><strong>${escapeHtml(user.globalName || user.username)}</strong><small>${escapeHtml(user.username || "")}</small></span></div>${installedHtml}${repairHtml}<button type="button" class="mobile-account-action ${state.showOnlyMyProjects ? "active" : ""}" id="mobileMyProjectsBtn"><i class="fas fa-layer-group"></i><span><strong>我的项目</strong><small>上传 / 审核状态</small></span><i class="fas ${state.showOnlyMyProjects ? "fa-check" : "fa-chevron-right"}"></i></button><button type="button" class="mobile-account-action" id="mobileUploadBtn"><i class="fas fa-cloud-upload-alt"></i><span><strong>上传</strong></span><i class="fas fa-chevron-right"></i></button>${adminHtml}${superAdminHtml}<div class="mobile-account-divider"></div><button type="button" class="mobile-account-action mobile-account-danger" id="mobileLogoutBtn"><i class="fas fa-right-from-bracket"></i><span><strong>登出</strong></span></button></div>`;',
  '}',
  'function renderMobileFontOptions() {',
  '  return CONTENT_FONT_OPTIONS.map(option => `<button class="mobile-sort-option mobile-font-option ${state.contentFont === option.value ? "active" : ""}" type="button" data-font-value="${option.value}"><span>${escapeHtml(option.label)}</span>${state.contentFont === option.value ? `<i class="fas fa-check"></i>` : ""}</button>`).join("");',
  '}',
  'function renderMobileDiscoveryTools() {',
  '  const mode = String(state.mobileToolMode || "");',
  '  const title = ({ page: "浏览", search: "搜寻", sort: "排序", account: "个人" })[mode] || "浏览工具";',
  '  const isOpen = Boolean(mode);',
  '  const specialView = state.showOnlyMyProjects || state.showSubscribedAndInstalledProjects;',
  '  const homeActive = isDiscoverHomeView();',
  '  const browseActive = !mode && state.viewMode === "catalog" && !specialView;',
  '  const accountActive = mode === "account" || (!mode && specialView);',
  '  const accountIcon = state.currentUser?.avatarUrl ? `<img class="mobile-nav-avatar" src="${escapeHtml(state.currentUser.avatarUrl)}" alt="">` : `<i class="fas fa-circle-user"></i>`;',
  '  return `<div class="mobile-tool-backdrop ${isOpen ? "show" : ""}" id="mobileToolBackdrop"></div><section class="mobile-tool-sheet ${isOpen ? "show" : ""}" id="mobileToolSheet" aria-hidden="${isOpen ? "false" : "true"}" ${isOpen ? "" : "inert"}><div class="mobile-tool-sheet-head"><strong id="mobileToolTitle">${title}</strong><button type="button" id="mobileToolClose">完成</button></div><div class="mobile-tool-panel" data-mobile-panel="page" ${mode === "page" ? "" : "hidden"}>${renderMobilePageOptions()}</div><div class="mobile-tool-panel" data-mobile-panel="search" ${mode === "search" ? "" : "hidden"}>${renderUnifiedSearch("mobile")}</div><div class="mobile-tool-panel mobile-sort-list" data-mobile-panel="sort" ${mode === "sort" ? "" : "hidden"}>${renderMobileSortOptions()}</div><div class="mobile-tool-panel mobile-account-tool-panel" data-mobile-panel="account" ${mode === "account" ? "" : "hidden"}>${renderMobileAccountPanel()}</div></section><nav class="mobile-tool-dock" aria-label="主导航"><button type="button" class="${homeActive ? "active" : ""}" data-workshop-view="discover"><i class="fas fa-house"></i><span>首页</span></button><button type="button" class="${mode === "page" || browseActive ? "active" : ""}" data-mobile-tool="page"><i class="fas fa-compass"></i><span>浏览</span></button><button type="button" class="${mode === "search" ? "active" : ""}" data-mobile-tool="search"><i class="fas fa-magnifying-glass"></i><span>搜寻</span></button><button type="button" class="${mode === "sort" ? "active" : ""}" data-mobile-tool="sort"><i class="fas fa-arrow-down-wide-short"></i><span>排序</span></button><button type="button" class="${accountActive ? "active" : ""}" data-mobile-tool="account">${accountIcon}<span>个人</span></button></nav>`;',
  '}',
  'function renderDesktopSidebar() {',
  '  if (!isDesktopWorkshopLayout()) return "";',
  '  return `<aside class="desktop-sidebar"><div class="sidebar-brand"><div class="sidebar-brand-mark"><i class="fas fa-tools"></i></div><div class="sidebar-brand-copy"><strong>命定创意工坊</strong><small>Creative Workshop</small></div></div><div class="sidebar-section-label">浏览</div>${renderTagFilter()}<div class="sidebar-spacer"></div><div class="sidebar-bottom">${renderTavernStatus()}</div></aside>`;',
  '}',
  'function renderHeader() {',
  '  const desktopLayout = isDesktopWorkshopLayout();',
  '  const searchHtml = renderUnifiedSearch("desktop");',
  '  const installedToggleHtml = state.showOnlyMyProjects ? "" : `<label class="toggle-switch desktop-installed-filter" id="installedProjectsToggle"><span>订阅 / 已安装</span><input type="checkbox" ${state.showSubscribedAndInstalledProjects ? "checked" : ""}></label>`;',
  '  const closeHtml = isEmbedded ? `<button class="btn btn-outline workshop-close-btn" id="workshopCloseBtn" type="button"><i class="fas fa-right-from-bracket"></i> <span>退出</span></button>` : "";',
  '  const repairHtml = isEmbedded ? `<button class="btn btn-outline workshop-repair-btn" id="dlcRepairBtn" type="button"><i class="fas fa-screwdriver-wrench"></i> <span>DLC 修复</span></button>` : "";',
  '  const mobileBrandHtml = desktopLayout ? "" : `<div class="header-left mobile-header-brand"><div class="logo"><h1><i class="fas fa-tools"></i> 命定创意工坊</h1></div></div>`;',
  '  const desktopToolbarHtml = desktopLayout ? `<div class="desktop-toolbar">${searchHtml}<div class="desktop-toolbar-actions">${renderSortControl()}${installedToggleHtml}</div></div>` : "";',
  '  const mobileStatusHtml = desktopLayout ? "" : `${renderTavernStatus()}`;',
  '  const utilityHtml = `${mobileStatusHtml}${repairHtml}${renderScriptDependencyHealthNotice()}${closeHtml}`;',
  '  if (state.currentUser) {',
  '    return `<header class="header"><div class="header-top">${mobileBrandHtml}${desktopToolbarHtml}<div class="user-info">${utilityHtml}<div class="user-menu ${state.userMenuOpen ? "open" : ""}" id="userMenu"><button class="user-menu-trigger" id="userMenuTrigger"><span class="user-menu-name">${escapeHtml(state.currentUser.globalName || state.currentUser.username)}</span><img src="${escapeHtml(state.currentUser.avatarUrl || "https://cdn.discordapp.com/embed/avatars/0.png")}" class="avatar"><i class="fas fa-chevron-down"></i></button><div class="user-menu-dropdown"><button class="user-menu-item ${state.showOnlyMyProjects ? "active" : ""}" id="myProjectsMenuBtn"><i class="fas fa-layer-group"></i> ${state.showOnlyMyProjects ? "返回全部项目" : "我的项目"}</button><button class="user-menu-item" id="uploadBtn"><i class="fas fa-cloud-upload-alt"></i> 上传</button>${state.currentUser.isAdmin ? "<button class=\\"user-menu-item\\" id=\\"adminPanelBtn\\"><i class=\\"fas fa-clipboard-check\\"></i> 审核</button><button class=\\"user-menu-item\\" id=\\"bannerSettingsBtn\\"><i class=\\"fas fa-panorama\\"></i> 首页 Banner</button>" : ""}${state.currentUser.isSuperAdmin ? "<button class=\\"user-menu-item\\" id=\\"addAdminBtn\\"><i class=\\"fas fa-user-shield\\"></i> 添加管理员</button><button class=\\"user-menu-item\\" id=\\"adminLogsBtn\\"><i class=\\"fas fa-clock-rotate-left\\"></i> 日志</button>" : ""}<button class="user-menu-item" id="logoutBtn"><i class="fas fa-sign-out-alt"></i> 登出</button></div></div></div></div></header>`;',
  '  }',
  '  const localAdminHtml = isPrivateLocalPreviewHost() ? `<button class="btn btn-outline" id="localAdminLoginBtn"><i class="fas fa-user-shield"></i> <span>本地 Admin</span></button>` : "";',
  '  return `<header class="header"><div class="header-top">${mobileBrandHtml}${desktopToolbarHtml}<div class="user-info">${utilityHtml}${localAdminHtml}<button class="btn btn-primary" id="loginBtn"><i class="fab fa-discord"></i> <span>Discord 登录</span></button></div></div></header>`;',
  '}',
  'function renderProjectsGrid(projects) {',
  '  const hasQuery = Boolean(String(state.searchKeyword || "").trim() || getActivePublicTags().length);',
  '  const emptyText = hasQuery ? "没有符合当前条件的项目" : "暂无项目";',
  '  return `<div class="projects-grid">${projects.length ? projects.map(renderProjectCard).join("") : `<p class="projects-empty">${emptyText}</p>`}</div>`;',
  '}',
  'function renderDiscoverMoreCard(sortMode, label) {',
  '  return `<button type="button" class="discover-more-card" data-discover-more-sort="${sortMode}"><span>More</span><strong>${escapeHtml(label)}</strong><i class="fas fa-arrow-right"></i></button>`;',
  '}',
  'function renderDiscoverShelf(title, subtitle, projects, options = {}) {',
  '  const items = (projects || []).map(project => `<div class="discover-shelf-item">${renderDiscoverCard(project)}</div>`).join("");',
  '  const moreCard = options.moreSort ? `<div class="discover-shelf-item discover-shelf-item--more">${renderDiscoverMoreCard(options.moreSort, options.moreLabel || title)}</div>` : "";',
  '  return `<section class="discover-shelf"><div class="discover-shelf-head"><div><small>${escapeHtml(subtitle)}</small><h2>${escapeHtml(title)}</h2></div></div><div class="discover-shelf-track-shell"><button type="button" class="discover-shelf-scroll discover-shelf-scroll--prev" data-shelf-scroll="-1" aria-label="向左浏览${escapeHtml(title)}"><i class="fas fa-chevron-left"></i></button><div class="discover-shelf-track" data-shelf-track>${items}${moreCard}</div><button type="button" class="discover-shelf-scroll discover-shelf-scroll--next" data-shelf-scroll="1" aria-label="向右浏览${escapeHtml(title)}"><i class="fas fa-chevron-right"></i></button></div></section>`;',
  '}',
  'function renderDiscoverBanner() {',
  '  const banner = state.discoverBanner || {};',
  '  if (!banner.imageUrl) return "";',
  '  const x = Math.min(100, Math.max(0, Number(banner.positionX ?? 50)));',
  '  const y = Math.min(100, Math.max(0, Number(banner.positionY ?? 50)));',
  '  const zoom = Math.min(3, Math.max(1, Number(banner.zoom ?? 1)));',
  '  const mx = Math.min(100, Math.max(0, Number(banner.mobilePositionX ?? x)));',
  '  const my = Math.min(100, Math.max(0, Number(banner.mobilePositionY ?? y)));',
  '  const mz = Math.min(3, Math.max(1, Number(banner.mobileZoom ?? zoom)));',
  '  return `<div class="discover-banner" style="--banner-x:${x}%;--banner-y:${y}%;--banner-zoom:${zoom};--banner-mobile-x:${mx}%;--banner-mobile-y:${my}%;--banner-mobile-zoom:${mz};"><img src="${escapeHtml(banner.imageUrl)}" alt="创意工坊横幅"></div>`;',
  '}',
  'function renderDiscoverHome() {',
  '  const shelves = state.discoverShelves || {};',
  '  if (shelves.loading && !(shelves.discover || []).length) return `<div class="discover-loading"><i class="fas fa-spinner fa-spin"></i><span>正在整理今天的发现...</span></div>`;',
  '  return `<div class="discover-home">${renderDiscoverBanner()}${renderDiscoverShelf("发现推荐", "FOR YOU", shelves.discover || [])}${renderDiscoverShelf("最新发布", "LATEST", shelves.published || [], { moreSort: "published", moreLabel: "更多最新" })}${renderDiscoverShelf("玩家好评", "PLAYER PICKS", shelves.rating || [], { moreSort: "rating", moreLabel: "更多好评" })}${renderDiscoverShelf("下载最多", "MOST DOWNLOADED", shelves.downloads || [], { moreSort: "downloads", moreLabel: "更多下载" })}</div>`;',
  '}',
  'function renderMyProjectsPageHead() {',
  '  if (!state.showOnlyMyProjects) return "";',
  '  return `<section class="my-projects-page-head"><div><small>个人空间</small><h2>我的项目</h2></div><button type="button" class="btn btn-primary my-projects-upload-btn" id="myProjectsUploadBtn"><i class="fas fa-plus"></i><span>上传项目</span></button></section>`;',
  '}',
  'function renderProjectsGrid(projects) {',
  '  const hasQuery = Boolean(String(state.searchKeyword || "").trim() || getActivePublicTags().length);',
  '  const emptyText = hasQuery ? "没有符合当前条件的项目" : "暂无项目";',
  '  return `<div class="projects-grid">${projects.length ? projects.map(renderProjectCard).join("") : `<p class="projects-empty">${emptyText}</p>`}</div>`;',
  '}',
  'function renderDiscoverMoreCard(sortMode, label) {',
  '  return `<button type="button" class="discover-more-card" data-discover-more-sort="${sortMode}"><span>More</span><strong>${escapeHtml(label)}</strong><i class="fas fa-arrow-right"></i></button>`;',
  '}',
  'function renderDiscoverShelf(title, subtitle, projects, options = {}) {',
  '  const items = (projects || []).map(project => `<div class="discover-shelf-item">${renderDiscoverCard(project)}</div>`).join("");',
  '  const moreCard = options.moreSort ? `<div class="discover-shelf-item discover-shelf-item--more">${renderDiscoverMoreCard(options.moreSort, options.moreLabel || title)}</div>` : "";',
  '  return `<section class="discover-shelf"><div class="discover-shelf-head"><div><small>${escapeHtml(subtitle)}</small><h2>${escapeHtml(title)}</h2></div></div><div class="discover-shelf-track-shell"><button type="button" class="discover-shelf-scroll discover-shelf-scroll--prev" data-shelf-scroll="-1" aria-label="向左浏览${escapeHtml(title)}"><i class="fas fa-chevron-left"></i></button><div class="discover-shelf-track" data-shelf-track>${items}${moreCard}</div><button type="button" class="discover-shelf-scroll discover-shelf-scroll--next" data-shelf-scroll="1" aria-label="向右浏览${escapeHtml(title)}"><i class="fas fa-chevron-right"></i></button></div></section>`;',
  '}',
  'function renderDiscoverBanner() {',
  '  const banner = state.discoverBanner || {};',
  '  if (!banner.imageUrl) return "";',
  '  const x = Math.min(100, Math.max(0, Number(banner.positionX ?? 50)));',
  '  const y = Math.min(100, Math.max(0, Number(banner.positionY ?? 50)));',
  '  const zoom = Math.min(3, Math.max(1, Number(banner.zoom ?? 1)));',
  '  const mx = Math.min(100, Math.max(0, Number(banner.mobilePositionX ?? x)));',
  '  const my = Math.min(100, Math.max(0, Number(banner.mobilePositionY ?? y)));',
  '  const mz = Math.min(3, Math.max(1, Number(banner.mobileZoom ?? zoom)));',
  '  return `<div class="discover-banner" style="--banner-x:${x}%;--banner-y:${y}%;--banner-zoom:${zoom};--banner-mobile-x:${mx}%;--banner-mobile-y:${my}%;--banner-mobile-zoom:${mz};"><img src="${escapeHtml(banner.imageUrl)}" alt="创意工坊横幅"></div>`;',
  '}',
  'function renderDiscoverHome() {',
  '  const shelves = state.discoverShelves || {};',
  '  if (shelves.loading && !(shelves.discover || []).length) return `<div class="discover-loading"><i class="fas fa-spinner fa-spin"></i><span>正在整理今天的发现...</span></div>`;',
  '  return `<div class="discover-home">${renderDiscoverBanner()}${renderDiscoverShelf("发现推荐", "FOR YOU", shelves.discover || [])}${renderDiscoverShelf("最新发布", "LATEST", shelves.published || [], { moreSort: "published", moreLabel: "更多最新" })}${renderDiscoverShelf("玩家好评", "PLAYER PICKS", shelves.rating || [], { moreSort: "rating", moreLabel: "更多好评" })}${renderDiscoverShelf("下载最多", "MOST DOWNLOADED", shelves.downloads || [], { moreSort: "downloads", moreLabel: "更多下载" })}</div>`;',
  '}',
  'function renderProjectLoadMore() {',
  '  if (isDiscoverHomeView() || !shouldShowProjectLoadMore()) return "";',
  '',
  '  const loading = state.projectPagination.loadingMore;',
  '  const label = loading ? "加载中..." : "加载更多";',
  '  return `<div class="project-load-more"><button class="btn btn-outline project-load-more-btn${loading ? " is-loading" : ""}" id="projectLoadMoreBtn" ${loading ? "disabled" : ""}><i class="fas ${loading ? "fa-spinner" : "fa-angles-down"}"></i>${label}</button><div class="project-load-more-meta">已加载 ${state.projects.length}</div></div>`;',
  '}',
  'function renderLayout(projects) {',
  '  const contentHtml = isDiscoverHomeView() ? renderDiscoverHome(projects) : `${renderMyProjectsPageHead()}${renderSearchSummary()}${renderProjectsGrid(projects)}${renderProjectLoadMore()}`;',
  '  return `<div class="workshop-shell">${renderDesktopSidebar()}<main class="workshop-main">${renderHeader()}${renderMobileBreadcrumb()}${contentHtml}${renderMobileDiscoveryTools()}</main></div>`;',
  '}',
].join('\n');
