export const homeLayoutRenderScript = [
  'const WORKSHOP_RELEASE_VERSION = "2.0.14";',
  'const WORKSHOP_RELEASE_IMPORT = "import \\\'https://testingcf.jsdelivr.net/gh/AkabaneSaki/myrepo@2.0.14/test-dist/CreativeWorkshop/index.js\\\'";',
  'function isDesktopWorkshopLayout() {',
  '  return typeof window !== "undefined" && typeof window.matchMedia === "function" && window.matchMedia("(min-width: 1024px)").matches;',
  '}',
  'let workshopDesktopLayoutMatch = isDesktopWorkshopLayout();',
  'window.addEventListener("resize", () => {',
  '  const nextDesktopLayoutMatch = isDesktopWorkshopLayout();',
  '  if (nextDesktopLayoutMatch === workshopDesktopLayoutMatch) return;',
  '  workshopDesktopLayoutMatch = nextDesktopLayoutMatch;',
  '  renderApp();',
  '});',
  'function renderReleaseNotice() {',
  '  if (!shouldShowWorkshopReleaseNotice(WORKSHOP_RELEASE_VERSION)) return "";',
  '  return `<button class="release-notice" id="releaseNoticeBtn" type="button" title="点击复制最新版导入代码"><i class="fas fa-triangle-exclamation"></i><span>重大更新</span><strong>请更新至 v${WORKSHOP_RELEASE_VERSION}</strong></button>`;',
  '}',
  'function renderSortControl() {',
  '  if (state.showOnlyMyProjects || state.showSubscribedAndInstalledProjects) return "";',
  '  const options = [',
  '    { value: "published", label: "按发布时间" },',
  '    { value: "updated", label: "按更新日期" },',
  '    { value: "likes", label: "按点赞数" },',
  '    { value: "downloads", label: "按下载量" },',
  '  ];',
  '  const current = options.find(option => option.value === state.sortMode) || options[0];',
  '  const optionHtml = options.map(option => `<button class="user-menu-item sort-menu-item ${state.sortMode === option.value ? "active" : ""}" type="button" data-sort-value="${option.value}"><i class="fas ${state.sortMode === option.value ? "fa-circle-check" : "fa-arrow-right"}"></i> ${option.label}</button>`).join("");',
  '  return `<div class="user-menu sort-menu ${state.sortMenuOpen ? "open" : ""}" id="sortMenu"><button class="user-menu-trigger sort-menu-trigger" id="sortMenuTrigger"><i class="fas fa-arrow-down-wide-short"></i><span class="user-menu-name">${current.label}</span><i class="fas fa-chevron-down"></i></button><div class="user-menu-dropdown">${optionHtml}</div></div>`;',
  '}',
  'function renderFontControl() {',
  '  const current = getContentFontOption(state.contentFont);',
  '  const optionHtml = CONTENT_FONT_OPTIONS.map(option => `<button class=\"user-menu-item font-menu-item ${state.contentFont === option.value ? "active" : ""}\" type=\"button\" data-font-value=\"${option.value}\"><i class=\"fas ${state.contentFont === option.value ? "fa-circle-check" : "fa-font"}\"></i><span>${escapeHtml(option.label)}</span></button>`).join("");',
  '  return `<div class=\"user-menu font-menu ${state.fontMenuOpen ? "open" : ""}\" id=\"fontMenu\"><button class=\"user-menu-trigger font-menu-trigger\" id=\"fontMenuTrigger\" type=\"button\" title=\"切换内容字体\"><i class=\"fas fa-font\"></i><span class=\"user-menu-name\">${escapeHtml(current.label)}</span><i class=\"fas fa-chevron-down\"></i></button><div class=\"user-menu-dropdown\">${optionHtml}</div></div>`;',
  '}',
  'function renderTavernStatus() {',
  '  const status = state.tavern.status || "disconnected";',
  '  const meta = {',
  '    disconnected: { label: "未连接 SillyTavern", icon: "fa-plug-circle-xmark" },',
  '    connecting: { label: "正在连接 SillyTavern", icon: "fa-spinner fa-spin" },',
  '    connected: { label: "已连接 SillyTavern", icon: "fa-plug-circle-check" },',
  '    error: { label: "SillyTavern 连接异常", icon: "fa-triangle-exclamation" },',
  '  }[status] || { label: "未连接 SillyTavern", icon: "fa-plug-circle-xmark" };',
  '  return `<div class="tavern-status tavern-status--${status}" title="${meta.label}"><i class="fas ${meta.icon}"></i><span>${meta.label}</span></div>`;',
  '}',
  'function renderTagFilter() {',
  '  if (state.showOnlyMyProjects) return `<div class="sidebar-view-state"><i class="fas fa-layer-group"></i><span><small>当前视图</small><strong>我的项目</strong></span></div>`;',
  '  if (state.showSubscribedAndInstalledProjects) return `<div class="sidebar-view-state"><i class="fas fa-bookmark"></i><span><small>当前视图</small><strong>订阅 / 已安装</strong></span></div>`;',
  '  const options = [{ value: "all", label: "全部项目", typeClass: "all", icon: "fa-border-all" }, ...BASE_TAG_META.map(option => ({ ...option, icon: { system: "fa-microchip", extension: "fa-puzzle-piece", character: "fa-user-group", event: "fa-calendar-days" }[option.typeClass] || "fa-folder" }))];',
  '  const pendingAttr = state.filterRequestPending ? "disabled" : "";',
  '  const pendingClass = state.filterRequestPending ? "is-disabled" : "";',
  '  const optionHtml = options.map(option => `<button class="tag-filter-btn sidebar-nav-btn ${state.activeBaseTag === option.value ? "active" : ""} ${option.typeClass} ${pendingClass}" type="button" data-base-tag="${option.value}" ${pendingAttr}><i class="fas ${option.icon}"></i><span>${escapeHtml(option.label)}</span></button>`).join("");',
  '  return `<nav class="tag-filter sidebar-nav" id="baseTagFilter" aria-label="作品分类">${optionHtml}</nav>`;',
  '}',
  'function getProjectTagFilterGroups() {',
  '  const groups = [];',
  '  if (state.activeBaseTag === "all" || state.activeBaseTag === "扩展") {',
  '    const extensionTypes = Array.from(new Set((PROJECT_TAXONOMY.extensionTypes || []).map(value => String(value).trim()).filter(Boolean)));',
  '    if (extensionTypes.length) groups.push({ label: "扩展类型", tags: extensionTypes });',
  '  }',
  '  if (state.activeBaseTag === "all" || state.activeBaseTag === "角色") {',
  '    Object.entries(PROJECT_TAXONOMY.characterFacets || {}).forEach(([label, values]) => {',
  '      const tags = Array.from(new Set((values || []).map(value => String(value).trim()).filter(Boolean)));',
  '      if (tags.length) groups.push({ label, tags });',
  '    });',
  '  }',
  '  return groups;',
  '}',
  'function renderSearchTagSuggestions() {',
  '  if (state.showOnlyMyProjects || state.showSubscribedAndInstalledProjects) return `<div class="search-tag-empty-state">当前视图不使用官方标签筛选。</div>`;',
  '  const selectedTags = getActivePublicTags();',
  '  const groupsHtml = getProjectTagFilterGroups().map(group => {',
  '    const tagsHtml = group.tags.map(tag => { const active = selectedTags.includes(tag); return `<button type="button" class="search-tag-chip ${active ? "active" : ""}" data-search-tag="${escapeHtml(tag)}" aria-pressed="${active ? "true" : "false"}">${escapeHtml(tag)}${active ? `<i class="fas fa-check"></i>` : ""}</button>`; }).join("");',
  '    return `<section class="search-tag-group" data-search-tag-group><div class="search-tag-group-title">${escapeHtml(group.label)}</div><div class="search-tag-chip-row">${tagsHtml}</div></section>`;',
  '  }).join("");',
  '  return `<div class="search-tag-groups">${groupsHtml || `<div class="search-tag-empty-state">这个分类没有官方标签</div>`}</div><div class="search-tag-empty" hidden>没有匹配的官方标签，按 Enter 可直接搜索项目 / 作者。</div>`;',
  '}',
  'function renderActiveSearchTags() {',
  '  const tags = getActivePublicTags();',
  '  if (!tags.length) return "";',
  '  return `<div class="search-active-tags"><div class="search-active-tags-head"><span>已选官方标签</span><button type="button" data-clear-all-search-tags>清除全部</button></div><div class="search-active-tag-row">${tags.map(tag => `<button type="button" class="search-active-tag" data-remove-search-tag="${escapeHtml(tag)}">${escapeHtml(tag)}<i class="fas fa-xmark"></i></button>`).join("")}</div></div>`;',
  '}',
  'function renderUnifiedSearch(mode) {',
  '  const mobile = mode === "mobile";',
  '  const inputId = mobile ? "projectSearchInputMobile" : "projectSearchInput";',
  '  const draft = String(state.searchDraft ?? state.searchKeyword ?? "");',
  '  const committed = String(state.searchKeyword || "").trim();',
  '  return `<div class="unified-search unified-search--${mode}" data-unified-search="${mode}"><div class="unified-search-box"><i class="fas fa-search"></i><input id="${inputId}" type="search" autocomplete="off" placeholder="搜索项目、作者或官方标签" value="${escapeHtml(draft)}">${committed ? `<button type="button" class="unified-search-clear" data-clear-text-search title="清除文字搜索"><i class="fas fa-xmark"></i></button>` : ""}</div><div class="search-assist"><div class="search-assist-head"><span>官方标签</span><small>点标签加入条件 · Enter 搜索文字</small></div>${renderActiveSearchTags()}${renderSearchTagSuggestions()}</div></div>`;',
  '}',
  'function renderMobileCategoryNav() {',
  '  if (state.showOnlyMyProjects || state.showSubscribedAndInstalledProjects) return "";',
  '  const options = [{ value: "all", label: "全部" }, ...BASE_TAG_META];',
  '  const pendingAttr = state.filterRequestPending ? "disabled" : "";',
  '  return `<nav class="mobile-category-nav" id="mobileBaseTagFilter" aria-label="作品分类">${options.map(option => `<button type="button" class="mobile-category-tab ${state.activeBaseTag === option.value ? "active" : ""}" data-base-tag="${option.value}" ${pendingAttr}>${escapeHtml(option.label)}</button>`).join("")}</nav>`;',
  '}',
  'function renderSearchSummary() {',
  '  const keyword = String(state.searchKeyword || "").trim();',
  '  const tags = getActivePublicTags();',
  '  if (!keyword && !tags.length) return "";',
  '  const keywordHtml = keyword ? `<button type="button" class="search-summary-chip search-summary-query" data-clear-text-search><i class="fas fa-search"></i>${escapeHtml(keyword)}<i class="fas fa-xmark"></i></button>` : "";',
  '  const tagsHtml = tags.map(tag => `<button type="button" class="search-summary-chip" data-remove-search-tag="${escapeHtml(tag)}">${escapeHtml(tag)}<i class="fas fa-xmark"></i></button>`).join("");',
  '  return `<div class="search-query-summary"><span class="search-query-summary-label">当前条件</span>${keywordHtml}${tagsHtml}${tags.length > 1 ? `<button type="button" class="search-summary-clear" data-clear-all-search-tags>清除标签</button>` : ""}</div>`;',
  '}',
  'function renderMobileSortOptions() {',
  '  if (state.showOnlyMyProjects || state.showSubscribedAndInstalledProjects) return `<div class="mobile-tool-empty">当前视图使用固定排序。</div>`;',
  '  const options = [',
  '    { value: "published", label: "按发布时间" },',
  '    { value: "updated", label: "按更新日期" },',
  '    { value: "likes", label: "按点赞数" },',
  '    { value: "downloads", label: "按下载量" },',
  '  ];',
  '  return options.map(option => `<button class="mobile-sort-option ${state.sortMode === option.value ? "active" : ""}" type="button" data-sort-value="${option.value}"><span>${option.label}</span>${state.sortMode === option.value ? `<i class="fas fa-check"></i>` : ""}</button>`).join("");',
  '}',
  'function renderMobileFontOptions() {',
  '  return CONTENT_FONT_OPTIONS.map(option => `<button class="mobile-sort-option mobile-font-option ${state.contentFont === option.value ? "active" : ""}" type="button" data-font-value="${option.value}"><span>${escapeHtml(option.label)}</span>${state.contentFont === option.value ? `<i class="fas fa-check"></i>` : ""}</button>`).join("");',
  '}',
  'function renderMobileDiscoveryTools() {',
  '  const mode = String(state.mobileToolMode || "");',
  '  const title = ({ search: "搜索", sort: "排序" })[mode] || "浏览工具";',
  '  const isOpen = Boolean(mode);',
  '  return `<div class="mobile-tool-backdrop ${isOpen ? "show" : ""}" id="mobileToolBackdrop"></div><section class="mobile-tool-sheet ${isOpen ? "show" : ""}" id="mobileToolSheet" aria-hidden="${isOpen ? "false" : "true"}"><div class="mobile-tool-sheet-head"><strong id="mobileToolTitle">${title}</strong><button type="button" id="mobileToolClose">完成</button></div><div class="mobile-tool-panel" data-mobile-panel="search" ${mode === "search" ? "" : "hidden"}>${renderUnifiedSearch("mobile")}</div><div class="mobile-tool-panel mobile-sort-list" data-mobile-panel="sort" ${mode === "sort" ? "" : "hidden"}>${renderMobileSortOptions()}</div></section><nav class="mobile-tool-dock" aria-label="浏览工具"><button type="button" class="${mode === "search" ? "active" : ""}" data-mobile-tool="search"><i class="fas fa-search"></i><span>搜索</span></button><button type="button" class="${mode === "sort" ? "active" : ""}" data-mobile-tool="sort"><i class="fas fa-arrow-down-wide-short"></i><span>排序</span></button></nav>`;',
  '}',
  'function renderDesktopSidebar() {',
  '  if (!isDesktopWorkshopLayout()) return "";',
  '  return `<aside class="desktop-sidebar"><div class="sidebar-brand"><div class="sidebar-brand-mark"><i class="fas fa-tools"></i></div><div class="sidebar-brand-copy"><strong>命定创意工坊</strong><small>Creative Workshop</small></div></div><div class="sidebar-section-label">浏览</div>${renderTagFilter()}<div class="sidebar-spacer"></div><div class="sidebar-bottom">${renderReleaseNotice()}${renderTavernStatus()}</div></aside>`;',
  '}',
  'function renderHeader() {',
  '  const desktopLayout = isDesktopWorkshopLayout();',
  '  const searchHtml = renderUnifiedSearch("desktop");',
  '  const installedToggleHtml = state.showOnlyMyProjects ? "" : `<label class="toggle-switch desktop-installed-filter" id="installedProjectsToggle"><span>订阅 / 已安装</span><input type="checkbox" ${state.showSubscribedAndInstalledProjects ? "checked" : ""}></label>`;',
  '  const closeHtml = isEmbedded ? `<button class="btn btn-outline workshop-close-btn" id="workshopCloseBtn" type="button"><i class="fas fa-right-from-bracket"></i> <span>退出</span></button>` : "";',
  '  const mobileBrandHtml = desktopLayout ? "" : `<div class="header-left mobile-header-brand"><div class="logo"><h1><i class="fas fa-tools"></i> 命定创意工坊</h1></div>${renderReleaseNotice()}</div>`;',
  '  const desktopToolbarHtml = desktopLayout ? `<div class="desktop-toolbar">${searchHtml}<div class="desktop-toolbar-actions">${renderSortControl()}${installedToggleHtml}</div></div>` : "";',
  '  const mobileStatusHtml = desktopLayout ? "" : renderTavernStatus();',
  '  const utilityHtml = `${mobileStatusHtml}${closeHtml}`;',
  '  if (state.currentUser) {',
  '    return `<header class="header"><div class="header-top">${mobileBrandHtml}${desktopToolbarHtml}<div class="user-info">${utilityHtml}<div class="user-menu ${state.userMenuOpen ? "open" : ""}" id="userMenu"><button class="user-menu-trigger" id="userMenuTrigger"><span class="user-menu-name">${escapeHtml(state.currentUser.globalName || state.currentUser.username)}</span><img src="${escapeHtml(state.currentUser.avatarUrl || "https://cdn.discordapp.com/embed/avatars/0.png")}" class="avatar"><i class="fas fa-chevron-down"></i></button><div class="user-menu-dropdown"><button class="user-menu-item ${state.showOnlyMyProjects ? "active" : ""}" id="myProjectsMenuBtn"><i class="fas fa-layer-group"></i> ${state.showOnlyMyProjects ? "返回全部项目" : "我的项目"}</button><button class="user-menu-item" id="uploadBtn"><i class="fas fa-cloud-upload-alt"></i> 上传</button>${state.currentUser.isAdmin ? "<button class=\\"user-menu-item\\" id=\\"adminPanelBtn\\"><i class=\\"fas fa-clipboard-check\\"></i> 审核</button>" : ""}${state.currentUser.isSuperAdmin ? "<button class=\\"user-menu-item\\" id=\\"addAdminBtn\\"><i class=\\"fas fa-user-shield\\"></i> 添加管理员</button><button class=\\"user-menu-item\\" id=\\"adminLogsBtn\\"><i class=\\"fas fa-clock-rotate-left\\"></i> 日志</button>" : ""}<button class="user-menu-item" id="logoutBtn"><i class="fas fa-sign-out-alt"></i> 登出</button></div></div></div></div></header>`;',
  '  }',
  '  return `<header class="header"><div class="header-top">${mobileBrandHtml}${desktopToolbarHtml}<div class="user-info">${utilityHtml}<button class="btn btn-primary" id="loginBtn"><i class="fab fa-discord"></i> <span>Discord 登录</span></button></div></div></header>`;',
  '}',
  'function renderProjectsGrid(projects) {',
  '  const hasQuery = Boolean(String(state.searchKeyword || "").trim() || getActivePublicTags().length);',
  '  const emptyText = hasQuery ? "没有符合当前条件的项目" : "暂无项目";',
  '  return `<div class="projects-grid">${projects.length ? projects.map(renderProjectCard).join("") : `<p class="projects-empty">${emptyText}</p>`}</div>`;',
  '}',
  'function renderProjectLoadMore() {',
  '  if (!shouldShowProjectLoadMore()) return "";',
  '',
  '  const loading = state.projectPagination.loadingMore;',
  '  const label = loading ? "加载中..." : "加载更多";',
  '  return `<div class="project-load-more"><button class="btn btn-outline project-load-more-btn${loading ? " is-loading" : ""}" id="projectLoadMoreBtn" ${loading ? "disabled" : ""}><i class="fas ${loading ? "fa-spinner" : "fa-angles-down"}"></i>${label}</button><div class="project-load-more-meta">已加载 ${state.projects.length}</div></div>`;',
  '}',
  'function renderLayout(projects) {',
  '  return `<div class="workshop-shell">${renderDesktopSidebar()}<main class="workshop-main">${renderHeader()}${renderMobileCategoryNav()}${renderSearchSummary()}${renderProjectsGrid(projects)}${renderProjectLoadMore()}${renderMobileDiscoveryTools()}</main></div>`;',
  '}',
].join('\n');
