export const homeReviewDiffRenderScript = [
  "function getAdminReviewChangeEntry(change) {",
  "  return change?.current || change?.previous || {};",
  "}",
  "function getAdminReviewChangeTitle(change, kind) {",
  "  const entry = getAdminReviewChangeEntry(change);",
  "  if (kind === 'worldbook') return entry.comment || entry.name || entry.uid || change.entryKey || '无标题';",
  "  return entry.scriptName || entry.name || entry.id || entry.findRegex || change.entryKey || '未命名正则';",
  "}",
  "function getAdminReviewStatusMeta(status) {",
  "  if (status === 'added') return { label: '新增', symbol: '+', className: 'added' };",
  "  if (status === 'deleted') return { label: '删除', symbol: '−', className: 'deleted' };",
  "  if (status === 'modified') return { label: '修改', symbol: '~', className: 'modified' };",
  "  return { label: '未修改', symbol: '=', className: 'unchanged' };",
  "}",
  "function getAdminReviewFieldLabel(field) {",
  "  const labels = { content: '正文', text: '正文', comment: '标题', name: '名称', key: '主要关键词', keys: '主要关键词', keysecondary: '次要关键词', key_secondary: '次要关键词', uid: 'UID', id: 'ID', scriptName: '正则名称', script_name: '正则名称', findRegex: '匹配表达式', find_regex: '匹配表达式', replaceString: '替换文本', replace_string: '替换文本', position: '位置', depth: '深度', order: '顺序', enabled: '启用状态', disabled: '禁用状态', constant: '常驻', selective: '选择性', probability: '概率', extensions: '扩展设置' };",
  "  return labels[field] || field;",
  "}",
  "function splitAdminReviewDiffLines(value) {",
  "  const text = String(value || '');",
  "  return text ? text.split('\\n') : [];",
  "}",
  "function compressAdminReviewSameRows(rows) {",
  "  const output = [];",
  "  for (let index = 0; index < rows.length;) {",
  "    if (rows[index].type !== 'same') { output.push(rows[index]); index += 1; continue; }",
  "    let end = index + 1;",
  "    while (end < rows.length && rows[end].type === 'same') end += 1;",
  "    const run = rows.slice(index, end);",
  "    if (run.length <= 6) output.push(...run);",
  "    else output.push(...run.slice(0, 2), { type: 'skip', count: run.length - 4 }, ...run.slice(-2));",
  "    index = end;",
  "  }",
  "  return output;",
  "}",
  "function buildAdminReviewLineDiff(beforeText, afterText) {",
  "  const before = splitAdminReviewDiffLines(beforeText);",
  "  const after = splitAdminReviewDiffLines(afterText);",
  "  let prefix = 0;",
  "  while (prefix < before.length && prefix < after.length && before[prefix] === after[prefix]) prefix += 1;",
  "  let suffix = 0;",
  "  while (suffix < before.length - prefix && suffix < after.length - prefix && before[before.length - 1 - suffix] === after[after.length - 1 - suffix]) suffix += 1;",
  "  const left = before.slice(prefix, before.length - suffix);",
  "  const right = after.slice(prefix, after.length - suffix);",
  "  let middle = [];",
  "  if (left.length && right.length && left.length * right.length <= 160000) {",
  "    const dp = Array.from({ length: left.length + 1 }, () => new Uint16Array(right.length + 1));",
  "    for (let i = 1; i <= left.length; i += 1) {",
  "      for (let j = 1; j <= right.length; j += 1) {",
  "        dp[i][j] = left[i - 1] === right[j - 1] ? dp[i - 1][j - 1] + 1 : Math.max(dp[i - 1][j], dp[i][j - 1]);",
  "      }",
  "    }",
  "    const reversed = [];",
  "    let i = left.length;",
  "    let j = right.length;",
  "    while (i > 0 || j > 0) {",
  "      if (i > 0 && j > 0 && left[i - 1] === right[j - 1]) { reversed.push({ type: 'same', text: left[i - 1] }); i -= 1; j -= 1; }",
  "      else if (j > 0 && (i === 0 || dp[i][j - 1] > dp[i - 1][j])) { reversed.push({ type: 'add', text: right[j - 1] }); j -= 1; }",
  "      else { reversed.push({ type: 'del', text: left[i - 1] }); i -= 1; }",
  "    }",
  "    middle = reversed.reverse();",
  "  } else {",
  "    middle = [...left.map(text => ({ type: 'del', text })), ...right.map(text => ({ type: 'add', text }))];",
  "  }",
  "  const rows = [];",
  "  if (prefix > 2) rows.push({ type: 'skip', count: prefix - 2 });",
  "  before.slice(Math.max(0, prefix - 2), prefix).forEach(text => rows.push({ type: 'same', text }));",
  "  rows.push(...middle);",
  "  if (suffix) after.slice(after.length - suffix, Math.min(after.length, after.length - suffix + 2)).forEach(text => rows.push({ type: 'same', text }));",
  "  if (suffix > 2) rows.push({ type: 'skip', count: suffix - 2 });",
  "  return compressAdminReviewSameRows(rows);",
  "}",
  "function renderAdminReviewDiffRows(change) {",
  "  const before = change.status === 'added' ? '' : (change.previousReviewText || change.previousRaw || '');",
  "  const after = change.status === 'deleted' ? '' : (change.currentReviewText || change.currentRaw || '');",
  "  const rows = buildAdminReviewLineDiff(before, after);",
  "  if (!rows.length) return '<div class=\"admin-review-diff-empty\">没有可显示的文本差异</div>';",
  "  return `<div class=\"admin-review-diff-code\">${rows.map(row => {",
  "    if (row.type === 'skip') return `<div class=\"admin-review-diff-skip\">@@ … ${row.count} 行未变化 … @@</div>`;",
  "    const marker = row.type === 'add' ? '+' : row.type === 'del' ? '−' : ' ';",
  "    return `<div class=\"admin-review-diff-line admin-review-diff-line--${row.type}\"><span>${marker}</span><code>${escapeHtml(row.text || '')}</code></div>`;",
  "  }).join('')}</div>`;",
  "}",
  "function renderAdminReviewChangedEntry(change, kind, index) {",
  "  const meta = getAdminReviewStatusMeta(change.status);",
  "  const title = getAdminReviewChangeTitle(change, kind);",
  "  const fields = Array.isArray(change.changedFields) ? change.changedFields : [];",
  "  const fieldText = fields.length ? fields.slice(0, 6).map(getAdminReviewFieldLabel).join(' · ') + (fields.length > 6 ? ` · +${fields.length - 6}` : '') : '内容变化';",
  "  return `<details class=\"admin-review-diff-entry admin-review-diff-entry--${meta.className}\" open><summary><span class=\"admin-review-diff-status admin-review-diff-status--${meta.className}\">${meta.symbol} ${meta.label}</span><span class=\"admin-review-diff-entry-title\">${escapeHtml(title)}</span><span class=\"admin-review-diff-fields\">${escapeHtml(fieldText)}</span></summary><div class=\"admin-review-diff-entry-body\">${renderAdminReviewDiffRows(change)}</div></details>`;",
  "}",
  "function renderAdminReviewRiskDelta(riskDelta) {",
  "  if (!riskDelta) return '';",
  "  const items = [];",
  "  if (riskDelta.newEjs) items.push(`<span class=\"admin-review-risk-chip admin-review-risk-chip--warning\"><i class=\"fas fa-code\"></i> 新增 EJS ${riskDelta.newEjs}</span>`);",
  "  if (riskDelta.newCharacterArtwork) items.push(`<span class=\"admin-review-risk-chip admin-review-risk-chip--good\">👍🏻 新增角色立绘 ${riskDelta.newCharacterArtwork}</span>`);",
  "  if (riskDelta.newWarnings) items.push(`<span class=\"admin-review-risk-chip admin-review-risk-chip--danger\"><i class=\"fas fa-triangle-exclamation\"></i> 新增检查警告 ${riskDelta.newWarnings}</span>`);",
  "  return items.length ? `<div class=\"admin-review-risk-delta\"><strong>本次新增风险 / 信号</strong><div>${items.join('')}</div></div>` : '';",
  "}",
  "function renderAdminReviewDiffSummary(reviewDiff) {",
  "  if (!reviewDiff || reviewDiff.mode !== 'update') return '';",
  "  const summary = reviewDiff.summary || {};",
  "  return `<section class=\"admin-review-diff-summary\"><div class=\"admin-review-diff-summary-head\"><div><strong>${Number(summary.changed || 0)}</strong> 处变化需要审核</div><span>${Number(summary.unchanged || 0)} 条未修改，默认折叠</span></div><div class=\"admin-review-diff-counts\"><span class=\"added\">+ 新增 ${Number(summary.added || 0)}</span><span class=\"modified\">~ 修改 ${Number(summary.modified || 0)}</span><span class=\"deleted\">− 删除 ${Number(summary.deleted || 0)}</span><span class=\"unchanged\">= 未改 ${Number(summary.unchanged || 0)}</span></div>${renderAdminReviewRiskDelta(reviewDiff.riskDelta)}</section>`;",
  "}",
  "function renderAdminReviewUnchangedSummary(changes, kind) {",
  "  const unchanged = (Array.isArray(changes) ? changes : []).filter(change => change.status === 'unchanged');",
  "  if (!unchanged.length) return '';",
  "  const titles = unchanged.slice(0, 30).map(change => `<span>${escapeHtml(getAdminReviewChangeTitle(change, kind))}</span>`).join('');",
  "  const more = unchanged.length > 30 ? `<span>… 另外 ${unchanged.length - 30} 条</span>` : '';",
  "  return `<details class=\"admin-review-unchanged\"><summary><span><i class=\"fas fa-equals\"></i> 未修改 ${unchanged.length} 条</span><small>通常无需重新审核</small></summary><div class=\"admin-review-unchanged-titles\">${titles}${more}</div><button class=\"btn btn-outline admin-review-load-unchanged\" type=\"button\" data-admin-load-unchanged=\"${kind}\">加载完整未修改内容</button><div data-admin-unchanged-content=\"${kind}\"></div></details>`;",
  "}",
  "function renderAdminReviewDiffSection(title, icon, changes, kind) {",
  "  const list = Array.isArray(changes) ? changes : [];",
  "  const changed = list.filter(change => change.status !== 'unchanged');",
  "  const changedHtml = changed.length ? changed.map((change, index) => renderAdminReviewChangedEntry(change, kind, index)).join('') : '<div class=\"admin-review-no-changes\"><i class=\"fas fa-circle-check\"></i> 本部分没有内容变化</div>';",
  "  return `<section class=\"admin-review-diff-section\"><div class=\"detail-section-title\"><span><i class=\"fas ${icon}\"></i> ${title}</span><span>${changed.length} 处变化</span></div><div class=\"admin-review-diff-list\">${changedHtml}</div>${renderAdminReviewUnchangedSummary(list, kind)}</section>`;",
  "}",
  "function bindAdminReviewDiffLazyContent(overlay, reviewDiff) {",
  "  overlay.querySelectorAll('[data-admin-load-unchanged]').forEach(button => {",
  "    button.addEventListener('click', () => {",
  "      const kind = button.dataset.adminLoadUnchanged;",
  "      const list = Array.isArray(reviewDiff?.[kind]) ? reviewDiff[kind] : [];",
  "      const entries = list.filter(change => change.status === 'unchanged').map(change => change.current || change.previous).filter(Boolean);",
  "      const target = overlay.querySelector(`[data-admin-unchanged-content=\"${kind}\"]`);",
  "      if (!target) return;",
  "      const isWorldbook = kind === 'worldbook';",
  "      target.innerHTML = renderDetailSection(isWorldbook ? '未修改世界书条目' : '未修改正则', isWorldbook ? 'fa-scroll' : 'fa-code', entries, isWorldbook ? renderDetailEntry : renderRegexEntry, '无未修改内容');",
  "      bindAdminReviewEntryToggles(target);",
  "      button.remove();",
  "    });",
  "  });",
  "}",
].join('\n');
