export const homeAdminReviewModalScript = [
'function renderAdminReviewQueueSignals(project) {',
  '  const signals = [];',
  '  if (project?.hasEjs) signals.push(`<span class="admin-review-mini-signal admin-review-mini-signal--ejs">EJS</span>`);',
  '  if (project?.hasCharacterArtwork) signals.push(`<span class="admin-review-mini-signal admin-review-mini-signal--image"><i class="fas fa-user-portrait"></i> 角色立绘</span>`);',
  '  if (project?.conflictsWithOriginal) signals.push(`<span class="admin-review-mini-signal admin-review-mini-signal--warning"><i class="fas fa-shield-halved"></i> 原版冲突</span>`);',
  '  const signalHtml = signals.join("") || `<span class="admin-review-mini-signal is-muted">打开后检查详细变化</span>`;',
  '  return `<div class="admin-review-card-meta-row"><div class="admin-review-card-signals">${signalHtml}</div></div>`;',
  '}',
  '',
  'function renderAdminReviewCard(project, index, total) {',
  '  const coverSources = getCoverImageSources(project);',
  '  const typeLabel = getProjectTypeDisplayLabel(project);',
  '  return `',
  '    <article class="admin-review-card" data-review-card data-project-id="${escapeHtml(String(project.id || ""))}" role="button" tabindex="0" aria-label="审核：${escapeHtml(project.name || "未命名项目")}">',
  '      <div class="admin-review-card-grid">',
  '        <div class="admin-review-thumb" data-cover-src="${escapeHtml(coverSources.primary)}" data-cover-fallback-src="${escapeHtml(coverSources.fallback)}" data-cover-placeholder-src="${escapeHtml(coverSources.placeholder)}" data-cover-auth-src="${escapeHtml(coverSources.authenticated || "")}" style="background-image:url(\'${escapeHtml(coverSources.primary)}\')"></div>',
  '        <div class="admin-review-card-body">',
  '          <div class="admin-review-card-head">',
  '            <div class="admin-review-card-heading">',
  '              <div class="admin-review-title-line"><span class="admin-review-position" data-review-position>${index + 1}/${total}</span><span class="type-badge ${getTypeClass(project)}">${escapeHtml(typeLabel)}</span><span class="admin-review-title">${escapeHtml(project.name || "未命名项目")}</span></div>',
  '              <div class="admin-review-author"><i class="fas fa-user"></i> ${escapeHtml(getAuthorName(project))}</div>',
  '            </div>',
  '            <button class="btn btn-outline admin-review-tail-btn" type="button" data-id="${escapeHtml(String(project.id || ""))}" data-action="skip"><i class="fas fa-arrow-down"></i> 放到队尾</button>',
  '          </div>',
  '          ${renderAdminReviewQueueSignals(project)}',
  '        </div>',
  '      </div>',
  '    </article>',
  '  `;',
  '}',
  '',
  'function refreshAdminReviewPositions(overlay) {',
  '  const cards = Array.from(overlay.querySelectorAll("[data-review-card]"));',
  '  cards.forEach((card, index) => {',
  '    const position = card.querySelector("[data-review-position]");',
  '    if (position) position.textContent = `${index + 1}/${cards.length}`;',
  '  });',
  '}',
  '',
  'function skipAdminReviewCard(overlay, projectId) {',
  '  const card = Array.from(overlay.querySelectorAll("[data-review-card]")).find(item => item.dataset.projectId === String(projectId));',
  '  if (!card || !card.parentElement) return;',
  '  const list = card.parentElement;',
  '  list.appendChild(card);',
  '  card.classList.remove("is-skipped");',
  '  void card.offsetWidth;',
  '  card.classList.add("is-skipped");',
  '  refreshAdminReviewPositions(overlay);',
  '  const nextCard = list.querySelector("[data-review-card]");',
  '  nextCard?.scrollIntoView({ behavior: "smooth", block: "nearest" });',
  "  showToast('已放到队尾', 'info');",
  '}',
  '',
  'function renderAdminInspectionSignals(entries, regexEntries) {',
  '  const worldbookEntries = Array.isArray(entries) ? entries : [];',
  '  const regexList = Array.isArray(regexEntries) ? regexEntries : [];',
  '  const allEntries = [...worldbookEntries, ...regexList];',
  '  const hasInspectionData = allEntries.some(entry => entry && (Object.prototype.hasOwnProperty.call(entry, "hasEjs") || Object.prototype.hasOwnProperty.call(entry, "hasCharacterArtwork") || Object.prototype.hasOwnProperty.call(entry, "inspectionWarnings") || Object.prototype.hasOwnProperty.call(entry, "externalLinks")));',
  '  const hasEjs = allEntries.some(entry => Boolean(entry?.hasEjs));',
  '  const hasCharacterArtwork = allEntries.some(entry => Boolean(entry?.hasCharacterArtwork));',
  '  const warningCount = allEntries.reduce((count, entry) => count + (Array.isArray(entry?.inspectionWarnings) ? entry.inspectionWarnings.length : 0), 0);',
  '  const externalLinkCount = collectProjectExternalLinks(worldbookEntries, regexList).reduce((count, group) => count + group.links.length, 0);',
  '  const signals = [',
  '    `<span class="admin-review-signal"><i class="fas fa-book-open"></i> 世界书 ${worldbookEntries.length}</span>`,',
  '    `<span class="admin-review-signal"><i class="fas fa-code"></i> 正则 ${regexList.length}</span>`,',
  '  ];',
  '  if (hasInspectionData && hasEjs) signals.push(`<span class="admin-review-signal admin-review-signal--ejs">EJS</span>`);',
  '  if (hasInspectionData && hasCharacterArtwork) signals.push(`<span class="admin-review-signal admin-review-signal--good">👍🏻 角色立绘</span>`);',
  '  if (hasInspectionData && externalLinkCount) signals.push(`<span class="admin-review-signal admin-review-signal--info"><i class="fas fa-link"></i> 外链 ${externalLinkCount}</span>`);',
  '  if (hasInspectionData && warningCount) signals.push(`<span class="admin-review-signal admin-review-signal--warning"><i class="fas fa-triangle-exclamation"></i> ${warningCount} 个检查警告</span>`);',
  '  return `<div class="admin-review-signals">${signals.join("")}</div>`;',
  '}',
  '',
  'function bindAdminReviewEntryToggles(overlay) {',
  "  overlay.querySelectorAll('[data-entry-toggle]').forEach(header => {",
  "    header.addEventListener('click', () => {",
  "      header.classList.toggle('open');",
  '      const content = header.nextElementSibling;',
  "      if (content) content.classList.toggle('open');",
  '    });',
  '  });',
  '}',
  '',
  'function getAdminReviewQueueProjects(queueOverlay, queueProjects) {',
  '  const source = Array.isArray(queueProjects) ? queueProjects : [];',
  '  const byId = new Map(source.map(item => [String(item.id), item]));',
  '  return Array.from(queueOverlay?.querySelectorAll?.("[data-review-card]") || []).map(card => byId.get(String(card.dataset.projectId))).filter(Boolean);',
  '}',
  '',
  'function getAdminReviewAdjacentProject(queueOverlay, queueProjects, projectId, direction) {',
  '  const ordered = getAdminReviewQueueProjects(queueOverlay, queueProjects);',
  '  if (ordered.length <= 1) return null;',
  '  const currentIndex = ordered.findIndex(item => String(item.id) === String(projectId));',
  '  if (currentIndex < 0) return null;',
  '  const nextIndex = currentIndex + (direction < 0 ? -1 : 1);',
  '  if (nextIndex < 0 || nextIndex >= ordered.length) return null;',
  '  return ordered[nextIndex] || null;',
  '}',
  '',
  'function removeAdminReviewQueueProject(queueOverlay, queueProjects, projectId) {',
  '  const card = Array.from(queueOverlay?.querySelectorAll?.("[data-review-card]") || []).find(item => item.dataset.projectId === String(projectId));',
  '  card?.remove();',
  '  if (Array.isArray(queueProjects)) {',
  '    const index = queueProjects.findIndex(item => String(item.id) === String(projectId));',
  '    if (index >= 0) queueProjects.splice(index, 1);',
  '  }',
  '  refreshAdminReviewPositions(queueOverlay);',
  '  const count = queueOverlay?.querySelector(".admin-review-queue-summary strong");',
  '  if (count) count.textContent = String(queueOverlay.querySelectorAll("[data-review-card]").length);',
  '}',
  '',
  'async function openAdminReviewDetail(project, queueOverlay, queueProjects = []) {',
  '  const loadingOverlay = openModal(\'<div class="detail-loading"><div class="loading-spinner"></div><div class="detail-loading-text">正在加载审核内容...</div></div>\', \'<i class="fas fa-clipboard-check"></i> 审核详情\');',
  '  try {',
  '    const detail = await fetchAdminReviewDetail(project.id);',
  '    loadingOverlay.remove();',
  '    const reviewProjectData = detail.project || project;',
  '    const entries = detail.worldbookEntriesPreview || detail.project?.worldbookEntriesPreview || [];',
  '    const regexEntries = detail.regexEntriesPreview || detail.project?.regexEntriesPreview || [];',
  '    const reviewDiff = detail.reviewDiff || null;',
  '    const isDiffReview = reviewDiff?.mode === "update";',
  '    const contentReviewHtml = isDiffReview ? `${renderAdminReviewDiffSummary(reviewDiff)}${renderAdminReviewDiffSection("世界书变化", "fa-scroll", reviewDiff.worldbook, "worldbook")}${renderAdminReviewDiffSection("正则变化", "fa-code", reviewDiff.regex, "regex")}` : `${renderDetailSection("世界书条目", "fa-scroll", entries, renderDetailEntry, "无世界书内容")}${renderDetailSection("正则列表", "fa-code", regexEntries, renderRegexEntry, "无正则内容")}`;',
  '    const description = String(reviewProjectData.description || "暂无项目简介").trim() || "暂无项目简介";',
  '    const precautions = String(reviewProjectData.precautions || "").trim();',
  '    const conflictResolution = await loadProjectOriginalConflictItems(reviewProjectData);',
  '    const originalConflictReviewHtml = reviewProjectData?.conflictsWithOriginal && conflictResolution.requestedIds.length ? `<section class="admin-review-original-conflicts"><div class="admin-review-section-title"><i class="fas fa-shield-halved"></i><span>声明冲突的原版条目</span><strong>${conflictResolution.requestedIds.length} 项</strong></div>${conflictResolution.items.length ? `<ul class="detail-original-conflict-list">${conflictResolution.items.map(item => `<li><i class="fas fa-book"></i><span>${escapeHtml(item?.displayName || "原版条目")}</span></li>`).join("")}</ul>` : ""}<p>${conflictResolution.complete ? "玩家安装或更新时仍会被明确询问是否由 Workshop 帮忙关闭；不会直接修改。" : "当前无法完整解析 Creator 选择的条目。审核时请注意；安装端会 fail-closed，不会允许自动关闭未完整确认的列表。"}</p></section>` : "";',
  '    const orderedQueueProjects = getAdminReviewQueueProjects(queueOverlay, queueProjects);',
  '    const currentQueueIndex = orderedQueueProjects.findIndex(item => String(item.id) === String(project.id));',
  '    const canPrev = currentQueueIndex > 0;',
  '    const canNext = currentQueueIndex >= 0 && currentQueueIndex < orderedQueueProjects.length - 1;',
  '    const bodyHtml = [',
  '      `<div class="admin-review-detail-shell">`,',
  '      `<header class="detail-project-header admin-review-project-header">`,',
  '      `<div class="admin-review-project-headline"><div><div class="detail-project-name">${escapeHtml(reviewProjectData.name || "未命名项目")}</div><div class="detail-identity-row"><span>${escapeHtml(getAuthorName(reviewProjectData))}</span><span class="detail-identity-separator">·</span><span class="detail-type-label">${escapeHtml(getBaseTag(reviewProjectData))}</span></div></div><div class="admin-review-detail-signals">${renderAdminInspectionSignals(entries, regexEntries)}</div></div>`,',
  '      `</header>`,',
  '      `<div class="admin-review-detail-scroll">`,',
  '      `<main class="admin-review-detail-main">`,',
  '      `<details class="admin-review-description"><summary><span><i class="fas fa-align-left"></i> 项目简介</span><span class="admin-review-description-hint">点击展开 / 收起</span></summary><div class="admin-review-description-body">${escapeHtml(description)}</div></details>`,',
  '      precautions ? `<details class="admin-review-description" open><summary><span><i class="fas fa-triangle-exclamation"></i> 安装注意事项</span><span class="admin-review-description-hint">Creator 提供 · 纯文本</span></summary><div class="admin-review-description-body" style="white-space:pre-line">${escapeHtml(precautions)}</div></details>` : "",',
  '      originalConflictReviewHtml,',
  '      renderExternalLinksPanel(entries, regexEntries, { title: "审核外链", notice: "静态检测结果，仅供审核定位；未访问、未验证这些 URL 的远端内容。" }),',
  '      contentReviewHtml,',
  '      `</main></div>`,',
  '      `<div class="admin-review-workflow-bar">`,',
  '      `<div class="admin-review-workflow-progress"><strong>${currentQueueIndex >= 0 ? currentQueueIndex + 1 : 1}/${Math.max(orderedQueueProjects.length, 1)}</strong><span>连续审核</span></div>`,',
  '      `<div class="admin-review-workflow-nav"><button class="btn btn-outline" type="button" data-admin-review-back aria-label="返回队列" title="返回队列"><i class="fas fa-list"></i></button><button class="btn btn-outline" type="button" data-admin-review-prev aria-label="上一个" title="上一个" ${canPrev ? "" : "disabled"}><i class="fas fa-chevron-left"></i></button><button class="btn btn-outline" type="button" data-admin-review-next aria-label="下一个" title="下一个" ${canNext ? "" : "disabled"}><i class="fas fa-chevron-right"></i></button></div>`,',
  '      `<div class="admin-review-workflow-decisions"><button class="btn admin-review-reject-btn" type="button" data-admin-review-submit="reject"><i class="fas fa-xmark"></i> 拒绝</button><button class="btn admin-review-approve-btn" type="button" data-admin-review-submit="approve"><i class="fas fa-check"></i> 批准</button></div>`,',
  '      `</div></div>`,',
  '    ].join("");',
  '    const overlay = openModal(bodyHtml, `<i class="fas fa-clipboard-check"></i> 审核详情`);',
  '    overlay.classList.add("admin-review-detail-overlay");',
  '    overlay.querySelector(".modal-content")?.classList.add("admin-review-detail-modal");',
  '    bindAdminReviewEntryToggles(overlay);',
  '    if (isDiffReview) bindAdminReviewDiffLazyContent(overlay, reviewDiff);',
  '    overlay.querySelector("[data-admin-review-back]")?.addEventListener("click", () => overlay.remove());',
  '    const openAdjacent = direction => {',
  '      const adjacent = getAdminReviewAdjacentProject(queueOverlay, queueProjects, project.id, direction);',
  '      if (!adjacent) return;',
  '      overlay.remove();',
  '      openAdminReviewDetail(adjacent, queueOverlay, queueProjects);',
  '    };',
  '    overlay.querySelector("[data-admin-review-prev]")?.addEventListener("click", () => openAdjacent(-1));',
  '    overlay.querySelector("[data-admin-review-next]")?.addEventListener("click", () => openAdjacent(1));',
  '    overlay.querySelectorAll("[data-admin-review-submit]").forEach(button => {',
  '      button.addEventListener("click", async () => {',
  '        const action = button.dataset.adminReviewSubmit;',
  '        if (action !== "approve" && action !== "reject") return;',
  '        if (action === "approve" && !confirm(`确定批准「${reviewProjectData.name || "该项目"}」吗？`)) return;',
  '        let rejectReason;',
  '        if (action === "reject") {',
  "          rejectReason = prompt('请输入拒绝原因');",
  '          if (!rejectReason) return;',
  '        }',
  '        const restore = setButtonLoading(button, action === "approve" ? "批准中" : "拒绝中");',
  '        try {',
  '          const orderedBefore = getAdminReviewQueueProjects(queueOverlay, queueProjects);',
  '          const currentIndex = orderedBefore.findIndex(item => String(item.id) === String(project.id));',
  '          await reviewProject(project.id, { action, ...(rejectReason ? { rejectReason } : {}), expectedRevision: project?.draftRevision || reviewProjectData?.draftRevision });',
  "          showToast(action === 'approve' ? '已批准' : '已拒绝');",
  '          overlay.remove();',
  '          removeAdminReviewQueueProject(queueOverlay, queueProjects, project.id);',
  '          await fetchProjects(true).catch(error => console.warn("刷新项目列表失败，继续审核队列", error));',
  '          const queueSort = queueOverlay?.dataset.reviewSort || "oldest";',
  '          const queueProjectType = queueOverlay?.dataset.reviewProjectType || "";',
  '          const refreshedQueue = await fetchPendingProjects({ sort: queueSort, projectType: queueProjectType }).catch(error => { console.warn("刷新审核队列失败，沿用当前列表", error); return null; });',
  '          if (refreshedQueue) {',
  '            const refreshedProjects = Array.isArray(refreshedQueue.projects) ? refreshedQueue.projects : [];',
  '            const liveIds = new Set(refreshedProjects.map(item => String(item.id)));',
  '            queueOverlay?.querySelectorAll?.("[data-review-card]").forEach(card => { if (!liveIds.has(String(card.dataset.projectId))) card.remove(); });',
  '            if (Array.isArray(queueProjects)) queueProjects.splice(0, queueProjects.length, ...refreshedProjects);',
  '            refreshAdminReviewPositions(queueOverlay);',
  '            const queueCount = queueOverlay?.querySelector(".admin-review-queue-summary strong");',
  '            if (queueCount) queueCount.textContent = String(Number(refreshedQueue.total ?? refreshedProjects.length));',
  '          }',
  '          const remaining = getAdminReviewQueueProjects(queueOverlay, queueProjects);',
  '          if (remaining.length > 0) {',
  '            const nextIndex = currentIndex >= 0 && currentIndex < remaining.length ? currentIndex : 0;',
  '            openAdminReviewDetail(remaining[nextIndex], queueOverlay, queueProjects);',
  '          } else {',
  '            const sort = queueOverlay?.dataset.reviewSort || "oldest";',
  '            const projectType = queueOverlay?.dataset.reviewProjectType || "";',
  '            queueOverlay.remove();',
  '            openAdminPanel({ sort, projectType });',
  '          }',
  '        } catch (error) {',
  "          showToast(error.message, 'error');",
  '        } finally { restore(); }',
  '      });',
  '    });',
  '  } catch (error) {',
  '    loadingOverlay.remove();',
  "    showToast('加载审核详情失败: ' + error.message, 'error');",
  '  }',
  '}',
  '',

  "function renderAdminReviewQueueContents(pending, total, sort, projectType) {",
  "  const typeOptions = ['', '角色', '系统核心', '扩展', '事件'];",
  "  const toolbarHtml = `<div class=\"admin-review-toolbar\"><div class=\"admin-review-toolbar-main\"><label class=\"admin-review-sort-control\"><span>排序</span><select data-admin-review-sort><option value=\"oldest\" ${sort === 'oldest' ? 'selected' : ''}>最旧优先</option><option value=\"latest\" ${sort === 'latest' ? 'selected' : ''}>最新优先</option></select></label><div class=\"admin-review-type-filters\">${typeOptions.map(type => `<button type=\"button\" class=\"admin-review-filter-btn ${type === projectType ? 'active' : ''}\" data-admin-review-type=\"${escapeHtml(type)}\">${escapeHtml(type || '全部')}</button>`).join('')}</div></div><button type=\"button\" class=\"btn btn-outline admin-review-cleanup-btn\" data-admin-review-cleanup><i class=\"fas fa-broom\"></i><span>清理过期请求</span></button></div>`;",
  "  const summaryHtml = `<div class=\"admin-review-queue-summary\"><div><strong>${total}</strong> 个项目等待审核<span>点卡片可直接查看</span></div><button type=\"button\" class=\"btn btn-primary admin-review-start-btn\" data-admin-review-start ${pending.length ? '' : 'disabled'}><i class=\"fas fa-play\"></i> 开始审查</button></div>`;",
  "  const listHtml = pending.length ? `<div class=\"admin-review-list\">${pending.map((project, index) => renderAdminReviewCard(project, index, pending.length)).join('')}</div>` : `<div class=\"empty-state\"><i class=\"fas fa-circle-check\"></i><div>当前筛选下暂无待审核项目</div></div>`;",
  "  return `${toolbarHtml}${summaryHtml}${listHtml}`;",
  "}",
  "",
  'async function openAdminPanel(options = {}) {',
  '  if (!state.currentUser?.isAdmin) {',
  "    showToast('无权限', 'error');",
  '    return;',
  '  }',
  '  let currentSort = options.sort === "latest" ? "latest" : "oldest";',
  '  let currentProjectType = BASE_TAGS.includes(options.projectType) ? options.projectType : "";',
  '  try {',
  '    const data = await fetchPendingProjects({ sort: currentSort, projectType: currentProjectType });',
  '    let currentPending = data.projects || [];',
  '    let currentTotal = Number(data.total ?? currentPending.length);',
  '    const html = `<div class="admin-review-queue">${renderAdminReviewQueueContents(currentPending, currentTotal, currentSort, currentProjectType)}</div>`;',
  "    const overlay = openModal(html, '<i class=\"fas fa-clipboard-check\"></i> 审核中心');",
  '    overlay.classList.add("admin-review-overlay");',
  '    overlay.dataset.reviewSort = currentSort;',
  '    overlay.dataset.reviewProjectType = currentProjectType;',
  '    let refreshSequence = 0;',
  '    overlay.querySelector(".modal-content")?.classList.add("admin-review-modal");',
  "    function setAdminReviewQueueBusy(busy) {",
  "      overlay.classList.toggle('is-refreshing', busy);",
  "      overlay.setAttribute('aria-busy', busy ? 'true' : 'false');",
  "      overlay.querySelectorAll('[data-admin-review-sort],[data-admin-review-type],[data-admin-review-start],[data-admin-review-cleanup],[data-action]').forEach(control => { control.disabled = busy; });",
  "    }",
  "",
  "    function bindAdminReviewQueueInteractions() {",
  "      overlay.querySelector('[data-admin-review-sort]')?.addEventListener('change', event => {",
  "        const nextSort = event.target?.value === 'latest' ? 'latest' : 'oldest';",
  "        if (nextSort === currentSort) return;",
  "        refreshAdminReviewQueue(nextSort, currentProjectType);",
  "      });",
  "      overlay.querySelectorAll('[data-admin-review-type]').forEach(button => {",
  "        button.addEventListener('click', () => {",
  "          const nextType = button.dataset.adminReviewType || '';",
  "          if (nextType === currentProjectType) return;",
  "          refreshAdminReviewQueue(currentSort, nextType);",
  "        });",
  "      });",
  "      overlay.querySelectorAll('button[data-action]').forEach(button => {",
  "        button.addEventListener('click', () => {",
  "          const projectId = button.dataset.id;",
  "          const project = currentPending.find(item => String(item.id) === String(projectId));",
  "          if (!projectId || !project) return;",
  "          skipAdminReviewCard(overlay, projectId);",
  "        });",
  "      });",
  "      overlay.querySelector('[data-admin-review-start]')?.addEventListener('click', () => {",
  "        const firstCard = overlay.querySelector('[data-review-card]');",
  "        const project = firstCard ? currentPending.find(item => String(item.id) === String(firstCard.dataset.projectId)) : null;",
  "        if (project) openAdminReviewDetail(project, overlay, currentPending);",
  "      });",
  "      overlay.querySelector('[data-admin-review-cleanup]')?.addEventListener('click', async event => {",
  "        const button = event.currentTarget;",
  "        if (!button || button.disabled) return;",
  "        if (!confirm('清理已经被新版本取代的旧审核请求？这些记录会保留在历史中。')) return;",
  "        const restore = setButtonLoading(button, '清理中');",
  "        try {",
  "          const result = await cleanupOutdatedReviewDrafts();",
  "          const cleanedCount = Number(result?.cleanedCount || 0);",
  "          showToast(cleanedCount > 0 ? `已清理 ${cleanedCount} 条过期请求` : '没有需要清理的过期请求', cleanedCount > 0 ? 'success' : 'info');",
  "          await refreshAdminReviewQueue(currentSort, currentProjectType);",
  "        } catch (error) {",
  "          showToast('清理过期请求失败: ' + error.message, 'error');",
  "        } finally {",
  "          restore();",
  "        }",
  "      });",
  "      overlay.querySelectorAll('[data-review-card]').forEach(card => {",
  "        const openFromCard = event => {",
  "          if (event?.target?.closest?.('button, select')) return;",
  "          const project = currentPending.find(item => String(item.id) === String(card.dataset.projectId));",
  "          if (project) openAdminReviewDetail(project, overlay, currentPending);",
  "        };",
  "        card.addEventListener('click', openFromCard);",
  "        card.addEventListener('keydown', event => {",
  "          if (event.key !== 'Enter' && event.key !== ' ') return;",
  "          event.preventDefault();",
  "          openFromCard(event);",
  "        });",
  "      });",
  "    }",
  "",
  "    async function refreshAdminReviewQueue(nextSort, nextProjectType) {",
  "      const sequence = ++refreshSequence;",
  "      const scrollContainer = overlay.querySelector('.modal-body');",
  "      const previousScrollTop = Number(scrollContainer?.scrollTop || 0);",
  "      setAdminReviewQueueBusy(true);",
  "      try {",
  "        const nextData = await fetchPendingProjects({ sort: nextSort, projectType: nextProjectType });",
  "        if (!overlay.isConnected || sequence !== refreshSequence) return;",
  "        const nextPending = nextData.projects || [];",
  "        const nextTotal = Number(nextData.total ?? nextPending.length);",
  "        const queue = overlay.querySelector('.admin-review-queue');",
  "        if (!queue) return;",
  "        currentSort = nextSort;",
  "        currentProjectType = nextProjectType;",
  "        currentPending = nextPending;",
  "        currentTotal = nextTotal;",
  "        overlay.dataset.reviewSort = currentSort;",
  "        overlay.dataset.reviewProjectType = currentProjectType;",
  "        queue.innerHTML = renderAdminReviewQueueContents(currentPending, currentTotal, currentSort, currentProjectType);",
  "        bindCoverImageFallbacks(queue);",
  "        bindAdminReviewQueueInteractions();",
  "        if (scrollContainer) scrollContainer.scrollTop = previousScrollTop;",
  "      } catch (error) {",
  "        if (sequence !== refreshSequence) return;",
  "        const sortControl = overlay.querySelector('[data-admin-review-sort]');",
  "        if (sortControl) sortControl.value = currentSort;",
  "        overlay.querySelectorAll('[data-admin-review-type]').forEach(button => button.classList.toggle('active', (button.dataset.adminReviewType || '') === currentProjectType));",
  "        showToast('审核队列刷新失败: ' + error.message, 'error');",
  "      } finally {",
  "        if (sequence === refreshSequence && overlay.isConnected) setAdminReviewQueueBusy(false);",
  "      }",
  "    }",
  "",
  "    bindAdminReviewQueueInteractions();",
  '  } catch (error) {',
  "    showToast(error.message, 'error');",
  '  }',
  '}',
  '',
].join('\n');
