export const homeAdminToolsModalScript = [
'async function openAdminLogsModal() {',
  '  if (!state.currentUser?.isSuperAdmin) {',
  "    showToast('无权限', 'error');",
  '    return;',
  '  }',
  '  try {',
  '    const data = await fetchAdminLogs();',
  '    const logs = data.logs || [];',
  '    const actionLabels = { project_approved: "批准项目", project_rejected: "拒绝项目", admin_added: "添加管理员", admin_removed: "移除管理员" };',
  '    const html = logs.length ? logs.map(log => {',
  '      let detail = {};',
  '      try { detail = log.detail ? JSON.parse(log.detail) : {}; } catch { detail = {}; }',
  '      const actionLabel = actionLabels[log.action] || log.action;',
  '      const projectName = detail.projectName ? `<strong>${escapeHtml(detail.projectName)}</strong>` : escapeHtml(log.targetType || "操作记录");',
  '      const rejectHtml = detail.rejectReason ? `<div class="admin-log-reason"><strong>拒绝原因：</strong>${escapeHtml(detail.rejectReason)}</div>` : "";',
  '      const traceRows = [',
  '        ["目标 ID", log.targetId],',
  '        ["修订号", detail.draftRevision],',
  '        ["审核目标", detail.reviewTarget],',
  '        ["发布项目 ID", detail.publishedProjectId],',
  '        ["项目创建", detail.projectCreatedAt ? formatDateTime(detail.projectCreatedAt) : null],',
  '        ["项目更新", detail.projectUpdatedAt ? formatDateTime(detail.projectUpdatedAt) : null],',
  '        ["版本变化", detail.previousVersion && detail.version ? `${detail.previousVersion} → ${detail.version}` : detail.version],',
  '        ["版本备注", detail.versionLabel],',
  '      ].filter(([, value]) => value !== undefined && value !== null && value !== "");',
  '      const traceHtml = traceRows.length ? `<details class="admin-log-trace"><summary>追踪信息</summary>${traceRows.map(([label, value]) => `<div><span>${escapeHtml(label)}</span><code>${escapeHtml(String(value))}</code></div>`).join("")}</details>` : "";',
  '      return `<div class="admin-card admin-log-card"><div class="admin-log-head"><div><div class="admin-card-title">${escapeHtml(actionLabel)}</div><div>${projectName}</div></div><time>${escapeHtml(formatDateTime(log.createdAt))}</time></div><div class="admin-log-actor"><i class="fas fa-user-shield"></i> ${escapeHtml(log.actorName)} (${escapeHtml(log.actorId)})</div>${rejectHtml}${traceHtml}</div>`;',
  '    }).join("") : "<p>暂无日志</p>";',
  '    openModal(`<h3>管理员操作日志</h3>${html}`, `<i class=\\"fas fa-clock-rotate-left\\"></i> 操作日志`);',
  '  } catch (error) {',
  "    showToast('加载管理员日志失败: ' + (error && error.message ? error.message : '未知错误'), 'error');",
  '  }',
  '}',
  '',
  'async function openAddAdminModal() {',
  '  if (!state.currentUser?.isSuperAdmin) {',
  "    showToast('无权限', 'error');",
  '    return;',
  '  }',
  '  let admins = [];',
  '  try {',
  '    const data = await fetchAdminList();',
  '    admins = data.admins || [];',
  '  } catch (error) {',
  "    showToast('加载管理员列表失败: ' + (error && error.message ? error.message : '未知错误'), 'error');",
  '  }',
  '  const adminsHtml = admins.length',
  '    ? admins.map(admin => {',
  '        return \'<div class="admin-list-item">\'',
  "          + '<div><img src=\"' + escapeHtml(admin.avatarUrl || 'https://cdn.discordapp.com/embed/avatars/0.png') + '\" style=\"width:32px; height:32px; border-radius:50%; margin-right:8px; vertical-align:middle;\">'",
  "          + escapeHtml(admin.globalName || admin.username) + ' (' + escapeHtml(admin.id) + ')</div>'",
  '          + \'<button class="btn" data-id="\' + admin.id + \'" data-action="remove">移除管理员</button>\'',
  "          + '</div>';",
  "      }).join('')",
  "    : '<p>暂无管理员</p>';",
  '  const overlay = openModal(',
  '    [',
  "      '<div>',",
  "      '<h3>添加管理员</h3>',",
  '      \'<input type="text" id="targetUserId" placeholder="用户ID" style="width:100%; padding:8px; margin-bottom:16px;">\',',
  '      \'<button class="btn btn-primary" id="confirmAdd">设为管理员</button>\',',
  '      \'<hr style="margin:20px 0;">\',',
  "      '<h3>现有管理员列表</h3>',",
  "      '<div id=\"adminListContainer\">' + adminsHtml + '</div>',",
  "      '</div>',",
  "    ].join(''),",
  '    \'<i class="fas fa-user-shield"></i> 管理员设置\',',
  '  );',
  "  overlay.querySelector('#confirmAdd').onclick = async () => {",
  "    const targetId = overlay.querySelector('#targetUserId').value.trim();",
  '    if (!targetId) return;',
  '    try {',
  '      await setAdmin(targetId, true);',
  "      showToast('已设为管理员');",
  '      overlay.remove();',
  '      openAddAdminModal();',
  '    } catch (error) {',
  "      showToast(error.message, 'error');",
  '    }',
  '  };',
  '  overlay.querySelectorAll(\'button[data-action="remove"]\').forEach(button => {',
  "    button.addEventListener('click', async () => {",
  '      const userId = button.dataset.id;',
  "      if (!userId || !confirm('确定要移除该管理员吗？')) return;",
  '      try {',
  '        await setAdmin(userId, false);',
  "        showToast('已移除管理员');",
  '        overlay.remove();',
  '        openAddAdminModal();',
  '      } catch (error) {',
  "        showToast(error.message, 'error');",
  '      }',
  '    });',
  '  });',
  '}',
].join('\n');
