export const homeModalCoreScript = [
'function openModal(contentHtml, titleHtml) {',
  '  const resolvedTitle = titleHtml || \'<i class="fas fa-pen"></i> 操作\';',
  "  const overlay = document.createElement('div');",
  "  overlay.className = 'modal-overlay';",
  '  overlay.style.zIndex = String(9999 + document.querySelectorAll(".modal-overlay").length);',
  '  overlay.innerHTML = [',
  '    \'<div class="modal-content">\',',
  '    \'  <div class="modal-header">\',',
  "    '    <h2>' + resolvedTitle + '</h2>',",
  '    \'    <button class="close-btn" type="button"><i class="fas fa-times"></i></button>\',',
  "    '  </div>',",
  "    '  <div class=\"modal-body\">' + contentHtml + '</div>',",
  "    '</div>',",
  "  ].join('');",
  '  const requestClose = () => {',
  "    if (overlay.dataset.dirty === 'true' && !confirm('有未保存的修改，确定放弃吗？')) return false;",
  '    overlay.remove();',
  '    return true;',
  '  };',
  "  overlay.addEventListener('click', event => {",
  "    if (event.target === overlay && overlay.dataset.dirty === 'true' && !confirm('有未保存的修改，确定放弃吗？')) event.stopImmediatePropagation();",
  '  }, true);',
  "  overlay.addEventListener('input', event => { if (event.target.closest('form')) overlay.dataset.dirty = 'true'; });",
  "  overlay.addEventListener('change', event => { if (event.target.closest('form')) overlay.dataset.dirty = 'true'; });",
  "  overlay.addEventListener('click', event => {",
  '    if (event.target === overlay) {',
  '      overlay.remove();',
  '    }',
  '  });',
  "  overlay.querySelector('.close-btn').addEventListener('click', requestClose);",
  '  document.body.appendChild(overlay);',
  '  bindCoverImageFallbacks(overlay);',
  '  bindSafeExternalLinkButtons(overlay);',
  '  return overlay;',
  '}',
  '',
  'function bindSafeExternalLinkButtons(root) {',
  '  if (!root?.querySelectorAll) return;',
  '  root.querySelectorAll("[data-external-url]").forEach(button => {',
  '    if (button.dataset.externalUrlBound === "1") return;',
  '    button.dataset.externalUrlBound = "1";',
  '    button.addEventListener("click", event => {',
  '      event.preventDefault();',
  '      event.stopPropagation();',
  '      openExternalLinkWarning(button.dataset.externalUrl || "");',
  '    });',
  '  });',
  '}',
  '',
  'function openExternalLinkWarning(rawUrl) {',
  '  const url = normalizeExternalHttpUrl(rawUrl);',
  '  if (!url) { showToast("链接格式无效，已阻止操作。", "warning"); return null; }',
  '  let hostname = "外部网站";',
  '  try { hostname = new URL(url).hostname || hostname; } catch {}',
  '  const bodyHtml = `<div class="external-link-warning"><div class="external-link-warning-icon"><i class="fas fa-triangle-exclamation"></i></div><div class="external-link-warning-copy"><strong>这是创作者提供的外部链接</strong><p>创意工坊不会自动打开，也没有验证目标页面的内容。请复制链接后自行决定是否访问。</p><span class="external-link-warning-host">${escapeHtml(hostname)}</span><code>${escapeHtml(url)}</code></div><div class="external-link-warning-actions"><button class="btn btn-outline external-link-warning-cancel" type="button">取消</button><button class="btn btn-primary external-link-warning-copy-btn" type="button"><i class="fas fa-copy"></i> 复制链接</button></div></div>`;',
  '  const warningOverlay = openModal(bodyHtml, `<i class="fas fa-shield-halved"></i> 外部链接`);',
  '  warningOverlay.classList.add("external-link-warning-modal");',
  '  const cancelButton = warningOverlay.querySelector(".external-link-warning-cancel");',
  '  if (cancelButton) cancelButton.addEventListener("click", () => warningOverlay.remove());',
  '  const copyButton = warningOverlay.querySelector(".external-link-warning-copy-btn");',
  '  if (copyButton) copyButton.addEventListener("click", async () => {',
  '    const copied = await copyTextToClipboard(url);',
  '    if (!copied) { showToast("浏览器禁止自动复制，请手动选择链接复制。", "warning"); return; }',
  '    warningOverlay.remove();',
  '    showToast("链接已复制，请自行决定是否打开。", "info");',
  '  });',
  '  return warningOverlay;',
  '}',
  '',
  "function openInstalledProjectRebindModal(installedProjectId) {",
  "  const match = getInstalledProjectRebindCandidate(installedProjectId);",
  "  if (!match?.projects?.length) { showToast('暂时没有找到可确认的工坊项目', 'warning'); return null; }",
  "  const localProject = state.tavern.installedProjects.find(project => String(project?.installedProjectId || project?.projectId || '') === match.installedProjectId);",
  "  const choices = match.projects.map(project => {",
  "    const author = getAuthorName(project);",
  "    const version = project?.versionLabel || project?.version || '';",
  "    return `<button class=\"repair-project-choice\" type=\"button\" data-rebind-project-choice=\"${escapeHtml(project.id)}\"><span class=\"repair-project-choice-copy\"><strong>${escapeHtml(project.name || '未命名项目')}</strong><small>${escapeHtml(author)}${version ? ` · ${escapeHtml(String(version))}` : ''}</small></span><span class=\"repair-project-choice-action\"><i class=\"fas fa-circle-check\"></i> 确认是这个</span></button>`;",
  "  }).join('');",
  "  const bodyHtml = `<div class=\"repair-match-box candidates\"><p>本机已经安装了「${escapeHtml(localProject?.projectNameHint || localProject?.name || '这个项目')}」，但原来的工坊记录已经找不到。请确认下面哪个才是现在的项目。</p><div class=\"repair-project-candidates\">${choices}</div><p class=\"repair-muted\">只有你确认后，工坊才会把这个本地安装与新的项目对应起来。</p></div>`;",
  "  const overlay = openModal(bodyHtml, '<i class=\"fas fa-link\"></i> 确认对应项目');",
  "  overlay.querySelectorAll('[data-rebind-project-choice]').forEach(button => {",
  "    button.addEventListener('click', () => {",
  "      const remoteProject = match.projects.find(project => project?.id === button.dataset.rebindProjectChoice);",
  "      if (!remoteProject || !confirmInstalledProjectRebind(match.installedProjectId, remoteProject)) {",
  "        showToast('无法确认这个项目，请重新打开后再试', 'warning');",
  "        return;",
  "      }",
  "      overlay.remove();",
  "      renderApp();",
  "      showToast('已确认「' + (remoteProject.name || '项目') + '」，后续更新和卸载会继续识别原本安装的内容');",
  "    });",
  "  });",
  "  return overlay;",
  "}",
  "",
  'function openReleaseNoticeModal() {',
  '  const existing = document.querySelector("[data-workshop-release-modal]");',
  '  if (existing) return existing;',
  '  const migrationNotes = (WORKSHOP_CONFIG.client.migrations || [])',
  '    .filter(item => item?.beforeVersion && compareWorkshopVersions(state.tavern.clientVersion, item.beforeVersion) < 0)',
  '    .map(item => `<li class="release-update-migration-note">${escapeHtml(item.message || "")}</li>`)',
  '    .join("");',
  '  const bodyHtml = `',
  '    <div class="release-update-guide">',
  '      <p class="release-update-lead"><strong>Creative Workshop 版本过旧，请先更新。</strong></p>',
  '      <p>当前版本：<strong>v${escapeHtml(state.tavern.clientVersion || "未知")}</strong> → 最新版本：<strong>v${WORKSHOP_STABLE_CLIENT_VERSION}</strong></p>',
  '      <ol class="release-update-steps">',
  '        <li>回到 <strong>SillyTavern → 酒馆助手</strong>。</li>',
  '        <li>找到「命定创意工坊」脚本。</li>',
  '        <li>在现有 <code>import</code> 地址里，把 <code>@</code> 后面的版本号改成 <strong>${WORKSHOP_STABLE_CLIENT_VERSION}</strong>。</li>',
  '        ${migrationNotes}',
  '        <li>保存并刷新 SillyTavern，然后重新打开创意工坊。</li>',
  '      </ol>',
  '      <p class="release-update-version-warning"><strong>宝宝们，记得自己改版本号～知道了吗？</strong></p>',
  '      <div class="release-update-actions">',
  '        <button class="btn btn-outline" id="releaseUpdateAcknowledgeBtn" type="button">我记住了喵</button>',
  '        <button class="release-update-look-again" id="releaseUpdateLookAgainBtn" type="button">我要再看一眼喵</button>',
  '      </div>',
  '    </div>',
  '  `;',
  '  const overlay = openModal(bodyHtml, `<i class="fas fa-rotate"></i> Creative Workshop 更新提醒`);',
  '  overlay.dataset.workshopReleaseModal = "true";',
  '  overlay.querySelector(".close-btn")?.remove();',
  '  overlay.addEventListener("click", event => { if (event.target === overlay) event.stopImmediatePropagation(); }, true);',
  '  overlay.querySelector("#releaseUpdateAcknowledgeBtn")?.addEventListener("click", () => requestCloseWorkshop());',
  '  overlay.querySelector("#releaseUpdateLookAgainBtn")?.addEventListener("click", () => showToast("可以唷～那再看一眼", "warning"));',
  '  return overlay;',
  '}',
  '',
  "function openScriptDependencyHealthModal() {",
  "  const health = getScriptDependencyHealthSummary();",
  "  const outdated = Array.isArray(health?.outdated) ? health.outdated : [];",
  "  if (!outdated.length) { showToast('当前没有其他脚本需要更新'); return null; }",
  "  const rows = outdated.map(item => {",
  "    const installed = item?.installedVersion ? `v${item.installedVersion}` : '未知版本';",
  "    const latest = item?.latestVersion ? `v${item.latestVersion}` : '最新版';",
  "    const name = item?.dependencyName || item?.scriptName || '脚本';",
  "    const targetVersion = item?.latestVersion ? String(item.latestVersion) : '最新版';",
  "    return `<section class=\"dependency-health-item\"><div class=\"dependency-health-heading\"><strong>${escapeHtml(name)}</strong><span>${escapeHtml(installed)} <i class=\"fas fa-arrow-right\"></i> ${escapeHtml(latest)}</span></div><p>到酒馆助手找到这个脚本，在现有 import 地址里把 @ 后面的版本号改成 <strong>${escapeHtml(targetVersion)}</strong>，保存并刷新。</p></section>`;",
  "  }).join('');",
  "  return openModal(`<div class=\"dependency-health-list\">${rows}</div>`, '<i class=\"fas fa-circle-up\"></i> 其他脚本有更新');",
  "}",
  "",
  'function setButtonLoading(button, pendingText) {',
  '  if (!button) return () => {};',
  '  const originalHtml = button.innerHTML;',
  '  button.disabled = true;',
  '  button.classList.add("is-loading");',
  '  button.innerHTML = `<span class="inline-loading-spinner"></span><span>${pendingText}</span>`;',
  '  return () => {',
  '    button.disabled = false;',
  '    button.classList.remove("is-loading");',
  '    button.innerHTML = originalHtml;',
  '  };',
  '}',
  '',
].join('\n');
