export const homeModalCoreScript = [
'function openModal(contentHtml, titleHtml) {',
  '  const resolvedTitle = titleHtml || \'<i class="fas fa-pen"></i> 操作\';',
  "  const overlay = document.createElement('div');",
  "  overlay.className = 'modal-overlay';",
  '  overlay.style.zIndex = String(9999 + document.querySelectorAll(".modal-overlay").length);',
  '  overlay.innerHTML = [',
  '    \'<div class="modal-content">\',',
  '    \'  <div class="modal-header">\',',
  "    '    <h2>' + resolvedTitle + '</h2>',",
  '    \'    <button class="close-btn" type="button"><i class="fas fa-times"></i></button>\',',
  "    '  </div>',",
  "    '  <div class=\"modal-body\">' + contentHtml + '</div>',",
  "    '</div>',",
  "  ].join('');",
  '  const requestClose = () => {',
  "    if (overlay.dataset.dirty === 'true' && !confirm('有未保存的修改，确定放弃吗？')) return false;",
  '    overlay.remove();',
  '    return true;',
  '  };',
  "  overlay.addEventListener('click', event => {",
  "    if (event.target === overlay && overlay.dataset.dirty === 'true' && !confirm('有未保存的修改，确定放弃吗？')) event.stopImmediatePropagation();",
  '  }, true);',
  "  overlay.addEventListener('input', event => { if (event.target.closest('form')) overlay.dataset.dirty = 'true'; });",
  "  overlay.addEventListener('change', event => { if (event.target.closest('form')) overlay.dataset.dirty = 'true'; });",
  "  overlay.addEventListener('click', event => {",
  '    if (event.target === overlay) {',
  '      overlay.remove();',
  '    }',
  '  });',
  "  overlay.querySelector('.close-btn').addEventListener('click', requestClose);",
  '  document.body.appendChild(overlay);',
  '  bindCoverImageFallbacks(overlay);',
  '  bindSafeExternalLinkButtons(overlay);',
  '  return overlay;',
  '}',
  '',
  'function bindSafeExternalLinkButtons(root) {',
  '  if (!root?.querySelectorAll) return;',
  '  root.querySelectorAll("[data-external-url]").forEach(button => {',
  '    if (button.dataset.externalUrlBound === "1") return;',
  '    button.dataset.externalUrlBound = "1";',
  '    button.addEventListener("click", event => {',
  '      event.preventDefault();',
  '      event.stopPropagation();',
  '      openExternalLinkWarning(button.dataset.externalUrl || "");',
  '    });',
  '  });',
  '}',
  '',
  'function openExternalLinkWarning(rawUrl) {',
  '  const url = normalizeExternalHttpUrl(rawUrl);',
  '  if (!url) { showToast("链接格式无效，已阻止操作。", "warning"); return null; }',
  '  let hostname = "外部网站";',
  '  try { hostname = new URL(url).hostname || hostname; } catch {}',
  '  const bodyHtml = `<div class="external-link-warning"><div class="external-link-warning-icon"><i class="fas fa-triangle-exclamation"></i></div><div class="external-link-warning-copy"><strong>这是创作者提供的外部链接</strong><p>创意工坊不会自动打开，也没有验证目标页面的内容。请复制链接后自行决定是否访问。</p><span class="external-link-warning-host">${escapeHtml(hostname)}</span><code>${escapeHtml(url)}</code></div><div class="external-link-warning-actions"><button class="btn btn-outline external-link-warning-cancel" type="button">取消</button><button class="btn btn-primary external-link-warning-copy-btn" type="button"><i class="fas fa-copy"></i> 复制链接</button></div></div>`;',
  '  const warningOverlay = openModal(bodyHtml, `<i class="fas fa-shield-halved"></i> 外部链接`);',
  '  warningOverlay.classList.add("external-link-warning-modal");',
  '  const cancelButton = warningOverlay.querySelector(".external-link-warning-cancel");',
  '  if (cancelButton) cancelButton.addEventListener("click", () => warningOverlay.remove());',
  '  const copyButton = warningOverlay.querySelector(".external-link-warning-copy-btn");',
  '  if (copyButton) copyButton.addEventListener("click", async () => {',
  '    const copied = await copyTextToClipboard(url);',
  '    if (!copied) { showToast("浏览器禁止自动复制，请手动选择链接复制。", "warning"); return; }',
  '    warningOverlay.remove();',
  '    showToast("链接已复制，请自行决定是否打开。", "info");',
  '  });',
  '  return warningOverlay;',
  '}',
  '',
  "function openInstalledProjectRebindModal(installedProjectId) {",
  "  const match = getInstalledProjectRebindCandidate(installedProjectId);",
  "  if (!match?.projects?.length) { showToast('暂时没有找到可确认的工坊项目', 'warning'); return null; }",
  "  const localProject = state.tavern.installedProjects.find(project => String(project?.installedProjectId || project?.projectId || '') === match.installedProjectId);",
  "  const choices = match.projects.map(project => {",
  "    const author = getAuthorName(project);",
  "    const version = project?.versionLabel || project?.version || '';",
  "    return `<button class=\"repair-project-choice\" type=\"button\" data-rebind-project-choice=\"${escapeHtml(project.id)}\"><span class=\"repair-project-choice-copy\"><strong>${escapeHtml(project.name || '未命名项目')}</strong><small>${escapeHtml(author)}${version ? ` · ${escapeHtml(String(version))}` : ''}</small></span><span class=\"repair-project-choice-action\"><i class=\"fas fa-circle-check\"></i> 确认是这个</span></button>`;",
  "  }).join('');",
  "  const bodyHtml = `<div class=\"repair-match-box candidates\"><p>本机已经安装了「${escapeHtml(localProject?.projectNameHint || localProject?.name || '这个项目')}」，但原来的工坊记录已经找不到。请确认下面哪个才是现在的项目。</p><div class=\"repair-project-candidates\">${choices}</div><p class=\"repair-muted\">只有你确认后，工坊才会把这个本地安装与新的项目对应起来。</p></div>`;",
  "  const overlay = openModal(bodyHtml, '<i class=\"fas fa-link\"></i> 确认对应项目');",
  "  overlay.querySelectorAll('[data-rebind-project-choice]').forEach(button => {",
  "    button.addEventListener('click', () => {",
  "      const remoteProject = match.projects.find(project => project?.id === button.dataset.rebindProjectChoice);",
  "      if (!remoteProject || !confirmInstalledProjectRebind(match.installedProjectId, remoteProject)) {",
  "        showToast('无法确认这个项目，请重新打开后再试', 'warning');",
  "        return;",
  "      }",
  "      overlay.remove();",
  "      renderApp();",
  "      showToast('已确认「' + (remoteProject.name || '项目') + '」，后续更新和卸载会继续识别原本安装的内容');",
  "    });",
  "  });",
  "  return overlay;",
  "}",
  "",
  'function openReleaseNoticeModal() {',
  '  const bodyHtml = `',
  '    <div class="release-update-guide">',
  '      <p class="release-update-lead">旧版 Creative Workshop 脚本可能缺少新的修复和功能。请更新到 <strong>v${WORKSHOP_RELEASE_VERSION}</strong>。</p>',
  '      <ol class="release-update-steps">',
  '        <li>点击下方按钮复制最新版导入代码。</li>',
  '        <li>回到 <strong>SillyTavern</strong>，打开 <strong>酒馆助手</strong>。</li>',
  '        <li>找到你现在使用的「命定创意工坊」脚本。</li>',
  '        <li>把旧的 <code>import ...</code> 整行替换成下面的新代码。</li>',
  '        <li>保存脚本，然后刷新 SillyTavern 或重新打开创意工坊。</li>',
  '      </ol>',
  '      <div class="release-update-codebox">',
  '        <textarea class="release-update-code" id="releaseUpdateCode" readonly spellcheck="false">${escapeHtml(WORKSHOP_RELEASE_IMPORT)}</textarea>',
  '        <button class="release-update-copy-btn" id="releaseUpdateCopyBtn" type="button" aria-label="复制导入代码"><i class="fas fa-copy"></i><span>复制</span></button>',
  '      </div>',
  '    </div>',
  '  `;',
  '  const overlay = openModal(bodyHtml, `<i class="fas fa-rotate"></i> Creative Workshop 更新指南`);',
  '  const copyBtn = overlay.querySelector("#releaseUpdateCopyBtn");',
  '  const codeField = overlay.querySelector("#releaseUpdateCode");',
  '  if (copyBtn && codeField) copyBtn.addEventListener("click", async () => {',
  '    codeField.focus();',
  '    codeField.select();',
  '    codeField.setSelectionRange(0, codeField.value.length);',
  '    let copied = false;',
  '    try { copied = document.execCommand("copy"); } catch (error) { console.warn("Selected-field copy failed", error); }',
  '    if (!copied && navigator.clipboard?.writeText) {',
  '      try {',
  '        await navigator.clipboard.writeText(codeField.value);',
  '        copied = true;',
  '      } catch (error) {',
  '        console.warn("Clipboard API unavailable", error);',
  '      }',
  '    }',
  '    if (copied) {',
  '      copyBtn.innerHTML = `<i class="fas fa-check"></i><span>已复制</span>`;',
  '      showToast("已复制。下一步：SillyTavern → 酒馆助手 → 替换旧 import → 保存并刷新。");',
  '    } else {',
  '      showToast("浏览器禁止自动复制，代码已经选中，请长按或右键复制。", "warning");',
  '    }',
  '  });',
  '}',
  '',
  "function openScriptDependencyHealthModal() {",
  "  const health = getScriptDependencyHealthSummary();",
  "  const outdated = Array.isArray(health?.outdated) ? health.outdated : [];",
  "  if (!outdated.length) { showToast('当前没有已知脚本依赖需要更新'); return null; }",
  "  const rows = outdated.map((item, index) => {",
  "    const installed = item?.installedVersion ? `v${item.installedVersion}` : '未知版本';",
  "    const latest = item?.latestVersion ? `v${item.latestVersion}` : '最新版';",
  "    const name = item?.dependencyName || item?.scriptName || '脚本依赖';",
  "    const suggestedUrl = getScriptDependencySuggestedImport(item);",
  "    const updateCode = suggestedUrl ? `import '${suggestedUrl}'` : '';",
  "    const codeHtml = updateCode",
  "      ? `<div class=\"release-update-codebox dependency-update-codebox\"><textarea class=\"release-update-code dependency-update-code\" readonly spellcheck=\"false\">${escapeHtml(updateCode)}</textarea><button class=\"release-update-copy-btn\" type=\"button\" data-dependency-copy=\"${index}\" aria-label=\"复制新版 import\"><i class=\"fas fa-copy\"></i><span>复制</span></button></div>`",
  "      : '<p class=\"dependency-health-note\">当前 import 不是可安全自动改写的已知 URL，请手动检查该脚本的发布页。</p>';",
  "    return `<section class=\"dependency-health-item\"><div class=\"dependency-health-heading\"><strong>${escapeHtml(name)}</strong><span>${escapeHtml(installed)} <i class=\"fas fa-arrow-right\"></i> ${escapeHtml(latest)}</span></div><p>Workshop 只检测到版本较旧，不会自动修改你的酒馆助手脚本。</p>${codeHtml}</section>`;",
  "  }).join('');",
  "  const overlay = openModal(`<div class=\"dependency-health-list\">${rows}</div>`, '<i class=\"fas fa-circle-up\"></i> 脚本依赖可更新');",
  "  overlay.querySelectorAll('[data-dependency-copy]').forEach(button => {",
  "    button.addEventListener('click', async () => {",
  "      const container = button.closest('.dependency-update-codebox');",
  "      const field = container?.querySelector('.dependency-update-code');",
  "      if (!field) return;",
  "      field.focus();",
  "      field.select();",
  "      field.setSelectionRange(0, field.value.length);",
  "      let copied = false;",
  "      try { copied = document.execCommand('copy'); } catch (error) { console.warn('Dependency import copy failed', error); }",
  "      if (!copied && navigator.clipboard?.writeText) {",
  "        try { await navigator.clipboard.writeText(field.value); copied = true; } catch (error) { console.warn('Clipboard API unavailable', error); }",
  "      }",
  "      if (copied) { button.innerHTML = '<i class=\"fas fa-check\"></i><span>已复制</span>'; showToast('已复制新版 import。替换旧 import 后保存并刷新 SillyTavern。'); }",
  "      else showToast('浏览器禁止自动复制，代码已经选中，请长按复制。', 'warning');",
  "    });",
  "  });",
  "  return overlay;",
  "}",
  "",
  'function setButtonLoading(button, pendingText) {',
  '  if (!button) return () => {};',
  '  const originalHtml = button.innerHTML;',
  '  button.disabled = true;',
  '  button.classList.add("is-loading");',
  '  button.innerHTML = `<span class="inline-loading-spinner"></span><span>${pendingText}</span>`;',
  '  return () => {',
  '    button.disabled = false;',
  '    button.classList.remove("is-loading");',
  '    button.innerHTML = originalHtml;',
  '  };',
  '}',
  '',
].join('\n');
