export const homeProjectDetailModalScript = [
'async function showProjectDetail(project) {',
  '  const loadingOverlay = openModal(\'<div class="detail-loading"><div class="loading-spinner"></div><div class="detail-loading-text">正在加载项目详情...</div></div>\', \'<i class="fas fa-info-circle"></i> 项目详情\');',
  '  loadingOverlay.classList.add("project-detail-modal");',
  '  try {',
  '    const detail = await fetchProjectEntries(project);',
  '    const detailProject = detail.project || project;',
  '    if (detailProject?.conflictsWithOriginal && Array.isArray(detailProject?.originalConflictReferenceItemIds) && detailProject.originalConflictReferenceItemIds.length) {',
  '      const conflictResolution = await loadProjectOriginalConflictItems(detailProject);',
  '      detail.project = { ...detailProject, resolvedOriginalConflictItems: conflictResolution.items, originalConflictItemsComplete: conflictResolution.complete };',
  '    }',
  '    if (!loadingOverlay.isConnected) return;',
  '    loadingOverlay.remove();',
  '    const overlay = openModal(renderProjectDetail(detail.project || detailProject, detail.entries || [], detail.regexEntries || []), \'<i class="fas fa-info-circle"></i> 项目详情\');',
  '    overlay.classList.add("project-detail-modal");',
  "    overlay.addEventListener('click', event => {",
  '      const jump = event.target instanceof Element ? event.target.closest(".detail-toc-item") : null;',
  '      if (!jump) return;',
  '      const href = String(jump.getAttribute("href") || "");',
  '      if (!href.startsWith("#")) return;',
  '      const target = overlay.querySelector(href);',
  '      if (!target) return;',
  '      event.preventDefault();',
  '      overlay.querySelectorAll(".detail-toc-item").forEach(item => item.classList.remove("active"));',
  '      jump.classList.add("active");',
  '      const reduceMotion = typeof window.matchMedia === "function" && window.matchMedia("(prefers-reduced-motion: reduce)").matches;',
  '      const scroller = overlay.querySelector(".modal-body");',
  '      if (scroller instanceof HTMLElement) {',
  '        const scrollerRect = scroller.getBoundingClientRect();',
  '        const targetRect = target.getBoundingClientRect();',
  '        const top = scroller.scrollTop + targetRect.top - scrollerRect.top - 12;',
  '        scroller.scrollTo({ top: Math.max(0, top), behavior: reduceMotion ? "auto" : "smooth" });',
  '      } else {',
  '        target.scrollIntoView({ behavior: reduceMotion ? "auto" : "smooth", block: "start" });',
  '      }',
  '    });',
  "    overlay.querySelectorAll('[data-entry-toggle]').forEach(header => {",
  "      header.addEventListener('click', () => {",
  "        header.classList.toggle('open');",
  '        const content = header.nextElementSibling;',
  "        if (content) content.classList.toggle('open');",
  '      });',
  '    });',
  "    overlay.querySelectorAll('[data-detail-entry-group-toggle]').forEach(toggle => {",
  "      toggle.addEventListener('click', () => {",
  '        const group = toggle.closest("[data-detail-entry-group]");',
  '        const nav = toggle.closest(".detail-entry-nav");',
  '        if (!group || !nav) return;',
  '        const shouldOpen = !group.classList.contains("open");',
  '        if (shouldOpen) {',
  '          nav.querySelectorAll("[data-detail-entry-group].open").forEach(item => {',
  '            if (item === group) return;',
  '            item.classList.remove("open");',
  '            const itemToggle = item.querySelector("[data-detail-entry-group-toggle]");',
  '            if (itemToggle) itemToggle.setAttribute("aria-expanded", "false");',
  '          });',
  '        }',
  '        group.classList.toggle("open", shouldOpen);',
  '        toggle.setAttribute("aria-expanded", shouldOpen ? "true" : "false");',
  '      });',
  '    });',
  '    const mobileReader = overlay.querySelector("[data-mobile-entry-reader]");',
  '    const mobileReaderContent = overlay.querySelector("[data-mobile-reader-content]");',
  '    const mobileReaderLabel = overlay.querySelector("[data-mobile-reader-label]");',
  '    const mobileReaderCount = overlay.querySelector("[data-mobile-reader-count]");',
  '    const mobileReaderJumpName = overlay.querySelector("[data-mobile-reader-jump-name]");',
  '    const mobileReaderPrev = overlay.querySelector("[data-mobile-reader-prev]");',
  '    const mobileReaderNext = overlay.querySelector("[data-mobile-reader-next]");',
  '    const mobileReaderPicker = overlay.querySelector("[data-mobile-reader-picker]");',
  '    const mobileReaderPickerSearch = overlay.querySelector("[data-mobile-reader-picker-search]");',
  '    const mobileReaderPickerList = overlay.querySelector("[data-mobile-reader-picker-list]");',
  '    let mobileReaderKind = "worldbook";',
  '    let mobileReaderIndex = 0;',
  '    const isMobileDetail = () => typeof window.matchMedia === "function" && window.matchMedia("(max-width: 640px)").matches;',
  '    const mobileDescriptionWrap = overlay.querySelector("[data-mobile-description-wrap]");',
  '    const mobileDescription = overlay.querySelector("[data-mobile-description]");',
  '    const mobileDescriptionToggle = overlay.querySelector("[data-mobile-description-toggle]");',
  '    const syncMobileDescriptionToggle = () => {',
  '      if (!isMobileDetail() || !mobileDescriptionWrap || !mobileDescription || !mobileDescriptionToggle) return;',
  '      const expanded = mobileDescriptionWrap.classList.contains("expanded");',
  '      const overflowing = mobileDescription.scrollHeight > mobileDescription.clientHeight + 2;',
  '      mobileDescriptionToggle.hidden = !expanded && !overflowing;',
  '      mobileDescriptionToggle.textContent = expanded ? "收起完整说明" : "展开完整说明";',
  '    };',
  '    mobileDescriptionToggle?.addEventListener("click", () => { mobileDescriptionWrap?.classList.toggle("expanded"); syncMobileDescriptionToggle(); });',
  '    if (isMobileDetail()) requestAnimationFrame(syncMobileDescriptionToggle);',
  '    const getMobileReaderButtons = kind => Array.from(overlay.querySelectorAll(`[data-mobile-reader-kind="${kind}"]`));',
  '    const getMobileReaderSourceIndex = (kind, position) => Number(getMobileReaderButtons(kind)[position]?.dataset.mobileReaderIndex || 0);',
  '    const getMobileReaderSource = (kind, position) => {',
  '      const sourceIndex = getMobileReaderSourceIndex(kind, position);',
  '      return kind === "worldbook" ? overlay.querySelector(`[data-detail-entry-panel="${sourceIndex}"]`) : overlay.querySelector(`[data-mobile-regex-source="${sourceIndex}"]`);',
  '    };',
  '    const getMobileReaderName = (kind, position) => {',
  '      const button = getMobileReaderButtons(kind)[position];',
  '      return button?.querySelector(".mobile-detail-entry-name")?.textContent?.trim() || `条目 ${position + 1}`;',
  '    };',
  '    const closeMobileReaderPicker = () => { if (mobileReaderPicker) mobileReaderPicker.hidden = true; };',
  '    const renderMobileReaderPicker = (query = "") => {',
  '      if (!mobileReaderPickerList) return;',
  '      mobileReaderPickerList.replaceChildren();',
  '      const normalizedQuery = String(query || "").trim().toLowerCase();',
  '      getMobileReaderButtons(mobileReaderKind).forEach((sourceButton, index) => {',
  '        const name = getMobileReaderName(mobileReaderKind, index);',
  '        const source = getMobileReaderSource(mobileReaderKind, index);',
  '        const keywords = source ? Array.from(source.querySelectorAll(".detail-keyword-list")).map(item => item.textContent || "").join(" ") : "";',
  '        if (normalizedQuery && !`${name} ${keywords}`.toLowerCase().includes(normalizedQuery)) return;',
  '        const row = document.createElement("button");',
  '        row.type = "button";',
  '        row.className = `mobile-reader-picker-item${index === mobileReaderIndex ? " active" : ""}`;',
  '        const copy = document.createElement("span");',
  '        copy.textContent = name;',
  '        const number = document.createElement("small");',
  '        number.textContent = `${index + 1}`;',
  '        row.append(copy, number);',
  '        row.addEventListener("click", () => { mobileReaderIndex = index; syncMobileReader(); closeMobileReaderPicker(); });',
  '        mobileReaderPickerList.appendChild(row);',
  '      });',
  '    };',
  '    const syncMobileReader = () => {',
  '      if (!mobileReader || !mobileReaderContent) return;',
  '      const buttons = getMobileReaderButtons(mobileReaderKind);',
  '      mobileReaderIndex = Math.max(0, Math.min(mobileReaderIndex, Math.max(0, buttons.length - 1)));',
  '      const name = getMobileReaderName(mobileReaderKind, mobileReaderIndex);',
  '      if (mobileReaderLabel) mobileReaderLabel.textContent = mobileReaderKind === "worldbook" ? "世界书内容" : "正则内容";',
  '      if (mobileReaderCount) mobileReaderCount.textContent = `${mobileReaderIndex + 1} / ${buttons.length}`;',
  '      if (mobileReaderJumpName) mobileReaderJumpName.textContent = name;',
  '      if (mobileReaderPrev) mobileReaderPrev.disabled = mobileReaderIndex <= 0;',
  '      if (mobileReaderNext) mobileReaderNext.disabled = mobileReaderIndex >= buttons.length - 1;',
  '      mobileReaderContent.replaceChildren();',
  '      const source = getMobileReaderSource(mobileReaderKind, mobileReaderIndex);',
  '      if (mobileReaderKind === "worldbook" && source) {',
  '        const clone = source.cloneNode(true);',
  '        clone.classList.add("active");',
  '        clone.removeAttribute("data-detail-entry-panel");',
  '        mobileReaderContent.appendChild(clone);',
  '      } else if (source) {',
  '        const heading = source.querySelector(".entry-header")?.cloneNode(true);',
  '        const body = source.querySelector(".entry-content")?.cloneNode(true);',
  '        if (heading) {',
  '          heading.removeAttribute("data-entry-toggle");',
  '          heading.querySelector(".fa-chevron-right")?.remove();',
  '          mobileReaderContent.appendChild(heading);',
  '        }',
  '        if (body) { body.classList.add("open"); mobileReaderContent.appendChild(body); }',
  '      }',
  '      bindSafeExternalLinkButtons(mobileReaderContent);',
  '      mobileReaderContent.scrollTop = 0;',
  '    };',
  '    const openMobileReader = (kind, sourceIndex) => {',
  '      if (!isMobileDetail() || !mobileReader) return false;',
  '      mobileReaderKind = kind;',
  '      const position = getMobileReaderButtons(kind).findIndex(button => Number(button.dataset.mobileReaderIndex || 0) === Number(sourceIndex));',
  '      mobileReaderIndex = position >= 0 ? position : 0;',
  '      syncMobileReader();',
  '      closeMobileReaderPicker();',
  '      mobileReader.hidden = false;',
  '      overlay.classList.add("mobile-reader-open");',
  '      return true;',
  '    };',
  '    overlay.querySelectorAll("[data-mobile-reader-kind]").forEach(button => {',
  '      button.addEventListener("click", () => { openMobileReader(String(button.dataset.mobileReaderKind || "worldbook"), Number(button.dataset.mobileReaderIndex || 0)); });',
  '    });',
  '    overlay.querySelectorAll(".mobile-detail-entry-group").forEach(group => {',
  '      group.addEventListener("toggle", () => {',
  '        if (!group.open) return;',
  '        overlay.querySelectorAll(".mobile-detail-entry-group[open]").forEach(other => { if (other !== group) other.open = false; });',
  '      });',
  '    });',
  '    overlay.querySelector("[data-mobile-detail-back]")?.addEventListener("click", () => overlay.querySelector(".close-btn")?.click());',
  '    overlay.querySelector("[data-mobile-reader-back]")?.addEventListener("click", () => { if (mobileReader) mobileReader.hidden = true; overlay.classList.remove("mobile-reader-open"); closeMobileReaderPicker(); });',
  '    mobileReaderPrev?.addEventListener("click", () => { if (mobileReaderIndex > 0) { mobileReaderIndex -= 1; syncMobileReader(); } });',
  '    mobileReaderNext?.addEventListener("click", () => { if (mobileReaderIndex < getMobileReaderButtons(mobileReaderKind).length - 1) { mobileReaderIndex += 1; syncMobileReader(); } });',
  '    overlay.querySelector("[data-mobile-reader-jump]")?.addEventListener("click", () => {',
  '      if (!mobileReaderPicker) return;',
  '      mobileReaderPicker.hidden = false;',
  '      if (mobileReaderPickerSearch) mobileReaderPickerSearch.value = "";',
  '      renderMobileReaderPicker();',
  '      setTimeout(() => mobileReaderPickerSearch?.focus(), 30);',
  '    });',
  '    overlay.querySelector("[data-mobile-reader-picker-close]")?.addEventListener("click", closeMobileReaderPicker);',
  '    mobileReaderPicker?.addEventListener("click", event => { if (event.target === mobileReaderPicker) closeMobileReaderPicker(); });',
  '    mobileReaderPickerSearch?.addEventListener("input", () => renderMobileReaderPicker(mobileReaderPickerSearch.value));',
  "    overlay.querySelectorAll('[data-detail-entry-nav]').forEach(button => {",
  "      button.addEventListener('click', () => {",
  '        const workspace = button.closest(".detail-entry-workspace");',
  '        const target = String(button.dataset.detailEntryNav || "");',
  '        if (!workspace || !target) return;',
  '        workspace.querySelectorAll("[data-detail-entry-nav]").forEach(item => { item.classList.remove("active"); item.setAttribute("aria-selected", "false"); });',
  '        workspace.querySelectorAll("[data-detail-entry-panel]").forEach(panel => panel.classList.remove("active"));',
  '        button.classList.add("active");',
  '        button.setAttribute("aria-selected", "true");',
  '        const panel = workspace.querySelector(`[data-detail-entry-panel="${target}"]`);',
  '        if (panel) panel.classList.add("active");',
  '        const pane = workspace.querySelector(".detail-entry-pane");',
  '        if (pane) pane.scrollIntoView({ block: "start" });',
  '      });',
  '    });',
  "    overlay.querySelectorAll('.detail-like-btn').forEach(detailLikeButton => {",
  '    if (detailLikeButton) {',
  "      detailLikeButton.addEventListener('click', async event => {",
  '        event.stopPropagation();',
  '        if (detailLikeButton.disabled) return;',
  '        const projectId = detailLikeButton.dataset.id || detail.project?.id || project.id;',
  '        if (!projectId) return;',
  '        await toggleLike(projectId);',
  '        const nextLike = getLikeState(projectId);',
  "        detailLikeButton.classList.toggle('liked', nextLike.liked);",
  "        detailLikeButton.setAttribute('aria-pressed', nextLike.liked ? 'true' : 'false');",
  "        const count = detailLikeButton.querySelector('strong');",
  '        if (count) count.textContent = String(nextLike.count);',
  '        const label = detailLikeButton.querySelector(".detail-like-label");',
  '        if (label) label.textContent = nextLike.liked ? "已喜欢" : "喜欢";',
  "        detailLikeButton.title = nextLike.liked ? '取消点赞' : '点赞项目';",
  '      });',
  '    }',
  '    });',
  '    const ratingStars = Array.from(overlay.querySelectorAll("[data-project-rating]"));',
  '    const ratingStarsWrap = overlay.querySelector(".private-rating-stars");',
  '    const ratingCommentInput = overlay.querySelector("[data-private-rating-comment]");',
  '    const ratingSubmitButton = overlay.querySelector("[data-private-rating-submit]");',
  '    const clearRatingPreview = () => { ratingStarsWrap?.classList.remove("previewing"); ratingStars.forEach(star => star.classList.remove("preview")); };',
  '    const selectPrivateRating = rating => {',
  '      if (ratingStarsWrap) ratingStarsWrap.dataset.selectedRating = String(rating);',
  '      ratingStars.forEach(star => star.classList.toggle("active", Number(star.dataset.projectRating || 0) <= rating));',
  '      if (ratingSubmitButton) ratingSubmitButton.disabled = rating < 1;',
  '      const hint = overlay.querySelector("[data-private-rating-hint]");',
  '      if (hint) hint.textContent = `已选择 ${rating}★ · 送出后保存`;',
  '    };',
  '    ratingStars.forEach(button => {',
  '      button.addEventListener("mouseenter", () => {',
  '        if (button.disabled) return;',
  '        const previewRating = Number(button.dataset.projectRating || 0);',
  '        ratingStarsWrap?.classList.add("previewing");',
  '        ratingStars.forEach(star => star.classList.toggle("preview", Number(star.dataset.projectRating || 0) <= previewRating));',
  '      });',
  '      button.addEventListener("click", event => {',
  '        event.preventDefault();',
  '        event.stopPropagation();',
  '        if (button.disabled) return;',
  '        const rating = Number(button.dataset.projectRating || 0);',
  '        if (rating < 1 || rating > 5) return;',
  '        clearRatingPreview();',
  '        selectPrivateRating(rating);',
  '      });',
  '    });',
  '    ratingStarsWrap?.addEventListener("mouseleave", clearRatingPreview);',
  '    ratingSubmitButton?.addEventListener("click", async event => {',
  '      event.preventDefault();',
  '      event.stopPropagation();',
  '      if (ratingSubmitButton.disabled) return;',
  '      const projectId = String(ratingSubmitButton.dataset.projectId || detail.project?.id || project.id || "");',
  '      const rating = Number(ratingStarsWrap?.dataset.selectedRating || 0);',
  '      const comment = String(ratingCommentInput?.value || "").trim();',
  '      if (!projectId || rating < 1 || rating > 5) return;',
  '      ratingStars.forEach(star => { star.disabled = true; });',
  '      ratingSubmitButton.disabled = true;',
  '      if (ratingCommentInput) ratingCommentInput.disabled = true;',
  '      try {',
  '        const result = await setPrivateProjectRating(projectId, rating, comment);',
  '        const savedRating = Number(result?.rating || rating);',
  '        const savedComment = String(result?.comment ?? comment);',
  '        ratingStars.forEach(star => star.classList.toggle("active", Number(star.dataset.projectRating || 0) <= savedRating));',
  '        if (ratingStarsWrap) ratingStarsWrap.dataset.selectedRating = String(savedRating);',
  '        const hint = overlay.querySelector("[data-private-rating-hint]");',
  '        if (hint) hint.textContent = `已评分 ${savedRating}★ · 可修改星级和评论`;',
  '        if (detail.project?.privateRating) { detail.project.privateRating.myRating = savedRating; detail.project.privateRating.myComment = savedComment; }',
  '        ratingSubmitButton.textContent = "更新评分";',
  '        showToast("匿名评分已送给作者", "success");',
  '      } catch (error) {',
  '        showToast("评分失败: " + (error?.message || String(error)), "error");',
  '      } finally {',
  '        ratingStars.forEach(star => { star.disabled = false; });',
  '        ratingSubmitButton.disabled = false;',
  '        if (ratingCommentInput) ratingCommentInput.disabled = false;',
  '      }',
  '    });',
  "    overlay.querySelectorAll('.detail-rebind-project-btn').forEach(button => {",
  "      button.addEventListener('click', event => {",
  '        event.stopPropagation();',
  '        if (button.dataset.id) openInstalledProjectRebindModal(button.dataset.id);',
  '      });',
  '    });',
  "    overlay.querySelectorAll('.detail-install-btn,.install-btn').forEach(button => {",
  "      button.addEventListener('click', event => {",
  '        event.stopPropagation();',
  '        if (button.disabled) return;',
  '        const projectId = button.dataset.id || detail.project?.id || project.id;',
  '        if (!projectId) return;',
  '        const localMeta = getLocalProjectMeta(projectId);',
  '        if (localMeta) {',
  '          requestUninstallProject(projectId);',
  "          showToast('已发送卸载请求', 'info');",
  '        } else {',
  '          void beginProjectInstall(detail.project || project, detail).catch(error => showToast("安装失败: " + error.message, "error"));',

  '        }',
  '        overlay.remove();',
  '      });',
  '    });',
  '    overlay.querySelectorAll("[data-compatibility-edit]").forEach(button => {',
  '      button.addEventListener("click", event => {',
  '        event.stopPropagation();',
  '        void openProjectCompatibilityModal(detail.project || project, overlay);',
  '      });',
  '    });',
  "    overlay.querySelectorAll('.detail-update-btn,.update-btn').forEach(button => {",
  "      button.addEventListener('click', event => {",
  '        event.stopPropagation();',
  '        if (button.disabled) return;',
  '        const targetProject = detail.project || project;',
  '        if (!targetProject?.id) return;',
  '        const restore = setButtonLoading(button, "加载差异");',
  '        requestProjectDiff(targetProject.id, targetProject.version)',
  '          .then(diff => openProjectUpdateModal(targetProject, diff))',
  '          .catch(error => showToast("加载更新差异失败: " + error.message, "error"))',
  '          .finally(restore);',
  '      });',
  '    });',
  '  } catch (error) {',
  '    loadingOverlay.remove();',
  "    showToast('加载详情失败: ' + error.message, 'error');",
  '  }',
  '}',
  '',
].join('\n');
