export const homeProjectUpdateModalScript = [
'async function openProjectCompatibilityModal(project, detailOverlay = null) {',
  '  if (!project?.builtForReferenceVersionId) { showToast("这个项目还没有填写制作时使用的角色卡版本", "warning"); return; }',
  '  let references = [];',
  '  try {',
  '    const data = await fetchCharacterReferences();',
  '    references = Array.isArray(data?.references) ? data.references : [];',
  '  } catch (error) { showToast("角色卡版本加载失败: " + error.message, "error"); return; }',
  '  const reference = references.find(item => Array.isArray(item.versions) && item.versions.some(version => version.id === project.builtForReferenceVersionId));',
  '  if (!reference) { showToast("找不到这个项目使用的角色卡版本", "error"); return; }',
  '  const builtVersion = reference.versions.find(version => version.id === project.builtForReferenceVersionId);',
  '  if (!builtVersion) return;',
  '  const versions = [...reference.versions].filter(version => Number(version.versionOrdinal) >= Number(builtVersion.versionOrdinal)).sort((a, b) => Number(a.versionOrdinal) - Number(b.versionOrdinal));',
  '  const testedOptions = [`<option value="">还没有测试更新版本</option>`, ...versions.map(version => `<option value="${escapeHtml(version.id)}"${version.id === project.testedThroughReferenceVersionId ? " selected" : ""}>${escapeHtml(reference.name)} / ${escapeHtml(version.versionLabel)}</option>`)].join("");',
  '  const latestVersion = [...reference.versions].sort((a, b) => Number(b.versionOrdinal) - Number(a.versionOrdinal))[0] || builtVersion;',
  '  const html = `<form id="compatibilityMetadataForm" class="project-form compatibility-form"><div class="project-form-section"><div class="compatibility-section-head"><h3>角色卡版本</h3><p>这里记录这个 DLC 已经测试过哪些角色卡版本，不会修改 DLC 内容。</p></div><div class="project-form-grid"><div class="form-group"><label>制作时用的版本</label><input value="${escapeHtml(reference.name)} / ${escapeHtml(builtVersion.versionLabel)}" disabled></div><div class="form-group"><label>当前最新版本</label><input value="${escapeHtml(reference.name)} / ${escapeHtml(latestVersion.versionLabel)}" disabled></div><div class="form-group project-form-field--wide"><label>已测试可用到</label><select id="testedThroughReferenceVersionId">${testedOptions}</select><div class="form-hint">只有你真的用这个版本测试过，才选择它。</div></div><label class="taxonomy-chip"><input type="checkbox" id="compatibilityConfirmed"><span>我已经用这个版本测试过</span></label><label class="taxonomy-chip"><input type="checkbox" id="knownIncompatible"${project.compatibilityKnownIncompatible ? " checked" : ""}><span>这个版本不能正常使用</span></label><div class="form-group project-form-field--wide"><label>备注</label><textarea id="compatibilityNote" rows="4" maxlength="500" placeholder="可选：写下测试结果或已知问题">${escapeHtml(project.compatibilityNote || "")}</textarea></div></div></div><div class="project-form-footer"><button type="submit" class="btn btn-primary form-submit-btn"><i class="fas fa-check"></i> 保存</button></div></form>`;',
  '  const overlay = openModal(html, `<i class="fas fa-shield-halved"></i> 角色卡版本`);',
  '  overlay.classList.add("compatibility-modal");',
  '  const form = overlay.querySelector("#compatibilityMetadataForm");',
  '  form.onsubmit = async event => {',
  '    event.preventDefault();',
  '    const testedThroughReferenceVersionId = form.querySelector("#testedThroughReferenceVersionId")?.value || null;',
  '    const knownIncompatible = Boolean(form.querySelector("#knownIncompatible")?.checked);',
  '    const confirmed = Boolean(form.querySelector("#compatibilityConfirmed")?.checked);',
  '    const note = form.querySelector("#compatibilityNote")?.value?.trim() || null;',
  '    if (testedThroughReferenceVersionId && !knownIncompatible && !confirmed) { showToast("请先勾选「我已经用这个版本测试过」", "warning"); return; }',
  '    const submit = form.querySelector(".form-submit-btn");',
  '    const restore = setButtonLoading(submit, "保存中");',
  '    try {',
  '      await updateProjectCompatibility(project.id, { testedThroughReferenceVersionId, knownIncompatible, note });',
  '      showToast("已更新角色卡版本状态");',
  '      overlay.remove();',
  '      if (detailOverlay?.isConnected) detailOverlay.remove();',
  '      await showProjectDetail(project);',
  '    } catch (error) { showToast("角色卡版本更新失败: " + error.message, "error"); } finally { restore(); }',
  '  };',
  '}',
  '',
  'function renderDiffGroup(title, icon, worldbookEntries, regexEntries) {',
  '  const hasWorldbook = Array.isArray(worldbookEntries) && worldbookEntries.length > 0;',
  '  const hasRegex = Array.isArray(regexEntries) && regexEntries.length > 0;',
  '  if (!hasWorldbook && !hasRegex) return "";',
  '  const worldbookHtml = hasWorldbook ? renderDetailSection("世界书条目", "fa-scroll", worldbookEntries, renderDetailEntry, "") : "";',
  '  const regexHtml = hasRegex ? renderDetailSection("正则列表", "fa-code", regexEntries, renderRegexEntry, "") : "";',
  '  return `<div class="update-diff-group"><div class="detail-section-title"><span><i class="fas ${icon}"></i> ${title}</span></div>${worldbookHtml}${regexHtml}</div>`;',
  '}',
  '',
  'function openProjectUpdateModal(project, resolvedDiff) {',
  '  const diff = resolvedDiff || getProjectUpdateDiff(project.id) || {',
  '    added: { worldbookEntries: [], regexEntries: [] },',
  '    modified: { worldbookEntries: [], regexEntries: [] },',
  '    removed: { worldbookEntries: [], regexEntries: [] },',
  '  };',
  '  const headerHtml = renderProjectDetail(project, [], []).replace(/<div class="detail-section">[\\s\\S]*$/, "</div>");',
  '  const bodyHtml = [',
  '    `<div class="update-modal">${headerHtml}`,',
  '    renderDiffGroup("新增内容", "fa-plus", diff.added?.worldbookEntries || [], diff.added?.regexEntries || []),',
  '    renderDiffGroup("修改内容", "fa-pen", diff.modified?.worldbookEntries || [], diff.modified?.regexEntries || []),',
  '    renderDiffGroup("删除内容", "fa-trash", diff.removed?.worldbookEntries || [], diff.removed?.regexEntries || []),',
  '    `<div class="update-modal-actions"><button class="btn btn-outline" data-update-cancel>取消</button><button class="btn btn-primary" data-update-confirm>确认更新</button></div></div>`,',
  '  ].join("");',
  '  const overlay = openModal(bodyHtml, `<i class="fas fa-arrows-rotate"></i> 更新项目`);',
  '  overlay.querySelector("[data-update-cancel]")?.addEventListener("click", () => overlay.remove());',
  '  overlay.querySelector("[data-update-confirm]")?.addEventListener("click", async () => {',
  '    const manageOriginalConflicts = await chooseOriginalConflictInstallManagement(project);',
  '    if (manageOriginalConflicts === null) return;',
  '    confirmProjectUpdate(project.id, project.version, manageOriginalConflicts);',
  "    showToast('已发送更新请求', 'info');",
  '    overlay.remove();',
  '  });',
  '}',
  '',
  "async function loadProjectOriginalConflictItems(project) {",
  "  const requestedIds = Array.isArray(project?.originalConflictReferenceItemIds) ? project.originalConflictReferenceItemIds.map(String).filter(Boolean) : [];",
  "  if (!project?.conflictsWithOriginal || !requestedIds.length) return { requestedIds, items: [], complete: true };",
  "  const referenceVersionId = String(project?.builtForReferenceVersionId || '');",
  "  if (!referenceVersionId) return { requestedIds, items: [], complete: false };",
  "  try {",
  "    const data = await fetchCharacterReferenceVersionItems(referenceVersionId);",
  "    const requested = new Set(requestedIds);",
  "    const items = (Array.isArray(data?.items) ? data.items : []).filter(item => item?.kind === 'worldbook' && requested.has(String(item.id)));",
  "    return { requestedIds, items, complete: items.length === requestedIds.length };",
  "  } catch (error) {",
  "    console.warn('[CreativeWorkshop] failed to load original conflict reference items', error);",
  "    return { requestedIds, items: [], complete: false };",
  "  }",
  "}",
  "",
  "async function chooseOriginalConflictInstallManagement(project) {",
  "  const resolved = await loadProjectOriginalConflictItems(project);",
  "  const requestedIds = resolved.requestedIds;",
  "  if (!project?.conflictsWithOriginal || !requestedIds.length) return false;",
  "  const selectedItems = resolved.items;",
  "  const canAutoManage = resolved.complete;",
  "  const listHtml = selectedItems.length",
  "    ? `<ul class=\"install-conflict-list\">${selectedItems.map(item => `<li><i class=\"fas fa-book\"></i><span>${escapeHtml(item.displayName || '原版条目')}</span></li>`).join('')}</ul>`",
  "    : '<div class=\"install-conflict-unavailable\">暂时无法读取 Creator 声明的原版条目列表。</div>';",
  "  const safetyHtml = canAutoManage",
  "    ? '<p>如果选择「是」，Workshop 会在安装时帮你暂时关闭这些条目，并记录它们原本的启用状态，方便之后更新或卸载时恢复。</p>'",
  "    : '<p>目前无法确认全部声明条目，因此 Workshop 不会自动关闭任何原版内容。你仍可以选择自己处理后继续安装。</p>';",
  "  const bodyHtml = `<div class=\"install-conflict-consent\"><div class=\"detail-warning\"><i class=\"fas fa-triangle-exclamation\"></i><div><strong>这个 DLC 声明会与原版内容冲突</strong><span>安装前请决定是否要由 Workshop 帮你暂时关闭这些世界书条目。</span></div></div>${listHtml}${safetyHtml}<div class=\"install-conflict-actions\"><button class=\"btn btn-outline\" type=\"button\" data-conflict-cancel>取消</button><button class=\"btn btn-outline\" type=\"button\" data-conflict-manual>不用，我自己处理并安装</button><button class=\"btn btn-primary\" type=\"button\" data-conflict-auto${canAutoManage ? '' : ' disabled'}>是，帮我关闭并安装</button></div></div>`;",
  "  const overlay = openModal(bodyHtml, '<i class=\"fas fa-shield-halved\"></i> 安装前确认');",
  "  return new Promise(resolve => {",
  "    let settled = false;",
  "    const finish = result => {",
  "      if (settled) return;",
  "      settled = true;",
  "      if (overlay.isConnected) overlay.remove();",
  "      resolve(result);",
  "    };",
  "    overlay.querySelector('[data-conflict-cancel]')?.addEventListener('click', () => finish(null));",
  "    overlay.querySelector('.close-btn')?.addEventListener('click', () => finish(null), { once: true });",
  "    overlay.addEventListener('click', event => { if (event.target === overlay) finish(null); });",
  "    overlay.querySelector('[data-conflict-manual]')?.addEventListener('click', () => finish(false));",
  "    overlay.querySelector('[data-conflict-auto]')?.addEventListener('click', () => finish(true));",
  "  });",
  "}",
  "",
].join('\n');
