export const homeProjectInstallModalScript = [
'async function beginProjectInstall(project, knownDetail = null) {',
  '  const projectId = project?.id;',
  '  if (!projectId) throw new Error("缺少项目 ID");',
  '  const detail = knownDetail || await fetchProjectEntries(project);',
  '  const worldbookEntries = Array.isArray(detail?.entries) ? detail.entries : [];',
  '  const regexEntries = Array.isArray(detail?.regexEntries) ? detail.regexEntries : [];',
  '  const projectVersion = detail?.project?.version || project?.version || null;',
  '  const manageOriginalConflicts = await chooseOriginalConflictInstallManagement(detail?.project || project);',
  '  if (manageOriginalConflicts === null) return;',
  '  if (worldbookEntries.length > 0) {',
  '    openInstallWorldbookModal(projectId, projectVersion, manageOriginalConflicts);',
  '    return;',
  '  }',
  '  if (regexEntries.length > 0) {',
  '    requestInstallProject(projectId, { ...(projectVersion ? { projectVersion } : {}), manageOriginalConflicts });',
  '    showToast("已发送正则安装请求", "info");',
  '    return;',
  '  }',
  '  throw new Error("项目没有可安装的世界书或正则内容");',
  '}',
  '',
  'function openInstallWorldbookModal(projectId, projectVersion, manageOriginalConflicts = false) {',
  '  const worldbooks = state.tavern.worldbooks || {};',
  '  const primary = worldbooks.primary || null;',
  '  const additional = Array.isArray(worldbooks.additional) ? worldbooks.additional.filter(Boolean) : [];',
  '  const available = Array.isArray(worldbooks.available) ? worldbooks.available.filter(Boolean) : [];',
  '  const additionalCandidates = Array.from(new Set([...additional, ...available])).filter(name => name !== primary);',

  '  const initialMode = primary ? "primary" : "additional";',
  '  const bodyHtml = `<form id="installWorldbookForm" class="install-worldbook-form"><div class="form-group"><label>安装位置</label><div class="install-target-switch"><button type="button" class="btn install-target-option${initialMode === "primary" ? " active" : ""}" data-install-target="primary"${primary ? "" : " disabled"}><i class="fas fa-book"></i><span>角色主世界书</span></button><button type="button" class="btn install-target-option${initialMode === "additional" ? " active" : ""}" data-install-target="additional"><i class="fas fa-layer-group"></i><span>附加世界书</span></button></div></div><div class="form-group install-additional-panel" data-additional-worldbook${initialMode === "additional" ? "" : " hidden"}><label for="additionalWorldbookSearch">选择附加世界书</label><div class="install-worldbook-search-wrap"><i class="fas fa-search"></i><input type="search" id="additionalWorldbookSearch" placeholder="搜索附加世界书" autocomplete="off"></div><div class="install-worldbook-list" data-additional-worldbook-list></div><div class="install-worldbook-create"><button type="button" class="btn btn-outline install-worldbook-create-trigger" data-new-additional-worldbook><i class="fas fa-plus"></i> 新建附加世界书</button><div class="install-worldbook-create-panel" data-new-additional-worldbook-panel hidden><label for="newAdditionalWorldbookName">世界书名称</label><input type="text" id="newAdditionalWorldbookName" data-new-additional-worldbook-name placeholder="例如：梅林 DLC" maxlength="120" autocomplete="off"><div class="install-worldbook-create-actions"><button type="button" class="btn btn-outline" data-new-additional-worldbook-cancel>取消</button><button type="button" class="btn btn-primary" data-new-additional-worldbook-confirm>建立并安装</button></div></div></div></div><button type="submit" class="btn install-submit-btn"><i class="fas fa-download"></i> 安装</button></form>`;',


  '  const overlay = openModal(bodyHtml, `<i class="fas fa-book"></i> 选择安装世界书`);',
  '  const form = overlay.querySelector("#installWorldbookForm");',
  '  const additionalPanel = overlay.querySelector("[data-additional-worldbook]");',
  '  const additionalSearch = overlay.querySelector("#additionalWorldbookSearch");',
  '  const additionalList = overlay.querySelector("[data-additional-worldbook-list]");',
  '  const newAdditionalTrigger = overlay.querySelector("[data-new-additional-worldbook]");',
  '  const newAdditionalPanel = overlay.querySelector("[data-new-additional-worldbook-panel]");',
  '  const newAdditionalName = overlay.querySelector("[data-new-additional-worldbook-name]");',
  '  const newAdditionalCancel = overlay.querySelector("[data-new-additional-worldbook-cancel]");',
  '  const newAdditionalConfirm = overlay.querySelector("[data-new-additional-worldbook-confirm]");',
  '  const targetButtons = Array.from(overlay.querySelectorAll("[data-install-target]"));',
  '  let installMode = initialMode;',
  '  let selectedAdditional = null;',
  '  const renderAdditionalList = query => {',
  '    if (!additionalList || installMode !== "additional") return;',
  '    const keyword = String(query || "").trim().toLowerCase();',
  '    const matches = additionalCandidates.filter(name => !keyword || String(name).toLowerCase().includes(keyword));',
  '    if (!matches.length) {',
  '      additionalList.innerHTML = `<div class="install-worldbook-empty">${additionalCandidates.length ? "没有匹配的附加世界书" : "当前角色没有附加世界书"}</div>`;',
  '      return;',
  '    }',
  '    additionalList.innerHTML = matches.map(name => `<button type="button" class="install-worldbook-option${selectedAdditional === name ? " active" : ""}" data-worldbook-name="${escapeHtml(name)}"><i class="fas fa-book-open"></i><span>${escapeHtml(name)}</span><i class="fas fa-check"></i></button>`).join("");',
  '    additionalList.querySelectorAll("[data-worldbook-name]").forEach(button => button.addEventListener("click", () => {',
  '      if (installMode !== "additional") return;',
  '      selectedAdditional = button.dataset.worldbookName || null;',
  '      renderAdditionalList(additionalSearch?.value || "");',
  '    }));',
  '  };',
  '  const setInstallMode = mode => {',
  '    installMode = mode;',
  '    targetButtons.forEach(button => {',
  '      const active = button.dataset.installTarget === mode;',
  '      button.classList.toggle("active", active);',

  '    });',
  '    if (additionalPanel) additionalPanel.hidden = mode !== "additional";',
  '    if (mode === "additional") { renderAdditionalList(additionalSearch?.value || ""); additionalSearch?.focus(); }',
  '  };',
  '  targetButtons.forEach(button => button.addEventListener("click", () => setInstallMode(button.dataset.installTarget)));',
  '  additionalSearch?.addEventListener("input", () => renderAdditionalList(additionalSearch.value));',
  '  newAdditionalTrigger?.addEventListener("click", () => {',
  '    if (newAdditionalPanel) newAdditionalPanel.hidden = false;',
  '    newAdditionalName?.focus();',
  '  });',
  '  newAdditionalCancel?.addEventListener("click", () => {',
  '    if (newAdditionalName) newAdditionalName.value = "";',
  '    if (newAdditionalPanel) newAdditionalPanel.hidden = true;',
  '  });',
  '  setInstallMode(initialMode);',

  '  const sendInstallRequest = worldbookName => {',
  '    const target = String(worldbookName || "").trim();',
  '    if (!target) return false;',
  '    requestInstallProject(projectId, { worldbookName: target, projectVersion, manageOriginalConflicts });',
  '    showToast(`已发送安装请求：${target}`, "info");',
  '    overlay.dataset.dirty = "false";',
  '    overlay.remove();',
  '    return true;',
  '  };',
  '  newAdditionalConfirm?.addEventListener("click", () => {',
  '    const worldbookName = String(newAdditionalName?.value || "").trim();',
  '    if (!worldbookName) { showToast("请输入新附加世界书名称", "warning"); newAdditionalName?.focus(); return; }',
  '    if (primary && String(primary).toLowerCase() === worldbookName.toLowerCase()) { showToast("新附加世界书不能与角色主世界书同名", "warning"); newAdditionalName?.focus(); return; }',
  '    const existingName = additionalCandidates.find(name => String(name).toLowerCase() === worldbookName.toLowerCase());',
  '    if (existingName) {',
  '      showToast("已有同名世界书，将安装到现有世界书", "info");',
  '      sendInstallRequest(existingName);',
  '      return;',
  '    }',
  '    sendInstallRequest(worldbookName);',
  '  });',
  '  newAdditionalName?.addEventListener("keydown", event => {',
  '    if (event.key !== "Enter") return;',
  '    event.preventDefault();',
  '    newAdditionalConfirm?.click();',
  '  });',

  '  form?.addEventListener("submit", event => {',
  '    event.preventDefault();',
  '    const worldbookName = installMode === "primary" ? String(primary || "").trim() : String(selectedAdditional || "").trim();',
  '    if (!worldbookName) { showToast(installMode === "primary" ? "当前角色没有主世界书" : "请先选择一个附加世界书", "warning"); return; }',
  '    sendInstallRequest(worldbookName);',
  '  });',
  '}',
  '',
].join('\n');
