export const homeProjectEditorModalScript = [
'function bindFileDrop(drop, input, emptyText, onFilesChanged) {',
  '  let selectedFiles = [];',
  '  const applyFiles = async files => {',
  '    const nextFiles = Array.from(files || []);',
  '    const accepted = onFilesChanged ? await onFilesChanged([...nextFiles]) : true;',
  '    if (accepted === false) return false;',
  '    selectedFiles = nextFiles;',
  '    drop.textContent = input.multiple && selectedFiles.length ? `${selectedFiles.length} 个文件（点击或拖入继续添加）` : (selectedFiles[0]?.name || emptyText);',
  '    return true;',
  '  };',
  '  if (input.multiple) {',
  '    ["dragenter", "dragover"].forEach(type => drop.addEventListener(type, event => {',
  '      event.preventDefault();',
  '      if (event.dataTransfer) event.dataTransfer.dropEffect = "copy";',
  '      drop.classList.add("is-dragover");',
  '    }));',
  '    ["dragleave", "drop"].forEach(type => drop.addEventListener(type, event => {',
  '      event.preventDefault();',
  '      drop.classList.remove("is-dragover");',
  '    }));',
  '    drop.addEventListener("drop", event => {',
  '      const incoming = Array.from(event.dataTransfer?.files || []);',
  '      void applyFiles(appendUniqueUploadFiles(selectedFiles, incoming));',
  '    });',
  '  }',
  '  input._fileDropController = { getFiles: () => [...selectedFiles], setFiles: files => applyFiles(files), clear: () => applyFiles([]) };',
  '  drop.onclick = () => input.click();',
  '  input.onchange = async () => {',
  '    const incoming = Array.from(input.files || []);',
  '    const nextFiles = input.multiple ? appendUniqueUploadFiles(selectedFiles, incoming) : incoming.slice(0, 1);',
  '    await applyFiles(nextFiles);',
  '    if (input.multiple) input.value = "";',
  '  };',
  '}',
  '',
  'async function validateJsonUpload(file, kind) {',
  '  if (!file) return null;',
  '  assertUploadSize(file);',
  '  if (!String(file.name || "").toLowerCase().endsWith(".json")) {',
  '    throw new Error(kind === "worldbook" ? "世界书文件必须是 .json" : "正则文件必须是 .json");',
  '  }',
  '  let parsed;',
  '  try {',
  '    parsed = JSON.parse(await file.text());',
  '  } catch {',
  '    throw new Error(kind === "worldbook" ? "这个世界书文件无法读取" : "这个正则文件无法读取");',
  '  }',
  '  if (kind === "worldbook") {',
  '    const entries = parsed && typeof parsed === "object" ? parsed.entries : null;',
  '    const recognized = Boolean(parsed && typeof parsed === "object" && !Array.isArray(parsed) && (Array.isArray(entries) || (entries && typeof entries === "object" && !Array.isArray(entries))));',
  '    if (!recognized) {',
  '      throw new Error("这个世界书文件无法读取，请确认它是从 SillyTavern 导出的世界书");',
  '    }',
  '  }',
  '  if (kind === "worldbook") {',
  '    const entries = parsed.entries;',
  '    const values = Array.isArray(entries) ? entries : Object.values(entries);',
  '    if (!values.length || values.some(entry => !entry || typeof entry !== "object" || Array.isArray(entry))) {',
  '      throw new Error("这个世界书是空的，请选择有内容的世界书文件");',
  '    }',
  '  } else {',
  '    const regexEntries = Array.isArray(parsed) ? parsed : [parsed];',
  '    const validRegex = regexEntries.length > 0 && regexEntries.every(entry => entry && typeof entry === "object" && !Array.isArray(entry) && typeof entry.scriptName === "string" && entry.scriptName.trim());',
  '    if (!validRegex) {',
  '      const worldbookEntries = parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed.entries : null;',
  '      const looksLikeWorldbook = Array.isArray(worldbookEntries) || (worldbookEntries && typeof worldbookEntries === "object" && !Array.isArray(worldbookEntries));',
  '      throw new Error(looksLikeWorldbook ? "你选的是世界书，请放到「世界书」那里" : "这个正则文件无法读取，请换一个正确的正则文件");',
  '    }',
  '  }',
  '  return parsed;',
  '}',
  '',
  'function buildTagOptions(baseTagOptions, currentBaseTag) {',
  '  return baseTagOptions',
  "    .map(tag => '<option value=\"' + tag + '\"' + (tag === currentBaseTag ? ' selected' : '') + '>' + tag + '</option>')",
  "    .join('');",
  '}',
  '',
  'function buildVersionLabelHtml(project) {',
  '  const value = escapeHtml(project?.versionLabel || "");',
  '  return `<div class="form-group"><label for="versionLabel">版本号（可选）</label><input type="text" id="versionLabel" maxlength="80" value="${value}" placeholder="例如：1.0、1.2、夏季版"><div class="form-hint">方便你自己区分版本，不填也可以。</div></div>`;',
  '}',
  '',
  'function buildExtensionTypeOptions(currentExtensionType) {',
  '  return (PROJECT_TAXONOMY.extensionTypes || []).map(value => `<option value="${escapeHtml(value)}"${value === currentExtensionType ? " selected" : ""}>${escapeHtml(value)}</option>`).join("");',
  '}',
  '',
  'function buildCreatorPresetTagOptions(project) {',
  '  const selectedTags = new Set(project ? getProjectTagPool(project) : []);',
  '  const extensionType = project ? getProjectExtensionType(project) : "";',
  '  if (extensionType) selectedTags.add(extensionType);',
  '  const groups = [];',
  '  const extensionTags = Array.from(new Set((PROJECT_TAXONOMY.extensionTypes || []).map(value => String(value).trim()).filter(Boolean)));',
  '  if (extensionTags.length) groups.push({ label: "扩展方向", values: extensionTags, facetGroup: "" });',
  '  Object.entries(PROJECT_TAXONOMY.characterFacets || {}).forEach(([label, values]) => {',
  '    const tags = Array.from(new Set((values || []).map(value => String(value).trim()).filter(Boolean)));',
  '    if (tags.length) groups.push({ label, values: tags, facetGroup: label });',
  '  });',
  '  return groups.map((group, groupIndex) => {',
  '    const selectedCount = group.values.filter(value => selectedTags.has(value)).length;',
  '    const choices = group.values.map((value, choiceIndex) => { const inputId = `presetTag_${groupIndex}_${choiceIndex}`; return `<label class="taxonomy-chip" for="${inputId}"><input id="${inputId}" type="checkbox" data-preset-tag${group.facetGroup ? ` data-facet-group="${escapeHtml(group.facetGroup)}"` : ""} value="${escapeHtml(value)}"${selectedTags.has(value) ? " checked" : ""}><span>${escapeHtml(value)}</span></label>`; }).join("");',
  '    const openAttr = selectedCount > 0 || groupIndex === 0 ? " open" : "";',
  '    return `<details class="taxonomy-facet-group"${openAttr}><summary><span>${escapeHtml(group.label)}</span><small>${selectedCount ? `已选 ${selectedCount}` : "可多选"}</small></summary><div class="taxonomy-chip-list">${choices}</div></details>`;',
  '  }).join("");',
  '}',
  '',
  'function buildDisplayTagOptions(project) {',
  '  const pool = project ? getProjectTagPool(project) : [];',
  '  const selected = new Set(project ? getProjectDisplayTags(project) : []);',
  '  return pool.map((value, index) => { const inputId = `displayTag_${index}`; return `<label class="taxonomy-chip display-tag-chip" for="${inputId}"><input id="${inputId}" type="checkbox" data-display-tag value="${escapeHtml(value)}"${selected.has(String(value)) ? " checked" : ""}><span>${escapeHtml(value)}</span></label>`; }).join("");',
  '}',
  '',
  'function validateProjectTaxonomySelection(payload) {',
  '  const maxTags = Number(PROJECT_TAXONOMY.maxCustomTags || 20);',
  '  const maxDisplayTags = Number(PROJECT_TAXONOMY.maxDisplayTags || 5);',
  '  const officialCount = Object.values(payload.facets || {}).flat().length;',
  '  if (officialCount + (payload.customTags || []).length > maxTags) return { valid: false, error: `标签最多 ${maxTags} 个` };',
  '  if ((payload.displayTags || []).length > maxDisplayTags) return { valid: false, error: `封面最多显示 ${maxDisplayTags} 个标签` };',
  '  return { valid: true };',
  '}',
  '',
  'const PROJECT_CONTENT_KIND_LABELS = { worldbook: "世界书", regex: "正则" };',
  '',
  'function getProjectContentRule(baseTag) {',
  '  return PROJECT_CONTENT_POLICY[baseTag] || PROJECT_CONTENT_POLICY["系统核心"];',
  '}',
  '',
  'function validateProjectContentSelection(baseTag, hasWorldbook, hasRegex) {',
  '  const rule = getProjectContentRule(baseTag);',
  '  const presence = { worldbook: Boolean(hasWorldbook), regex: Boolean(hasRegex) };',
  '  for (const kind of rule.required || []) {',
  '    if (!presence[kind]) return { valid: false, error: `这个类型需要上传${PROJECT_CONTENT_KIND_LABELS[kind] || kind}` };',
  '  }',
  '  if ((rule.anyOf || []).length && !rule.anyOf.some(kind => presence[kind])) {',
  '    const names = rule.anyOf.map(kind => PROJECT_CONTENT_KIND_LABELS[kind] || kind).join("或");',
  '    return { valid: false, error: `请上传${names}，选一种就可以` };',
  '  }',
  '  return { valid: true };',
  '}',
  '',
  'function getProjectContentRequirementText(baseTag) {',
  '  const rule = getProjectContentRule(baseTag);',
  '  const required = (rule.required || []).map(kind => `需要${PROJECT_CONTENT_KIND_LABELS[kind] || kind}`);',
  '  const anyOf = (rule.anyOf || []).length ? [`${rule.anyOf.map(kind => PROJECT_CONTENT_KIND_LABELS[kind] || kind).join("或")}选一种就可以`] : [];',
  '  return [...required, ...anyOf].join("；") || "这里没有必需文件";',
  '}',
  '',
  'function buildBuiltForReferenceOptions(references, selectedVersionId) {',
  '  const selected = String(selectedVersionId || "");',
  '  const groups = Array.isArray(references) ? references : [];',
  '  if (!groups.length) return `<option value="">还没有可选的角色卡版本</option>`;',
  '  return [`<option value="">请选择角色卡版本</option>`, ...groups.map(reference => {',
  '    const versions = Array.isArray(reference.versions) ? reference.versions : [];',
  '    const options = versions.map(version => `<option value="${escapeHtml(version.id)}"${version.id === selected ? " selected" : ""}>${escapeHtml(reference.name)} / ${escapeHtml(version.versionLabel)}</option>`).join("");',
  '    return options;',
  '  })].join("");',
  '}',
  '',
  'function buildProjectFormHtml(mode, project, references = []) {',
  "  const isEdit = mode === 'edit';",
  '  const baseTagOptions = BASE_TAGS;',
  '  const currentBaseTag = project ? getBaseTag(project) : "系统核心";',
  '  const presetTagsHtml = buildCreatorPresetTagOptions(project);',
  '  const presetTagValues = new Set([...(PROJECT_TAXONOMY.extensionTypes || []), ...Object.values(PROJECT_TAXONOMY.characterFacets || {}).flat()].map(String));',
  "  const customTags = project ? getProjectCustomTags(project).filter(tag => !presetTagValues.has(String(tag))).join(', ') : '';",
  '  const displayTagsHtml = buildDisplayTagOptions(project);',
  '  const displayTagCount = project ? getProjectDisplayTags(project).length : 0;',
  '  const worldbookEntries = Array.isArray(project?.worldbookEntriesPreview) ? project.worldbookEntriesPreview : [];',
  '  const regexEntries = Array.isArray(project?.regexEntriesPreview) ? project.regexEntriesPreview : [];',
  '  const currentCoverSources = project ? getCoverImageSources(project) : null;',
  '  const currentCoverSrc = currentCoverSources?.authenticated ? currentCoverSources.placeholder : getDirectCoverUrl(project);',
  '  const currentCoverAuthAttrs = currentCoverSources?.authenticated ? ` data-cover-img-auth-src="${escapeHtml(currentCoverSources.authenticated)}" data-cover-img-placeholder-src="${escapeHtml(currentCoverSources.placeholder)}"` : "";',
  "  const currentCoverHtml = project?.coverImage ? '<div class=\"edit-current-cover\"><div class=\"detail-section-title\"><span><i class=\"fas fa-image\"></i> 当前预览图</span></div><img src=\"' + escapeHtml(currentCoverSrc) + '\"' + currentCoverAuthAttrs + ' alt=\"当前预览图\"></div>' : '<div class=\"edit-current-cover edit-current-cover--empty\"><div class=\"detail-section-title\"><span><i class=\"fas fa-image\"></i> 当前预览图</span></div><div class=\"empty-state\">未上传预览图</div></div>';",
  '  const currentContentHtml = isEdit ? `<div class="edit-current-content">${currentCoverHtml}${renderDetailSection("世界书条目", "fa-scroll", worldbookEntries, renderDetailEntry, "无条目内容", project, true, false)}${renderDetailSection("正则列表", "fa-code", regexEntries, renderRegexEntry, "无正则内容", project, true, false)}</div>` : "";',





  '  return [',
  '    \'<form id="projectForm" class="project-form" data-mode="\' + mode + \'">\',',
  '    \'  <div class="project-form-layout">\',',
  '    \'    <div class="project-form-column project-form-column--main">\',',
  '    \'      <section class="project-form-section" aria-labelledby="projectFormIdentityTitle">\',',
  '    \'        <div class="project-form-section-head"><span class="project-form-section-index">01</span><div><h3 id="projectFormIdentityTitle">基本资料</h3><p>先告诉大家这是什么。</p></div></div>\',',
  '    \'        <div class="project-form-grid project-form-grid--identity">\',',
  '    \'          <div class="form-group project-form-field--wide"><label for="projName">标题 *</label><input type="text" id="projName" value="\' + escapeHtml(project?.name || \'\') + \'" required></div>\',',
  '    \'          <div class="form-group project-form-field--wide"><label for="projDesc">简介（支持 Markdown，可选）</label><textarea id="projDesc" rows="5" placeholder="简单介绍一下这个 DLC。可以使用 Markdown。">\' + escapeHtml(project?.description || \'\') + \'</textarea></div>\',',
  '    \'          <div class="form-group project-form-field--wide"><label for="projPrecautions">安装注意事项（可选）</label><textarea id="projPrecautions" rows="4" maxlength="2000" placeholder="例如：与某世界书冲突、需要先安装某插件、建议的安装顺序。这里按纯文本显示，不会执行任何指令。">\' + escapeHtml(project?.precautions || \'\') + \'</textarea><div class="form-hint">玩家会在安装按钮附近看到这段提示。仅显示文字，不会自动执行其中的操作。</div></div>\',',
  '    buildVersionLabelHtml(project),',
  '    \'        </div>\',',
  '    \'      </section>\',',
  "    '      <section class=\"project-form-section\" aria-labelledby=\"projectFormTaxonomyTitle\">',",
  "    '        <div class=\"project-form-section-head\"><span class=\"project-form-section-index\">02</span><div><h3 id=\"projectFormTaxonomyTitle\">分类与标签</h3><p>分类必填，标签最多 20 个。</p></div></div>',",
  "    '        <div class=\"project-form-grid project-form-grid--taxonomy\">',",
  "    '          <div class=\"form-group project-form-field--wide\"><label for=\"baseTag\">分类 *</label><select id=\"baseTag\">' + buildTagOptions(baseTagOptions, currentBaseTag) + '</select></div>',",
  "    '          <details class=\"creator-tag-picker project-form-field--wide\"><summary><span>标签（可选）</span><small>打开后直接点选</small></summary><div class=\"creator-tag-picker-body\"><div class=\"form-group\" id=\"presetTagsGroup\"><label>直接点选</label><div class=\"form-hint creator-tag-picker-hint\">和主页搜索是同一套标签，可多选。</div>' + presetTagsHtml + '</div><div class=\"form-group\"><label for=\"customTags\">没有想要的？自己填写</label><input type=\"text\" id=\"customTags\" value=\"' + escapeHtml(customTags) + '\" placeholder=\"例如：纯爱, 慢热, 高自由度\"><div class=\"form-hint\">用逗号分开，和上面合计最多 20 个。</div></div></div></details>',",
  "    '          <div class=\"form-group project-form-field--wide\" id=\"displayTagsGroup\"><label class=\"display-tags-label\">封面展示标签（可选） <small id=\"displayTagCount\">' + displayTagCount + ' / ' + (PROJECT_TAXONOMY.maxDisplayTags || 5) + '</small></label><div class=\"taxonomy-chip-list display-tag-picker\" id=\"displayTagPicker\">' + (displayTagsHtml || '<div class=\"display-tag-picker-empty\">先在上面选择或填写标签</div>') + '</div><div class=\"form-hint\">最多挑 5 个；不挑就按上面的顺序自动显示。</div></div>',",
  "    '        </div>',",
  "    '      </section>',",
  '    currentContentHtml,',
  '    \'    </div>\',',
  '    \'    <div class="project-form-column project-form-column--assets">\',',
  '    \'      <section class="project-form-section project-form-section--assets" aria-labelledby="projectFormContentTitle">\',',
  '    \'        <div class="project-form-section-head"><span class="project-form-section-index">03</span><div><h3 id="projectFormContentTitle">上传内容</h3><p>把你要分享的文件和图片放这里。</p></div></div>\',',
  '    \'        <div class="project-upload-stack">\',',
  '    \'          <div class="form-group project-upload-field"><label id="worldbookFileLabel" for="fileInput">\' + (isEdit ? \'更换世界书\' : \'世界书 *\') + \'</label><div class="file-drop project-file-drop project-file-drop--worldbook" id="fileDrop">\' + (isEdit ? \'选择新的世界书文件\' : \'选择世界书文件 (.json)\') + \'</div><input type="file" id="fileInput" name="worldbookFile" aria-label="世界书文件" accept=".json" style="display:none;"><div class="upload-file-preview" id="worldbookUploadPreview" hidden></div></div>\',',
  '    \'          <div class="form-group project-upload-field"><label id="regexFileLabel" for="regexInput">\' + (isEdit ? \'更换正则\' : \'正则（可选）\') + \'</label><div class="file-drop project-file-drop project-file-drop--regex" id="regexDrop">\' + (isEdit ? \'选择新的正则文件（可多选）\' : \'选择正则文件（可多选）\') + \'</div><input type="file" id="regexInput" name="regexFiles" aria-label="正则文件" accept=".json" multiple style="display:none;"><div class="upload-file-preview" id="regexUploadPreview" hidden></div><div class="form-hint" id="contentRequirementHint"></div></div>\',',
  '    \'          <div class="form-group project-upload-field"><label for="coverInput">\' + (isEdit ? \'更换封面图\' : \'封面图（可选）\') + \'</label><div class="file-drop project-file-drop project-file-drop--cover" id="coverDrop">\' + (isEdit ? \'选择新图片\' : \'选择图片\') + \'</div><input type="file" id="coverInput" name="coverImage" aria-label="封面图" accept="image/jpeg,image/png,image/webp" style="display:none;"><div class="upload-file-preview" id="coverUploadPreview" hidden></div></div>\',',
  '    \'        </div>\',',
  '    \'      </section>\',',
  '    \'    </div>\',',
  '    \'  </div>\',',
  '    \'  <div class="project-form-footer"><div class="project-form-footer-note"><i class="fas fa-circle-check"></i><span>系统会先检查文件，然后让你确认两个问题。</span></div><button type="submit" class="btn btn-primary form-submit-btn"><i class="fas fa-cloud-upload-alt"></i> \' + (isEdit ? \'保存修改\' : \'下一步\') + \'</button></div>\',',
  "    '</form>',",
  "  ].join('');",
  '}',
  '',
  'function collectProjectFormPayload(form) {',
  "  const name = form.querySelector('#projName').value.trim();",
  "  const description = form.querySelector('#projDesc').value;",
  "  const precautions = form.querySelector('#projPrecautions')?.value.trim() || null;",
  "  const versionLabel = form.querySelector('#versionLabel')?.value.trim() || null;",
  "  const projectType = form.querySelector('#baseTag').value;",
  "  const extensionType = null;",
  "  const rawCustomTags = parseTagsInput(form.querySelector('#customTags').value);",
  '  const selectedPresetTags = Array.from(form.querySelectorAll("[data-preset-tag]:checked")).map(input => String(input.value).trim()).filter(Boolean);',
  '  const facets = {};',
  '  if (projectType === "角色") {',
  '    form.querySelectorAll("[data-preset-tag][data-facet-group]:checked").forEach(input => {',
  '      const group = String(input.dataset.facetGroup || "");',
  '      if (!group) return;',
  '      if (!Array.isArray(facets[group])) facets[group] = [];',
  '      facets[group].push(String(input.value));',
  '    });',
  '  }',
  '  const officialTagValues = new Set(Object.values(facets).flat().map(String));',
  '  const customTags = Array.from(new Set([...selectedPresetTags.filter(tag => !officialTagValues.has(tag)), ...rawCustomTags.filter(tag => !officialTagValues.has(tag))]));',
  '  const tagPool = new Set([...officialTagValues, ...customTags]);',
  '  const selectedDisplayTags = Array.from(form.querySelectorAll("[data-display-tag]:checked")).map(input => String(input.value)).filter(tag => tagPool.has(tag));',
  '  const displayTags = selectedDisplayTags.length ? selectedDisplayTags : undefined;',
  "  const legacyBaseTag = projectType === '系统核心' ? '系统' : projectType;",
  '  return { name, description, precautions, versionLabel, projectType, extensionType, facets, customTags, displayTags, tags: [legacyBaseTag, ...customTags] };',
  '}',
  '',
  'function prepareProjectForm(overlay) {',
  "  const form = overlay.querySelector('#projectForm');",
  "  const baseTagSelect = overlay.querySelector('#baseTag');",
  "  const presetTagsGroup = overlay.querySelector('#presetTagsGroup');",
  "  const customTagsInput = overlay.querySelector('#customTags');",
  "  const displayTagPicker = overlay.querySelector('#displayTagPicker');",
  "  const displayTagCount = overlay.querySelector('#displayTagCount');",
  "  const worldbookFileLabel = overlay.querySelector('#worldbookFileLabel');",
  "  const regexFileLabel = overlay.querySelector('#regexFileLabel');",
  "  const contentRequirementHint = overlay.querySelector('#contentRequirementHint');",
  "  const fileInput = overlay.querySelector('#fileInput');",
  "  const regexInput = overlay.querySelector('#regexInput');",
  "  const coverInput = overlay.querySelector('#coverInput');",
  "  const fileDrop = overlay.querySelector('#fileDrop');",
  "  const regexDrop = overlay.querySelector('#regexDrop');",
  "  const coverDrop = overlay.querySelector('#coverDrop');",
  "  const worldbookPreview = overlay.querySelector('#worldbookUploadPreview');",
  "  const regexPreview = overlay.querySelector('#regexUploadPreview');",
  "  const coverPreview = overlay.querySelector('#coverUploadPreview');",
  '  const worldbookEmptyText = fileDrop.textContent;',
  '  const regexEmptyText = regexDrop.textContent;',
  '  const coverEmptyText = coverDrop.textContent;',
  '  const uploadState = { worldbook: null, regex: null, regexFiles: [] };',
  '  const getCurrentFormTagPool = () => {',
  '    const preset = Array.from(form.querySelectorAll("[data-preset-tag]:checked")).map(input => String(input.value).trim()).filter(Boolean);',
  '    const custom = parseTagsInput(customTagsInput?.value || "");',
  '    return Array.from(new Set([...preset, ...custom]));',
  '  };',
  '  const refreshDisplayTagPicker = () => {',
  '    if (!displayTagPicker) return;',
  '    const maxTags = Number(PROJECT_TAXONOMY.maxDisplayTags || 5);',
  '    const previousSelected = new Set(Array.from(displayTagPicker.querySelectorAll("[data-display-tag]:checked")).map(input => String(input.value)));',
  '    const pool = getCurrentFormTagPool();',
  '    const selected = new Set(Array.from(previousSelected).filter(tag => pool.includes(tag)).slice(0, maxTags));',
  '    displayTagPicker.innerHTML = pool.length ? pool.map(value => `<label class="taxonomy-chip display-tag-chip"><input type="checkbox" data-display-tag value="${escapeHtml(value)}"${selected.has(value) ? " checked" : ""}><span>${escapeHtml(value)}</span></label>`).join("") : `<div class="display-tag-picker-empty">先在上面选择或填写标签</div>`;',
  '    const updateCount = () => { if (displayTagCount) displayTagCount.textContent = `${displayTagPicker.querySelectorAll("[data-display-tag]:checked").length} / ${maxTags}`; };',
  '    displayTagPicker.querySelectorAll("[data-display-tag]").forEach(input => {',
  '      input.addEventListener("change", () => {',
  '        if (input.checked && displayTagPicker.querySelectorAll("[data-display-tag]:checked").length > maxTags) {',
  '          input.checked = false;',
  '          showToast(`首页最多显示 ${maxTags} 个`, "warning");',
  '        }',
  '        updateCount();',
  '      });',
  '    });',
  '    updateCount();',
  '  };',
  '  const refreshContentRequirementUi = () => {',
  '    const baseTag = baseTagSelect?.value || "系统核心";',
  '    const rule = getProjectContentRule(baseTag);',
  '    const worldbookRequired = (rule.required || []).includes("worldbook");',
  '    const eitherContent = (rule.anyOf || []).includes("worldbook") && (rule.anyOf || []).includes("regex");',
  '    if (form.dataset.mode !== "edit") {',
  '      if (worldbookFileLabel) worldbookFileLabel.textContent = worldbookRequired ? "世界书 *" : (eitherContent ? "世界书（二选一）" : "世界书（可选）");',
  '      if (regexFileLabel) regexFileLabel.textContent = eitherContent ? "正则（二选一）" : "正则（可选）";',
  '    }',
  '    if (contentRequirementHint) contentRequirementHint.textContent = getProjectContentRequirementText(baseTag);',
  '  };',
  '  const normalizeCustomTagsInput = () => {',
  '    if (!customTagsInput) return;',
  '    const preset = new Set(Array.from(form.querySelectorAll("[data-preset-tag]:checked")).map(input => String(input.value)));',
  '    customTagsInput.value = parseTagsInput(customTagsInput.value).filter(tag => !preset.has(tag)).join(", ");',
  '  };',
  '  if (baseTagSelect) baseTagSelect.addEventListener("change", () => { refreshContentRequirementUi(); refreshDisplayTagPicker(); });',
  '  if (presetTagsGroup) presetTagsGroup.addEventListener("change", () => { normalizeCustomTagsInput(); refreshDisplayTagPicker(); });',
  '  if (customTagsInput) customTagsInput.addEventListener("input", refreshDisplayTagPicker);',
  '  if (customTagsInput) customTagsInput.addEventListener("blur", () => { normalizeCustomTagsInput(); refreshDisplayTagPicker(); });',
  '  refreshContentRequirementUi();',
  '  refreshDisplayTagPicker();',
  '  const bindPreviewClear = (container, kind, onClear) => {',
  '    const button = container?.querySelector(`[data-upload-preview-clear="${kind}"]`);',
  '    if (button) button.onclick = event => { event.stopPropagation(); onClear(); };',
  '  };',
  '  const refreshRegexSelection = async nextFiles => {',
  '    if (!nextFiles.length) {',
  '      uploadState.regex = null;',
  '      uploadState.regexFiles = [];',
  '      clearUploadPreview(regexPreview);',
  '      regexDrop.textContent = regexEmptyText;',
  '      return true;',
  '    }',
  '    try {',
  '      const prepared = await prepareRegexUploads(nextFiles);',
  '      uploadState.regex = prepared;',
  '      uploadState.regexFiles = prepared.files;',
  '      renderRegexUploadPreview(regexPreview, prepared);',
  '      regexDrop.textContent = `${prepared.files.length} 个正则文件（点击或拖入可以继续添加）`;',
  '      regexPreview.querySelectorAll("[data-regex-upload-remove]").forEach(button => {',
  '        button.onclick = event => {',
  '          event.stopPropagation();',
  '          const index = Number(button.dataset.regexUploadRemove);',
  '          if (!Number.isInteger(index)) return;',
  '          const remaining = uploadState.regexFiles.filter((_, fileIndex) => fileIndex !== index);',
  '          void refreshRegexSelection(remaining);',
  '        };',
  '      });',
  '      return true;',
  '    } catch (error) {',
  '      regexDrop.textContent = uploadState.regexFiles.length ? `${uploadState.regexFiles.length} 个正则文件（点击或拖入可以继续添加）` : regexEmptyText;',
  '      if (uploadState.regex) showToast("未添加正则文件：" + error.message, "error");',
  '      else renderUploadPreviewError(regexPreview, error);',
  '      return false;',
  '    }',
  '  };',
  '  bindFileDrop(fileDrop, fileInput, worldbookEmptyText, async files => {',
  '    uploadState.worldbook = null;',
  '    clearUploadPreview(worldbookPreview);',
  '    if (!files[0]) return;',
  '    try {',
  '      const prepared = await prepareWorldbookUpload(files[0]);',
  '      uploadState.worldbook = prepared;',
  '      renderWorldbookUploadPreview(worldbookPreview, prepared);',
  '      bindPreviewClear(worldbookPreview, "worldbook", () => {',
  '        fileInput.value = "";',
  '        uploadState.worldbook = null;',
  '        clearUploadPreview(worldbookPreview);',
  '        fileDrop.textContent = worldbookEmptyText;',
  '      });',
  '    } catch (error) {',
  '      renderUploadPreviewError(worldbookPreview, error);',
  '    }',
  '  });',
  '  bindFileDrop(regexDrop, regexInput, regexEmptyText, async files => {',
  '    const previousRegex = uploadState.regex;',
  '    uploadState.regex = null;',
  '    clearUploadPreview(regexPreview);',
  '    if (!files.length) return;',
  '    try {',
  '      const prepared = await prepareRegexUploads(files);',
  '      uploadState.regex = prepared;',
  '      renderRegexUploadPreview(regexPreview, prepared);',
  '    } catch (error) {',
  '      uploadState.regex = previousRegex;',
  '      if (previousRegex) {',
  '        renderRegexUploadPreview(regexPreview, previousRegex);',
  '        showToast("未添加正则文件：" + error.message, "error");',
  '      } else {',
  '        renderUploadPreviewError(regexPreview, error);',
  '      }',
  '      return false;',
  '    }',
  '  });',
  '  regexPreview.addEventListener("click", event => {',
  '    const button = event.target.closest("[data-regex-upload-remove]");',
  '    if (!button) return;',
  '    event.stopPropagation();',
  '    const index = Number(button.dataset.regexUploadRemove);',
  '    if (!Number.isInteger(index)) return;',
  '    const remaining = (uploadState.regex?.files || []).filter((_, fileIndex) => fileIndex !== index);',
  '    void regexInput._fileDropController?.setFiles(remaining);',
  '  });',
  '  bindFileDrop(coverDrop, coverInput, coverEmptyText, async files => {',
  '    clearUploadPreview(coverPreview);',
  '    if (!files[0]) return;',
  '    try {',
  '      await renderCoverUploadPreview(coverPreview, files[0]);',
  '      bindPreviewClear(coverPreview, "cover", () => {',
  '        coverInput.value = "";',
  '        clearUploadPreview(coverPreview);',
  '        coverDrop.textContent = coverEmptyText;',
  '      });',
  '    } catch (error) {',
  '      renderUploadPreviewError(coverPreview, error);',
  '    }',
  '  });',
  '  return { form, fileInput, regexInput, coverInput, uploadState, submitBtn: overlay.querySelector(".form-submit-btn") };',
  '}',
  '',
  'function setSubmitState(button, pendingText, idleText, pending) {',
  '  if (!button) return;',
  '  button.disabled = pending;',
  '  button.textContent = pending ? pendingText : idleText;',
  '}',
  '',
  'async function openUploadModal() {',
  '  if (!state.currentUser) {',
  "    showToast('请先登录', 'warning');",
  '    return;',
  '  }',
  '  let characterReferences = [];',
  '  try {',
  '    const referenceData = await fetchCharacterReferences();',
  '    characterReferences = Array.isArray(referenceData?.references) ? referenceData.references : [];',
  '  } catch (error) {',
  '    showToast("角色卡版本加载失败，可以稍后再试", "warning");',
  '  }',
  "  const overlay = openModal(buildProjectFormHtml('create', null, characterReferences), '<i class=\"fas fa-cloud-upload-alt\"></i> 发布项目');",
  "  overlay.classList.add('project-form-modal');",
  '  const { form, fileInput, regexInput, coverInput, uploadState, submitBtn } = prepareProjectForm(overlay);',
  '  form.onsubmit = async event => {',
  '    event.preventDefault();',
  '    const payload = collectProjectFormPayload(form);',
  '    const hasWorldbook = Boolean(fileInput.files[0]);',
  '    const hasRegex = Boolean(uploadState.regex?.uploadFile);',
  '    if (!payload.name) {',
  "      showToast('请填写项目名称', 'warning');",
  "      setSubmitState(submitBtn, '正在提交...', '下一步', false);",
  '      return;',
  '    }',
  '    const taxonomyValidation = validateProjectTaxonomySelection(payload);',
  '    if (!taxonomyValidation.valid) {',
  '      showToast(taxonomyValidation.error, "warning");',
  "      setSubmitState(submitBtn, '正在提交...', '下一步', false);",
  '      return;',
  '    }',
  '    const contentValidation = validateProjectContentSelection(payload.projectType, hasWorldbook, hasRegex);',
  '    if (!contentValidation.valid) {',
  '      showToast(contentValidation.error, "warning");',
  "      setSubmitState(submitBtn, '正在提交...', '下一步', false);",
  '      return;',
  '    }',
  '    const publishCheck = await openCreatorPublishCheck(characterReferences);',
  '    if (!publishCheck) return;',
  '    Object.assign(payload, publishCheck);',
  "    setSubmitState(submitBtn, '正在提交...', '下一步', true);",
  '    try {',
  '      const preparedWorldbook = hasWorldbook ? (uploadState.worldbook || await prepareWorldbookUpload(fileInput.files[0])) : null;',
  '      const preparedRegex = uploadState.regex?.uploadFile ? uploadState.regex : null;',
  '      const createRes = await createProject(payload);',
  '      const projectId = createRes.projectId;',
  '      if (preparedWorldbook?.file) await uploadProjectFile(projectId, preparedWorldbook.file);',
  '      if (preparedRegex?.uploadFile) await uploadRegexFile(projectId, preparedRegex.uploadFile);',
  '      if (coverInput.files[0]) await uploadCoverFile(projectId, coverInput.files[0]);',
  "      showToast('已提交，等待审核');",
  '      overlay.remove();',
  '      await fetchProjects();',
  '    } catch (error) {',
  "      showToast('提交失败：' + error.message, 'error');",
  '    } finally {',
  "      setSubmitState(submitBtn, '正在提交...', '下一步', false);",
  '    }',
  '  };',
  '}',
  '',
  'async function openEditProjectModal(project) {',
  '  let characterReferences = [];',
  '  try {',
  '    const referenceData = await fetchCharacterReferences();',
  '    characterReferences = Array.isArray(referenceData?.references) ? referenceData.references : [];',
  '  } catch (error) {',
  '    showToast("角色卡版本加载失败，可以稍后再试", "warning");',
  '  }',
  "  const overlay = openModal(buildProjectFormHtml('edit', project, characterReferences), '<i class=\"fas fa-edit\"></i> 修改项目');",
  "  overlay.classList.add('project-form-modal');",
  "  overlay.querySelectorAll('[data-entry-toggle]').forEach(header => {",
  "    header.addEventListener('click', event => {",
  "      if (event.target.closest('button,input,label')) return;",
  "      header.classList.toggle('open');",
  '      const content = header.nextElementSibling;',
  "      if (content) content.classList.toggle('open');",
  '    });',
  '  });',
  "  overlay.querySelectorAll('[data-entry-remove]').forEach(button => {",
  "    button.addEventListener('click', async event => {",
  '      event.stopPropagation();',
  '      const projectId = button.dataset.projectId;',
  '      const kind = button.dataset.entryKind;',
  '      const entryKey = button.dataset.entryKey;',
  '      if (!projectId || !kind || !entryKey) return;',
  "      if (!confirm('确定从当前项目中移除此条内容？修改会进入审核草稿。')) return;",
  "      const restore = setButtonLoading(button, '删除中');",
  '      try {',
  '        const result = await removeProjectEntry(projectId, kind, entryKey);',
  "        showToast('条目已移除，已切换到最新草稿');",
  '        overlay.remove();',
  '        await fetchProjects(true);',
  '        const targetId = result.projectId || projectId;',
  '        const nextDetail = await fetchProjectEntries(targetId, { forceRefresh: true });',
  '        const nextProject = nextDetail.project ? { ...nextDetail.project, publishedVersion: project.publishedVersion } : { ...project, id: targetId };',
  '        openEditProjectModal(nextProject);',
  '      } catch (error) {',
  "        showToast('删除失败: ' + error.message, 'error');",
  '      } finally { restore(); }',
  '    });',
  '  });',
  '  const { form, fileInput, regexInput, coverInput, uploadState, submitBtn } = prepareProjectForm(overlay);',
  '  form.onsubmit = async event => {',
  '    event.preventDefault();',
  '    const payload = collectProjectFormPayload(form);',
  '    const hasNewFile = Boolean(fileInput.files[0]);',
  '    const hasNewRegex = Boolean(uploadState.regex?.uploadFile);',
  '    const hasNewCover = Boolean(coverInput.files[0]);',
  '    const hasExistingWorldbook = Array.isArray(project?.worldbookEntriesPreview) && project.worldbookEntriesPreview.length > 0;',
  '    const hasExistingRegex = Array.isArray(project?.regexEntriesPreview) && project.regexEntriesPreview.length > 0;',
  '    if (!payload.name && !hasNewFile && !hasNewRegex && !hasNewCover) {',
  "      showToast('请至少填写项目名称或上传文件', 'warning');",
  "      setSubmitState(submitBtn, '保存中...', '保存修改', false);",
  '      return;',
  '    }',
  '    const taxonomyValidation = validateProjectTaxonomySelection(payload);',
  '    if (!taxonomyValidation.valid) {',
  '      showToast(taxonomyValidation.error, "warning");',
  "      setSubmitState(submitBtn, '保存中...', '保存修改', false);",
  '      return;',
  '    }',
  '    const contentValidation = validateProjectContentSelection(payload.projectType, hasNewFile || hasExistingWorldbook, hasNewRegex || hasExistingRegex);',
  '    if (!contentValidation.valid) {',
  '      showToast(contentValidation.error, "warning");',
  "      setSubmitState(submitBtn, '保存中...', '保存修改', false);",
  '      return;',
  '    }',
  '    const publishCheck = await openCreatorPublishCheck(characterReferences, project);',
  '    if (!publishCheck) return;',
  '    Object.assign(payload, publishCheck);',
  "    setSubmitState(submitBtn, '保存中...', '保存修改', true);",
  '    try {',
  '      const preparedWorldbook = hasNewFile ? (uploadState.worldbook || await prepareWorldbookUpload(fileInput.files[0])) : null;',
  '      const preparedRegex = hasNewRegex ? uploadState.regex : null;',
  '      const updateResult = await updateProject(project.id, payload);',
  '      const targetProjectId = updateResult.draftProjectId || updateResult.projectId || project.id;',
  '      if (preparedWorldbook?.file) await uploadProjectFile(targetProjectId, preparedWorldbook.file);',
  '      if (preparedRegex?.uploadFile) await uploadRegexFile(targetProjectId, preparedRegex.uploadFile);',
  '      if (hasNewCover) await uploadCoverFile(targetProjectId, coverInput.files[0]);',
  "      showToast(hasNewFile || hasNewRegex || hasNewCover ? '修改已提交审核，主页仍显示旧版本' : (project.status === 'rejected' ? '项目已重新提交审核' : '项目更新成功'));",
  '      overlay.remove();',
  '      await fetchProjects();',
  '    } catch (error) {',
  "      showToast('更新失败: ' + error.message, 'error');",
  '    } finally {',
  "      setSubmitState(submitBtn, '保存中...', '保存修改', false);",
  '    }',
  '  };',
  '}',
  '',
].join('\n');
